### ISSUE TITLE
Bower installs fail (with error)

### ISSUE THREAD

**Issue by ar-rm** [bdkjones/CodeKit#105]
**Quick, short summary:**
Bower installs fail

**Expected results:**
Bower installs shouldn't fail

**Actual results:**

CodeKit Log Error:

```
Bower: Failed to install 'bootstrap'. Error information:

Code & Message: (null), https://github.com/twbs/bootstrap.git#*

Try these steps to fix general errors:

1. Be sure you're connected to the Internet.
2. If you are running any blocking/security apps like Little Snitch or Antivirus software, disable those.
3. Make sure your network or firewall is not blocking the default port for git:// URLs, which is 9418. (Corporate networks do this frequently.) Use the "Tasks" menu to switch Git to use https:// URLs instead.
4.Delete these hidden directories in your home folder: ".cache", ".local", ".npm"
5. Download and install Xcode. Run it once, let the configuration script complete and try Bower again. You can then delete Xcode.
```
- Nothing reported to system.log

**Exact steps to reproduce:**
I just go to the "Components" view, pick a project and clicking "Install".

I've tried...:
- On an existing project and a new one
- Tried all of the suggested steps _except_:
  - 4: Removed `.cache`, `.local"`, but not .npm. There's a lot of stuff in there and I'm scared to throw it all away. I currently have homebrew installed and I think I'm using that for npm (which might mean ~/.npm is safe to remove??), but I'm not completely sure.
    - Speaking of suggestion 4, small typo: Missing a space after "4.".
    - Currently `"4.Delete"`, Should be `"4. Delete"`
  - 5. I think I did this a few days ago when I installed an update of something that broke because of El Capitan (sorry for the lack of details)

**Your configuration (any details about your system that you think might be relevant)**
Just installed CodeKit Beta 6 before running into this.

**Comment by mimetic** [comment]
Is there an easier way to fix the PATH or ENV than downloading and reinstalling Xcode?!?!?

**Comment by bdkjones** [comment]
There might be, if I knew what the hell caused this Bower issue. The Xcode installation process has a script that runs and cleans up a ton of settings on your Mac. It's the fastest, easiest way I know of to solve the problem.

**Comment by mimetic** [comment]
Thanks… I tossed Xcode, and downloaded it, and it didn’t do anything at all. Somehow, I need to uninstall Xcode…can’t find the quick and dirty for that. Advise if you know!

> On Aug 30, 2017, at 8:59 PM, Bryan Jones <notifications@github.com> wrote:
> 
> There might be, if I knew what the hell caused this Bower issue. The Xcode installation process has a script that runs and cleans up a ton of settings on your Mac. It's the fastest, easiest way I know of to solve the problem.

...David I. Gross...

Inside-Outside Project Fundraiser: http://gofundme.com/insideoutsideproject <http://gofundme.com/insideoutsideproject>

LinkedIn: http://www.linkedin.com/in/davidigross
Photo Portfolio site: http://www.davidgrossphoto.com/
Inside-Outside: http://insideoutsideproject.com/
Mimetic Books: http://www.mimetic.com/
Mimetic Galleries: http://info.mimetic.com/

Email: davidigross@me.com <mailto:davidigross@me.com>
Secure: digross@protonmail.com <mailto:digross@protonmail.com> (you need an account)

Telephone : +1 (408) 426-5669
Skype : davidgross
Facebook : http://facebook.com/digross


CONFIDENTIALITY NOTE:
This e-mail and any attachments or previous e-mail messages attached to it are confidential and may be protected by legal privilege.  If you are not the intended recipient, you are hereby notified that any disclosure, distribution, or copying of this message, or any attachment, is prohibited.  If you have received this message in error, please notify the original sender immediately by returning it to the sender and delete this copy, along with any attachments, from your computer without reading or saving it in any manner.  Thank you for your cooperation.

**Comment by bdkjones** [comment]
Try deleting .local, .npm, .cache, .config, .gem from your home directory. Note those are hidden folders; you’ll need to use terminal or enable hidden folders/files in the Finder to see them.

**Comment by mimetic** [comment]
I tried deleting those already (except .gem). No change.

**Comment by bdkjones** [comment]
If you have developer access, grab the Xcode 9 beta. That will re-run the cleanup script when you install it.

**Comment by jasonhibbs** [comment]
Same issue. I’ve never used Bower in CodeKit, but tried today. After following the recommended steps, downloading and reinstalling Xcode from the App Store has not helped. Now downloading current Dev beta as suggested.
