### ISSUE TITLE
[feature?] Plan for bundling ES modules?

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#11]
Currently, the only way I know how to bundle JS files is with the good o'l `// @codekit-append/prepend`.

This has worked great, but, now that things are venturing into the ES.Next world I was curious if you'd put thought into doing bundles with something like systemjs or amd?

You could have some restrictions in place like the latest typescript compiler where bundling only works when using either of those two module export types.

Or will this be in hook land?

**Comment by Kerrick** [comment]
Any news on ES6 imports being handled by CodeKit without having to use the TypeScript workaround?

**Comment by bdkjones** [comment]
I'm working on it! The major issue is source map support across modules with Babel in the middle. JavaScript is...a disaster.
