### ISSUE TITLE
Image optimization information in log

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit#121]
**Quick, short summary:**
The log shows if an image was optimized or if there was no reduction in size, but it does not show the file sizes or reduction percentage.

**Expected results:**
The data from the image details sidebar being shown in the log:
<img width="176" alt="screen shot 2016-06-28 at 12 11 25 pm" src="https://cloud.githubusercontent.com/assets/777155/16425338/be737d2a-3d29-11e6-91d9-e73b913f80e8.png">

**Actual results:**

<img width="633" alt="screen shot 2016-06-28 at 12 13 55 pm" src="https://cloud.githubusercontent.com/assets/777155/16425355/d31615b2-3d29-11e6-827f-c59778256daf.png">

**Comment by bdkjones** [comment]
Implemented for the next release. See #328 for more details. Thanks!
