### ISSUE TITLE
How to delete bower packages?!

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#145]
I fear I'm gonna embarrass myself big time :X

But I honestly can't find a way to delete bower packages.
The UI doesn't give me an option, neither on right click nor a button in the sidebar.
Pressing the checkmark only updates / reinstalls it.

CodeKit gives zero fu**s like a boss when I delete the folder in Finder :D

Is there a major flaw nobody found out yet or is my head a giant flaw?

![a3b47b6b-f516-4501-8a6b-bff68251a9cc](https://cloud.githubusercontent.com/assets/1983382/17509733/cfeb0240-5e1b-11e6-8749-63b8e542d5e3.png)

**Comment by stratboy** [comment]
me too me too! :)

**Comment by stratboy** [comment]
Is the delete stuff still on you list?
