### ISSUE TITLE
Autocheck linked files check syntax checkbox su**s! :D

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#146]
I almost always don't want things like jquery and modernizr syntax checked, but CodeKit always checks the sweet lil shield icon. 

Following your suggestion I go with `@codekit-prepend` in-file statements now, which makes this issue even more inconvenient. I have to leave the file, enter the app and, which I wanted to avoid using in-file-statements, right?

Two suggestions:

1) Either an option somewhere burried on app-level that I don't want linked files syntax checked on unless I check the box myself.

2) Or expanding the statement syntax. I mean something like:
`@codekit-prepend "jquery.js", false;`
`@codekit-prepend "modernizr.js", nosyntaxcheck;`
But hey, you're the magician–

3) How about 1) **and** 2) :O

What do you think?

**Comment by davegillem** [comment]
+1

**Comment by bdkjones** [comment]
Implemented for the 3.6 release. See #406 for details.
