### ISSUE TITLE
Native Module Bundling

### ISSUE THREAD

**Issue by robstown** [bdkjones/CodeKit#168]
**Quick, short summary:**
I am probably going to get crucified for this, as it was already discussed in length in #11 , but CK3 is so close to being able to natively bundle modules without hooks that I thought maybe it might be worth reconsidering.  Hooks, as much as they kick ass for non-mainstream activities, are fragile, have to be modified everytime file names and paths change, and can bring other headaches for the bash illiterate like myself (see #167).  The bottom line is that modules are here to stay and getting standardized for ES6. I think there will always be reasons to bundle instead of handling natively in JS going forward.  As much as browserify sucks sometimes (or pick another another poison), if you use without all the options it can be somehwhat straightforward.  I understand that many of the current user base may not use CK for bundling, but this may be a way to increase the user base going forward.

**Expected results:**
I crash and burn for suggesting this feature

**Actual results:**
I don't know, but it's looking good so far.

**Comment by bdkjones** [comment]
Okay. @subhaze: it sounds like the ES6 module syntax is where the puck is going. Which means the `require()` approach will be a thing of the past in the (near-ish) future. 

So I think the right idea is to make Rollup a first-class citizen in CodeKit and present an option to bundle files linked by `import` statements. Rollup options will be available on a project-wide basis (like Babel's) but not a file-by-file basis.

Folks that want to use `require()` can do so with a Hook.

**Comment by subhaze** [comment]
FWIW, there is official plugins being worked on by rollup team to transform commonjs style modules into ES Modules so that Rollup can roll them up as well.

https://github.com/rollup/rollup/wiki/Plugins

https://github.com/rollup/rollup-plugin-commonjs

**Comment by nickngqs** [comment]
Is this feature currently implemented?

**Comment by bdkjones** [comment]
I'm working on it.

**Comment by nickngqs** [comment]
Nice! Was just curious, thinking there's something wrong with my code. Cheers!

**Comment by zmip** [comment]
Any updates on this? Just curious. I'd like to develop a Vue.js app without npm/webpack, just CodeKit. But I don't think it's going to work without using hooks and getting in the same messy situation that npm/webpack is offering.

**Comment by bdkjones** [comment]
It's still in the pipeline. There are a couple things that I have to take care of first before I can fully implement bundling correctly. The blockers should be out of the way this month.

**Comment by RobertCordes** [comment]
Hey @bdkjones, just wanted to know if you've made any progress on this 😊 I just bought your app — the problem is that I totally rely on using modules, but I just hate having to deal with Webpack etc. I'm currently using Laravel Mix but I was hoping CodeKit could finally be the end of all this madness ❤️

**Comment by nextriot** [comment]
Awesome! This is the only reason I've had to move away from Codekit, looking forward to coming back. Webpack is ass.

**Comment by bdkjones** [comment]
Well, currently I’ve put my other work on hold to handle Mojave and dark mode. Supporting that (and backporting the support all the way to 10.11) is a massive, massive amount of work. So I’d guess probably later this summer.

**Comment by katerlouis** [comment]
I say you spent enough time in the dark desert 8)

![tenor](https://user-images.githubusercontent.com/1983382/42440183-3e202130-8365-11e8-9859-945deb223410.gif)

**Comment by treyseals** [comment]
Up-voting this as I'll also confirm that webpack and browserify are horrible and sloppy approaches to module bundling.

**Comment by nextriot** [comment]
Just started working on a new web app, and webpack is **STILL** ass. 
Any updates @bdkjones?

**Comment by bdkjones** [comment]
Yes. Grab the demo build from codekitapp.com/binaries/beta/bundle4.zip

It should be automatic: anything that contains ES6 imports should be bundled into an output file. You control the format by selecting the base JS file. Babel transpiling and source map nonsense should just work.

Note: if ESLint complains about “import” you need to set it to use “module” type in settings.

Let me know how the build works for you.

**Comment by bdkjones** [comment]
Also note: if you select the IIFE format for the bundle, the name of the function is the name of the base JS file (cleaned of illegal characters for JS).

IIFE is what you want for Browsers. UMD is best if you need to support Browsers and Node. If you require the other formats, they’re available, but you should evaluate the life choices that led you to needing them.

**Comment by bdkjones** [comment]
Additionally: CodeKit supports bundling pure ES6 modules, but also recognizes commonJS (node) modules and import statements that target JSON files.

The Linked Files pane now shows ES6 imports first and the legacy @codekit-prepend/append links below that. CodeKit will always have legacy support for those statements, but once this build goes live they will be officially deprecated in favor of ES6 imports.

Finally: sweet mother of Christ was it complicated to make all of this “just work”. I hate Javascript.

**Comment by bdkjones** [comment]
Yes. I’ll have a screencast about it. But first...please confirm that it works on production examples. I’ve done some simple tests, but that’s it.

**Comment by bdkjones** [comment]
Seriously though....somebody tell me this stuff actually works.

**Comment by nextriot** [comment]
I may have already started by doing this incorrectly - I just copied a similar flow as to what I would do with React. 

Linking doesn't seem to be getting picked up. Also a couple of other tries have given me issues around 'require' statements not being defined etc. which seems about right given the state of the output file.

Here's what I've got...

<img width="840" alt="screen shot 2018-12-10 at 14 53 58" src="https://user-images.githubusercontent.com/711457/49747960-b741da00-fc8b-11e8-9cab-651c711b0bd7.png">

Codekit Output:
<img width="811" alt="screen shot 2018-12-10 at 14 54 20" src="https://user-images.githubusercontent.com/711457/49747987-c163d880-fc8b-11e8-9689-458ebb15920c.png">

Output file:
<img width="841" alt="screen shot 2018-12-10 at 14 54 43" src="https://user-images.githubusercontent.com/711457/49748000-c9bc1380-fc8b-11e8-90b4-744bd92419ce.png">

**Comment by nextriot** [comment]
I'm just linking the minified index file inside of an html page for now.

**Comment by bdkjones** [comment]
Require is not ES6 modules. Email me a demo project I can use to see what’s going on. 

The ESLint error is what I mentioned above. Change the source type setting

**Comment by bdkjones** [comment]
Does the file with the “require” statement also contain “import” or “export”? See: https://github.com/rollup/rollup/issues/1058#issuecomment-254187433

**Comment by zmip** [comment]
Wow, Bryan this is amazing news! This thread started in August 2016, and I guess only a few of us were left secretly hoping that you'd get around implementing this. And now it seems you have! I'm excited. Over the past year I've been thinking that incorporating Webpack-functionality into CodeKit could be a game changing feature for CodeKit. We hear you that it's a &^$% of a job, so even more kudo's to you for pushing through. No time to test this right now, but man, I'm impressed, even if the feature is not production-ready.

**Comment by bdkjones** [comment]
Thanks. I looked at this back in 2016, but the tooling was super unreliable back then and tons of edge cases failed. I decided to wait for it to evolve a little bit and for the JS clowns to decide which was the require/import battle would be settled.

**Comment by mrkos67** [comment]
I snagged the beta build4 ZIP you linked to above to get this ES6 module stuff working. I'm using the basic export/import setup from the example in Section 16.1.1 from http://exploringjs.com/es6/ch_modules.html. I have the "ES6 Bundle Format" set to "IIFE" as you suggested above, but Codekit gives me the build error: 

> Bundled successfully, but with warnings: 'lib' is imported by main.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'lib' in output.globals – guessing 'lib'

Not sure what this means, but testing in the browser I get the following error in the console:

> main.js:3 Uncaught ReferenceError: lib is not defined
    at main.js:3

What am I missing?

**Comment by subhaze** [comment]
Not seeing a code snippet to reproduce I'm guessing your code is mimicking that link exactly, you'll need to modify `import { square, diag } from 'lib';` to be a relative path.

Say your folder structure is like this:

```
project/
  main.js
  lib.js
```

You'll probably need something like `import { square, diag } from './lib';` notice the added "./" if no relative path is given module loaders assume it can be found in some installed/standards area.

Such as, when doing `npm i rxjs --save` would save rxjs to a local `node_modules` folder and you could import directly like in the example of the link: `import { Observable } from 'rxjs';` but if you've created a file called 'rxjs.js' yourself you'd need `import { Observable } from './rxjs';`

Hope this helps!

**Comment by bdkjones** [comment]
Michael is exactly right. If ‘lib’ is installed in some standard node or bower package, you can grab the latest beta build, which will automatically find it: codekitapp.com/binaries/beta/bundle5.zip <http://codekitapp.com/binaries/beta/bundle5.zip>

**Comment by mrkos67** [comment]
Derp. I knew it was gonna be something simple. Thanks!

**Comment by bdkjones** [comment]
Implemented for 3.8. 

I know it took a long time, but the tooling simply wasn't mature enough to make this simple and easy until more recently. There were tons of edge cases and tons of missing elements here and there that prevented me from doing it the way I wanted to do it.

I really hope I got it right. If I did, you should now be able to bundle JS modules by changing literally one dropdown. Source maps, transpiling, minification and syntax-checking all come along for the ride. CodeKit will automatically (by default, but you can override) tweak ESLint, Babel and Terser settings to do the right thing when it sees import statements in your file.

I *think*, but I'm still testing, that I even got this to work with JS files in CodeKit Frameworks. Long-story short: bundling is a thing in 3.8.

**Comment by FreelanceWebNinja** [comment]
> Just started working on a new web app, and webpack is **STILL** ass.
> Any updates @bdkjones?

Can confirm: webpack is still ass.

If CodeKit can provide bundling (ala its Linked Files / @codekit-prepend / include) AND pre-writing/rendering in such a way it would be a game-changer.

**Comment by AL20** [comment]
Hi,
I'd like to implement [_postcss-css-variables_ package](https://github.com/CodyHouse/postcss-css-variables) in a CK setup but don't really know how to do it.

After reading this thread, it seems to be possible but I don't know how to achieve it.
Can I get some help ?

Thanks,

**Comment by bdkjones** [comment]
Yep, it's possible. The simplest way is to use node's `eval` option: https://nodejs.org/api/cli.html#cli_e_eval_script

Your Hook would be:

    node -e "[your script here]"

The example they give on the css-variables page should get you started, you just need to use CodeKit's environment variables instead of hard-coded paths. If you're running this tool on a standalone CSS file, you'd use the 'input' path variable. If you're running it on a CSS file that's produced by compiling Sass, you'd use the 'output' path variable and have your Hook run when the Sass file is changed. See codekitapp.com/help/hooks/ for details.
