### ISSUE TITLE
Sass Linting

### ISSUE THREAD

**Issue by Ne-Ne** [bdkjones/CodeKit#175]
Based for a follow up issue from CK2: - https://github.com/bdkjones/CodeKit/issues/432

Is there any follow up for this in Codekit v3? (https://www.npmjs.com/package/stylelint)

-Neil

**Comment by Ne-Ne** [comment]
@bdkjones Now that Codekit is shipped, I think this should be be re-opened.

This is could be a good feature for large teams / large quantity of style files.

**Comment by bradryanbice** [comment]
Agreed, please consider this as an update!

**Comment by HarroH** [comment]
+1
