### ISSUE TITLE
Current Coda 2 plugin causes issues with Codekit 3

### ISSUE THREAD

**Issue by robstown** [bdkjones/CodeKit#18]
**Quick, short summary:**
When using Coda 2 plugin, opening projects in Coda automatically opens Codekit 2.x unless I have Codekit 3 open prior to opening project in Coda.  This can cause logistical shuffle when Codekit 3 crashes or is closed, as Codekit 2 will be opened automatically.  You have to close the Coda 2 project, re-open Codekit 3, then re-open the Coda project.

**Expected results:**
Codekit 3 is liked as default to open when opening Coda projects

**Actual results:**
Codekit 2 is opened

**Exact steps to reproduce:**
Open project in Coda without Codekit already open

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**
Codekit 3.0 build 23903, Coda 2.5.16,  CodekitCodaPlugin 1.0

**Comment by siliconkibou** [comment]
I'm still having an issue here.  CK2 is removed (best I can tell - gone from Applications, etc.), but the Coda 2 plugin still launches the menubar for CK2 (and not CK3).  The menubar cannot be closed or interacted with (most options in its menu are disabled), and can only be closed with a Force Quit in Activity Monitor, etc.

I have no idea where it may be finding this CK2 menubar app to launch it, as again, I've removed CK2 from Applications, deleted trash, etc.

Thoughts?

**Comment by bdkjones** [comment]
Could be a backup on a Time Machine volume or cloned disk. Use Activity Monitor to inspect the process and see which files are open.

**Comment by siliconkibou** [comment]
Thanks for the rapid response... got it.  Application Support still had a folder for CodeKit (apparently for CK2), containing what looks like a Sparkle update copy of CK2 that Coda 2 was finding.

/Users/[redacted]/Library/Application Support/CodeKit/.Sparkle/CodeKit 18911 1/CodeKit.app
