### ISSUE TITLE
'let' unsupported by uglify?

### ISSUE THREAD

**Issue by mattpilott** [bdkjones/CodeKit#189]
Maybe i'm being a moron but I just tried to use `let` like the crazy cat I am and CodeKit failed to compile. By CodeKit I of course mean uglify.

Here's the code I tried to compile:

```
    let time = new Date().getHours();

    let hours = [
        4,
        12,
        17,
        23
    ];

    let greetings = [
        'Wow you\'re up late! Good morning.',
        'Good morning.',
        'Good afternoon.',
        'Good evening.'
    ];

    let greet = greetings[hours.findIndex(hour => hour > time)];

    document.querySelector('.js-greet').innerHTML = greet;
```

and here's the joyous little failure notice I received:

![screen shot 2016-09-26 at 20 14 09](https://cloud.githubusercontent.com/assets/2401925/18848351/ce9339f0-8425-11e6-838c-abc6234d60f0.png)

Let me know if i'm missing something please.

**Comment by MTCoster** [comment]
I know this issue has been closed for a while, but `uglify-es` is now an officially supported option (still using the [harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony)) for es6 sources.  Would it be possible to get an option to use this instead?

**Comment by bdkjones** [comment]
Transpile with Babel before minifying and you should be all set. The Uglify project is in a bit of...flux...right now. The main contributor isn't really putting out stable releases, which makes it very difficult to integrate.
