### ISSUE TITLE
There's no indication for optimized images, and it gives error when trying to optimize it again

### ISSUE THREAD

**Issue by jaimeeee** [bdkjones/CodeKit#19]
**Quick, short summary:**

On CodeKit 2 after an image was optimized it showed a check indicating it was already optimized, now there's no indicator.

When trying to optimize for a second time a JPG image it gives this error:

```
JPEG Optimizer: Unable to optimize this file. It may be corrupt or damaged. Try re-exporting it from your image editor.
```

Some other images like this one: http://jaimeeee.com/_public/package-adult.png have a 0 bytes initial size: 
![screen shot 2016-05-19 at 11 08 53](https://cloud.githubusercontent.com/assets/258357/15400855/bb3abd12-1db2-11e6-8bfe-1ee6b373a1c1.png)

**Expected results:**

To have a checkmark if the image has been optimized already, and show the correct initial size.

**Actual results:**

There's no indicator if an image is already optimized, if you try to optimize an already optimized JPG, it will throw an error.

**Exact steps to reproduce:**
1. Select an image
2. Click on the Optimize button

**Comment by nickensoul** [comment]
![screenshot 06 18-28-18](https://cloud.githubusercontent.com/assets/14836054/22653342/7b4a866e-eca2-11e6-9301-569ba61d1845.png)
![screenshot 06 18-27-23](https://cloud.githubusercontent.com/assets/14836054/22653343/7b4c034a-eca2-11e6-8ef0-6479d248886a.png)
@bdkjones 
Thank for this app!
About this issue,
I still have this error. Image sizes are right, but got an error when CodeKit tries to optimize already optimized jpegs.
3.0.5 build 25504
