### ISSUE TITLE
Custom Project Icons

### ISSUE THREAD

**Issue by matt3224** [bdkjones/CodeKit#194]
I realise it's quite late in the day for this sort of madness but will there not be a way to add icons/images to the library in CodeKit?

I love seeing Kanye West's miserable face every time I change my project settings but what if I want to see another miserable celebrity to represent my project? What then? Currently I have something of a prototype solution, this consists of a less than dazzling picture of Justin Bieber, who's head I have cut out and sellotaped to my iMac, covering the exact area that CodeKit displays my project icon.

As you can imagine this is not exactly future-proof.

**Comment by double3** [comment]
Hmm. Maybe I'm an idiot. Definitely possible. But I can't simply drag an image onto the project circle as you said, @bdkjones. It prompts me to create a new project or framework. ???

**Comment by makshh** [comment]
![Custom icon](http://i.giphy.com/3o6ZtiaTX934Se8EJq.gif)

**Comment by double3** [comment]
Ahh. Thought you meant I could drag from my Finder window into CodeKit. Thanks!

**Comment by bdkjones** [comment]
Nope. Projects are *always* self contained.

**Comment by darylknight** [comment]
I've been using CodeKit for years and only just found this. More embarrassment. Winning!

**Comment by daveyank** [comment]
Just came here to request this same feature (I love Jean-Luc Picard, but...). I've got these big ole favicon PNG files in each of my projects and now all I need to do is drag them to the CodeKit project icon circle? DAY MADE!

Thanks, Bryan. As always, fantastic app!

**Comment by AlejandroColinaPew** [comment]
![codekit](https://user-images.githubusercontent.com/11632065/26946058-ecab3402-4c5b-11e7-970d-e2b84b163864.jpg)

**Comment by tarikkavaz** [comment]
@matt3224 is my hero

**Comment by petrchutny** [comment]
What about a situation when I don't want to have the logo of the project in its folder, and just want to drag it outside from OS X on the project icon circle? That doesn't seem to work :( So I am left with the funny, yet limited default icon set…

**Comment by bdkjones** [comment]
Correct. The image must be inside the project folder, as projects are always self-contained units.

**Comment by petrchutny** [comment]
Ok, thanks for your clarification.

**Comment by tbnv** [comment]
I'd like all my projects to use a very boring `<>` instead of the other marvelous icons included by default and used randomly. How can I do this?

**Comment by bdkjones** [comment]
This isn’t currently possible, with one exception: provide an Apple-touch-icon.png anywhere in the project and CodeKit will automatically set that as the icon.

**Comment by chepkasoff** [comment]
@max-ci God bless you!
