### ISSUE TITLE
Google Closure for transpiling?

### ISSUE THREAD

**Issue by matt3224** [bdkjones/CodeKit#205]
Is it worthwhile having Closure in CodeKit?

**Comment by addyosmani** [comment]
Feel free to ping us if you do end up exploring this and have any questions. The benefits are somewhat called out perf wise by https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

**Comment by matt3224** [comment]
I did come across this post when looking into native modules, it seems rollup is the way so i'm going to close this issue and rely on this one #168 to be closed with the addition of rollup based bundling using CK

**Comment by bdkjones** [comment]
@addyosmani Thanks very much! I'll take you up on that if I decide to adopt Closure.

@matt3224 I do think rollup will be the way I eventually go. I'm just waiting for the whole thing to mature a bit
