### ISSUE TITLE
[JavaScript] When saving a JS file that outputs to itself, newlines are added

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#213]
**Quick, short summary:**

I was experimenting with hooks and processing js files and noticed if you set the output path to itself, each save produces 2 new lines at the end of the file.

**Expected results:**

No new lines to be produced.

**Actual results:**

Two newlines are added for each save.

**Exact steps to reproduce:**
Save either of the two JS files within attached project and you should see the newlines inserted.

**A link to download a simplified project or file that shows the issue:**

[ck-newline.zip](https://github.com/bdkjones/codekit3/files/552291/ck-newline.zip)

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Fixed for 3.0.1. Interesting catch.

**Comment by subhaze** [comment]
This appears to be occurring again in 3.0.4

**Comment by bdkjones** [comment]
Can you give me a demo file showing the issue?

**Comment by subhaze** [comment]
Yeah, trying to narrow it down

**Comment by kokoshneta** [comment]
This still seems to be present in 3.6.1. Two newlines are added when a JavaScript file (_any_ JavaScript file, as far as I can tell) outputs to itself. Even a simple file containg nothing but `var x = 1;` gets two newlines appended.

**Comment by bdkjones** [comment]
Okay. I had not accounted for the case where a file was set to output to itself, which is not a common thing. That's fixed for the next release and the newlines will no longer be added.

**Comment by kokoshneta** [comment]
Excellent news!

For the record, the use case for the file outputting to itself is if you want the file to be processed and parsed, to let you know of any syntax errors, but you don’t want it to make a minified version of the file. 

Ideally, in my use case, the file would just be syntax-checked, but no new output created at all, but I haven’t been able to find a way to do that (is there a way?), so I’ve been outputting to the source file as a workaround.
