### ISSUE TITLE
Website Bugs

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#214]
I don't know if you want this here; I'll just do it :D
Join me, fellow beta-testers!

Let's find every single bug and rub it into Brybrys face for not telling us to prepare for celebration on the shortfall of a "release party"! ;)
# Serifs

I fear the sweet serifs are not intended.
Chrome 53 on Mac OS X 10.11.6 (late 2013 MBPr 15'')
![Chrome 53 on Mac OS X 10.11.6 (late 2013 MBPr 15'')](https://cloud.githubusercontent.com/assets/1983382/19742642/49f21c8a-9bc6-11e6-9286-e8092f645d8e.png)

![even more serifs](https://cloud.githubusercontent.com/assets/1983382/19742857/2586b580-9bc7-11e6-9af4-09ef064517b9.png)
# Safari the new IE?

In latest Safari nothing happens (9.1.2– don't know if Sierra is already shipped and I didn't notice 8)) 
![Oh no!](https://cloud.githubusercontent.com/assets/1983382/19742818/06bdb536-9bc7-11e6-8b09-c6d3cedc1e9a.png)
# www.codekit.app

Comeon! you're too cool to not invest in this fancy domain.

**Comment by subhaze** [comment]
Missing favicon

**Comment by julienma** [comment]
Small typo on 1st paragraph of https://codekitapp.com/help/teams/:
`default langauge settings` => `default language settings`

Out of interest, how do you generate your web pages, especially the [Help](https://codekitapp.com/help/) and [Updates](https://codekitapp.com/updates/) sections.
Is that markdown -> static pages (like Hugo or Jekyll)?

**Comment by bdkjones** [comment]
Interesting. This one will require @guymeyer

**Comment by bdkjones** [comment]
Thanks guys! Fix for the serifs issue should be deployed. Will someone clear their browser cache and test? Guy and I can't reproduce the serif issue on our Macs. 

Favicon is coming. I've fixed the typo @julienma (great catch) and will upload the new file in a few.

**Comment by bdkjones** [comment]
@katerlouis The SVG animation works for me over here on Safari on macOS.

**Comment by subhaze** [comment]
I've not been able to reproduce the serif issue.

**Comment by guymeyer** [comment]
@subhaze was it doing it for you before?

If not, did you install San Francisco manually? We think thats the problem.

**Comment by subhaze** [comment]
I've never seen the issue, though, I'm not sure if the fix was up or not by the time I looked for it; It was around the time I reported the favicon.

I don't have San Francisco installed.

**Comment by katerlouis** [comment]
Serifs Bug is gone (for me at least)
But in Safari the app window still doesn't do a thing.

**Comment by guymeyer** [comment]
@katerlouis is it working on any section or not at all?

**Comment by katerlouis** [comment]
Put a screencast in the CodeKit 3 - Beta Dropbox

El Capitan 10.11.6, Safari 9.1.2

https://www.dropbox.com/s/hps6p9hayjg4c61/Website%20Bug%20%E2%80%93%20OSX10.11.6%E2%80%93Safari9.1.2.mov?dl=0

**Comment by subhaze** [comment]
@katerlouis FYI, when you push to that dropbox folder, you're basically pushing your files to everyone associated with that folder...

**Comment by guymeyer** [comment]
@katerlouis ok, to fix this:

Go to your applications folder and launch another browser.

:P

**Comment by bdkjones** [comment]
Hmm. I wonder if it's at all related to the default language of your Mac. I mean, the site works perfectly in Safari on macOS 10.12.1 for me, so I'm trying to narrow down the differences between your setup and mine. Are you running any browser plugins? If so, disable them. Does that solve it?

**Comment by katerlouis** [comment]
@guymeyer I actually don't mind that much about this bug; but it maaay be not too ideal for this precious conversion rate everybody's blabbin'bout, when the main feature of a website promoting a Mac App won't work at all in the Mac native browser :D – 

Anyhow: installed plugins are *Evernote Helper*, *Pocket* and *uBlock* – Switched all off and restarted Safari. Still same issue. Console is clean; javascript seems to work, since the Logos in the background animate on scroll.

Flash isn't involved in any way, is it?
My twisted inner apple-hater refuses to bend to this hillarious flash-war they are fighting. Meaning: Regarding to Safari I don't have the latest flash version which they keep rubbing in my face whenever they can!

Hoping I'm the only one with this issue or that every decent webdev uses Chrome or Foxxy doesn't feel like the Bryan-way.

**Comment by bdkjones** [comment]
No, flash is not involved. But I do want to track down the issue because I'm afraid other people may see the same thing. That site has to work. Can you create a new user account with default settings, reboot into that account, and try?

**Comment by katerlouis** [comment]
Done.
Same issue. (should we talk elsewhere cuz of spam, since I'm the only one with this issue?) 

@subhaze – Didn't think about that; cerebellum saw CodeKit folder and just put it there. Not gonna happen again.

**Comment by subhaze** [comment]
I can repro this as well in safari.

OS: 10.11.6
Safari: 9.1.3

**Comment by bdkjones** [comment]
Well, now that it's been reproduced it's definitely an issue. @katerlouis are you on 10.11 as well, or macOS Sierra?

**Comment by bdkjones** [comment]
Nevermind, I see you're both on 10.11.6. That's the common denominator. @guymeyer We need a system running 10.11.6. Do you have one or can you set one up to test with?

**Comment by katerlouis** [comment]
Same issue in browser-stack reproducable

![image](https://cloud.githubusercontent.com/assets/1983382/19819794/9c4a2ac2-9d56-11e6-9798-cb7a61d9cf4f.png)

**Comment by bdkjones** [comment]
Perfect. We can test with that.

**Comment by mcansh** [comment]
Buy button on iOS is using the default styles ![](http://i.imgur.com/bX0Tk6I.jpg)

**Comment by bdkjones** [comment]
Yea, another minor bug to iron out. @guymeyer

**Comment by matt3224** [comment]
Hey @bdkjones @guymeyer I tried purchasing CK3 via the site and found that if you click paypal then do not complete the purchase and try to change the amount you want to pay (in my case $21 to $28) it clears all your info and says you have already used your upgrade, yet I have not made a purchase.

Can you clear this so I can buy CK3 at the upgrade price and stop this from happening to someone else, by checking if the payment was successful before invalidating their CK2 serial.

![littledotmatt_2016-oct-26](https://cloud.githubusercontent.com/assets/2401925/19836778/ec6ca186-9ea2-11e6-9b0e-2fc7b92e3ff2.jpg)

**Comment by bdkjones** [comment]
Hi Matt, that order is cleared and you're all set. Thanks!

**Comment by rvola** [comment]
An image size bug in page https://codekitapp.com/updates (mobile)

<img width="800" alt="image-size" src="https://cloud.githubusercontent.com/assets/6870615/19920410/cdcd3a1e-a0d8-11e6-9207-271a21c15cb9.png">
61/png/32x32/1/_/1/2/image-size.png/EKPB_wIY3dwkIAcoBw/R5OR2miF7RZyDjsrVUx75V9FcSW3B9eki7U83pJM7N0?size=480x320&size_mode=3)

**Comment by rvola** [comment]
A menu problem that does not remain fixed during the scroll in mobile

<img width="925" alt="codekit-menu" src="https://cloud.githubusercontent.com/assets/6870615/19920450/f88c4100-a0d8-11e6-8d6c-fcb60ead27c2.png">

**Comment by katerlouis** [comment]
Any news on the crucial "nothing happens on El Capitans Safari 9.1.3"?
It's still happening to me.
I'd like to help.

**Comment by bdkjones** [comment]
@guymeyer is looking into it. We're going to fix it, but it's not the TOP of the priority list because the browser's old.

**Comment by devilskitchen** [comment]
Website top nav—flexbox does not cascade on Safari (although it does on Firefox (sometimes)).

So, the top menu looks like this...

<img width="1243" alt="screen shot 2016-11-22 at 22 12 51" src="https://cloud.githubusercontent.com/assets/1190864/20544313/627bcd28-b101-11e6-91b3-d6afc70ac859.png">

Whereas you really want something like this (see added style in the inspector)...

<img width="1240" alt="screen shot 2016-11-22 at 22 13 13" src="https://cloud.githubusercontent.com/assets/1190864/20544344/8375065c-b101-11e6-85d4-03c4be93c1c8.png">

i.e. add `flex:1 1 auto;` to the `li` elements.

**Comment by bdkjones** [comment]
New website for 3.2, so these shouldn't apply any longer.
