### ISSUE TITLE
take a break.

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#215]
**Quick, short summary:**
You've worked hard and delivered a complete app, congrats!, even with us nagging for MOAR FEATURE please!! :P

**Expected results:**
Telling us to shut up for a moment so you can breathe.

**Actual results:**
Continuing on as if you've not busted your ass on getting this out the door (this is me totally assuming, you're hopefully on the beach right now)

**Comment by bdkjones** [comment]
Ha, unfortunately the work never ends. Several major bugs have already been discovered and there's more help pages to finish and more screencasts to record... The beach will have to wait. But thank yoU!
