### ISSUE TITLE
Keep window width in all settings tabs

### ISSUE THREAD

**Issue by kosmiq** [bdkjones/CodeKit#217]
**Quick, short summary:**
The CodeKit window width varies between settings. It only remembers and respect my wanted width on each one instead of using the same for all.

**Expected results:**
Keep a consistent window width, especially after I have dragged it out to be wider, and use that width on all settings tabs.

**Actual results:**
Dragging to a width in the file view and then switching to Log (or whatever else for that matter) will cause the window to become narrower/wider depending on what width I dragged that one to previously.

**Exact steps to reproduce:**
Open CodeKit. Open the File View and drag the window to a nice width. Switch to the log and watch the window width shrink. Drag that one to an arbitrary width, get lucky and set the same as File view. Switch to Settings and watch the window change to yet another size (different from both Files view and the Log). Go to package manager and in changes yet again. And so on.

Or fix it by drawing a line on your screen and align all tabs to that exact pixel like a madman.

**A link to download a simplified project or file that shows the issue:**
Not applicable.

**Your configuration (any details about your system that you think might be relevant)**
MacOS 10.12.1.
Just installed CodeKit 3.

**Comment by subhaze** [comment]
https://github.com/bdkjones/CodeKit/issues/17

**Comment by bdkjones** [comment]
Yea, I'm not opposed to revisiting this in the future sometime, but there's a lot of other things I need to get done first.
