### ISSUE TITLE
keep node_modules folder in source but remove in build

### ISSUE THREAD

**Issue by imtiazwazir** [bdkjones/CodeKit#218]
is there a way I can keep node_modules folder for source but remove it in build folder

![screen shot 2016-10-27 at 7 12 09 pm](https://cloud.githubusercontent.com/assets/1964969/19770642/76285a90-9c79-11e6-967a-d17c625269de.png)

**Comment by bdkjones** [comment]
See addition in #237. You'd simply set the Output Action for all items in the folder to `ignore` using the new feature discussed in that thread.
