### ISSUE TITLE
Incorrect link to Node

### ISSUE THREAD

**Issue by RichDonnellan** [bdkjones/CodeKit#223]
**Quick, short summary:** Clicking on Node in the components section takes you to the Babel website instead of Node.

**Expected results:** Redirect to https://nodejs.org/en/

**Actual results:** Redirect to http://babeljs.io/

**Exact steps to reproduce:**
![codekit-node-link](https://cloud.githubusercontent.com/assets/7773718/19833731/be8630e4-9e01-11e6-85e3-2be75aa09ff5.png)

**Comment by bdkjones** [comment]
Thanks! Fixed for 3.0.2
