### ISSUE TITLE
JSHint settings page does not show all options

### ISSUE THREAD

**Issue by hpohlmeyer** [bdkjones/CodeKit#224]
**Quick, short summary:**
The options in the JSHint Settings view are cut off and do not show all options.

**Expected results:**
All available options should be shown

**Actual results:**
The options are clipped off after a varying lengths.

**Exact steps to reproduce:**
1. Open CodeKit
2. Go to any project
3. Open the project settings (also happens in CK default settings)
4. Go to Syntax Checkers → JSHint

**Further Details**
When I hide the descriptions, I see more of the options, but the size of the clipping “container” stay the same. The container expands to a greater length, when I switch to JSLint and back to JSHint, but still won’t show all options.

**Images:**
![hidden descriptions](https://cloud.githubusercontent.com/assets/6564077/19836747/3030ed6c-9eaa-11e6-9dfb-13373614b19d.png)
![visible descriptions](https://cloud.githubusercontent.com/assets/6564077/19836748/306c86ba-9eaa-11e6-93a1-14612a769c64.png)

**My configuration**
MBPr Mid 2012
macOS Sierra 10.12
CodeKit 3.0.1

**Comment by a-dg** [comment]
Same issue here, though mine cuts off at a different place.

**Comment by bdkjones** [comment]
Oy. That's embarrassing. Really wish I had done a beta. Fixed for 3.0.2.
