### ISSUE TITLE
CK fails to load css/js or itself when the preview start path doesn't have a trailing slash

### ISSUE THREAD

**Issue by matt3224** [bdkjones/CodeKit#225]
**Quick, short summary:**
CodeKit doesn't understand no trailing slash in the preview path

**Expected results:**
CodeKit to resolve all asset urls if trailing slash is missing. Maybe do something like add a trailing slash if the file does not end in an extension.

**Actual results:**
CodeKit loads html only

**Exact steps to reproduce:**
Create a project with an index.html then add a subfolder called `subfolder` with index.html, style.css and script.js files. Now set the Preview Start Path to `/subfolder` and now try to view your project.

![screen shot 2016-10-30 at 13 32 34](https://cloud.githubusercontent.com/assets/2401925/19836885/5ade3542-9ea5-11e6-947e-f3912abadc0c.png)

**A link to download a simplified project or file that shows the issue:**
[site.zip](https://github.com/bdkjones/CodeKit/files/560478/site.zip)

**Your configuration (any details about your system that you think might be relevant)**
CK RC7

**Comment by subhaze** [comment]
A similar issue has been brought up before, in CK 2, but I believe all those issues are gone :( so I can't link it.

IIRC CK used to add the trailing slash, but, this totally breaks mod_rewrite. With the above solution any URLs that are valid on my system that end with `/some/endpoint` but, rightfully, 404 with `/some/endpoint/` would break.

**Comment by bdkjones** [comment]
? This works exactly as it should as far as I can tell. I used your demo project, added it to CodeKit and hit Preview. The Preview URL is exactly what it should be: `http://vdk.local:5757/subfolder`

The `index.html` file in `subfolder` is properly found and loaded.

**Comment by matt3224** [comment]
Have you checked the resources though? Mine acts like they are missing as its trying to get them from the root instead of subfolder

**Comment by bdkjones** [comment]
Well yea, that's exactly what SHOULD be happening. The paths to your assets in the <link> and <script> tags are not correct. 

The preview path addition doesn't magically give you a second document root; the document root for the website is either the project root folder or the subfolder thereof that you specify in the next textfield down in Project Settings. The paths for every asset must be relative to the document root. 

The preview path addition is basically like saying, "Load my website and then click on the 'help' link (or whatever) so I don't have to'.

**Comment by matt3224** [comment]
Sure i'm with you but shouldn't relative urls work as one would imagine, for example when you don't prefix your link href or script src with a `/`

**Comment by bdkjones** [comment]
I mean, the *real* issue here is that web developers have come to rely on Apache bailing them out. If you request this URL:

    http://somesite.com/subfolder

And there's not a file named `subfolder` in the document root, that request should 404. That request does NOT match a path for a *folder* named `subfolder` in the document root. To request a folder resource, the path MUST end in a trailing slash:

    http://somesite.com/subfolder/

But users have been trained that the above two URLs are the same. They are not. With a default Apache config, when a request for the first URL does not find a file named `subfolder`, a 301 redirect is sent to add the trailing slash.

I COULD do the same in CodeKit. But there are people who disable this MOD_REWRITE in Apache for various reasons, and then CodeKit would be a problem for them. So right now, the answer is: be exact in your URLs.

**Comment by bdkjones** [comment]
The reason your resources are loaded from the document root when the trailing slash is missing is that the browser sends the wrong `GET` request because without the trailing slash, it doesn't realize there's a baseURL to append to your relative URLs in the tags.

**Comment by matt3224** [comment]
Cool thanks

**Comment by bdkjones** [comment]
After thinking about it, I'm planning to make CodeKit adopt Apache's default behavior. The preview server will issue redirects when a URL points to an existing directory but does not have a trailing slash. Too many people are confused about the situation.

**Comment by matt3224** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2401925/19875193/9266d91a-9fc2-11e6-9058-e76ad6a0f43b.gif)
