### ISSUE TITLE
Incorrect default values for some ESLint rules

### ISSUE THREAD

**Issue by makshh** [bdkjones/CodeKit#227]
**Quick, short summary:**

If you check `curly` or `key-spacing` you will get an error during syntax checking.

**Expected values:**

[curly] : `'all'`
[key-spacing] : `{'singleLine': {'beforeColon': false, 'afterColon': true, 'mode':'strict'}, 'multiLine': {'beforeColon': false, 'afterColon': true, 'align': 'value', 'mode':'minimum'}}`

**Actual values:**

[curly] : `'all', 'consistent'`
[key-spacing] : `'singleLine': {'beforeColon': false, 'afterColon': true, 'mode':'strict'}, 'multiLine': {'beforeColon': false, 'afterColon': true, 'align': 'value', 'mode':'minimum'}`

[curly]: <http://eslint.org/docs/rules/curly>
[key-spacing]: <http://eslint.org/docs/rules/key-spacing>

**Comment by makshh** [comment]
**Expected values:**

[id-blacklist] : `'error', 'data', 'err', 'e', 'cb', 'callback'`

**Actual values:**

[id-blacklist] : `['error', 'data', 'err', 'e', 'cb', 'callback']`

[id-blacklist]: <http://eslint.org/docs/rules/id-blacklist>

**Comment by bdkjones** [comment]
Thanks! Fixed for 3.0.2
