### ISSUE TITLE
Search for linter toggles

### ISSUE THREAD

**Issue by matt3224** [bdkjones/CodeKit#228]
Can we get a search box for the linters, having to scroll up and down all the toggles to find what I want could be instantly improved if I could just search for the rules.

Even better, why not allow us to enable the toggle right from the error console. Outputting `no-undef` is great but it would be awesome if I could just click that and be taken to the toggle or toggle it there and then.

**Comment by subhaze** [comment]
https://github.com/bdkjones/CodeKit/issues/84

**Comment by bdkjones** [comment]
Implemented a while ago...I suck at GitHub.
