### ISSUE TITLE
[ESLint] ignore .eslintrc files in skipped folders

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#229]
**Quick, short summary:**
I was running into an odd ESLint error in the CK console `ESLint failed to run with an unknown error. This can be caused by invalid option parameters on rules or a malformed JS file.` It took me a bit to realize that this was due to CK dipping down into the node_modules folder and loading .eslintrc files from there. Or at least I assume it was, because as soon as I adjusted ESLint config files to ignore all, it worked fine. The only .eslintrc files in the project were within node_modules.

**Expected results:**
Only merge .eslintrc files that aren't within skipped folders.

**Actual results:**
Merging .eslintrc files that are within skipped folders.

**Exact steps to reproduce:**
npm install browserify, then try to lint a JS file.

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Mmm, CodeKit doesn’t look for those files. ESLint scans for them automatically. I have no control over where it finds them or loads them from. However, I have changed the default for handling .eslintrc files to “ignore”.

-Bryan
