### ISSUE TITLE
.codekit-cache folder is visible in the file list

### ISSUE THREAD

**Issue by a-dg** [bdkjones/CodeKit#230]
**Quick, short summary:**
The `.codekit-cache` folder is visible in the file list.

**Expected results:**
`.codekit-cache` should be hidden in the file list.

**Actual results:**
`.codekit-cache` is visible in the file list.

**Exact steps to reproduce:**
Open a CodeKit 2 project in CodeKit 3.0.1, and `.codekit-cache` will be there at the top.

Screenshot: https://cl.ly/3N261P2E3R0d

**Comment by bdkjones** [comment]
Fixed for 3.0.2
