### ISSUE TITLE
Search field value returns after being implicitly cleared

### ISSUE THREAD

**Issue by a-dg** [bdkjones/CodeKit#231]
**Quick, short summary:**
A previous value in the search field returns after being implicitly cleared by selecting a different file type.

**Expected results:**
- If the search field text is cleared by any action (either explicitly by the user or implicitly by CodeKit), it should not re-appear automatically
- The value of the search field should impact how the files are filtered

**Actual results:**
- A previous value of the search field can re-appear when showing the filter menu again
- An automatically re-appearing search field value creates a disconnect between the apparent filter options and how the files are actually filtered

**Exact steps to reproduce:**
1. Enter text in the search field
2. Notice that the files are filtered correctly
3. Select a file type from the filter menu
4. Notice that the search field value has been cleared, and that the files are filtered correctly based on your selection
5. Click off the filter menu to dismiss it
6. Click the filter menu again
7. Notice that the file type selection remains, but that the search field text has also re-appeared
8. Also notice that the search field text has no impact on how the files are filtered
9. Hit the Return key
10. Notice that the files are once again filtered by the value in the search field

Video: https://cl.ly/3f2G3e0K2v1Z

**Comment by bdkjones** [comment]
Good catch! Fixed for 3.0.2
