### ISSUE TITLE
HTML files don't get processed

### ISSUE THREAD

**Issue by oppenheimer-** [bdkjones/CodeKit#233]
The folders "build" and "source" exist and "source" holds locked/unlocked html-files, one of it is index.html. But they are not being processed or built, although they are all set to "Process it". It doesn't matter if it's set to this or "Ignore it". No hooks used.

A message appears in the log:

> This file was processed, but there was nothing to do. Check your settings and/or Hooks.

**Expected results:**
The html-files should be processed and show up under /build without renaming to *.kit

**Actual results:**
No files show up, server complains about missing index.html
_Renaming to *.kit fixes the problem._

**Steps to reproduce:**
Tick html files to be processed and hit "Process" or "Build Project"

**Comment by bdkjones** [comment]
This is behaving correctly. If you set an HTML file to `process` and do not provide any processing to do (via a Hook), CodeKit has nothing to do on that file. `process` does not mean "if I don't tell you how to process this file, fall back to copying it". `Process` means, "I will tell you how to handle this file via a Hook`. If you want your HTML files copied to the output folder, then you set the Output Action to copy.
