### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by BroccoliLeg** [bdkjones/CodeKit#234]
**Quick, short summary:**
Installed the latest Codekit from the website (replaced Codekit 2 in my Applications folder). Started Codekit. Crash.

**Expected results:**
Codekit starts.

**Actual results:**
Codekit crashes.

**Exact steps to reproduce:**
See short summary.

**Your configuration (any details about your system that you think might be relevant)**
[crashlog.txt](https://github.com/bdkjones/CodeKit/files/561614/crashlog.txt)

**Comment by BroccoliLeg** [comment]
Update: After deleting my old Codekit 2 preferences from the library, Codekit 3 works.

**Comment by bdkjones** [comment]
Interesting. Your old 2.x plist was apparently corrupted. CodeKit 3 migrates those settings on the first run and it sounds like that migration crashed for you because the 2.x file was malformed.

**Comment by BroccoliLeg** [comment]
Weird. I used Codekit 2 right before the upgrade and it was fine.

Oh well, it's fine now. Thnx for the update!
