### ISSUE TITLE
SVG in "build" are not optimized or copied

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#236]
**Quick, short summary:**
Using **build mode**, svg files are not optimized copied to the build folder

**Expected results:**
SVG file is optimized and copied to the **build** folder

**Actual results:**
If the setting is _Optimize svg files are changed / build_ no file is copied or optimized in the **build**
If the setting is _Copy svg files (whithout Optimizing) changing / build_ is selected, the SVG files are in the **build** but not optimized.

**Video Demo**
[Dropbox](https://www.dropbox.com/s/qmvzzefi2exvxrm/codekit-3-svg.mp4) (download file for best quality)

**Comment by bdkjones** [comment]
I need a demo project showing the issue, please.

**Comment by rvola** [comment]
I thought at first that the problem was the migration Codekit v2 default options v3.
I deleted all the library files to return to the cleaned version.

Here is a simple project setting up the build with svg should be "optimized" then "copied" without success.

[Download Project](
https://www.dropbox.com/s/c591ovdnkh0wujh/test-svg.zip?dl=0)

**Comment by BroccoliLeg** [comment]
I'm having the same issue.

It seems this has something to do with the creation of folders. Example: a folder with only .svg files in it. Set them all to "optimize": no output to build folder. Set one of the .svg files to "copy": folder gets created, 1 svg file gets copied, optimization happens on all the other files in that folder.

**Comment by bdkjones** [comment]
Ah, that's a great tip. It may be the case that SVGO does not create the output directory if it's missing. I will verify that this afternoon.

**Comment by bdkjones** [comment]
Yep. That's exactly what's happening. I've filed a bug with SVGO: https://github.com/svg/svgo/issues/621

I'll also update CodeKit tonight so that the app creates folders if needed before calling SVGO.

**Comment by rvola** [comment]
ok, thank you for push 3.0.3.
However this version blocks when there are several subfolders.
I just update the demo file [here](https://www.dropbox.com/s/1drwp4g15s038bl/test-svg2.zip?dl=0).
<img width="1251" alt="capture d ecran 2016-11-04 a 10 15 35" src="https://cloud.githubusercontent.com/assets/6870615/20000480/e4008d36-a277-11e6-8130-a0af1a042ab4.png">

**Comment by bdkjones** [comment]
Okay, I've tracked this down and fixed it for the 3.0.4 update. Sorry for the delay.
