### ISSUE TITLE
Exclude bower_components or other folder using 'build'

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#237]
**Quick, short summary:**
Using the **build** it is impossible to exclude the **bower_component** file while requesting a compilation of several files that reference it.

**Expected results:**
**Bower_components** the record or other record can be banned export in **build**, while retaining the ability to include files minifer.

**Actual results:**
If I right click _Skip this folder_, the record is excluded from the build folder, by cons if a file refers to content in a file (minification) it will be empty because Codekit has no right to see folder contents.

**More Details:**
For example we want to include 2 JS files from the folder **bower_components**, but we do not want the **bower_components** file is fully copied into the build folder.

**Exact steps to reproduce:**
check this video: [Dropbox](https://www.dropbox.com/s/qtxp1c44e2ys916/skip-folder.mp4) (download file for best quality)

**Comment by rvola** [comment]
same 
#218

**Comment by rvola** [comment]
a possible track to exclude file would be to add a file that prohibits the build. example a file : notbuild.codekit

**Comment by bdkjones** [comment]
Well, the long-term solution here is to allow JS files to prepend/append files that are contained in Skipped Folders. The even LONGER term fix is to deprecate the `@codekit-append/prepend` statements when JS Modules are ready.

In the meantime, the appropriate way to handle this case would be to set all the items in `bower_components` to an `ignore` Output Action. This will stop those files from being copied into your build folder, but will leave them available to prepend/append to other files.

Obviously, selecting each file and setting ignore would take forever. So I've added a new feature to CodeKit 3.0.2. When you select a folder that is NOT skipped, you can now set the Output Action for all child items of that folder in one click:

![screen shot 2016-10-31 at 22 19 05](https://cloud.githubusercontent.com/assets/926566/19880199/757ac726-9fb8-11e6-8a7b-cef5be81b9f9.png)

**Comment by gpapin** [comment]
This doesn't work for me... The folders are all marked as to ignore but some of them (not all randomly...) are still coped across...  

I had to add a script to remove the copied folder at the end to get the expected result...
