### ISSUE TITLE
Execute Hooks after build

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#238]
**Quick, short summary:**
Can choose to execute a hook after finalizing the **build**

**Expected results:**
Able to execute a hook eg gz compression of a JS file (gzip -9rkf *.js) on the build folder after compilation

**Actual results:**
The hook is executed on the source folder and is not considered in the treatment of build

**Exact steps to reproduce:**

- Codekit create a **build**
- Add a js file
- Add a hook _shell_ `gzip -9rkf *.js`
- Start a build ...

// Only the source files have been compressed gzip)

**Comment by rvola** [comment]
So much for me I had not grasped that it was now possible to identify the file in output folder **build**
https://codekitapp.com/help/hooks/

For my example JS files compression, here's what I replaced:
Filename > contains > 'js'
`gzip -9rkf $CK_OUTPUT_PATH;
`

**Comment by bdkjones** [comment]
Looks good. Wrap `$CK_OUTPUT_PATH` in quotes, though, so that it will work if your path has spaces or other characters that need to be escaped.
