### ISSUE TITLE
Summary for ESLint's eqeqeq option outdated

### ISSUE THREAD

**Issue by seanCodes** [bdkjones/CodeKit#239]
### Issue

The CodeKit summary for the ESLint eqeqeq option mentions the use of the `'allow-null'` option, which is deprecated. From CodeKit (emphasis mine):

> Warns when "==" or "!=" is used instead of "===" or "!==". **You can set the option parameter to 'allow-null' to force typesafe comparison operators except when comparing to "null".** You can also set it to 'smart' to exclude warnings in a few special cases.

### Fix

According to the [ESLint docs](http://eslint.org/docs/rules/eqeqeq), the current way of configuring this option (as of v3.3.0) is with a second argument, which is an object with the property `'null'` and possible values:
- `'always'` (default) require `===` and `!==` with `null`
- `'never'` never use `===` and `!==` with `null`
- `'ignore'` don't apply this rule to `null`.

A possible correction (matching the voice/tone of the no-warning-comments option) could be:

> Warns when "==" or "!=" is used instead of "===" or "!==". You can also set it to 'smart' to exclude warnings in a few special cases.
> 
> The 'null' option defaults to 'always', which requires using "===" and "!==" with "null". Change to 'never' to never use "===" and "!==" with "null", or 'ignore' to ignore this rule when comparing with "null".

The input field should probably be updated from `'always'` to `'always', {'null': 'always'}`.

**Comment by bdkjones** [comment]
Fixed for 3.0.2. Thanks!
