### ISSUE TITLE
Server indicator could be difficult with colourblindness

### ISSUE THREAD

**Issue by defectivebit** [bdkjones/CodeKit#240]
**Quick, short summary:** The server indicator in CodeKit 3 is not immediately clear that it is a server indicator, and it's simple red/yellow/green status indicator could be difficult for those with colourblindness (specifically protanopia).

**Expected results:** An icon representing a server, along with a symbolic indication of status (checkmark, X mark, or loading mark) makes it more obvious that it represents the internal server and makes it easier for the colourblind to discern the server's status.

**Actual results:** The green/yellow/red dot does not have an immediately clear purpose, and doing some testing with xScope, may not be easy for those suffering from certain colourblindness conditions to read.

**Exact steps to reproduce:**

1. Open CodeKit 3
2. Open xScope and activate the Loupe tool
3. Click the "Normal vision" dropdown and choose "Protanopia 1%" option to simulate red/green colourblindness.
4. Hover over the server indicator icon.
5. Reset/stop the server to observe the yellow/red states.

**A link to download a simplified project or file that shows the issue:** n/a

**Your configuration (any details about your system that you think might be relevant)** n/a

**Comment by bdkjones** [comment]
@guymeyer

**Comment by bdkjones** [comment]
We addressed this by adding the chevron to the icon so that it's clear you can click this element for more information. In the ensuing popup, the status of the server is spelled out in text.
