### ISSUE TITLE
Codekit does not save the list of favorites bower

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#241]
**Quick, short summary:**
After adding or deleting a favorite bower, Codekit does not back the restart of the list software. The default list is displayed.

**Expected results:**
Able to fully save the list of favorites bower

**Actual results:**
The list is saved. The list is visible in the .plist file in Preferences. The software is started by clicking on favorite bower, the default list reappears.

**Exact steps to reproduce:**
* I created a new user session.
* I open codekit (first opening)
* I added an empty folder in order to access the codekit Bower
* I let fly a favorite (eg WordPress)
* I wait 5 seconds
* I leave Codekit
* I restart Codekit
* I go to Bower favorite
* Wordpress (unchecked favorites) and again to favorite

**Comment by rvola** [comment]
ok, I think I know where the problem lies!

If I add a favorite and I leave codekit, it does not appear to the software restarts.

So now, I add a favorite, I leave Codekit
I delete the **bower-info.json** file in the _Application Support_
I restart Codekit
Codekit recharge list bower
Bingo is my favorite in the list!

A priori the cache system developed in **bower-info.json** backup favorites then it must be the task of the .plist file

**Comment by bdkjones** [comment]
Fixed for 3.0.2. Thanks!
