### ISSUE TITLE
Feature request: icon indicates pause state

### ISSUE THREAD

**Issue by toddprouty** [bdkjones/CodeKit#245]
It would be useful if the menu bar and/or dock icons gave a visual indication of whether or not CodeKit was paused, e.g., turning gray when paused. You can always toggle it until the right state is achieved, but a quick visual indicator would be nice.

**Comment by bdkjones** [comment]
Agreed. @guymeyer also wanted this.

**Comment by katerlouis** [comment]
I'd like this setting to be optional.

**Comment by bdkjones** [comment]
Implemented for the next update:

<img width="127" alt="screen shot 2017-02-08 at 16 39 24" src="https://cloud.githubusercontent.com/assets/926566/22764061/39cc8dc8-ee1d-11e6-98fd-6d70b92fdbfb.png">

<img width="445" alt="screen shot 2017-02-08 at 16 11 43" src="https://cloud.githubusercontent.com/assets/926566/22764063/3d10a9a6-ee1d-11e6-8b8f-b8c24da56901.png">

**Comment by bdkjones** [comment]
Also, did you guys know that Unicode does not have a "pause" character? 85,324,231 variations of each emoji, but "pause" somehow didn't make the cut. Good stuff.
