### ISSUE TITLE
Errors buried in long log, difficult to understand what the issue is.

### ISSUE THREAD

**Issue by zeg-io** [bdkjones/CodeKit#248]
**Quick, short summary:**
I have an angular based front end, when I run Build Project on it it seems to run fine, processing a ton of JS files, then it stops at item number 215.  No clue what it is or why, it just says "Build Aborted" The details just say "due to an error or because you cancelled it"  I didn't cancel it. (Found the issue before posting see below)

**Expected results:**
Either don't fail, or if it does, tell me what it was doing so I can troubleshoot.

I found the issue, so specifically there was a sass file which had this line:
`$color-notice-green:#D6ECD0`
(note the lack of a space)
I changed it to this:
`$color-notice-green: #D6ECD0`
and it fixed it.

I would expect the failed items to be moved to the bottom of the list so that the aborted build can be EASILY explained. (I hadn't seen the red item as the list scrolled passed it before it went red). Or alternately, highlight all the red items on a tab and select that tab automatically if it fails.

**Actual results:**
Build Aborted, failed item buried in hundreds of line items.

**Exact steps to reproduce:**
Try to build my project...I mean, I can't tell what the issue is.  There is a .sass file that is red in the log, 

**A link to download a simplified project or file that shows the issue:**
Just create a sass file with the variable above.

**Your configuration (any details about your system that you think might be relevant)**

**Comment by subhaze** [comment]
Maybe update the title so that it's more specific to the issue you found while debugging, nice digging. Since it's not angular specific, the title change might help others find this quicker when searching.

**Comment by bdkjones** [comment]
Yea, the log needs a little organization for builds. Definitely on my list.

**Comment by bdkjones** [comment]
3.5.2 introduces the ability to show only errors/warnings and search results for a specific string. Should alleviate this.
