### ISSUE TITLE
Changing JavaScript Output doesn't seem to affect existing files.

### ISSUE THREAD

**Issue by zeg-io** [bdkjones/CodeKit#249]
**Quick, short summary:**
Have an existing project (from 2). It was outputting JS in the "This folder" section to `/min` and the "output filename" to `*-min.js`
I modified this by changing the "Output Filename" to `*.js`

**Expected results:**
I expected those old file names to change to the new naming convention, or at a minimum for new filenames to be created.

**Actual results:**
Nothing.  Nothing seems to be affected.  I even deleted one of the files hoping that doing so would allow the new file to be created.  Nope. It generated the old filename.

**Exact steps to reproduce:**
See summary.

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by zeg-io** [comment]
More info.  I changed the "relative to" to be relative to the build path now and applied the changes.  It now outputs the correct file where I expect it... BUT... the rest of the files remain unaffected.  Meaning while the file I edited changed locations, the other files in that folder did not get minified to the new location.

**Comment by bdkjones** [comment]
That expectation was not correct. As explained at the top of the Output Path section in Project Settings, in the help documentation, and in my screencasts: changing the Default Output Path options in Project Settings does not automatically affect existing files. To do that, you need to click the "Apply to Existing Files" button at the bottom. 

See the docs or screencasts for a full explanation.
