### ISSUE TITLE
Custom Bower Components Folder Location isn't added to Load Paths for Foundation

### ISSUE THREAD

**Issue by purplespider** [bdkjones/CodeKit#250]
**Quick, short summary:**
It seems that if you set a custom Components Folder location in Settings > Bower (e.g. `thirdparty/bower_components`), this folder isn't added to the SASS/Libsass Load Paths when Foundation is installed, meaning `@import "foundation"` fails.

**Expected results:**
`@import "foundation";` in a `scss/myapp.scss` file should import the foundation.scss file inside the foundation folder of bower_components. Compiling successfully.

**Actual results:**
`@import "foundation";` in `scss/myapp.scss` compilation fails with the error:
````
Sass: Error: File to import not found or unreadable: foundation.
       Load paths:
         /Users/james/Desktop/BowerTestSite/scss
         /Users/james/Desktop/BowerTestSite/bower_components/foundation/scss
         /Users/james/Desktop/BowerTestSite/bower_components/foundation-sites/scss
         /Users/james/Desktop/BowerTestSite/bower_components/foundation-sites
         /Users/james/Desktop/BowerTestSite/bower_components/motion-ui
         Sass::Globbing::Importer
        on line 1 of /Users/james/Desktop/BowerTestSite/scss/myapp.scss
  Use --trace for backtrace.
````
The foundation load paths it's looking in are incorrect due to the custom Bower Components folder location, it should be looking in `/Users/james/Desktop/BowerTestSite/`**`thirdparty`**`/bower_components/foundation/scss`. 

**Exact steps to reproduce:**
1. Create new project
2. Set **Settings > Bower > Components Folder** to `thirdparty/bower_components`
3. Install Foundation via Assets tab.
4. Create a `scss/myapp.scss` file containing `@import "foundation";`
5. Try and compile `scss/myapp.scss`.

**A link to download a simplified project or file that shows the issue:**
http://spdr.me/XnzX

**Your configuration (any details about your system that you think might be relevant)**
Tried both SASS and Libsass.

This is a simplified example of the issue. In the actual project I'm using for this I cannot keep bower_components in the project root or use CodeKit's built in "New Zurb Foundation Project..." feature.

**Comment by bdkjones** [comment]
Yea, if you modify the default paths then you'll need to update your `@import` statement with a fully relative path to the location of Foundation. CodeKit does provide the default location to the Sass compiler, but it becomes a performance issue to supply all Bower paths to the compiler every time.
