### ISSUE TITLE
node_modules not built?

### ISSUE THREAD

**Issue by zeg-io** [bdkjones/CodeKit#251]
**Quick, short summary:**
I have an angular UI project. When I build my project the node modules structure isn't moved over to the /build folder, therefore the build breaks (because it can no longer find the libraries it needs.

In addition, html files aren't copied over by default (yes, I added my own copy task)

I may not have a full understanding of the expected use-case, but for projects such as these I'd like to get everything in one place and ready to go.

**Expected results:**
I'd expect the /build folder to output a fully usable result, including a copy of the node_modules folder.

**Actual results:**
Broken site.

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Select the `node_modules` folder (which should be skipped by default) and make sure its Output Action is `copy`.

And you don't need a custom task to copy over HTML files. Add `*.html` as a language in `Other Languages` in Project Settings, then set the default Output Action for that type of file to `copy` and click `Apply To Existing Files`.
