### ISSUE TITLE
rendering of error log is strange

### ISSUE THREAD

**Issue by JohnMica** [bdkjones/CodeKit#253]
as per the picture bellow, you can see the error log appears to have some interesting double rendering, not sure if this is from codekit or linters/

- open a project in codekit and sublime-text
- modify a file and save it with an error 
- codekit will produce the error log that looks like the picture attached.
- macos sierra 10.12.1

![captura de ecran din 2016 11 05 la 22 30 02](https://cloud.githubusercontent.com/assets/7076631/20034010/db1a7fde-a3a7-11e6-81cc-16fab6e45662.png)

**Comment by iambz** [comment]
Same issue here. But somehow, it only appears when the log section has the focus.
If I click anywhere else in app (like just next to it close to the icons on the left), it displays good.

**Comment by bdkjones** [comment]
Thanks; I've fixed this for the next update.
