### ISSUE TITLE
chrome workers.js called but not found

### ISSUE THREAD

**Issue by JohnMica** [bdkjones/CodeKit#254]
As per the picture attached, it seems that when playing with Codekit and localhost for a new simple website the following resource wants to be loaded but cannot be found.

service-worker.js with bad request
service-worker.js failed to load - err_invalid_response

ckcachecontrol - issue with a DOM element that is not there (codekit coudltn find it because it doesnt exists )

it this a bug or a chrome thing or just plain weirdly my mistake ?

![captura de ecran din 2016 11 06 la 17 49 00](https://cloud.githubusercontent.com/assets/7076631/20040114/547bc170-a449-11e6-9679-0c38d7d462d1.png)

macos sierra, chrome 54.0.2840.71 (64-bit), sublime text.

**Comment by bdkjones** [comment]
Does the file exist in the document root folder of the site?

**Comment by JohnMica** [comment]
no it doesnt exist in the site at all. all i got is few sass, 1 css, 1 js, 1 jade and 1 html (html and css compiled by codekit).
strange

**Comment by makshh** [comment]
Isn't it related to this?

http://stackoverflow.com/questions/33328579/service-worker-throwing-an-neterr-file-exists-error

**Comment by bdkjones** [comment]
Cool. This does not seem related to CodeKit.
