### ISSUE TITLE
[JavaScript] Thoughts on linking .es6 extensions, or more?

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit#256]
**Quick, short summary:**

Currently CK can link the dependencies for .js and .ts files (which is freaking awesome) and I was curious about adding .es6 since CK supports that extension for JS files. It's not a valid extension, but, could prove useful when writing hooks and only triggering them based on dependencies when using .es6

The reason behind this is due to me trying to find a decent workflow for Browserify integration with CK, while still using Babel provided by CK.

As it stands it's required to have a source/build process setup to ensure required paths are consistent. Which is OK, but you end up with a lot of JS files in the build folder that you don't necessarily need + the bundled file.

The alternative would be including babelify locally and only using CK for ESLinting, which is OK too, but would just feel better if we were using CK's built-in support for Babel instead.

With the ability to support .es6 linking, we could produce a .js file right beside it and trigger Browserify only when the main bundled file is affected or one of it's dependencies.

**A step further**

What would be really interesting is if we were able to define extensions, or if CK were able to pick up the extension from something like:

```js
import {default as html} from './some-template.html';
import {default as css} from './some-styles.css';
```

Where we could just save those dependencies and use Browserify transforms on them during the final Hook/Build process... This may be a huge asking... but would add some major/efficient functionality to using Browserify or other Third-party tools that allow transforming on non-js files.

**Comment by bdkjones** [comment]
Is that `step further` thing actually a thing? JS files can import HTML or CSS now?

**Comment by subhaze** [comment]
Heh... kinda... yeah... just depends on your tooling.

Browserify has quite a few [transforms](https://github.com/substack/node-browserify/wiki/list-of-transforms) that allow for pulling in html/css/etc content. There's also https://github.com/css-modules/css-modules that's been getting a lot of attention.

All this would still be possible without the linking of course, but, would be nice to not have to wildcard extensions/directories and build each "something" was saved, instead of CK just knowing that file you saved was a dependency X file so run the Hook.

**Comment by bdkjones** [comment]
I mean, I can implement this without too much hassle, I think. The key will be providing the extension in the import statement. If it’s missing, CodeKit assumes it’s .js. As long as your provide an extension, I can make the linker work like Kit’s, where any file of any type is a valid one. 

BUT, CodeKit can’t concatenate HTML and CSS files into the middle of a string of JS files. So in that case, when the chain is processed by CodeKit’s built-in tools, those files would have to be dropped from the chain.

**Comment by subhaze** [comment]
That makes sense and is how most of the transforms work, extension based.

Completely understood about CK not doing the html/css concats into JS files; I would assume this would work the same way as the current workflow of JS files, importing other JS files Babel will transform that import statement into CommonJS format, but CK wont bundle it up.

This has just been my exploration with using Hooks and third-party tooling. I've been trying to write a post for Browserify but I keep back tracking or deleting and starting again thinking of better ways to integrate with CKs current options. Hence the initial request for just .es6 support, but, I started thinking more about what other possibilities there could be.

And I do realize if this is baked in, it's something you gotta support... So it would def be worth thinking through, but from my initial thoughts this would open up the door for really nice Rollup/Browserify Hooks, where you just Hook to an entry file and CK realizes the rest of the dependency chain and runs that Hook when its dependencies update.

**Comment by bdkjones** [comment]
As far as I can tell, .es6 files haven’t caught on. We’ve got .js and .mjs. In 3.8, CodeKit is aware of .mjs files and will handle them, even though they’re not very popular. Is there still a need for the non-standard .es6?

**Comment by subhaze** [comment]
You are correct, IIRC it was just a means to help work flow at the time.
