### ISSUE TITLE
“Skipped Folders” are not saved when editing Defaults.

### ISSUE THREAD

**Issue by Tazintosh** [bdkjones/CodeKit#257]
“Skipped Folders” are not saved when editing Defaults.

Here’s how to reproduce:
• Open Defaults (⌘D)
• In Project Settings, Skipped Folders, add some text
• Do —not— leave the field and click Done
• Open Defaults again: the new Skipped Folders values have not been saved
=> To make it work, another section on the left column for example, must be selected.

I've not checked others text files or text areas, so perhaps the issue also exist for them.

**Comment by bdkjones** [comment]
Fixed in 3.0.6. Thanks.
