### ISSUE TITLE
SVGO settings not being applied

### ISSUE THREAD

**Issue by nerdmanship** [bdkjones/CodeKit#258]
**Quick, short summary:**
Most SVGO options doesn't apply when clicking "Optimize"

**Expected results:**
SVGO to perform the chosen optimisation options and output an optimised file

**Actual results:**
- Performs pretty-print
- Inserts som line breaks
- Does not perform any other optimisations as far as I can tell
- Focused tests on "Remove comments", "XML namespace"

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**
Potentially related to this: _SVG in "build" are not optimized or copied #236_

CK project including original SVG, optimised SVG, CK config: _https://github.com/nerdmanship/TestProject-for-CK_

Youtube video of attempt to optimise (not from same test project, but same workflow): https://youtu.be/2ut8zR6ETZs

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
This was indeed a bug. It's fixed for the 3.0.4 release. Thanks!
