### ISSUE TITLE
Autoprefixer bug

### ISSUE THREAD

**Issue by JonathanDoelan** [bdkjones/CodeKit#263]
I’ve found an annoying bug:
If I set „Run Autoprefixer …“ in the „Defaults for new Projects“ for SASS, the checkbox isn’t checked in the Project-settings if I create a new project …
thx!

**Comment by bdkjones** [comment]
Ah, Christ that's embarrassing. Mainly for me. Also for the 80 beta testers who used this thing for months. Fixed for the next update.
