### ISSUE TITLE
Coda 2 Plugin Bug

### ISSUE THREAD

**Issue by JonathanDoelan** [bdkjones/CodeKit#264]
If I hide the codekit-config-file from Finder, Coda 2 won’t open codekit, when I open the related project in Coda 2.

**Comment by bdkjones** [comment]
Oy, that's an oversight. I've submitted version 3.1 of the plugin to Panic. It should be available on their plugin site shortly. It will also go live on my site with the 3.0.4 update, which I plan to ship tonight. Thanks!
