### ISSUE TITLE
Build functionality (feature request)

### ISSUE THREAD

**Issue by JonathanDoelan** [bdkjones/CodeKit#265]
Feature Request:

I really love the new build-functionality, BUT there is one thing I am missing: After building the build-folder, the build-folder is the one that I’m viewing in the Browser. If the CMS, I’m using, is creating files, that I’ve uploaded (moved), or if other files are generated from the CMS into the build-folder … CodeKit doesn’t offer a build-option to „keep“ these files, after a „clean build“. I know I can uncheck the option „Perform a clean build“, but it would be super nice, if I could mark a folder (or file) to be not deleted or overwritten while building the whole project (in a clean way).

**Comment by bdkjones** [comment]
The trouble here is that the build folder is never indexed by CodeKit (for obvious performance reasons), so there's no way to select anything in the build folder and tell the app to keep it. 

In this case, you'd want to turn off the `clean build` option and manage deleting orphaned files yourself.
