### ISSUE TITLE
No projects available after moving codekit3 to applications folder overwriting codekit2 as advised 

### ISSUE THREAD

**Issue by reibejoy** [bdkjones/CodeKit#268]
**Quick, short summary:**
I had codekit 2 installed and wanted to update with the built-in updater. It did not work (failed on the last step; error while extracting). 
So I downloaded the fresh installer as advised on twitter. 
I extracted the app and moved it to my applications folder, replacing the old application. 

Starting the app I am greeted by "No Projects, Captain". 
None of my projects are there. 

**Expected results:**
The projects should be there (as advertised)

**Actual results:** 
"No Projects, Captain". 

**Exact steps to reproduce:**
Download Installer, extract and add to applications folder, overwriting codekit 2 application. 
codekit 2 should have some projects to see this happening.

**Comment by subhaze** [comment]
It's not advertised to move your "projects" just your settings, as well as, preserving in previous settings per project based on the old CK 2 config file if one is present when adding your projects back.

>**Migrating Settings**
>
The first time you run CodeKit 3, your preferences from version 2.x are automatically migrated. All New Project Defaults and App Preferences come across.
>
>**Projects Don't Move Automatically**
>
>CodeKit 3 will not automatically move all your projects to the new app. This lets you migrate a few at a time, if needed, or continue using CodeKit 2 for certain projects until you're ready to migrate.

More information can be found [at help/upgrading](https://codekitapp.com/help/upgrading/)

**Comment by bdkjones** [comment]
Yep. It's a one-time hassle because the app's bundleID changed for 3.0.

**Comment by reibejoy** [comment]
OK, thanks for clarifying this. Somehow I thought that the projects would all be automatically there. Thanks to a quick finder query; drag n dropping the old config files into codekit, the projects are back.
