### ISSUE TITLE
Allow to ignore files/directories for Browser Injection not working

### ISSUE THREAD

**Issue by Aresinho** [bdkjones/CodeKit#274]
**Short Summary**

According to documentation:

> 
> Injection vs. Full Reload
> ====
> 
> When you save a stylesheet, CodeKit refreshes the browser by injecting changes without reloading the entire page. This lets you easily style modal content. When you save a page or script, however, the whole site reloads to capture those changes.

This makes a lot of sense: However, the file watcher does not ignore some IDE configuration files that are automatically modified when a file is saved, or the **window losses focus**: IE. Intelli-J family of IDEs (.idea directory)

Browser refreshing injects CSS without a problem when the file is saved. However, when phpStorm window losses focus, ie: like when trying to select something in the inspector, the browser refreshes, even when the whole .idea folder was set to ignore

**Expected Results**
After setting "Output settings" to ignore in a directory or any file file browser the browser should reload when those files change

**Actual results**
Extreme sadness when the browser refreshes

**Steps to reproduce**
1. Add a new project
2. Go to General Project Settings
3. Click on "Browser Refreshing"
4. Make sure "Animation" checkbox is on
5. Toggle "External Server Required" to on
6. Enter URL on "External Server Address" example: http://projectname.dev 
7. Exit settings
8. Ignore the .idea folder
9. Make sure the compiles SCSS file is the one required by external server address

**Your configuration (any details about your system that you think might be relevant)**
Project works if access directly
Project uses GIT
Project is a LAMP project
Running macOS Sierra 10.12.1

**Comment by bdkjones** [comment]
What you want to do is add your `.idea` folder to the Skipped Items list in Project Settings > General, then refresh the project in CodeKit.

Although CodeKit does not do any processing on "ignored" files, it does watch them and reload the browser when they change because that's generally what you want to do with most ignored files.
