### ISSUE TITLE
ESLint – Missing `max-statements-per-line` rule

### ISSUE THREAD

**Issue by seanCodes** [bdkjones/CodeKit#275]
CodeKit includes ESLint's `max-statements` rule but is missing [`max-statements-per-line`](http://eslint.org/docs/rules/max-statements-per-line).

Possible summary:
“Warns when a single line contains more than the specified 'max' number of statements.”

Default value:
`{'max': 1}`

**Comment by bdkjones** [comment]
Added for the 3.0.4 release. Thanks.
