### ISSUE TITLE
ESLint – Outdated options for `quotes` rule

### ISSUE THREAD

**Issue by seanCodes** [bdkjones/CodeKit#276]
The default options currently used in CodeKit for ESLint’s [`quotes`](http://eslint.org/docs/rules/quotes#options) rule are deprecated.

Current: `'double', 'avoid-escape'`
Expected: `'double', {'avoidEscape': true, 'allowTemplateLiterals': true}`

**Comment by bdkjones** [comment]
Thanks. Updated for the next release.
