### ISSUE TITLE
Compass error logs missing details

### ISSUE THREAD

**Issue by jaredSiebert** [bdkjones/CodeKit#277]
**Quick, short summary:**
When compiling a Compass project in Codekit3, the logs provide no insight to what the problem was

**Expected results:**
Should show error details like you get in CodeKit2 and running `compass watch` in the console
![image](https://cloud.githubusercontent.com/assets/1281322/20398773/90231b94-aca3-11e6-9a5b-3f074a9c61fc.png)

**Actual results:**
When the compilation fails, the error log provides `(null)` as the error message
![image](https://cloud.githubusercontent.com/assets/1281322/20398803/aec9f3d8-aca3-11e6-9822-5e210397d2ed.png)

**Exact steps to reproduce:**
* Clone sample project
* Add project to CodeKit3
* Compile SCSS file with any error (invalid variable name, missing semi-colon, etc)
* View CodeKit log

**A link to download a simplified project or file that shows the issue:**
https://github.com/jaredSiebert/Codkit3-bug

**Comment by bdkjones** [comment]
Hmm. I'll investigate. In the meantime, you should immediately start migrating away from Compass. It's been officially end-of-lifed and will receive no future updates. When the next major version of Sass is released, Compass won't work any more and it's incredibly likely that I'll drop it from CodeKit completely.

**Comment by bdkjones** [comment]
Fixed in 3.0.6.
