### ISSUE TITLE
Monitor changes on other file types on Kit imports

### ISSUE THREAD

**Issue by diniscorreia** [bdkjones/CodeKit#279]
This may be an edge case, but still: I'm importing some JS and SASS into a Kit file.

I'm importing the minified JS and compiled CSS - however, when I modify the source JS or SASS it doesn't trigger the processing of the Kit file.

Is there any way to achieve this? I was looking into Hooks, but it looks like I can only build the whole project, not process an individual file.

**Comment by bdkjones** [comment]
This is a bug I’m looking into. Will be fixed for the next release.

**Comment by zengabor** [comment]
I am also having this issue. This is something that worked great earlier. I think it stopped working already in CodeKit 2 but I may be wrong.

As a workaround now I have to save the kit files to trigger the processing.

**Comment by bdkjones** [comment]
This should be solved in my next update, but I'd like to verify. Please email me at bryan@codekitapp.com so I can send a beta release to you.
