### ISSUE TITLE
Ignored codekit-append/prepend files (feature request)

### ISSUE THREAD

**Issue by davegillem** [bdkjones/CodeKit#281]
I'd like to be able to set a file to ignore issues in linked files in the append/prepend code statement instead of the inspector panel. This would help when switching code branches in git and maintaining the ignore setting. 

Possibly using something like the less compilers import option.
 For example:
`// @codekit-prepend (ignore) "foo.js"`

**Comment by rvola** [comment]
Hi @davegillem 
Just remove the @ to stop being processed

**Comment by davegillem** [comment]
I don't want processing skipped. I'm referring to ignoring the warnings. The same thing achieved by unchecking the icon next to the file in the inspector panel. It mutes the warnings but still processes the files. Helpful for code you didn't right.

**Comment by rvola** [comment]
same #146

**Comment by davegillem** [comment]
You are correct. I searched but apparently not well enough. This is a duplicate of #146.
