### ISSUE TITLE
Final new line at eof included in compiled Kit output

### ISSUE THREAD

**Issue by indrekpaas** [bdkjones/CodeKit#282]
**Quick, short summary:** CodeKit 2 ignored final new lines in Kit partials when outputting compiled files. CodeKit 3 however, is including them. I suppose this has to do with the new `@import` indentation support and I'm not sure which of the two behaviors is correct, but the change feels unnatural.

**Expected results:** Final new line at end-of-file of a Kit partial ignored in the compiled output.

**Actual results:** Final new line at end-of-file of a Kit partial is included (and indented if applicable) in the compiled output.

**Comment by bdkjones** [comment]
I need a test project, please. Thanks.

**Comment by indrekpaas** [comment]
Of course—https://we.tl/twAepObaCz

**Comment by bdkjones** [comment]
The new behavior is technically correct: whatever is in the imported file goes into the base file, literally character-for-character. Is this breaking something on your site?

**Comment by indrekpaas** [comment]
It's not breaking anything, but is rather an aesthetic question. I tend to have strict whitespace rules. Thanks for looking into this.

**Comment by bdkjones** [comment]
Yea, I mean I think the correct approach is to remove the final newline from the imported file if you don't want it in the final output. That keeps things very simple and honors the idea that Kit is, fundamentally, just simple string replacement.
