### ISSUE TITLE
Dublicated classes with SASS

### ISSUE THREAD

**Issue by mortenhjort** [bdkjones/CodeKit#284]
**Quick, short summary:**
I get dublicated classes when using the SASS compiler

Here is the compiled CSS:
https://cl.ly/1R1j3e1j0N0b

Here is the full structure:
https://cl.ly/1K3M24201X01

**Your configuration (any details about your system that you think might be relevant)**
Newest version of MacOS and CodeKit.

**Comment by bdkjones** [comment]
User error. `global.scss` is imported into multiple partial files, then again in `style.scss`. Your structure is incorrect.
