### ISSUE TITLE
Uglify breaking my acceptance tests.

### ISSUE THREAD

**Issue by chris-fa** [bdkjones/CodeKit#285]
**Quick, short summary:**
I have a souce JS file with this line 

```
window.location.href = '/partners/bank/create';
```

Then I modified it like this

```
window.location.href = '/partners/bank/createe';
```

**Note** the extra `e` on `createe`.

Run acceptance tests using Zombie JS headless browser, and I get `Error while processing event 'click'`... `Invalid or unexpected token`. I checked many times, there is no `click()` call on global scope.

I go back to `window.location.href = '/partners/bank/create';` and process the file; it doesn't throw any error and works perfectly.

**Expected results:**
When processing after adding an extra `e` to the string, it should still work.

But if it didn't, when going back to the original string and recompiling, it should **NOT** work so I can confirm the bug is related to the version 3 of CodeKit.

**Actual results:**
Processing the file with the new change breaks it.

Processing the file with the old string works. However it spit out the **exact same minified file**, making it looks like it's outputting a cached minified version, rather than a newly processed file from the old source.

**NOTE:** the source file works perfectly with Zombie JS, meaning the uglify version is the broken one.

**Exact steps to reproduce:**
Processing (Uglifying) a source JS file and running it on Zombie JS headless browser.

**A link to download a simplified project or file that shows the issue:**
Proprietary project, can't send a link

**Your configuration (any details about your system that you think might be relevant)**
Using Zombie JS as a headless browser. Downloaded CodeKit 3, using it on Trial, but **license is expired** and our Tech department still haven't bought the licenses yet.

**Comment by chris-fa** [comment]
Nevermind, after 2 days of this, I suddenly decided to turn off and on my VM and now it works. It's probably something with Node.js

**Comment by bdkjones** [comment]
Cool; self-fixing bugs are my favorite kind.
