### ISSUE TITLE
Changes in source files are not processed

### ISSUE THREAD

**Issue by c330s** [bdkjones/CodeKit#286]
(this might be connected [issue 279][1])

**Quick, short summary:**

I’m converting `text.md` to `text.kit` and import this into `page.kit`. 
`page.kit` is then converted to `page.html`. 

                     head.kit  ↘
       text.md  →   _text.kit  →  page.kit  →  page.html
                   footer.kit  ↗︎

       changes  |    changes   |    n. a.   |  no changes 

When I save changes to `text.md`, I get an CodeKit-notification and the browser refreshes. 

**Expected results:**

Changes should be processed to `page.html`. 

**Actual results:**

Unfortunately the `page.html` _does not show the changes_ to `text.md`.  
`_text.kit` reflects the changes.  
`page.html` is not compiled. The Browser refreshes to the exact same (old) state. 

**Additional information:**

The files _were_ located on an NAS, I tried to move them to my computer:  
Did not help.
 
This project did work fine in CodeKit 2 (with files on the NAS). 

I have another project with a similar structure (no Markdown, only Kit), this shows the same problem.  
The other project uses a build folder. A new build generates the changed `page.html`.

**Your configuration (any details about your system that you think might be relevant)**

CodeKit 3.0.3, Build 25444
 Mac OS 10.11.6

[1]: https://github.com/bdkjones/CodeKit/issues/279

**Comment by bdkjones** [comment]
Yep, this should be #279. Could you please email me at bryan@codekitapp.com? I'd like to send you a beta build of the app to see if this issue is solved before I release that to the world.

**Comment by c330s** [comment]
The beta (Build 25450) solved it for the md-project mentioned above. 
The other project still doesn’t work. 

The structure of the non-working project is like this (names shortened): 

```
_ref-df-card.kit → _ref-cards.kit → ref.kit → ref.html
```

I made a small screengrab to show what’s happening: 

https://youtu.be/EuVyKmSLzso

I’m saving at 0:15 and 0:24 (you can see the statusbar of sublime change).
