### ISSUE TITLE
New indentation broken for <pre>

### ISSUE THREAD

**Issue by c330s** [bdkjones/CodeKit#287]
**Quick, short summary:**

My `kit`-file has a multi line `<pre>` segment:

 ```HTML
<pre><code>Line 1
Line 2
</code></pre>
```

It gets imported into another `kit`-file, where the »content \[…] is now properly indented with leading whitespace« (from ›Whats New in 3.0‹).

The HTML compiled from this file finally looks like this:  

```HTML
<some>
	<other> 
		<code>
			<pre><code>Line 1
			Line 2
			</code></pre>
		</code>
	...
````

**Expected results:**

Content inside the `<pre>` should not be automatically indented: 

 ```
Line 1
Line 2
```

**Actual results:**

… but it is:

```
Line 1
			Line 2
````

**Your configuration (any details about your system that you think might be relevant)**

CodeKit 3.0.3, Build 25444
Mac OS 10.11.6

**Comment by bdkjones** [comment]
Oy. I do see the issue. The bad news is that this will be a bear to do anything about because the Kit compiler isn't a traditional compiler in the tokenize-lex-parse sense. I will put a fix on my list, but in the meantime I'd see if you can stop using `<pre>` tags as a workaround.

**Comment by bdkjones** [comment]
Ah, the other way to solve this is to make sure the `@import` statement that brings in your Kit file has no leading whitespace before it. As long as it doesn't, CodeKit shouldn't add any leading whitespace to the lines in the file. Note this is recursive to the base file. ALL `@import` statements that are parents of a file with a `<pre>` block need to have zero leading whitespace before them.

**Comment by c330s** [comment]
Thanks! Removing the whitespace does the trick.

In addition to the parent `@import`, I have also to remove the whitespace of preceding `@import`-statements.
