### ISSUE TITLE
Element’s order of `buildSteps[some].itemsToProcess` in config.codekit3 changes silently

### ISSUE THREAD

**Issue by realfish** [bdkjones/CodeKit#288]
In config.codekit3, every time Refreshing the project, the array `itemsToProcess` of some `buildSteps` element changes silently — all the elements in `itemsToProcess` are re-ordered.

![Diff of config.codekit3](https://cloud.githubusercontent.com/assets/3247876/20855407/b3764030-b937-11e6-9f39-b4dd5930ac52.png)

**Comment by bdkjones** [comment]
Can you post a link to download a demo project that shows the issue? I'll take a look.

**Comment by realfish** [comment]
See [realfish/codekit3-issue](https://github.com/realfish/codekit3-issue288). Thank you.

**Comment by bdkjones** [comment]
Ok, fixed for the 3.0.4 release. Thanks.
