### ISSUE TITLE
Slim Logic-less option causes error

### ISSUE THREAD

**Issue by AlexColinaPew** [bdkjones/CodeKit#289]
**Quick, short summary:**
Selecting the 'logic-less' option  for a slim file causes error: run': invalid option: --logic-less
**Expected results:**
A compiled HTML page
**Actual results:**

```
ERROR MESSAGE

Slim: /Applications/CodeKit.app/Contents/Resources/engines/slim/lib/slim/command.rb:18:in `run': invalid option: --logic-less (OptionParser::InvalidOption)
	from /Applications/CodeKit.app/Contents/Resources/engines/slim/bin/slimrb:10:in `<main>'
```

**Exact steps to reproduce:**
Select the 'logic-less' option  for a slim file.

**Comment by bdkjones** [comment]
This is fixed in the next update.
