### ISSUE TITLE
Feature Request: Setting for skipped files (like gitignore)

### ISSUE THREAD

**Issue by supermueller** [bdkjones/CodeKit#293]
Like setting skipped folders in the project settings it would be very helpful to set skipped files too. Additionally with wildcards to define ignore patterns like in gitignore.

**Comment by bdkjones** [comment]
The performance hit for this is not worth it. Regex is dog slow and for projects with 50,000 files it becomes untenable to check each file for a matching pattern. It simply takes too much time. If you need file-level control, the correct approach is to simply set that file's output action to "ignore". There is no need for skipped files; the reason folders can be skipped is to stop the app from recursively indexing directories (like the clusterfuck that is node_modules, where idiot hipsters have found a way to use 80,000 files to do just five things) that would lead to long refresh times.
