### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by timmschroeder** [bdkjones/CodeKit#294]
Message: An error occurred while extracting the archive. Please try again later.

Try to update to 3.0.3 via the App "check for updates". After the download and clicking the "Install and Relaunch" button, the error message occurs.

**Comment by bdkjones** [comment]
Yea. This is expected and covered in several closed issues now. You let 2.x get out of date and your order version does not have cryptographic signatures for 3. Download 3 manually, replace 2, see codekitapp.com/help/upgrading/

**Comment by dlsso** [comment]
It sounds like your suggestion is uninstall 2, install 3. I assume that will blow away your license info. Is there any way to do it without losing license info?

**Comment by bdkjones** [comment]
Come on, give me some credit. Just replace 2.x with 3.0.

**Comment by dlsso** [comment]
Thanks.

To clarify for others: license info is not lost. You can simply extract 3.0 to the same location as 2.x and overwrite.

**Comment by kultigin** [comment]
To clarify: all log is lost, the projects are gone and I guess their settings too :) I do give credit though.

**Comment by bdkjones** [comment]
Settings are NOT lost. Please see codekitapp.com/help/upgrading/ for details.
