### ISSUE TITLE
Couldn't compile simple slim file

### ISSUE THREAD

**Issue by tranvictor** [bdkjones/CodeKit#295]
**Quick, short summary:**
I couldn't get Codekit to compile simple Slim file correctly
**Expected results:**
```
<!DOCTYPE html><html><head><title>Slim Examples</title></head><body><h1>Markup 
examples</h1></body></html>
```
**Actual results:**
```
_buf = []; _buf << ("<!DOCTYPE html><html><head><title>Slim Examples</title></head><body><h1>Markup examples</h1></body></html>"); 
; 
; 
; 
; 
; 
; _buf = _buf.join
```
**Exact steps to reproduce:**
Just add a simple `index.slim` file whose content is:
```
doctype html
html
  head
    title Slim Examples
  body
    h1 Markup examples
```
**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Your settings aren't correct. Read the slim docs and adjust the settings in CodeKit for the type of output you'd like. This looks like the rails-compatible option is enabled.
