### ISSUE TITLE
Archive Extract Fails Update 2.9 > 3.x 

### ISSUE THREAD

**Issue by Timoti** [bdkjones/CodeKit#296]
Upgrading from 2.9 using Codekit [menu] >> Check For Updates… 

Results in: "An error occurred while extracting the archive. Please try again later."

Expected results: v3 Nirvana

Actual results: Error Msg as above

There are no example files: CK had already forgotten all my projects  = something it has done with great regularity (sigh)

MacOS 10.11.6 - macbook retina 15" Mid 2012

IN the meantime, will a manual download  / install be the best approach?

**Comment by bdkjones** [comment]
#294

**Comment by Timoti** [comment]
and I did search… honest! - Thanks Bryan.
