### ISSUE TITLE
Refresh Issue CSS not loading

### ISSUE THREAD

**Issue by vcao** [bdkjones/CodeKit#298]
**Quick, short summary:**
Ran into an issue where the browser refresh initiates, but fails to load the stylesheet. Error code in browser: "Resource interpreted as Stylesheet but transferred with MIME type text/html"

**Expected results:**
Browser refresh with stylesheets

**Actual results:**
Just content, no CSS.

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Demo project. Thanks.

**Comment by vcao** [comment]
Not sure if you would want to download my Vagrant box to try and replicate the issue. Did a short screencast instead.

https://youtu.be/G6EGxoMMBTc

**Comment by bdkjones** [comment]
Ah. You're using an external server. In that case, your server is simply returning the wrong mime type for the asset. You've got something misconfigured, but CodeKit isn't the issue.
