### ISSUE TITLE
Slim Lang output error in v3.0.4 but not in v3.0.3

### ISSUE THREAD

**Issue by aPinix** [bdkjones/CodeKit#299]
## **Slim Lang output error in v3.0.4 but not in v3.0.3
[slim.zip](https://github.com/bdkjones/CodeKit/files/684532/slim.zip)
**

**index.slim**
`doctype html`
`html`
  `head`
    `meta charset="utf-8"`
    `title title`
    `link rel="stylesheet" type="text/css" href="assets/css/styles.css"`
    `script src="assets/js/scripts.js"`
  `body`
    `.wrapper`
      `.box`

**Expected results:**
`<!DOCTYPE html>`
`<html>`
  `<head>`
    `<meta charset="utf-8">`
    `<title>title</title>`
    `<link href="assets/css/styles.css" rel="stylesheet" type="text/css">`
    `<script src="assets/js/scripts.js"></script>`
  `</head>`
  `<body>`
    `<div class="wrapper">`
      `<div class="box"></div>`
    `</div>`
  `</body>`
`</html>`

**Actual results:**
`_buf = []; _temple_html_pretty1 = /<code|<pre|<textarea/; _buf << ("<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <title>title</title>\n    <link href=\"assets/css/styles.css\" rel=\"stylesheet\" type=\"text/css\">\n    <script src=\"assets/js/scripts.js\"></script>\n  </head>\n  <body>\n    <div class=\"wrapper\">\n      <div class=\"box\"></div>\n    </div>\n  </body>\n</html>"); `
`; `
`; `
`; `
`; `
`; `
`; `
`; `
`; `
`; `
`; _buf = _buf.join`

**Exact steps to reproduce:**
Just save and generate index.html

**A link to download a simplified project or file that shows the issue:**
No need, just use the code above or use the **ZIP** in attach

**Your configuration (any details about your system that you think might be relevant)**
Default new standard config does this

**Comment by bdkjones** [comment]
Yea, I've had a few reports of this now. I have no idea what's going on, but I'm looking into it today.

**Comment by bdkjones** [comment]
Well, I've got no idea what's causing this, but I can reproduce it from the command line using Slim 3.0.7, so it appears to be an issue with Slim and not CodeKit. I've opened an issue on the Slim repo to see what's wrong:

https://github.com/slim-template/slim/issues/747

**Comment by bdkjones** [comment]
If I don't hear anything within a day, I'll probably roll Slim back to the last version I know worked, which is whatever version was in CodeKit 2.9.1. Ruby-based tools are kind of a nightmare.

**Comment by bdkjones** [comment]
mmm, looks like it's the `--compile` flag. I dunno why it's suddenly causing problems; it's been there all along, but removing it with Slim 3.0.7 solves the issue. I'll push an update this weekend to get this fixed.

**Comment by aPinix** [comment]
It seems to be ok in v3.0.5. There's another issue with Slim now, it doesn't hold up with tags (#{tag}). I created another issue. Still using v3.0.3. Keep up the good work mate ;)
