### ISSUE TITLE
CodeKit asking for registration again

### ISSUE THREAD

**Issue by darylknight** [bdkjones/CodeKit#300]
**Quick, short summary:**
CodeKit periodically forgets that it's been licensed and asks for my key again

**Expected results:**
Register CodeKit once and forget about it

**Actual results:**
CodeKit has asked for my license information twice since I bought a license for v3

**Exact steps to reproduce:**
None, sorry - it seems random

**Your configuration (any details about your system that you think might be relevant)**
OSX Sierra, 10.12.2. MacBook Retina 13", 2013

**Comment by bdkjones** [comment]
mmmm, that's not something anyone else has reported. The license information is stored in the app's plist file in ~/Library/Preferences

If you switch user accounts, you'll need to enter your license on each account. Or if you delete the app's plist file.

**Comment by darylknight** [comment]
I only have one user account on my machine. Since reporting this yesterday and re-adding my license info, I started work again this morning and CodeKit has this in the top right hand corner:

![image](https://cloud.githubusercontent.com/assets/1250017/21717947/08961d6c-d40c-11e6-9087-0c5e37664c05.png)

But when I click CodeKit > Register CodeKit, it already has my license information there

**Comment by mcansh** [comment]
this happened to me the other day, though quitting codekit and reopening it solved it

**Comment by bdkjones** [comment]
Hmm. The only thing I can think of is a corrupt plist file. Quit CodeKit, then run this in the Terminal:

    defaults delete com.incident57.CodeKit3

It's case-sensitive. You'll need to reconfigure your app preferences and new project defaults after doing the above.

**Comment by darylknight** [comment]
This might be a wider issue with my laptop - I've just had Transmit ask for license info again too...

**Comment by bdkjones** [comment]
Cool. Sounds like we've isolated this to your Mac.

**Comment by darylknight** [comment]
Update - I had this again today. CodeKit told me I have 5 days left to register, but when you click "Register CodeKit", my license information is already in there. Closing and re-opening CodeKit solves the issue.

![image](https://cloud.githubusercontent.com/assets/1250017/23456644/f15054c4-fe7c-11e6-9820-95a6833626bf.png)
