### ISSUE TITLE
Server doesn't list directory contents

### ISSUE THREAD

**Issue by adispezio** [bdkjones/CodeKit#301]
In Codekit 2, I was able to launch a server and navigate the directory structure of folders and files. In Codekit 3, I'm only able to get the server to load when serving an html page (eg, previewing a directory without an index.html file causes the server to timeout and Codekit loses connection).

Expected results:
When clicking preview, if no html index is specified, list the contents of the directory.

Actual results:
When clicking preview, if no html index is specified, the page never loads and not content is displayed (no network activity). Eventually Codekit loses connection (displays the orange warning).

Steps to reproduce:
1. Add a project to Codekit with no index.html in the root and a couple subdirs. 
2. Click the Preview button

Config:
Fresh MacOS 10.12.2 (Sierra)
Fresh Codekit 3 (no custom config)

**Comment by bdkjones** [comment]
Mmm, that's definitely not the case over here and no one else has reported this. Do you have any crap like Little Snitch running? Security software? Browser plugins? Etc.

**Comment by adispezio** [comment]
Thanks for the quick reply. I do have company-installed anti-virus (Sophos) but wasn't an issue with CK2. Otherwise it's a pretty fresh install. I did install node 6 but can't see how that would be an issue.

I'll try and fresh install and see if that helps. Thanks!

**Comment by bdkjones** [comment]
Yep. The first thing to do is kill the security garbage. It's likely interrupting the HTTP Request/response traffic.

**Comment by adispezio** [comment]
Bingo! Relaxed the web security, restarted and I'm seeing the dir contents. Thank you!
