### ISSUE TITLE
build process overwrite .gitignore in build folder

### ISSUE THREAD

**Issue by feekApp** [bdkjones/CodeKit#302]
Hi Bryan

I'am using OSX 10.11.6 and CodeKit 3.0.5 build 25504

**Quick, short summary:**

I have a .PUG (formally .JADE) project with a `/build` folder. Initially in the `/build` folder your .gitignore is placed with the content:

```
*
!.gitignore
```

In my project root folder I have also a .gitignore file containing:

```
uc.psd
```

When building the project, the .gitignore in the `/build` folder is overwritten by the .gitignore file of the project root. So the .gitignore file in the `/build` folder becomes 

```
uc.psd
```

**Expected results:**

the .gitignore file in the `/build` folder remains after building the project:

```
*
!.gitignore
```

Regards,
Feek

**Comment by bdkjones** [comment]
Should be a very simple solution: select the `.gitignore` file in the project root and set its Output Action to `ignore` instead of `copy`.

**Comment by feekApp** [comment]
Hi Bryan,

thnx for the quick reply.

Yes thats a solution. I already was writing a language hook for the .gitignore files. Maybe a idea for setting a language setting for .gitignore in CK by default? Line GIF JPG and PNG?

Again thnx for the great app!

Regards,
Feek

**Comment by me-benni** [comment]
@feekApp you don't set this in the language settings, but in the file explorer itself.
Just select the `.gitignore` and set it to `Ignore it` right under Output
![screen shot 2017-01-18 at 2 01 21 pm](https://cloud.githubusercontent.com/assets/825660/22065047/a5006e86-dd86-11e6-997e-beaa42de4d08.png)

**Comment by feekApp** [comment]
Hi @me-benni 

yes, I know, 

But when you want to set this setting for all future `.gitignore` files (in *"Edit Defaults for New Projects"*), you have to set a kind of Language rule.

Kind regards,
Feek

**Comment by me-benni** [comment]
ooohhh.. I see
