### ISSUE TITLE
Feature Request: TinyPNG Compression

### ISSUE THREAD

**Issue by czillgens** [bdkjones/CodeKit#303]
JPEG aren't reduced further in size when saved from current Photoshop Version.
But I still can get the file size smaller with tinypng.com (~ 10-20 %).
Maybe there is a way to integrate it into CodeKit?

**Comment by bdkjones** [comment]
Yep. The developer of this and tinyjpg won't license their software for inclusion in apps. Additionally, the reason you get an extra 10% reduction is that this tool reduces image quality; it's not a lossless optimization. Until they're willing to license, I can't do anything with them.
