### ISSUE TITLE
COMPASS compilation warns of deprecated use - but deprecated use inside CodeKit package

### ISSUE THREAD

**Issue by ortonomy** [bdkjones/CodeKit#305]
**Quick, short summary:**

> Compass: Compiled successfully, but with warnings:
> 
> DEPRECATION WARNING on line 87 of /Applications/CodeKit.app/Contents/Resources/engines/compass/compass-core/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified
> in a future version of Sass. To preserve the current behavior, use quotes:
> 
>   unquote('"$moz-"#{$experimental-support-for-mozilla} "$webkit-"#{$experimental-support-for-webkit} "$opera-"#{$experimental-support-for-opera} "$microsoft-"#{$experimental-support-for-microsoft} "$khtml-"#{$experimental-support-for-khtml}')
> 
> You can use the sass-convert command to automatically fix most cases.
> 

**Expected results:**
Compass compiles without warning

**Actual results:**
Compass compilation causes above error.

**Exact steps to reproduce:**
Use string interpolation in any SCSS files with COMPASS installed in the project.

**A link to download a simplified project or file that shows the issue:**
N/A

**Your configuration (any details about your system that you think might be relevant)**
N/A

**Comment by bdkjones** [comment]
Yep.

Compass itself has been end-of-lifed and this issue will not be fixed because Compass is no longer actively developed. You should drop Compass immediately and switch to other frameworks such as Bourbon. That will also let you compile with Libsass instead of Ruby Sass, which will change your life.

**Comment by bdkjones** [comment]
I should add: dropping Compass will, very soon, not be optional. The next major Sass revision will turn these deprecations into errors and Compass will flat-out not work anymore. I would not procrastinate on the migration.

**Comment by ortonomy** [comment]
@bdkjones - OK. That's fair enough. I saw that Compass had been 'end-of-lifed', but it was still supported in CodeKit. When these warnings turn to errors, will you also remove support from CodeKit? This will likely avoid anybody ending up in the same situation.

**Comment by bdkjones** [comment]
Yes. When Compass no longer officially works with the versions of Sass in CodeKit, it will be dropped from the app.
