### ISSUE TITLE
Cannot rename project

### ISSUE THREAD

**Issue by PaulPichaureau** [bdkjones/CodeKit#307]
When I try to rename a project by clicking on its name then right click and "Rename "nomeoftheproject"" nothing happens.

**Comment by bdkjones** [comment]
Yea, one other guy had this problem and it turned out there was some accessibility setting on his Mac that was the cause. Can't recall the details, but there should be a closed issue about it. This behavior is not what 99.99% of users, including me, see.

**Comment by PaulPichaureau** [comment]
It's https://github.com/bdkjones/CodeKit/issues/243
