### ISSUE TITLE
[v3.0.4] CodeKit sometimes loses "Generate a source map" setting.

### ISSUE THREAD

**Issue by mpiecko** [bdkjones/CodeKit#309]
Unfortunately i cannot reproduce the error, since it seems to happen randomly during work. The only time it happens for sure is, when i quit CodeKit and restart it again.

I have a JS file, that only prepends other JS files. This file has the "Minify the output" and "Generate a source map" option checked. And it usually works.

![image](https://cloud.githubusercontent.com/assets/209899/22321926/c60ccfee-e398-11e6-9de8-f9bfdf4c72d0.png)

For some reason, sometimes, and always when i restart CodeKit, the "Generate a source map" option is off again.

![image](https://cloud.githubusercontent.com/assets/209899/22321948/eff9c23a-e398-11e6-9a85-e279231262a5.png)

I do not use GIT in that project and this file is not touched by other tools at the same time. CodeKit is the only JS/CSS processor used.

**Comment by bdkjones** [comment]
Which editor are you using to save the file and is the project folder on your local disk or a remote, NAS volume?

**Comment by mpiecko** [comment]
We use PHPStorm. The project is always on a local drive. The only extra thing is, that we use Parallels with a Linux instance, which then servers the files from that directory (local development). But then it's strange, that only this setting is affected. We have no problems with other options in CodeKit.

**Comment by bdkjones** [comment]
In Project Settings > Languages > Javascript is the "generate source map" default on or off?

**Comment by mpiecko** [comment]
Thanks for helping us out.

Default is Off!


Bryan Jones <notifications@github.com> schrieb am Di., 31. Jan. 2017 um
21:01:

In Project Settings > Languages > Javascript is the "generate source map"
default on or off?

Sent from my iPhone

> On Jan 30, 2017, at 23:33, Michael Piecko <notifications@github.com>
wrote:
>
> We use PHPStorm. The project is always on a local drive. The only extra
thing is, that we use Parallels with a Linux instance, which then servers
the files from that directory (local development). But then it's strange,
that only this setting is affected. We have no problems with other options
in CodeKit.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bdkjones/CodeKit/issues/309#issuecomment-276474968>,
or mute
the thread

**Comment by bdkjones** [comment]
Yea, so what’s LIKELY happening here is that your complicated setup for where these files reside is saving file changes in a way that causes the macOS kernel to report to CodeKit that the file has been deleted, then report a new file has been created in the same spot. CodeKit responds to the delete event, nukes the file from the ones it has settings for, then responds to the create event, creating a new file with your defaults from project settings. Flip the generate source map default on.
