### ISSUE TITLE
CodeKit forgets compile paths when switching branches

### ISSUE THREAD

**Issue by darylknight** [bdkjones/CodeKit#310]
**Quick, short summary:**
config.codekit3 is not version controlled, but every time I switch branches, CodeKit forgets where to compile files to.

**Expected results:**
It should always compile them to where I set them to, regardless of switching branches.

**Actual results:**
Whenever I delete or switch git branches, codekit starts compiling sass and javascript files to the default locations again

**Comment by bdkjones** [comment]
You're not pausing CodeKit before switching branches, so it's doing exactly what it's programmed to do: respond to file-change events in realtime. See the Help page about working with Version Control on codekitapp.com.

**Comment by darylknight** [comment]
Of course, my fault! Sorry I missed the help section on working with Git - that makes sense. Thanks :)
