### ISSUE TITLE
Feature request: ability to output files to multiple paths

### ISSUE THREAD

**Issue by tyssen** [bdkjones/CodeKit#312]
I'm working on a project where there are different sites that reside in a single global project folder (they share styles and scripts) and would like to be able to save a master SASS/LESS file and have the various different sites' CSS files updated at the same time, e.g. /siteA/css/main.css, /siteB/css/main.css etc.

Or is something like that already possible?

**Comment by bdkjones** [comment]
You'd want each site to have its own Less file (although at this point you should really be using Sass) and have each of those less files import your master, shared file. When the master file is saved, all the other less files will recompile to capture the changes. You can also use CodeKit Frameworks to share assets across projects.
