### ISSUE TITLE
Slim doesn't compile tags (#{tag}) on v3.0.5

### ISSUE THREAD

**Issue by aPinix** [bdkjones/CodeKit#313]
**Quick, short summary:**
With declared variables inside a Slim file, when used tags calling the variables, Slim doesn't compile like it should.

**index.slim**
```slim
-title = 'website'

doctype html
  html
    head
      meta charset="utf-8"
      title #{title}
    body
      .wrapper
      .box
```

**Expected results:**
```html
<title>website</title>
```

**Actual results:**
Doesn't compile

**Exact steps to reproduce:**
Just use any tag as described above

**Comment by bdkjones** [comment]
Did you even read the error message that CodeKit displayed? Your issue has nothing to do with the variable. The error message that Slim throws is "unexpected indentation before `html`". Remove the leading indent before `html` and everything works fine.

**Comment by bdkjones** [comment]
Ah, in that case, that’s a known issue with 3.0.5. I’ll be updating it late tonight or tomorrow to bring back support for `include` in Slim files.
