### ISSUE TITLE
Feature Request: Add Pause CodeKit to Dock Context Menu

### ISSUE THREAD

**Issue by matt3224** [bdkjones/CodeKit#316]
Hey,

It would be really handy to be able to pause CodeKit simply by right clicking the dock icon.

Cheers!

![screen shot 2017-02-06 at 10 31 03](https://cloud.githubusercontent.com/assets/2401925/22643719/a0b048d0-ec57-11e6-8f44-996678f27417.png)

**Comment by bdkjones** [comment]
Not a bad idea. I'll do it.

**Comment by bdkjones** [comment]
Implemented for the next release:

<img width="457" alt="screen shot 2017-02-06 at 15 31 26" src="https://cloud.githubusercontent.com/assets/926566/22671106/6d74f752-ec81-11e6-88ad-ba749b37fdaf.png">
