### ISSUE TITLE
Possible Improvements for bower_components

### ISSUE THREAD

**Issue by TC72** [bdkjones/CodeKit#319]
I had started to write a very longwinded description of a bug but I've figured out what CodeKit is doing and reworded it as a request for a change.

I was getting confused after creating a foundation project by how CodeKit was able to import files required by the included scss/app.scss file. That file has 3 imports:
@import 'settings';
@import 'foundation';
@import 'motion-ui';

The CodeKit UI for "Linked Files" only shows "_settings.scss". I realise now that CodeKit finds the other 2 files because of bower.json files which tell it which files to use. For example bower_components/foundation-sites/bower.json file:
  "main": [
    "scss/foundation.scss",
    "dist/js/foundation.js"
  ],

It's great that this works but the UI not showing them in the linked files can lead to confusion. If it where possible to show them then that would be a great fix.

The main thing I wanted to ask was whether CodeKit could make use of this "main" definition to simplify using bower components. Instead of showing us all the files inside the bower_components folder could there be an option to "Only show Main files". In this example when you look inside the bower_compnents directory for foundation-sites you would only see the files foundation.scss and foundation.js. It would make it much clearer to people how to include the required files of a component into their code.

**Comment by TC72** [comment]
Just wanted to add as another note this could be toggle via an option when you right click on the main folder on the bower_component. There could be a setting for the project which says "Only show Entry-Point Files." Then the option menu on the folder of the component can toggle "Show All Files" and "Only Show Entry-Point Files.

I also found out these main files can be found quite easily using bower tools:
bower list --paths
bower list --json

**Comment by bdkjones** [comment]
Nope. CodeKit doesn't read the bower.json file. Essentially, there's some magic behind the scenes that detects whether a project is using Foundation and, if so, tells the Sass compiler to check some hard-coded paths. Similar trickery happens for other frameworks like Susy, Bourbon, etc. That's how the "it just works" happens.

**Comment by bdkjones** [comment]
Hiding files as suggested increases complexity and the potential for confusion down the road. As in: "Why isn't CodeKit showing all my files?"

**Comment by TC72** [comment]
Seems like using "bower list" either paths or json would make your life easier , you wouldn't need to hardcode and it'd work for more bower components.

On the other part of showing only the Entry-point files seems like something which could be off by default but people who understand what it does could switch it on.

I almost gave up on using bower_components because of these kinds of issues and took a lot of reading to be comfortable with what goes on. Handlebars was the bower_compnent which almost made me give up. It turns out the version you get from bower has no dist folder and no Entry-point files. It's useless unless you have a full build system to create the dist files. It's not usable in a normal CodeKit workflow and the easiest option is to download a dist version from somewhere else. (In the end I installed with "npm install handlebars -g" and copied the handlebars.js from there to make sure I used the same version for pre compiling which was simple thanks to CodeKit hooks + other languages.)

**Comment by bdkjones** [comment]
Yea, it's a performance thing. Compiling would be a little slower if *every* time it happened, CodeKit opened a json file, parsed it, resolved paths from the CWD, added those to the include paths, etc. 

I'd have to look at the performance impact.

**Comment by bdkjones** [comment]
So 3.8 will now show the full relative path to files in bower_components. But 3.9 will formally deprecate bower and move to npm. Bower isn’t being removed; it’ll stick around for backwards compatibility. As such, I’m closing the issue. Thanks!
