### ISSUE TITLE
Double clicking javascript Linked Files doesn't behave correctly

### ISSUE THREAD

**Issue by TC72** [bdkjones/CodeKit#320]
In CodeKit preferences there is an option for what to do when files are double-clicked, either show the file in the Finder or open with system default app.

This works correctly for files in the "Linked Files" Imports for sass files. When you double click Linked Files for javascript either prepend or append nothing happens, but it does work for ES6 Imports.

It would be nice if there where other options available on these files by right clicking on them, similar to right clicking on files in the normal file list:
Show in Finder
Open With >

The really useful option would be to "Show in CodeKit". That way when you find a javascript file that has linked files it would be easy to get to the linked file and see if it also includes other files. Right now the only option is "remove".

Overall it would be really nice if you could do more with the linked files, select multiple and copy and paste for example to quickly create a similar file for testing. I've resorted to editing the .codekit file before to get this to work. It also took me 6 months to work out what the blue badge means even with the tooltip ;-)

**Comment by bdkjones** [comment]
The double-click failure was definitely a bug. It's fixed for the next release. The only types of files affected by this bug were CoffeeScript and JavaScript; double-clicking imported files in other types of files works as expected.

As for the menu with additional options: I'll take a look at it. Implementing that is a lot of grunt work.
