### ISSUE TITLE
Include directives don't include files.

### ISSUE THREAD

**Issue by robsaunders** [bdkjones/CodeKit#322]
**Quick, short summary:**
Using include in a slim file actually creates the directive as a tag in output.

**Expected results:**
File should be imported and inserted correctly.

**Actual results:**
The command is interpreted as a tag, as the following:
```html
<include>head</include>
```

**Exact steps to reproduce:**
Create a .slim file with the following text:
```haml
include head
```

**Your configuration (any details about your system that you think might be relevant)**
Using codekit 3. This exact code worked on codekit 2.

Notes:
This happens whether you use hidden partials starting with an underscore, or put them in a new directory, etc etc. And under 'imports:' on the file information panel, it DOES show it as thinking it should be included, but it's not.

There's NO way of fooling the compiler into accepting it, you have to resort to dropping into ruby as such, this fixes it but the docs say NOT to do this, however for now it's the only way:

```ruby
== Slim::Template.new('_head.slim').render
```

EDIT:
It looks like sass @import doesn't work either. So V3 is riddled with bugs as well? (I came across really basic fundamental bugs in v2, which the dev blamed on mac os). I'm not sure how to provide more information except that I am running a fairly clean / new system, nothing special going on, and just installed codekit fresh.

I can reproduce this entire problem by just creating a new project, trying to include one file type with another with one line on each file (2 files total), not even touching any codekit configuration or anything.

test.slim:
```slim
h1 hi
include _new
```

_new.slim:
```slim
h1 this is my file
```

output:
```html
<h1>hi</h1><include>_new</include>
```

**Comment by bdkjones** [comment]
Yea, will have an update out this evening to address this.

**Comment by bdkjones** [comment]
Tested with 3.2. Slim includes work just fine when targeting `*.slim` files. This is a bug when targeting non-slim files, but that is addressed in the next release.

As for `@import` in Sass: that's working perfectly.

**Comment by robsaunders** [comment]
In the time that passed (6 months?) I've moved on and built my own generator which I prefer. Thanks though.

**Comment by bdkjones** [comment]
Mmm, the fix was actually implemented a long, long time ago. I'm just now getting around to updating GitHub.
