### ISSUE TITLE
@codekit-prepend without minifying?

### ISSUE THREAD

**Issue by VIEWSION** [bdkjones/CodeKit#324]
Hi!

Is there a way to prepend (already minified) .js files without processing them again? It is often not necessary and takes just too long....

Best,
Matthias

**Comment by bdkjones** [comment]
What you'd want to do is create a master JS file that prepends the output file of the chain you want to minify. In that master file, prepend your already-minified files in the appropriate place.

**Comment by VIEWSION** [comment]
Hey! Quick replay ;)
I want a master file with prepended ... let's say jquery/moment/other... libs   and a little of my own code. My own code is processed in a second, but if I also want some other files included, it takes quite long. I  just want to prepend without any processing - just prepending.

**Comment by bdkjones** [comment]
Oh, sure. Just set the Output Action to "Process" on the file with all your prepends, then turn off minification and transpiling for that file.
