### ISSUE TITLE
Browser Refresh issue with CSS only.

### ISSUE THREAD

**Issue by nicolastaffin** [bdkjones/CodeKit#330]
Hi Brian,
maybe something there, if it is not an issue, maybe can you help…

**Quick, short summary:**
Browser refresh works for HTML change in all browsers, but not CSS. Inspectors shows something happens on css save (html gets a codekit refresh class…) but CSS is not refreshed nor animated of course until real browser-command-R refresh. Dont' know what changed in my config or codekit.

**Expected results:**
Usual nice Codekit CSS refresh animated

**Actual results:**
something is triggered, but no refresh for css, until command-r. The weird thind is it happens all the same in chrome, FF, safari

**Exact steps to reproduce:**
Create new HTML, link to a CSS, edit LESS or CSS, save… nothing happens until manual refresh, edit html, browser refreshes. i did it on a clean file to test

**A link to download a simplified project or file that shows the issue:**
<html>
	<head>
		<style>
		@import url("style.css");
		</style>
	</head>
	<body>
		<h1>hello</h1>
	</body>
</html>

**Your configuration (any details about your system that you think might be relevant)**
old retina 15" with fan noise, El capitan, CodeKit 3.0.5
accessed the page through your preview button ( http://mycomputer.local:5757/ )

**Comment by bdkjones** [comment]
Use `<link>` tags to bring in your Stylesheets. Do not use `<style>` blocks.

**Comment by nicolastaffin** [comment]
Shame on me. The worse is i usualy do. Thanks a lot.

**Comment by bdkjones** [comment]
No problem. Inlined styles like this can't really be reloaded safely on certain browsers. Someday, I'll drop support for those. But using `<link>` tags is generally the better approach.
