### ISSUE TITLE
App won't open, just bounces on doc and stops responding

### ISSUE THREAD

**Issue by thelonewolf** [bdkjones/CodeKit#332]
Installed latest update and now app won't open just bounces on the doc and if you open force quick it shows it as not responding.

Need this fixed ASAP as I depend on this app for work and don't want to have to switch Grunt or Gulp.

**Expected results:**
App opens and works normally

**Actual results:**
Nothing app doesn't work

**Exact steps to reproduce:**
Installed latest version, even tried downloading a new file from the website, neither will open.

**Your configuration (any details about your system that you think might be relevant)**
Late 2012 iMac 27-inch, 32 GB Ram, 3.4 i7. OS X 10.11.6

**Comment by bdkjones** [comment]
It's migrating data. If you have a lot, it can take some time. Your other option is to quit and then launch the app while holding the `option` key, which will clear everything out and give you a fresh start.

**Comment by thelonewolf** [comment]
Ok thanks. Will try that, thank you.
