### ISSUE TITLE
Total written lines of code

### ISSUE THREAD

**Issue by dennishelbig** [bdkjones/CodeKit#335]
Is it possible to get a count of the written lines of code in a project?

Since CodeKit is already scanning all files, I through it would be great if it could count the written lines and show a total somewhere, excluding bower components and minified files of course. 
Maybe excluding marked folders / files as well.

Keep up the great work.

**Comment by bdkjones** [comment]
Mmmm, this is more appropriate for an IDE. CodeKit only opens and scans files that it knows can be imported into others; it doesn't read all files.

There are also several third-party apps that will do this. I used one on CodeKit itself. 879,000 lines of code last time I checked.
