### ISSUE TITLE
Codekit v3.0.8 | Sass Glob @import not working

### ISSUE THREAD

**Issue by aPinix** [bdkjones/CodeKit#336]
## **Quick, short summary:**
Problem with **Sass glob @import**.
But on the project shows files on imports section.

## **Expected results:**
```sass
@import 'mixins/*' // work like previous versions, at least v3.0.3 did
```

## **Actual results:**
```sass
@import 'mixins/*' // not working on v3.0.8
```

## **Exact steps to reproduce:**
Just import a folder with a couple of sass files in it from a main file.

## **A link to download a simplified project or file that shows the issue:**
**ZIP** file on **attach**: [sass_proj.zip](https://github.com/bdkjones/CodeKit/files/853658/sass_proj.zip)
![error_log](https://cloud.githubusercontent.com/assets/698523/24085823/c9767a28-0cfa-11e7-81e5-3030b451897e.png)
![linked_files](https://cloud.githubusercontent.com/assets/698523/24085824/c976c424-0cfa-11e7-8f94-1d1018aade01.png)

**Comment by bdkjones** [comment]
Globbing has never been supported with Libsass, in any version of CodeKit. You can turn off Libsass and use the old Ruby compiler, which does support it through a plugin.

However, globbing has been officially rejected by the Sass team for a whole list of really good reasons. I recommend dropping the globs and being explicit in your imports.

**Comment by aPinix** [comment]
You're right. Thanks for your response and specially for your awesome software 👍

**Comment by William-Owen** [comment]
I am unable to get globbing working after reading this in the help section 

> Import Globbing
> CodeKit supports Sass "import globbing". If you write @import 'someFolder/*', all Sass files in someFolder will be imported in alphabetical order. "Multi-level" globbing such as folder/**/*, however, is not supported because it's a terrible idea.

from https://codekitapp.com/help/sass/

However, I now read this and am unsure if this feature is or is not currently supported by Codekit. Perhaps updating the documentation to clarify if this only works with the old Ruby compiler would be useful.

**Comment by bdkjones** [comment]
Thanks; I'll take a look. To use the old Ruby compiler, simply turn off Libsass under Project Settings > Languages > Sass
