### ISSUE TITLE
Can't perform any action "launch path not accessible"

### ISSUE THREAD

**Issue by WilliamMayor** [bdkjones/CodeKit#337]
**Quick, short summary:**
I can't build my CSS or JS, or download bower components. When I try there's an error, most commonly the error says "launch path not accessible".

**Your configuration (any details about your system that you think might be relevant)**
When I tried to open CodeKit this morning I got a macOS error that said the CodeKit couldn't be opened. A quick Google suggested that the binaries in CodeKit.app/Content/MacOS needed to be given the execute bit. I did this:

    $ chmod +x CodeKit.app/Content/MacOS/CodeKit

Sure enough the application now opens but none of the features seem to work.

What do?

Sorry for not following the template :(

**Comment by bdkjones** [comment]
Sounds like you've got serious permissions issues on your Mac. Make sure your account is an admin account. Trash CodeKit, download a new copy, unzip it with the macOS unzip utility, then move it to your applications folder with Finder. ONLY FINDER. Using third party apps is how you get permissions on the binary modified by macOS. Also, quit any stupid security software that might be running and modifying the permissions of all the executables in CodeKit's bundle. Security software on a Mac is a waste; it's UNIX.

**Comment by WilliamMayor** [comment]
@bdkjones Thanks! I removed then re-installed and everything seems to be working now. Pretty obvious solution in hindsight, thanks. No idea what would have caused these permission issues. I don't have any stupid security stuff (macOS is based on UNIX, it would be a waste), nor do I use any third party installers/uninstallers.

**Comment by bdkjones** [comment]
Eh, maybe some bits got twiddled in the download. Glad you're up and running!
