### ISSUE TITLE
Google Web Starter Kit hangs on install -> v3.0.8

### ISSUE THREAD

**Issue by byronpolley** [bdkjones/CodeKit#338]
**Quick, short summary:**
WSK doesn't install

**Expected results:**
WSK should install.

**Actual results:**
Doesn't. Falling back to build 3.0.6 and it works on my system..

**Exact steps to reproduce:**
1. New Google Web Starter Kit project...

**Your configuration (any details about your system that you think might be relevant)**
MacOS 10.12.3 on 2014 13" MBP.

**Comment by bdkjones** [comment]
Working perfectly over here on 3.0.8. Please record a screencast showing the issue.

**Comment by bdkjones** [comment]
Unable to reproduce.
