### ISSUE TITLE
Can't copy link to the documentation

### ISSUE THREAD

**Issue by nickensoul** [bdkjones/CodeKit#341]
When I'm do a right mouse click on the Documentation link in CK and select 'Copy', then buffer is empty. But normal click fires as expected.

**Expected results:**
Buffer contains a link
**Actual results:**
Buffer is empty.
**Steps to reproduce:**
– open 'Languages' group in project settings
– select something (Kit for ex.)
– right click on Documentation
– copy
– try to paste somewhere (browser address bar for ex.)
![screenshot at mar 24 17-00-31](https://cloud.githubusercontent.com/assets/14836054/24300535/d71551d8-10bd-11e7-9c14-90b5bd324a0c.png)

﻿﻿CK v.3.0.8, build 25704
Hope this is not a dublicate.

**Comment by bdkjones** [comment]
Not a duplicate! I've fixed this for the next update; great catch!
