### ISSUE TITLE
CodeKit randomly loses files from project folder

### ISSUE THREAD

**Issue by kevinoes** [bdkjones/CodeKit#342]
CodeKit randomly "loses" SCSS and CSS files in a directory it's watching. I need to click the refresh icon to make it "find" the lost files again. It then works like it should until it randomly loses the SCSS and CSS files again. Seems to do it at least once per 30 minutes.

I'm not sure how you reproduce this. I've tried removing and adding the folder again, with the same result. CodeKit is configured to only watch the SCSS and CSS files in that folder.

I'm on macOS 10.12.3. Using latest version of CodeKit.

**Comment by bdkjones** [comment]
1. Are you performing a Git action without pausing the app?

2. Are you using some Java-based editor like phpstorm to save the files?

3. Is the project in some sort of syncing folder like Dropbox?

**Comment by kevinoes** [comment]
1. Yes, there are GIT actions happening. As far as I know it's mostly pull and commits.

2. No, using Atom.

3. No, no other actions (outside GIT) is happening on the folder.

**Comment by bdkjones** [comment]
Yep: https://codekitapp.com/help/git/
