### ISSUE TITLE
Feature request: Process kit files when changing inlined CSS/JS

### ISSUE THREAD

**Issue by heartfield** [bdkjones/CodeKit#344]
**Quick, short summary:**

Often I place my CSS inline when building sites and using Codekit I do it like this: 

```
<style> 
   <!-- @include "/build/css/main.css" -->
</style>
```

This works, also for inline Javascript, but the problem is that Codekit doesn't know it has to process the kit files when the CSS is changed when you inline the CSS like this in your kit file. I have to manually change the kit file (e.g. add a new empty line) to get the changed CSS processed into the output.

**Expected results:**

Process the kit files when changing inlined CSS (or JS)

**Actual results:**

Codekit doesn't reprocess kit files when inline CSS is changed

**Exact steps to reproduce:**

See my code example above

**Comment by bdkjones** [comment]
This is bad practice. It slows page rendering. Use `<link>` tags.

**Comment by heartfield** [comment]
For small files and critcal CSS above the fold (<14Kb) it should be fine.

**Comment by bdkjones** [comment]
I don't have the links handy, but I spent time investigating this a few years back. If I recall correctly, this approach literally causes the browser to discard its first rendering pass and start from scratch when it encounters the late `@import`. By contrast, the `<link>` tag does not do this, which improves page rendering performance. "Should be fine" is not "best practice". There's definitely a correct way to do this.

**Comment by heartfield** [comment]
Here is the recommendation for inline CSS by [Google Pagespeed Insights - Optimize CSS Delivery](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery).

Some research by [Filament Group](https://www.filamentgroup.com/lab/performance-rwd.html).

**Comment by bdkjones** [comment]
Well yea, but you're not inlining the styles. You're still using @import, which is part of the CSS spec and causes a roundtrip HTTP request to resolve the imported file, unless things have changed since I last researched this. If you're looking to inline styles, the actual rules have to be on the page.

**Comment by heartfield** [comment]
I think there's a misunderstanding. I'm not using @import, I have a `<style>` tag in the `<head>` of my html file. I let Codekit include the output (all the style rules that are compiled into in main.css) in this `<style>` tag. I know this is not the way Codekit is intended to work but it's the only way I know for getting CSS inline with Codekit.

**Comment by heartfield** [comment]
Yes, a Kit file that includes the minified CSS. (I mistakenly said html file in the last comment)

**Comment by oppenheimer-** [comment]
@bdkjones
Now that we can import file contents even from muted folders, would it be possible to "late import" generated css/js files?

Something like that: `<!-- @late-import css/above_the_fold.min.css -->`
I imagine it like a post-processing step with putting a hashed placeholder on first generation pass and then later on replacing that with the corresponding source.

**Comment by bdkjones** [comment]
I’m afraid I don’t follow. Additionally, the puck is moving towards HTTP2, in which separating “critical styles” from the rest of content is no longer a performance benefit.
