### ISSUE TITLE
Bug: Relative Kit Output doesn't work

### ISSUE THREAD

**Issue by git-no** [bdkjones/CodeKit#345]
**Quick, short summary:**
A relative output folder setting is not used when it is relative to the roots folder and point above.
Output folder is set **this folder** "../public"

**Expected results:**
html file creation is one level up the root folder within the folder public.

**Actual results:**
It creates a public folder within the project root folder.

**Exact steps to reproduce:**
1. Go to project settings, section Languages Kit.
2. Set Output folder to **this folder**: ../public
3. create within the project folder a file, call it e.g. index.kit.
4. Save the file to force compiling by Codekit.

**Comment by bdkjones** [comment]
This behavior is correct. CodeKit will not honor relative paths that go above the Project's Root Folder. There are several reasons for that, including safety.
