### ISSUE TITLE
Babel ES2015 Preset causes error in bower_components/what-input/dist/what-input.js

### ISSUE THREAD

**Issue by bowcom** [bdkjones/CodeKit#348]
**Quick, short summary:**
Using Minify and Babel with the ES2015 preset to transpile a file like this:
// @codekit-prepend  '../bower_components/jquery/dist/jquery.js'
// @codekit-prepend  '../bower_components/what-input/dist/what-input.js'
// @codekit-prepend  '../bower_components/foundation-sites/dist/js/foundation.js'
// @codekit-prepend  '../js/app.js'
$(document).ready(function(){ 
	alert("Help");
}); 

When the page with the file is loaded I end up with an on page js error of:
[Error] TypeError: undefined is not an object (evaluating 't.whatInput=n()')
	e (main.min.js:9:333)
	Global Code (main.min.js:9:348)

If I uncheck the ES2015 Preset and manually check all of the ES2015 Transform Plugins then it 
it works without causing a js error.  Maybe there is some other plugin that is activated within the preset that is not available as a manual option.

**A link to download a simplified project or file that shows the issue:**
Sorry, not far enough into the project to have anything significant to show.  This was sort of the first step in my learning process.  Great video on Babel by the way.

**Your configuration (any details about your system that you think might be relevant)**
I just used the CK3 Foundation setup and then added the Foundation Fonts.  Nothing special or real complicated.

**Comment by bdkjones** [comment]
Is this still an issue? I'd have to imagine they fixed this by now.
