### ISSUE TITLE
Autoprefixer fails when using disabling options

### ISSUE THREAD

**Issue by heartfield** [bdkjones/CodeKit#350]
The Autoprefixer in Codekit fails when using a disabling option in the browser string. The Autoprefixer [disabling options documentation](https://github.com/postcss/autoprefixer#disabling) . 

**Exact steps to reproduce:**
Using a string such as: `> 1%, last 2 versions, grid: false` will generate the following error in Codekit's log: "AutoPrefixer: Failed with this error: autoprefixer-cli: Unknown browser query `grid: false`"

I suspect this has something to do with the autoprefixer-cli being outdated. [Their github readme](https://github.com/ai/autoprefixer-cli#autoprefixer-cli-) says _The official way to use Autoprefixer is postcss-cli, this tool is for legacy code._

**Comment by luxlogica** [comment]
@heartfield, I think autoprefixer is correct in throwing an error there. The AutoPrefixer docs tell us that the `autoprefixer()` function has 8 *options* that can be passed to it as an object:

- **browsers**: the list of browsers autoprefixer should support
- env
- cascade
- add
- remove
- supports
- flexbox
- stats
- grid

Out of these 8 options, the only one that CodeKit allows us to change via its interface is the *first* one - "browsers". It does not allow us to change the others directly. I don't believe there is a way to set `grid: false` within CodeKit.

If this is functionality you need, you may consider changing this issue to a feature request.

**Comment by heartfield** [comment]
@luxlogica Thanks for the explanation. I will exclude IE in the browser list.
