### ISSUE TITLE
Dev. environment

### ISSUE THREAD

**Issue by Klezper** [bdkjones/CodeKit#351]
Hello, 
Tnx for a wonderful app!
Is it possible to create a development environment where the config files (config.codekit3) does not get copied when I copy the folder to the production environment?
What is best practice in this case?

**Comment by danielmee** [comment]
This had me stumped for a moment too but then I read about build folders. Basically, you have all your working files (Sass, Kit, etc) in one folder (I called mine 'source') and then CodeKit can process all the files over to a "Build" folder. Check out the good [Getting Started help docs](https://codekitapp.com/help/) he's written, or, specifically the [Youtube vid on the Build folder](https://www.youtube.com/watch?v=YGa1QEE1Tns) he's made.

**Comment by bdkjones** [comment]
Yep. @danielmee has it right. Thanks!
