### ISSUE TITLE
[Feature request] Bower uninstall

### ISSUE THREAD

**Issue by Skadi2k3** [bdkjones/CodeKit#353]
I just used the components feature of CodeKit and found that though I can install components just fine, I can't uninstall them. The designer on my team likes to code, but just won't use any cli. An uninstall option besides the update option we already have would be great. I would go so far as to label this an UX bug when you consider designers as one of your target audience.

**Comment by bdkjones** [comment]
Yea, I have the uninstall functionality ready to go, it’s just not exposed in the UI yet because I’m not sure what I’m going to do with Bower yet. Bower is sort of end-of-lifed, so I’m considering options.

**Comment by luxlogica** [comment]
+1 for moving across to [Yarn](https://yarnpkg.com/en/).

**Comment by bdkjones** [comment]
Closing this because we're going to leave Bower.
