### ISSUE TITLE
No changes detected sass

### ISSUE THREAD

**Issue by shaunpark3r** [bdkjones/CodeKit#354]
**Quick, short summary:**

For a while now when i'm saving my sass files it's not compiling. It's as though it's not detecting any changes when I hit save. The only way to solve this is to restart codekit which i'm having to do on an hourly basis. If i manually force a compile it will compile but without the changes.  

**Exact steps to reproduce:**
There's no real way for me to reproduce this that I'm aware off. 

**Your configuration (any details about your system that you think might be relevant)**
I'm meeting all the system requirements and have plenty of memory. 
<img width="1053" alt="screen shot 2017-04-27 at 09 45 57" src="https://cloud.githubusercontent.com/assets/7989806/25475366/6411080e-2b2e-11e7-8c37-e39ff242f888.png">

**Comment by bdkjones** [comment]
Which editor are you using to save the file? Is the project folder on a remote or external disk?
