### ISSUE TITLE
[Feature Request] Ability to Abort Build Process

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#359]
Sometimes - more often that I'd like to admit - I click the 'Build' button after changing some setting, only to realise the change will now force CodeKit to unintentionally recompile every one of the 50,000 files in my project. Including jQuery and all the external projects, throwing errors and making my computer beep non-stop for 15 minutes like it's Mardi Gras.

It would be incredibly useful if the 'Build' button once clicked turned into an 'Abort' button, allowing us to halt the build process sometime before completion.

**Comment by bdkjones** [comment]
Agreed. The abort functionality was pulled from the original 3.0 release because it's harder than you think to spin down 12 parallel processes in a coordinated, graceful way. When I bring it back, it will show up as a "cancel" button in the black bar at the bottom of the window.

**Comment by bdkjones** [comment]
With the new thread optimizations, this is now possible. Implemented for the next release.
