### ISSUE TITLE
A new development.. 

### ISSUE THREAD

**Issue by rjmayott** [bdkjones/CodeKit#362]
**Quick, short summary:**
Needs more arrested development
 
**Expected results:**
i expected a MS Word "Clipy" like assistant, Franklin, to make code suggestions for me

**Actual results:**
It's just a nice app, no racist harassing puppet to be found :(

**Exact steps to reproduce:**
Watched arrested development 5000 times

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
I tried to "laugh" at this, but GitHub told me I could not perform that action at this time. Apparently, GitHub hates you. Thanks!
