### ISSUE TITLE
update the libsass ?

### ISSUE THREAD

**Issue by JohnMica** [bdkjones/CodeKit#363]
Could you update the libsass so that the CSS grid layout properties are supported ?

it seems that the new version is ok (at least running on Node it seems to be fine).

**Comment by bdkjones** [comment]
CodeKit 3.1 is running Libsass 3.5.0 Beta 3. There is no newer version of Libsass. You're very likely running an out-of-date version of CodeKit.

**Comment by JohnMica** [comment]
Could be my syntax is not supported yet :) 
Thanks for the prompt reply.

**Comment by bdkjones** [comment]
Mmm, I know at least some grid syntax support was added in 3.5. Not sure if all of its available; you'd have to check with Libsass.
