### ISSUE TITLE
CK loads very slow using Hotspot with E or G conncetion

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#364]
CodeKits preview loads forever (infinite loop? Never saw it end there) when I use a hotspot with my Phone and only have E, G or no connection at all, although the project and everything inside it only uses local references. When I switch of WLAN or the Hotspot it loads instantaneously.

It looks like when I got WLAN connected CodeKit wants to do something that requires internet. What is CodeKit trying to do here?

**Comment by bdkjones** [comment]
This is a misunderstanding of networks. Even though all of your assets are hosted locally, the *network* is still the thing that resolves your address. When you load the Bonjour preview address or the LAN IP address in your browser, a call is sent out to the network to determine what that address points to. On a home network, that's your router. On an iPhone hotspot connection, it's some other device that essentially functions like a DNS server. 

The only way to completely cut the network out of the equation is to use the local feedback address: 127.0.0.1:5757 or localhost:5757, which are resolved on your Mac by /etc/hosts.
