### ISSUE TITLE
config conflicted copy

### ISSUE THREAD

**Issue by bradryanbice** [bdkjones/CodeKit#369]
**Quick, short summary:**
My codekit site's source files are in Dropbox, which allows me to work on a project from 2 different computers, at two different locations. This means I have Codekit installed on each of these computers (both machines are owned by me.) When I build the project at one of the machines, it changes "lastBuildDate" attribute, and also creates a "conflicted copy" version of the config.codekit3 file. Again, maybe just a side effect of using multiple machines, but just wondering if there's a workaround to creating the multiple configs.

**Expected results:**
Not sure what to expect here other than to just update the same config file and not create a duplicate.

**Actual results:**
Creates a duplicate config file.

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
CodeKit isn't creating a duplicate; Dropbox is. Your best bet is to pause Dropbox's file-watching while you're working, then re-enable it when you're done so that Dropbox syncs all the changes back to your other machines.

**Comment by bradryanbice** [comment]
Thanks
