### ISSUE TITLE
CK update not possible

### ISSUE THREAD

**Issue by formspiel** [bdkjones/CodeKit#370]
**Quick, short summary:**
On macOS 10.12.6 Beta (16G16b) it's not possible to update CK

**Expected results:**
CodeKit > Check For Updates

**Actual results:**
Message Dialog:
Update Error!
CodeKit can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move CodeKit to your Applications folder, relaunch it from there, and try again.
[Cancel Update]

**Exact steps to reproduce:**
Go to "CodeKit > Check For Updates" (I can reproduce it on my machine every time, even after restart.)

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

macOS 10.12.6 Beta (16G16b)
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports); 3,3 GHz Intel Core i7, 16GB RAM
<img width="532" alt="screen shot 2017-06-21 at 09 20 31" src="https://user-images.githubusercontent.com/1277141/27379340-1f7335c8-567b-11e7-889e-4d183fb91b6e.png">
![screen shot 2017-06-21 at 12 14 23](https://user-images.githubusercontent.com/1277141/27379362-31e34f2c-567b-11e7-8baa-a208cf05a21a.png)

**Comment by formspiel** [comment]
I updated manually to 3.2 (Build 25849) by downloading the newest version and it seems to be fixed. Neverless, hope the issue helps.

**Comment by bdkjones** [comment]
This is a macOS security feature. If you run the app outside of your Applications folder or if you unzip the download using anything other than the Finder or if you move the app using anything other than the Finder, macOS copies it to a hidden, read-only location and runs it from there.
