### ISSUE TITLE
[Feature Request] Adding custom browsers to use with CodeKit

### ISSUE THREAD

**Issue by taliesinpenbardd** [bdkjones/CodeKit#374]
I use Blisk browser for my dev, and I'd love to have it in the CodeKit preferences panel. Its bundle identifier is  : org.blisk.Blisk

More generally, that would be nice to have an option to pick an "exotic" browser.

Thanks by advance.
Cheers,
Luc

**Comment by bdkjones** [comment]
Ok, I've added support for Blisk to the next update. Once that goes live, please verify that it works on your end. Thanks!
