### ISSUE TITLE
Kit compiler: trailing whitespace in variables is included in output

### ISSUE THREAD

**Issue by indrekpaas** [bdkjones/CodeKit#376]
Creating a variable with **any** trailing whitespace outputs the specified whitespace. Leading whitespace, however, is correctly ignored.

Please see the reduced test case attached: [kit.zip](https://github.com/bdkjones/CodeKit/files/1134338/kit.zip)

**Comment by bdkjones** [comment]
Great catch and great bug report. Fixed for the next release. Thanks!
