### ISSUE TITLE
The icon does not change when the project is paused

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#377]
In version 3.2, the icon no longer indicates that Codekit is paused

**Comment by bdkjones** [comment]
Which icon are you referring to?

**Comment by rvola** [comment]
Hello Bryan,
I'm talking about the icon in the Dock.
Before when on Codex metals paused, the icon displayed a "Pause ⏸" red in the icon.

**Comment by bdkjones** [comment]
How are you pausing? Are you unchecking the project in the list?

**Comment by rvola** [comment]
I use the shortcut Ctrl + Alt + Cmd + =

To stop codekit to switch to another branch of GIT

**Comment by bdkjones** [comment]
It's ctrl+alt+command+/

Not =. That's likely the cause: you aren't pausing the app.

**Comment by rvola** [comment]
Nop back :)

I have an Azerty keyboard is the slash it is an equal.

Well I successfully completed using CleanMyMac to completely uninstall the application.

Following the update 3.2, I no longer saw the "pause" on the Codekit icon in the Dock.

Thank you for your patience
