### ISSUE TITLE
[Feature Request] "codekit-include" as a third option alongside append/prepend

### ISSUE THREAD

**Issue by martyf** [bdkjones/CodeKit#378]
**Quick, short summary:**
For combining JS files, add a third option "codekit-include" to include a file in a specific place of the file.

**Logic/Reasoning**
For some apps, that have larger amounts of JavaScript, it'd be great to wrap those within a single load callback while still maintaining smaller files of JS, such as:
```
$(window).on('load', function ()
{
   // @codekit-include 'test-a.js';
   // @codekit-include 'test-b.js';
});
```
This would be handy for having smaller program logic in different files for ease of management, but all accessible within the same callback scope.

**Expected results:**
Using "codekit-include" would then include them in-line.
```
$(window).on('load', function ()
{
   alert('test-a content');
   alert('test-b content');
});
```
The current "append" and "prepend" instructions can't perform this level of structure. Maybe I'm missing some logic or idea around structuring (and combining for) larger JS projects, but this would be a neat way to help manage smaller managable JS files but render them out as a single JS minified file for production.

**Comment by bdkjones** [comment]
Yea, this has been proposed a couple times and specifically rejected. Structuring code this way leads to all sorts of subtle bugs like variable shadowing, name collisions, etc. 

Most folks writing JavaScript don't even know about variable hoisting---they've have NO idea that stuff they're writing in `test-b.js` is actually going to be moved above the `@import` statement for `test-a.js`. Creating this sort of capability would very quickly lead to disaster.

The better approach is to enclose the contents of `test-a` and `test-b` in a function wrapper, then prepend them to the start of your main JS file. Inside your `onLoad` handler, call the functions that you defined. This neatly solves the problem, follows best practices, is FAR cleaner, AND sets you up nicely to move to ES6 modules down the road.
