### ISSUE TITLE
Incorrect output path relative to the root when . is in the folder name

### ISSUE THREAD

**Issue by manuelmoreale** [bdkjones/CodeKit#379]
**Quick, short summary:**
Folder name called `local.site.com`

Tried the following:
![codekit-1](https://user-images.githubusercontent.com/1738077/28402006-bda095c0-6d1d-11e7-93bb-8993e19b61fe.jpg)

**Expected results:**
Output to this path:`/local.site.com/assets/js/main.min.js`

**Actual results:**
Output to this path:`/Users/username/Sites/assets/js/main.min.js`

**Exact steps to reproduce:**

1. Add a tld to your folder name
2. Set the output folder relative to the root folder

**A link to download a simplified project or file that shows the issue:**
https://www.dropbox.com/s/v6nrus0ka8t6paz/bug.com.zip?dl=0

**Your configuration (any details about your system that you think might be relevant)**
10.12.5 (16F73) - CK 3.2 - 25849

**Comment by bdkjones** [comment]
Good catch and great report. Fixed for the next release. Thanks!
