### ISSUE TITLE
Sass error: Invalid flag !important when sass use variable !default 

### ISSUE THREAD

**Issue by ramjamx** [bdkjones/CodeKit#381]
**Quick, short summary:**
Sass error: invalid flag  "!important" when you import libraries like bulma.io 

**Expected results:**
Process _!default_ variable as  described [here](https://robots.thoughtbot.com/sass-default)

> You can assign to variables if they aren’t already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.

**Actual results:**
Resulting in error when you try to use sass libraries who are using !default.

**Exact steps to reproduce:**

1) Include a librarie like bulma.io vía bower

2) include sass subfolders  on bulma:

````
@import '../../bower_components/bulma/sass/utilities/*'
@import '../../bower_components/bulma/sass/base/*'
@import '../../bower_components/bulma/sass/elements/*'
@import '../../bower_components/bulma/sass/components/*'
@import '../../bower_components/bulma/sass/grid/*'
@import '../../bower_components/bulma/sass/layout/*'
```

3) Sass Error invalid flag "!important"


**A link to download a simplified project or file that shows the issue:**
Possible solution mentioned [here](https://stackoverflow.com/questions/20621062/compass-watch-command-is-erroring-out-when-trying-to-access-compass-core-1-0-0-a) about old gem libraries.

**Comment by bdkjones** [comment]
Yea, this isn't an issue with CodeKit; it's a current limitation of Libsass because full support for !defualt hasn't been finished. You'd need to ask the Libsass team for details or switch off Libsass and use the old Ruby compiler.

**Comment by ramjamx** [comment]
I try to run it with Use the libpass compiler switched off but, same result.
I Just want to overwrite some variables about primary colors, typhograpies etc. It can be done only with codekit? 

Thank you.

**Comment by bdkjones** [comment]
I have not used the framework you're talking about, so I can't give you more details about it. What I CAN say is that CodeKit is working 100% correctly. The Sass compiler is giving you an error and CodeKit is showing it to you.

It's 99.99% likely that there's a bug somewhere in the component you're using. That said, it's *possible* there's a bug with the Sass compiler, but if you've tried both Libsass and Ruby Sass and they both fail to compile the file, that's pretty telling. 

I'd contact the component author and ask them what's going on.
