### ISSUE TITLE
Browser refresh page instead of animate css, when i use  custom font

### ISSUE THREAD

**Issue by skhtml** [bdkjones/CodeKit#385]
**Quick, short summary:**
Browser live refresh not working properly:  Page fully refresh, instead of only css animate changes  when i compile sass file, and when i have custom font  include in index.html
**Expected results:**
Nice smooth animation only css and only selector what i changed
**Actual results:**
All page reloading, (no error in log) its just reload like i change html file, but i change only  .scss
**Exact steps to reproduce:**
1. include  fonts.css to index.html  
```
<link rel="stylesheet" href="fonts/fonts.css">
<link rel="stylesheet" href="css/all.css">
```
2. add line to use custom font in all.scss   
`font:14px 'PFDinDisplayPro',Arial,sans-serif;`
3. change some css rule in scss file, you can see  all page is reloading. 

**A link to download a simplified project or file that shows the issue:**
video when you can see issue http://take.ms/KNMGx 
archive when you can test issue :  http://take.ms/CoM7K

**Your configuration (any details about your system that you think might be relevant)**
Mac os 10.12.5 Sierra, Tested in Safari , chrome, firefox, same issue in all browsers.
Prepros 2x, 3x

**Comment by bdkjones** [comment]
I downloaded your project and tested in Safari on 10.12.5. When I save your Sass file, the page is not reloaded from scratch; the styles are simply reapplied to the page. 

I'm not able to reproduce this behavior. Did you mean to file this bug for Prepros? (You list Prepros 2 and 3 as your configuration.

**Comment by skhtml** [comment]
Thanks for super quick answer. 
I understand, if you are not be able to reproduce this issue you can not help me.  
Can i ask you to give me just random archive with html project with custom fonts ?  
Maybe you have some fish  projects for test. 
If it will be without bugs i can look what i do wrong, and fix it.

**Comment by bdkjones** [comment]
I'm not sure you're actually seeing a full page refresh in your video. The custom font is part of the page's styles, so when you use a custom font and have CodeKit reload the stylesheets, ALL the text on your page is going to flash because the font asset is reloaded by the browser. 

To test that, what I did was take your homepage and click one of your breadcrumb buttons at the bottom of the main banner area (to switch to the second image in your slideshow). I then made a change to your Sass file and saved it. CodeKit refreshed the page, all the text flashed, but the image stayed on the second one. If the entire page had been reloaded from scratch, the image would have returned to the first one.

**Comment by skhtml** [comment]
Ahh, now i understand.  Thank you so much for explaining, and for such a good app!

**Comment by skhtml** [comment]
Sorry , but thats me again...

In the fact, i agree, all page not refresh, but  all custom font refreshed. And i would never write you only if i did not test it  with Prepros App. 
I have tested same project with Prepros app, and when i compile scss file it animate only element what i change, and not redrawing all custom text. So in Prepros app it works good. 
I also watch my CPU load, and obviously because all font in page redraw in Codekit, it load much more than only animate one element in Prepros app. 

I write you because i am currently user of Prepros app (3 years), but i tested Codekit , and in my opinion it is much powerful for me than Prepros because of frameworks, and kit language.
