### ISSUE TITLE
Reliably crashing on macOS 10.13 Beta

### ISSUE THREAD

**Issue by hellodaniel** [bdkjones/CodeKit#386]
Codekit reliable crashes after 1 or 2 compiles on High Sierra. I know it's a little premature but I've been running this beta for about a month now and each beta release still seems to present the same issue. Pretty much only using Codekit for SASS compiling, have tried with `libsass` both on and off and have tried disabling/removing all  projects. 

Happy to investigate further and I suspect this might even be a known issue. 

**Expected results:** 
Codekit compiles as per normal. 

**Actual results:**
Codekit compiles, usually once or twice, then crashes. 

**Exact steps to reproduce:** Saving any SASS files (have the problem across all projects). SASS settings don't seem to matter, crashes regardless (although it seems to crash slightly less when 

**Your configuration (any details about your system that you think might be relevant):**
- 10.13 beta 17A315i (has happened on previous 2-3 beta versions, too)
- Running Apple File System (AFS), might be part of the issue? 
- Usually NOT using libsass
- Codekit does not / will not crash when idle

**Comment by bdkjones** [comment]
Yep. The crash is in some thread created by AppKit related to file-monitoring. I've filed the reports with Apple, as I strongly suspect this has to do with the new APFS in 10.13. I don't really worry about betas until September; it's Apple's issue to fix.

**Comment by hellodaniel** [comment]
yeah, tight.
