### ISSUE TITLE
[Feature Request] Vue Single File Components

### ISSUE THREAD

**Issue by jenny-leung** [bdkjones/CodeKit#387]
I'm starting to learn Vue JS and it seems like CodeKit does not have compile .vue files as describe here: https://vuejs.org/v2/guide/single-file-components.html
I was trying to setup my Macbook to use webpack, but there were errors.

I would like to know if it's possible to compile the .vue file with CodeKit. Or add this feature.
Thanks

**Comment by bdkjones** [comment]
Sure. You'd add *.vue as a custom language and then add a Hook to run the Vue compiler whenever vue files change. It's covered at codekitapp.com/help/

**Comment by luxlogica** [comment]
Sorry to revive an old topic, but thought this might be better than starting a new one... 

I've been able to survive so far without diving into VueJS too deeply, but as more of the frameworks and libraries we use start to adopt it, it's getting harder and harder to stay away. I *don't* want to instal Node, npm and all its friends on my Mac - hence my undying love for CodeKit - but unless CodeKit is able to compile .vue single-component files, we'll end up having to bite the bullet and do it. 

Is there any possibility at all of CodeKit adding the Vue compiler to its list of built-in tools?

**Comment by bdkjones** [comment]
Sure. I just don't have any expertise with Vue, so I need someone to put together a demo project showing the workflow and walking me through what needs to take place.

**Comment by katerlouis** [comment]
@bdkjones What do you mean by walking you through a project? If you mean what webpack is doing under the hood of a vue-cli setup, unfortunately I can't help. Showing you the workflow I can, though.

https://codesandbox.io/s/vue is a nice playground for a simple vue-cli project using Vues single file components.

Some weird webpack wizardry injects the `/src/main.js` into `/public/index.html` – `/src/main.js` then creates the main vue-instance, takes the first single file component `/src/App.vue` and renders it into `<div id="#app"></div>`

Every SFC must have a `<template>` describing the output which looks and feels veeery much like HTML, but actually isn't. (I guess?) this runs through some compilers to create render functions, (I guess?) like with JSX – by the way, Vue can also interpret JSX; but I've never seen a vue setup using it... – _(Careful! <template> must have one child and one child only!)_

Every SFC also **must have** a `<script>`-tag, where you can do all the javascript your heart desires. Importing / defining classes, functions, vars, so on and so forth. You then must `export default {}` with at least a `name: "Something"` prop-value-pair. This describes the component, which in fact is just another vue instance and behaves (I guess?!) the same as the main vue instance. That means you have your `data`, your `watch`ers, your `computed`-properties, life-cycle hooks like `created()`, `mounted()`, `beforeDestroy()` etc. 

Every SFC **can** have `<style>`-tag, where you can write your, you guessed it, css, less or sass/scss. Interesting is the option to [scope](https://vue-loader.vuejs.org/guide/scoped-css.html) your css, so it only affects this component. When scoped, Vue applies hashed (I guess?) `data-v-adfadf` attributes to the tags, and changes the css selectors to `a.something[data-v-adfadf`.


I leave it here, for now, scared that I misunderstood your request and you know all these things already But... Better too much than too little conversation, right? ;)


**App.vue**
```vue
<template>
  <div id="app">
    <img width="25%" src="./assets/logo.png">
    <HelloWorld msg="Hello Vue in CodeSandbox!" />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld";

export default {
  name: "App",
  components: {
    HelloWorld
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
