### ISSUE TITLE
Unwanted activation of Save Start

### ISSUE THREAD

**Issue by supermueller** [bdkjones/CodeKit#388]
**Quick, short summary:**

If CodeKit starts in the background (e.g. when using the Coda plugin) and the user holding down the option key, it activates Save Start and clear out all data.

**Expected results:**

Only clear out all data if the user wants that.

**Actual results:**

Clears out all data without confirmation

**Exact steps to reproduce:**

1. Quit CodeKit
2. Open a project with a CodeKit config file in Coda
3. Hold down the option key immediately after opening the project.
4. CodeKit clears out all data in the background.

**Suggested Solution:**

Force the user to confirm clearing out all data.

**Comment by bdkjones** [comment]
Agreed. Implemented for the next release.
