### ISSUE TITLE
[Feature Request] Purifycss

### ISSUE THREAD

**Issue by JayHoltslander** [bdkjones/CodeKit#390]
Would really like to see the option for [Purifycss](https://github.com/purifycss/purifycss) as a checkbox option alongside  "Run Bless" & "Run Autoprefixer".

I dislike having to resort to Grunt or Gulp for this and would rather see it in CodeKit.

**Comment by bdkjones** [comment]
There's no need for Grunt or gulp. This is what Hooks were designed for. Add one to run purifyCSS.

**Comment by JayHoltslander** [comment]
I wasn't even aware of that feature. 😳
Thanks!
![](https://i.giphy.com/Xh1vgIUkJbPKo.gif)

**Comment by JayHoltslander** [comment]
Aside: There's a screenshot missing in the docs at: https://codekitapp.com/help/hooks/
![](http://take.ms/Cpwmb)

**Comment by nicmare** [comment]
is there any tutorial on how to integrate purifyCSS into Codekit?

**Comment by bdkjones** [comment]
There’s not a specific tutorial for it, but you’d simply add a Hook or Build Step that runs PurifyCSS just as if you were at the command line. The only difference is that you’d use the special environment variables discussed at codekitapp.com/help/hooks/ <http://codekitapp.com/help/hooks/> to target the specific file being processed.

**Comment by luxlogica** [comment]
I've added a request to include PurgeCSS (#594) as an optional tick box in CSS-based languages. These types of processors are becoming increasingly common for CSS files, and do work which is just as valuable as file compression.  Their job is akin to javascript 'tree-shaking' which is already included in CodeKit, in Rollup. 

This 'CSS tree-shaking' provided by PurgeCSS/PurifyCSS is a pretty essential function, and it does feel like it should be in CodeKit. It doesn't feel right that we have it for javascript, but for CSS, the user has to jump through hoops...

For the user to make it work in CodeKit using hooks, they need to install Node, and learn how to use PurgeCSS/PurifyCSS from the command-life and/or setting up config files, and then learn how to set all of this up in the context of CodeKit. Honestly, not that friendly for a tool that is really quite valuable and necessary - and increasingly common. 

If this were only an edge-case, then relying on hooks would be fine, but as frameworks get bigger and more complex, and page loading speeds get increasingly more important, this really goes from a 'it-would-be-nice' to an essential feature. And after all, helping users NOT install Node and not use complex config files and command-line tools why we love CodeKit!

**Comment by bdkjones** [comment]
PurgeCSS is implemented. Thanks guys.

**Comment by nicmare** [comment]
i gave it a try 
![image](https://user-images.githubusercontent.com/898582/108592287-749ce180-736d-11eb-9b1e-f9ec938d4cd5.png)
200 kb before and now 16 kb. but unfortunately the complete website is broken. so it is useless.  do i need to follow some guidelines in order to get it work properly?

i use bootstrap 5 beta and scss

**Comment by bdkjones** [comment]
Did you read the docs or watch the screencast, as I suggested in the release notes?

**Comment by nicmare** [comment]
nope. did not notice it. i will check it out. i also found this [thread from the developer](https://www.webperftools.com/blog/how-to-remove-unused-css-in-wordpress/) as i also use wordpress

**Comment by nicmare** [comment]
what is the right node path if it should scan the parent folder??
![image](https://user-images.githubusercontent.com/898582/108592685-59cb6c80-736f-11eb-8dc8-7e654ed36046.png)
tried !(node_modules)/../*.php

**Comment by nicmare** [comment]
alright, seems to work: ../*.php
nice one!
but don't really understand how to use "!(node_modules)"

**Comment by bdkjones** [comment]
CodeKit doesn’t allow tools to run out of project folder to keep folks from nuking the wrong folders on their Mac. You need to add the right folder as a project. Sounds like you added just your stylesheets.

-Bryan
