### ISSUE TITLE
Forgotten flag in config file.

### ISSUE THREAD

**Issue by calvinjuarez** [bdkjones/CodeKit#392]
**Quick, short summary:**
CodeKit has apparently forgotten that the Uglify has a `support-ie8` option and removes it from my _config.codekit3_ files in all projects.  The UI still has the checkbox, though.

**Expected results:**
A checkbox in the UI will have a place to save its state in the config file.

**Actual results:**
The `support-ie8` flag is always removed from the config file.  (On my machine, but not my team members'.)

**Exact steps to reproduce:**
It's difficult for me to know.  Pause and unpause CodeKit?  Update CodeKit while paused?  Pause for a long time, maybe?  Or perhaps I updated the app, then switched to a branch in my project that was from an older project.  This is the second time this has happened to me, but the first time was ages back and I ended up getting a new computer, which (obviously) fixed it because of a fresh install.

I also have a lot of projects and I keep most of them disabled to keep the file watching overhead low.  And because I work a lot with Git, I keep CodeKit paused most of the time, unless I need it to compile something.

**Your configuration (any details about your system that you think might be relevant)**
macOS Sierra 10.12.6
CodeKit 3.2 Build 25849
Coda 2 2.6.6 (43619), plugin installed, but disabled

---

Is there some registry of settings that should be stored in the _config.codekit3_ file that I can rebuild somehow?  Or manually edit to include the `support-ie8` flag?

**Comment by bdkjones** [comment]
The name of the flag has changed. It used to be screw-ie8 and is now just ie8.

The flag should be in the config file and the old one is correctly removed.

**Comment by calvinjuarez** [comment]
Hmm...After fiddling with filenames, then putting everything back where I found it, both `screw-ie8` (which you mentioned) and `support-ie8` (the one I was talking about) are showing up again.  I'm not seeing one called `ie8`.

If it _should_ be removed, then CodeKit on my other guy's machine is _adding_ it for no reason, even though he's updated.

In any case, It seems this issue is resolved (though I have _no idea_ how).  I'll keep an eye on it and come back if something needs attention.  Thanks!

---

For any who find this:  The most I did was rename _~/Library/CodeKit/CodeKit7.datastore_ to _~/Library/CodeKit/CodeKit7.datastore.zip_ and back again.

**Comment by calvinjuarez** [comment]
This issue cropped up again, this time for a number of flags (`for-direction`, `getter-return`, `no-buffer-constructor`, `padding-line-between-statements`, `semi-style`, `switch-colon-spacing`).

I tried doing the "forget everything" start, then I deleted the app, deleted everything I could find in _~/Library/_ related to CodeKit, including _~/Library/Application Support/com.incident57.CodeKit3/`.  Nothing doing.

They're all ES-Lint flags, so I wonder if maybe there's some conflict with some version of ES-Lint that may be installed through NPM or something, that messes with CodeKit's data?

**Comment by bdkjones** [comment]
Are you sure you're running 3.3? Please post a screenshot of the About window.

**Comment by calvinjuarez** [comment]
![screen shot 2017-09-01 at 11 44 58](https://user-images.githubusercontent.com/2146819/29981467-00956cb6-8f0b-11e7-9d1f-18990c1544ea.png)

**Comment by calvinjuarez** [comment]
Aight, so I found that none of those flags were represented in _~/Library/Preferences/com.incident57.CodeKit3.plist_.  So I opened the default settings and I'm finding each one and toggling them and it seems to be updating them.  So that's my workaround now.  If this workaround stops working for me, I'll reopen the issue.  For now, though, this'll do.

**Comment by bdkjones** [comment]
That's correct behavior; the options would not be listed in that file unless they have been manually changed from the defaults the app ships with. That's how app preferences files work on macOS.

**Comment by calvinjuarez** [comment]
Cool, well, having entries in there for those missing bits of the config has fixed the config.  I went through each ESLint option and toggled it to put it in that file and refreshed the projects, and CodeKit's saving them to the config files now.  There were even a couple that must have gone missing without my noticing (specifically `array-bracket-newline` and `array-element-newline`).

Regardless of how macOS preferences work, CodeKit is forgetting flags.  I'll leave this issue up to you to reopen or leave closed, but that's what I've got.

And for those who find this with similar issues, toggling the missing options in the defaults can fix it.

**Comment by bdkjones** [comment]
Can you post a small demo project and an exact set of steps to reproduce? I'll take a look.

**Comment by calvinjuarez** [comment]
Thing is, it happens in the background.  I'll try to pay careful attention to figure out when it happens, though.  I really am trying to get you as much info as possible.  But yeah, when it happens next I'll try to get you a reduced test case.

**Comment by calvinjuarez** [comment]
*Update:* I think my globally installed eslint is the major problem.  I updated it from 4.5 to 4.15 and it seems to have fixed my computer's issue.

I've got eslint installed using npm via nvm.  Let me know if you'd like details and I'll send them.  My other guy's machine doesn't have eslint installed globally.
