### ISSUE TITLE
CodeKit does not refresh subfolders, folders, and refresh browser automatically

### ISSUE THREAD

**Issue by rafal-leap** [bdkjones/CodeKit#394]
**Quick, short summary:**
CodeKit does not refresh subfolders, folders, and refresh browser automatically. 

**Expected results:**
Codekit refuses to look for any file changes within my project under any subfolder. Only works when the project structure is flat. When any file is added to eg. "src" folder CodeKit does not refresh, compile and copy to dist. Even my old projects does not work anymore. Tested on less, scss, kit files. Only works when I hit Build Project button.

**Actual results:**

**Exact steps to reproduce:**
Run my Test-Project and try to make any changes in the index.kit file or styles.scss

**A link to download a simplified project or file that shows the issue:**
https://www.dropbox.com/s/6jgz0kibwp3deuy/Test-Project.zip?dl=0

**Your configuration (any details about your system that you think might be relevant)**
I'm on CodeKit 3.3 and OSX High Sierra.

**Comment by bdkjones** [comment]
Working just fine on 10.12.6. 

Beta releases of macOS are not supported. These types of issues always get resolved before Apple ships a GM.
