### ISSUE TITLE
CodeKit plugin for Atom text editor

### ISSUE THREAD

**Issue by treetrum** [bdkjones/CodeKit#395]
Long time CodeKit user. Finally got around to creating an Atom package similar to the official Coda plugin. After having it for a couple of days, I realise how unbelievably useful it is to not have to switch projects manually. My package basically just keeps CodeKit in sync with the current active folder in Atom.

Would love to have it listed under the available editor plugins on the CodeKit website.

Here's the link to the package:
https://atom.io/packages/codekit-atom-sync

**Comment by bdkjones** [comment]
Dear god, I am lazy. I FINALLY got around to putting this page up: https://codekitapp.com/help/plugin-atom/

Thanks so much for the awesome work, Sam! Sorry it took me so long to get it on the website.
