### ISSUE TITLE
Haml can't read external file

### ISSUE THREAD

**Issue by sKawashima** [bdkjones/CodeKit#398]
for example:
Folder:
```
folder
|--header.haml
|--index.haml
```
code:
```ruby
!!!
= Haml::Engine.new(File.read("header.haml")).render
```
Other compilers can compile this, but it can't compile with CodeKit.  
Error is `No such file or directory`.  

I examined the official website, but I could not find the information for compile.

**Comment by bdkjones** [comment]
You're writing Ruby code that has to be run in the Rails environment. `render()` is a Rails function. HAML in CodeKit isn't running inside of Rails, which is why this fails.
