### ISSUE TITLE
Hook Script for Timestamps / Permission Denied

### ISSUE THREAD

**Issue by johnozbay** [bdkjones/CodeKit#399]
Hi there! 

I'm trying use [this incredibly handy hook-script](https://useless.today/codekit-timestamps/) by @subhaze to add a timestamp to my files.

```
${CK_OUTPUT_PATHS:=""}
CK_OUTPUT_PATHS=(${CK_OUTPUT_PATHS//:/ })
now=$(date)
for i in "${CK_OUTPUT_PATHS[@]}"  
do  
    sed -i '' -e "s/{{TIMESTAMP}}/${now}/" "$i"
done 
```

However, as the commenter pointed out in the comments on the blog as well, I'm having a permission denied problem upon build :

> /bin/bash: line 1: /Users/john/Dropbox/clientname/public/about.html: Permission denied

I checked all the permissions + my user can do operations on files at this path without sudo in terminal. 
 
![Permission](https://media3.giphy.com/media/3oz8xNeAy5t6PdaClO/200.gif "Permission")

I looked around but couldn't find a better way to generate a timestamp / build-version / revision and insert into files. Any recommendations ?

**Comment by bdkjones** [comment]
1. Try a file outside of dropbox. Permission may be denied because Dropbox is holding an open file descriptor on that file.

2. If !1, try making the file globally writable. Does that work?

3. If the purpose of this is to bust caches on your server, wait a few days and you won't need it.

**Comment by johnozbay** [comment]
Hey Bryan, 

Many thanks for the quick reply.

1) Tried outside of Dropbox, same thing's happening. 

2) If I understand this correctly, what you're proposing is to change write permissions of these files am I correct? The files are actually in the build folder ('public') (all .kit or .html files), created by CodeKit itself. I've tried changing the source folder permissions, also didn't work. ~ And if I make the ones in the build folder globally writable, once they're modified / updated and codekit re-creates them, build will still fail each time. 

3) It is for version tracking, remote error tracking & exception handling with tools like [Sentry](https://sentry.io) and manual cache busting at scale. (I build mobile web apps, so intention is that things would be forever cached until they shouldn't be. Lastly, whenever the version changes, this would make it really easy to check which version had which error on which line in Sentry etc.)

**Comment by johnozbay** [comment]
Hey @bdkjones ~ the new shiny cache-busting feature addressed all my needs. How can I buy you a beer virtually? 🍺

**Comment by bdkjones** [comment]
Ha, glad you like it. You’re welcome to send cash to my email address with PayPal—I accept anything in increments of $1M USD.

**Comment by macfire** [comment]
@johnozbay 
I'm able to prepend a timestamp inside file via bash hook:

```bash
TIME=$(date +"%a %d %b %Y %H:%M:%S")
lf=$'\n';
sed "1s;^;/* $TIME */\\$lf;" $CK_INPUT_PATH > $CK_OUTPUT_PATH
```

(I tried the script by @subhaze and also got permission denied.)

**Comment by johnozbay** [comment]
Just realized this has been open for 2 years 😱 My OCD is triggered. Things are all working well now, so much so that I've a build process the size of an elephant in Codekit. 🐘 Closing it.

**Comment by bdkjones** [comment]
Nice! Self-closing bugs are my favorite kind.

**Comment by macfire** [comment]
Related topic: 
Timestamp Hook using Codekit3

```bash
NOW=`date "+%a %Y-%m-%d %T"`
sed -i -- "s|{{TIMESTAMP}}|${NOW}|g" $CK_OUTPUT_PATH
```

Example usage:
my_js_file.js

```javascript
var MyApp = new function() {
    let last_updated = "{{TIMESTAMP}}";

    this.get_last_update = function () {
        return last_updated;
    }
}
```

my_scss_file.scss
```scss

/* updated: {{TIMESTAMP}} */
```
*Scenario: Having a timestamp in our code makes it easier to verify that the latest file is being served on client's website which has very persistent caching.*
