### ISSUE TITLE
Configure Git Protocol adds extra [url ...] items to .gitconfig

### ISSUE THREAD

**Issue by mimetic** [bdkjones/CodeKit#400]
**Quick, short summary:**
Menu item Tasks:Configure Git Protocol adds extra [url ...] items to .gitconfig

**Expected results:**
Choosing "Tasks:Configure Git Protocol" and selecting `https://` creates 
`[url "https://"]`
`	insteadOf = git://`
and choosing "Tasks:Configure Git Protocol" and selecting `git://` removes those entries.

**Actual results:**
A new entry is created at the end of the .gitconfig file, leaving the old entry:
`[url "https://"]`
`[url "https://"]`
`	insteadOf = git://`

**Exact steps to reproduce:**
Switch back and forth between 'https' and 'git' using the "Tasks: Configure Git Protocol" menu item.
If you have the .gitconfig file open (e.g. in BBEdit) you can see the changes dynamically.

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Interesting. CodeKit doesn't actually create that file or modify it; it just calls a command on the Git binary. I would say this is a bug in Git.
