### ISSUE TITLE
[Request] Add support for jpegoptim --all-normal and --all-progressive flags

### ISSUE THREAD

**Issue by chris-scheurle** [bdkjones/CodeKit#401]
When working with large amounts of images from external sources, it would be nice, if I could make large images progressive or small ones non-progressive directly in the CodeKit interface.

Therefore, it would be nice if you could add some dropdown to the `jpegoptim` options where I can choose:
> **Progressive output:**
> [ Yes ]
> [ No ]
> [ Keep existing ]

 :smile:

**Comment by bdkjones** [comment]
Done. Implemented for the 3.6 release.
