### ISSUE TITLE
CK clones a Zurb Foundation 5 repo that allows jQuery to update, thus breaking many FND 5 functions

### ISSUE THREAD

**Issue by DanFeather** [bdkjones/CodeKit#402]
My website project, handled by CodeKit for almost 2 years, suddenly exhibited site-wide loss of functionality after a compile-and-build session. Eventually, I tracked it down to a too-new version of jQuery. Somehow, the compiling, etc., from CodeKit had downloaded version 3.2.1, and the research I found (which was confirmed in anote at Zurb's Github page  (https://github.com/zurb/foundation-sites/commit/6b6bc92b66d78a5f38af3968808bae984280ee8e) told me that Foundation v 5 needed to stick with version 2 of jQuery.

To see if this would be repeatable, I started a new project with the Foundation 5 that CodeKit installs. I found that CK's install does NOT ensure the jQuery is version 2. It uses version 3.

Bryan emailed me that CK downloads the Zurb Foundation 5 template from:(https://github.com/zurb/foundation-libsass-template). And then the bower.json grabs a newer version of jQuery. And then -- at least for my site -- lots of things (reveals, interchange, top-bar menu) break.

Seems like CK could be configured to clone the "final" version of Foundation 5 (see:  https://github.com/zurb/foundation-sites/tree/V5 ). it has version 2 of jQuery, and the .json file that accompanies it indicates in the "dependencies" that it shouldn't be "up-versioned."

**Comment by bdkjones** [comment]
Hmm. The `bower-foundation` repo has a `bower.json` file with `"jquery": "~2.1.0",` in it. That should, unless I'm misunderstanding something, limit the version of jQuery installed to `2.1.x`. 

What happens if you use the CLI to install a Foundation 5 project?
