### ISSUE TITLE
The old GitHub Desktop app doesn't pause CodeKit

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit#403]
I'm using the older GitHub Desktop app because the new one still doesn't feel as good :-)

When switching to the Github Desktop app CodeKit doesn't pause (I have both GitHub apps on my machine and switching to the newer *does* pause CodeKit as expected).

It's not a major issue for me, since I can use the Terminal for rebase, merge and  branching that usually mess things up for CodeKit.

But the checkbox *does* say "**Any** version-control app" 😀 

<img width="563" alt="ck-autopauseprefs" src="https://user-images.githubusercontent.com/5463/32269306-46f05da8-bef2-11e7-827a-1f3792c1c1e4.png">

**CodeKit Version 3.4 — Build 26097**

**Comment by bdkjones** [comment]
What’s the bundle identifier of the old app?

**Comment by greystate** [comment]
Good question - upon close inspection it's `com.github.GitHub` (I think?) - I looked in the `Info.plist` file:

```xml
<key>CFBundleIdentifier</key>
<string>com.github.GitHub</string>
```

**Comment by mcansh** [comment]
can we also add [Hyper](http://hyper.is) to the list of terminal apps? `co.zeit.hyper`

**Comment by makshh** [comment]
And one of the most popular terminal alternative [iTerm2](https://www.iterm2.com/)? I don't know how to check bundle identifier of that app.

**Comment by greystate** [comment]
@makshh Right-click the app in Finder and choose **Show Package Contents**. Then open the `Info.plist` file in a texteditor (it's an XML file) and search for *CFBundleIdentifier*...

**Comment by makshh** [comment]
Goot to know, `com.googlecode.iterm2`

**Comment by bdkjones** [comment]
These version control apps are added in 3.4.1:
`com.github.GitHub`

These finder replacement apps are added in 3.4.1 (if you turn that option on; remember it's off by default):

`co.zeit.hyper`
`com.googlecode.iterm2`
`com.eltima.cmd1`
`com.secretgeometry.Cathode`
`net.macterm.MacTerm`

If anyone comes across any others, please re-open and post the bundleIDs.
