### ISSUE TITLE
Enabling Cache-Buster Crashes Codekit on Compile / Build

### ISSUE THREAD

**Issue by johnozbay** [bdkjones/CodeKit#404]
Hey Bryan (@bdkjones) , 

First off, many thanks for the cache-buster feature! It's exactly what I needed, and this is a life saver. Sadly, whenever I enable cache-buster on a .kit file, it crashes CK immediately upon compilation of single file / build of project (presumably when that file compiles). Oddly enough however, if I run CK as root (by sudo-running the app's executable from terminal), then enabling cache-buster doesn't crash CK and it works. 

So I ran some tests with a `footer.kit` file, with a single line in it : `<script src="../js/main.js"></script>`

- Checked `footer.kit`'s file permissions, and all seems normal. I've tried 755, 775, 777 none works, still crashes. 
- Tried moving the folder out of my dropbox to see if dropbox is the cause, nope. Still crashes.
- Created a fresh new folder + `footer.kit` file on my desktop, and added this one line into the .kit file :  `<script src="../js/main.js"></script>` Crashed. 
- Added the linked file (`main.js`) to the correct path, also crashed.

But again, running CK as root worked in all scenarios. 

If it helps, it's OSX 10.12.6. 

Let me know if you'd like me to send anything else and I'll be happy to forward info your way! 

Cheers,

J

**Comment by johnozbay** [comment]
Update : 


When I run CodeKit executable from terminal with non sudo, and compile a file with cache-buster, I get this error in terminal when CK crashes : 

`
CodeKit(92347,0x700002277000) malloc: 
*** error for object 0x7fe942e83d50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
`

**Comment by bdkjones** [comment]
Mmmm, something sounds broken on your Mac. Check the permissions on the folder/file you’re working with. The fact that this works as a root user but not as an admin implies there is something wrong.

**Comment by johnozbay** [comment]
Fixed permissions on disk, and tested with a brand new folder & files on desktop. It still crashes. 
And that sudo trick isn't working anymore either. (not sure why it worked once, but not anymore 😢)

Odd thing I noticed, codekit crashes first, and a second or so later files are copied to the build folder, but they don't have the nice cache-buster strings in them. So they're copied as is. I'm lead to think that files are copied first, then the cache-buster code runs and modifies them, and that's exactly where the issue happens. See screen capture below :  

![codekit](https://user-images.githubusercontent.com/611338/32366610-80246ec0-c087-11e7-9488-6e5053f85785.gif)

**Comment by bdkjones** [comment]
Ok. No one else has reported the issue, so I’ll need the project you’re using to test. Zip it and send me a download link, please.

**Comment by johnozbay** [comment]
Sent a test project that crashes to the support email now ~ 
Let me know if you need anything else and I can happily help you debug. 

Many thanks Bryan!

**Comment by bdkjones** [comment]
Sigh. There is indeed a bug in my realloc function and the test case hits it because the file is so short. I allocate 20% more bytes than the file contains (to allow for the additional text we'll be adding in the cache-bust strings) and if we run out of space, I re-allocate double the space. Most folks aren't hitting the realloc function because their files are long enough that 20% extra space is tons of room.

In this test case, 20% extra is still less than the number of bytes consumed in a single cache-bust string addition, so the realloc function fires and crashes. 

It's the simple difference between `char* buffer` and `char** buffer`. Fixed for a point update that I'll have out in a couple days. In the meantime, any normal-length file should be fine.

**Comment by johnozbay** [comment]
![Debug Champion](https://media3.giphy.com/media/RPwrO4b46mOdy/200.gif)

Thanks a million for the fastest debugging operation and your timely response! ✌🏻
I'll test the new one on my end and let you know as well. 

Cheers ~

**Comment by bdkjones** [comment]
Fixed for 3.4.1.
