### ISSUE TITLE
Hook Error: invalid Regular Expression for the "matches" rule

### ISSUE THREAD

**Issue by davegillem** [bdkjones/CodeKit#405]
After updating to Version 3.4 -- Build 26097 I am now getting an error with all existing Hooks. Anytime a hook is run I get an error stating that there is a regular expression that cannot be evaluated. Most of the time I can just toggle the drop-downs to the same value and then it starts working. On a few I had to just copy everything to a new hook with all the same settings to get it to run.

For example:
`The Hook "Compile Handlebars" contains an invalid Regular Expression for the "matches" rule. It cannot be evaluated. See http://userguide.icu-project.org/strings/regexp for the correct RegEx syntax to use.  It cannot be evaluated. See http://userguide.icu-project.org/strings/regexp for the correct RegEx syntax to use.`

MacBook Pro (Retina, 15-inch, Mid 2015), OX 10.13

**Comment by bdkjones** [comment]
Hmm. Recreating the Hooks works? And this is only happening for Hooks with regex matches rules?

**Comment by davegillem** [comment]
Actually, I'm not even using a regex pattern at all.

![image](https://user-images.githubusercontent.com/1461548/32382766-1b28dfae-c084-11e7-8b0b-8e2b263b05d1.png)

However if I just toggle the drop-down menus to something else and then back, refresh, it works fine until the next restart of codekit

![image](https://user-images.githubusercontent.com/1461548/32384450-edce7d48-c088-11e7-9ec5-e8d4a2593a4e.png)

**Comment by greystate** [comment]
I'm seeing this one too - and I'm also just using the `Ends With` type.

**Comment by bdkjones** [comment]
Sigh. Okay, here's the cause:

1. On 10.13, Apple started requiring `NSPredicate` classes (the thing behind that giant list of rules in the UI) to be encoded and decoded "securely". Encoding is how CodeKit translates the predicate into a base64 blob of data that shows up in your project settings file. Decoding is how that data gets translated back into an `NSPredicate` object when the settings file is read. The "securely" aspect means you now have to tell the OS which specific kinds of objects are allowed in the predicate—numbers, strings, dictionaries, etc.

2. I caught that and added secure encoding/decoding support for the 3.4 update.

3. What Apple FAILED to mention in the AppKit release notes for 10.13 is that the `NSPredicate` produced by decoding the base64 data now has a `allowEvaluation` BOOL that is set to `NO` by default when the predicate is securely decoded.

4. That value must be set to `YES` by me once the secure decoding process is complete. 

I've fixed the issue and will put out a 3.4.1 presently to address it.

**Comment by greystate** [comment]
Hats off to you Bryan - you rock!

**Comment by davegillem** [comment]
Thank you for such a quick response and fix!!
