### ISSUE TITLE
MultiMarkdown breaking issues after update, HTML Footer not working

### ISSUE THREAD

**Issue by AlejandroColinaPew** [bdkjones/CodeKit#408]
**Quick, short summary:**
Multi Markdown has some parsing changes that break existing code. 
Most important to me:  `HTML Footer` directive is now ignored

but also, headings (#,##,etc), Footers and Tables are breaking. Many are related to a more strict whitespace handling in this version.

For headings, this used to work:
`###Footnotes`
now a space is required:
`### Footnotes`

Spaces in front of tables
```
    |Item     | Value | Qty   |
    |:------- | ----: | :---: |
    |Computer | $1600 |  5    |
    |Phone    | $12   |  12   |
    |Pipe     | $1    |  234  |
```
This is now required:
```
 |Item     | Value | Qty   |
 |:------- | ----: | :---: |
 |Computer | $1600 |  5    |
 |Phone    | $12   |  12   |
 |Pipe     | $1    |  234  |
```

Many of these can be addressed with search and replace but, what a chore.

**Comment by AlejandroColinaPew** [comment]
Workaround for `HTML Footer` which you could conveniently specify at the top of your document..
```
Title:    my cool readme
Author:   Me  
Date:     November 3, 2017  
Comment:  Readmes are human readable 
          and editable text files. 
CSS:      readme.css
HTML Footer:<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
            <script src="doc.js"></script>
```
is to simply put the code at the bottom of the document :-(
```
...last line in your doc.

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="doc.js"></script>
```
not so convenient when automating etc.

**Comment by bdkjones** [comment]
This isn’t an issue with CodeKit. CodeKit just runs the multimarkdown compiler. There’s nothing I can do here; this is just the most recent version of MMD.
