### ISSUE TITLE
Specify which links to cache-bust

### ISSUE THREAD

**Issue by MikeHarrison** [bdkjones/CodeKit#409]
**Quick, short summary:**
Feature request - the ability to exclude / include certain links for cache busting

**Desired results:**
The code below is in my site `head`:
```
<link rel="stylesheet" href="/assets/css/styles.css">

<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic' rel='stylesheet' type='text/css’>
```
I would like the `styles.css` to have the cache-busting string added, and the Google Fonts link to be left as is, as the cache-bust breaks the link

**Actual results:**
All links have the cache-busting string added

**Comment by bdkjones** [comment]
Yea, I see the problem. I'd prefer to avoid the need for manually turning off the cache buster for certain links. That would be messy and involve special comments or something.

The better approach, I think, is to simply make the cache-buster aware of types of links that cannot be safely busted. I will do that for the next update.

**Comment by MikeHarrison** [comment]
Super thanks Bryan. For my use case I would only want cache-busting on .css and .js files that have been compiled through Codekit, perhaps that could be the defining factor?

**Comment by bdkjones** [comment]
Okay, 3.4.1 no longer cache-busts links to Google Fonts. Will be out shortly.

**Comment by nye** [comment]
Hello! Is this only excluding links to Google Fonts? I think it should be nice to exclude other links as for example canonical links:

<link rel="canonical" href="https://www.mysite.com/canonical?ckcachebust=575978862">

Thanks!
