### ISSUE TITLE
Preview opening in Safari rather than Blisk

### ISSUE THREAD

**Issue by andy-barlow** [bdkjones/CodeKit#410]
On Mac OS High Sierra (not tested on other OS), preview with Blisk option opens Safari even though Blisk is installed, see http://recordit.co/UXqG8ErI9r.

**Comment by makshh** [comment]
I think bundle ID for Blisk is `org.blisk.Blisk`

**Comment by bdkjones** [comment]
Hmm... did they change it? If Blisk shows up in the preview browsers list, it means the bundle ID should be good. That list is populated dynamically by looking for bundle IDs of known browsers.

**Comment by andy-barlow** [comment]
That is exactly the message logged…

AndyB

**Comment by bdkjones** [comment]
And the other questions? Where is Blisk running from on your Mac? Can you look up it’s bundle ID for me?

**Comment by bdkjones** [comment]
Got it. The bundle ID is correctly `org.blisk.Blisk` in all places except one, which uses `com.` Fixed for 3.4.1. Thanks.
