### ISSUE TITLE
Permission denied when minifying output

### ISSUE THREAD

**Issue by mark-adigital** [bdkjones/CodeKit#411]
Hi,

I updated to Codekit version 3.4 build 26097 this morning and since that time am getting the following error when compiling Sass/JS: 

Error: EACCES: permission denied, open '<path>'

The values for '<path>' are correct and these files compiled without issue before the update. I've also tried doing a safe start and uninstalling/reinstalling Codekit to no avail.

Any help much appreciated,

Mark

**Comment by bdkjones** [comment]
Sounds like the permissions on the input file or output path have changed. Check both and make sure your user has read/write access.

If that does not work, the file may be corrupt. Create a new file from scratch and then copy the content into it. Delete the old file.

**Comment by mark-adigital** [comment]
Thanks for the response. After some further testing it looked like the error became a false positive at some stage so either the safe start or uninstall did work, but the error didn't stop displaying until after I'd also rebooted my machine.

**Comment by bdkjones** [comment]
Yea, if a reboot fixed it then something was mucked up on your system. Glad you got it sorted.
