### ISSUE TITLE
Hook fails to run completely with RegEx syntax error

### ISSUE THREAD

**Issue by martyf** [bdkjones/CodeKit#413]
**Quick, short summary:**
I have a simple hook that looks for changes of .handlebars files, and if found, re-creates my templates.js file

```
path=$(dirname "$CK_OUTPUT_PATH")
handlebars $path/ > $path/templates.js
```

This used to work correctly.

Today I have been making changes to some .handlebars files, and the hook fails to run:
> The Hook "Handlebars" contains an invalid Regular Expression for the "matches" rule. It cannot be evaluated. See http://userguide.icu-project.org/strings/regexp for the correct RegEx syntax to use.

If I run the same command via the command line - just the simple handlebars compile instruction - it runs correctly, such as:
> handlebars /full-path-to-handlebars-folder/ > templates.js

**Expected results:**
The hook should run successfully.

**Exact steps to reproduce:**
Use the hook above, and set to run on changes to any .handlebars files.

Make a handlebars file for the project, save (to trigger the Hook), and see it fail.

**Version:**
Running CodeKit v3.4

**Comment by bdkjones** [comment]
Yep. It's a bug caused by 10.13 and the re-compilation in 3.4. I'm literally in the process of deploying a 3.4.1 update that resolves it. Check for updates in about 45 minutes.

**Comment by martyf** [comment]
You're the man!

**Comment by bdkjones** [comment]
3.4.1 is live. Fixed.
