### ISSUE TITLE
When switching between Git client and Terminal CodeKit *toggles* the pause setting

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit#414]
I just noticed that when I switch between two apps that both should "pause" CodeKit, it actually toggles the setting.

**Steps to reproduce:**

1. Check both checkboxes in the **Pause File-Watching When** setting
2. Switch from code editor to Terminal -> CodeKit pauses file-watching
3. Switch to a Git client (e.g. *GitHub Desktop* or *Tower*) -> CodeKit stops pausing ??

The expected behavior for the third step would be for CodeKit to keep the paused state.

*CodeKit version: 3.4.2*

**Comment by bdkjones** [comment]
Thanks, I’ll take a look.

**Comment by bdkjones** [comment]
Confirmed and fixed for 3.5. Thanks!
