### ISSUE TITLE
CodeKit hangs when processing certain JavaScript code using ESLint.

### ISSUE THREAD

**Issue by mtthwbckmn** [bdkjones/CodeKit#417]
**Quick, short summary:**
When using certain snippets of JavaScript code that don't close properly, ESLint processing causes CodeKit to hang, with no way to recover without restarting the app.

**Expected results:**
ESLint should return `9:5 Parsing error: Unexpected token`. This is the result I get when processing the same file using Terminal.

**Actual results:**
If you save the file, CodeKit hangs on the following message:

> **Checking syntax in test.js**

At this point, CodeKit will no longer File-Watch JavaScript files, or successfully build a project using the **Build Project** button. If you fix the parsing error, and haven't already run **Build Project**, it will successfully build the project, but the original message remains at the bottom of CodeKit's progress bar. You can also switch CodeKit projects, but the errors will remain in CodeKit's progress bar.

**Exact steps to reproduce:**

1. Create a new project in CodeKit.
2. Create a new JavaScript file called `test.js`.
3. Setup ESLint for that `test.js` file.
4. Copy the following code to `test.js`:

```Javascript
( function() {
  $( 'body' ).click( function( e ) {
    var clickedOn = $( e.target );
    if ( clickedOn.parents().andSelf().is( '#foo' ) ) {
      // Do something.
    } else {
      // Do nothing.
    }
} );
````

**A link to download a simplified project or file that shows the issue:**
You can download a CodeKit project with just the CodeKit config file and `test.js` file [here](https://studiodirective.com/mail/codekit-hang-test.zip).

**Your configuration (any details about your system that you think might be relevant)**
iMac (Retina 5K, 27-Inch, Late 2015) - macOS 10.13.1 / CodeKit 3.4.2 / Coda 2.6.9
MacBook Pro (17-Inch, Late 2012) - macOS 10.13.1 / CodeKit 3.4.2 / Coda 2.6.9

**Comment by bdkjones** [comment]
Okay, I've just verified that this is still an issue with 3.5.2. I'll have to take a closer look at what's going on. Thanks for the report!

**Comment by bdkjones** [comment]
Got it. This is fixed for the next release. Thanks for the help!
