### ISSUE TITLE
Importing files located in skipped folders fails

### ISSUE THREAD

**Issue by seanCodes** [bdkjones/CodeKit#419]
When prepending/appending JS files using CodeKit special comments, files located in skipped directories are silently ignored.

This is an issue because it means that files in `node_modules` and `bower_components` folders (which are often skipped) can't be bundled with other JS without using other tools. This is also confusing because Less/Sass files can `@import` files from skipped folders without a problem.

---

**Expected results:**
CodeKit append/prepend comments can import any valid file, regardless of directory, as long as it exists.

**Actual results:**
CodeKit silently fails to append/prepend a file if it's located in a folder that's skipped by the project.

**Exact steps to reproduce:**
1. Create a new CK project
2. Create a new folder
3. Create a new JS file in that folder with some dummy code
4. Set that folder to be skipped by CK
5. Create another JS file at the root of the project with a `@codekit-prepend` comment in it
6. Process that JS file
7. Observe that the processed output file has no contents

**A link to download a simplified project or file that shows the issue:**
[ck-issue.zip](https://cl.ly/332e0O0c0E3Q/download/ck-issue.zip)

**Your configuration (any details about your system that you think might be relevant)**
None

---

Thanks!

**Comment by bdkjones** [comment]
Yep; this is a known limitation currently. I do plan to address it and allow importing of skipped items. Should be out in early 2018. (early meaning the first month or two, not Apple's definition of early.)

**Comment by jstrellner** [comment]
I just wasted 45 minutes trying to figure out what was going on.  Had a clean install of Foundation 6 installed from CodeKit.  After it pulled down the files and built it, I had it compiled the scss, but then when it got to the JS it complained...

> `$(document).foundation();`
> '$' is not defined. (no-undef)

I thought, no biggie, I see that the app.js it created didn't include the following:

`// @codekit-prepend "../node_modules/jquery/dist/jquery.js";`

Once added, it didn't work.  Didn't work for like 20 variations either.  It wasn't until I saw this bug report that I realized that the _node_modules_ folder is ignored (after the F6 install, it wasn't greyed out).

So, to anyone that runs into it, after installing Foundation from CodeKit, reboot the app.  Then go into settings and remove _node_modules_ from the listing, then it'll import jquery and build.

<img width="498" alt="screen shot 2018-03-19 at 4 51 50 pm" src="https://user-images.githubusercontent.com/5665666/37628527-0661316a-2b97-11e8-916c-198442bb5668.png">

**Comment by bdkjones** [comment]
This is a limitation I’m addressing for the next release. The reason it exists is that CodeKit doesn’t have a model for files that are skipped, so it literally doesn’t see them. The workaround for that is complex, but do-able I think.

**Comment by bdkjones** [comment]
Happy to report that is now implemented. It was MASSIVELY complex to do it because the whole idea of Skipped Items is to have CodeKit not know anything about the contents of those items in order to speed up the app when handling, say, node_modules folders that contain 144,000 files.

It involved a lot of major surgery to some of the core algorithms in CodeKit, so I want to test this before releasing. Can you send me your email address so I can provide a link to download a beta? Thanks

**Comment by jstrellner** [comment]
@bdkjones Not sure if you are asking me or the OP, but happy to test out.  joel at everwall com.

**Comment by seanCodes** [comment]
@bdkjones Super glad to hear it’s working! Happy to test it out. seanjcodes at gmail

**Comment by bdkjones** [comment]
Okay, this is implemented. Handling some component updates and hope to push 3.6 live tomorrow night.
