### ISSUE TITLE
Wrong external server URL (forced HTTPS?)

### ISSUE THREAD

**Issue by tbnv** [bdkjones/CodeKit#420]
Let's say I have a WordPress website at `http://domain.dev`. This is the URL defined for the "External Server Address" in CodeKit. In the browser, it looks like `http://localhost:5757/` wants to load `https://domain.dev` even if the URL I set in CodeKit is `http://domain.dev`.

It gives this error:

```
External Server Error
This project uses an external server, so CodeKit requested this URI: https://domain.dev/
The returned error was: "An SSL error has occurred and a secure connection to the server cannot be made." (Code -1200)
```

As you can see "CodeKit requested this URI: `https://domain.dev/`" instead of `http://domain.dev`.

* SSL is properly configured and I could access `https://domain.dev` if I'd want (but I don't).
* There is nothing I configured forcing HTTPS to be used (`.htaccess` or else), as far as I can tell.

The issue appeared this morning (maybe a consequence of the macOS 10.13.2 upgrade?).

**Comment by andoro** [comment]
The same, I just updated to macOS 10.13.2, so maybe yes but not sure.

**Comment by bdkjones** [comment]
Trace the HTTP request/response, please. I think your external server is redirecting CodeKit to a secure URL.

**Comment by tbnv** [comment]
Request:

```
Host: thibaut-imac.lan:5758
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://thibaut-imac.lan:5757
Sec-WebSocket-Protocol: ckrp
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: J5SyQtuCen9bHH/5S1z2DQ==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Response:
```
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: Y7Lp6FJ1oBS2DKV1Id4gYi7UTOw=
Sec-WebSocket-Protocol: ckrp
```

Does it help?

**Comment by andoro** [comment]
I have a site locally: abcd.dev:8888
If I open it in Chrome, it works with HTTP. If I open it in Safari, it tries to redirect to HTTPS.
Strange! Note that Codekit is turned off during this test.
These happen after updating to 10.13.2

If Codekit somehow uses Safari or system settings for a site, it can be a connection between these.
I used this manual to setup local test environment: https://mallinson.ca/osx-web-development/

**Comment by bdkjones** [comment]
So, Apple is really moving hard towards defaulting to TLS. This may be an issue isolated to Safari. Can folks here test with Chrome and see if the issue persists?

**Comment by NeverDesign** [comment]
I also updated to 10.13.2 yesterday and am experiencing the same issue, and see the same behaviour as Andoro above. If anyone knows a way around this let me know!

**Comment by tbnv** [comment]
@bdkjones Verified in Chrome, Firefox and Safari: 
<img width="1928" alt="capture" src="https://user-images.githubusercontent.com/1021579/33766217-d864397a-dc1c-11e7-8792-9d5f04cee405.png">

**Comment by bdkjones** [comment]
Ok, so the answer is: “Google is being dumb” They have added *.dev domains to the list of domains that the FORCE to https. You’ll need to use a different TLD in your vhost. See: https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by tbnv** [comment]
So that post yesterday as well (though I didn't have the time to change my local TLD yet). It seems it's the only possible solution.

**Comment by bdkjones** [comment]
Yea, I have no idea what the rationale for forcing .dev to https was, but it seems super irritating. There’s nothing I can do about it. Safari uses the same list, so that explains why the browsers are trying to switch to HTTPS.

I AM about to release an update with a much improved TLS setup, so you could continue to use .dev and just flip on TLS in CodeKit’s server popover.

**Comment by andoro** [comment]
OK I changed my local TLD to .loc from .dev and now everything works fine 👍

**Comment by tbnv** [comment]
Yes it's definitely solved by changing the TLD as mentionned above.

@bdkjones Thanks for the news about the upcoming update. Though, maybe it's better to advocate users about using another TLD instead of working around a system wide "security" change?

**Comment by bdkjones** [comment]
Ok, I spent a good bit of time trying to find a way around this issue. There is none. That stupid policy header seems to apply at the lowest levels of the OS, as I'm able to trace the proxy process in CodeKit and I see my request go out to `http://testsite.dev` but then in the error handler it tells me I was trying to access `https://testsite.dev`.

Normally, there are callback methods that fire when the origin server hands me a redirect. Those aren't firing here, however, because this isn't a redirect. The goddamn system is modifying the address when it executes the request. It's hard-coded in. 

SO, the next release of CodeKit will now warn you if your project has an External Server address that ends in `.dev` but does not begin with `https://`. I very seriously considered making the `OK` button for that warning say `Fuck Google`.

**Comment by bdkjones** [comment]
Also: as a replacement for `.dev` I would recommend `.test`. That gTLD is reserved so that no company with a popular web browser can buy it and then wreck everyone's day.

**Comment by tbnv** [comment]
Thanks a lot for trying hard. `.dev` was so obvious… but let's continue using another gTLD.

> CodeKit will now warn you if your project has an External Server address that ends in `.dev` but does not begin with `https://`

Is it working properly if it begins with `http://`? I think remember external server refresh didn't work… Maybe I should do another test.

**Comment by bdkjones** [comment]
Well, your external server has to be set up to use TLS, which involves certificates and appropriate vhost entries to handle traffic on 443, etc. You can’t just change the address from http to https and make it work; you have to set up the external server to handle TLS. That is a massive pain and there’s nothing I can do about it, so I’d recommend using .test instead. 

That said, the next release of CodeKit has a completely overhauled TLS approach in place. You can now set up CodeKit’s server to be secure (https) with one click and all browsers will recognize the certificates without warnings. It works wonderfully and involves no configuration on your part. However, that’s only for CodeKit’s server; not external servers like Mamp.
