### ISSUE TITLE
Drag and drop group show all groups

### ISSUE THREAD

**Issue by supermueller** [bdkjones/CodeKit#423]
**Quick, short summary:**

If you reorder groups by drag and drop, all hidden groups will be shown. Additionally after that the toggle for show/hide works not as usual.

**Expected results:**

The hidden groups should stay hidden.

**Actual results:**

The hidden groups will be shown.

**Exact steps to reproduce:**

Hide one ore more groups by clicking "hide" on the right. Drag a group and drop it on a new position. All hidden groups will be shown.

Additionally the toggle for showing/hiding still says "show" and you have to click it twice to hide a group again.

**Comment by bdkjones** [comment]
This was definitely a tricky one. Finally figured out what was going on and the issue is fixed for the upcoming 3.8 release. Thanks!
