### ISSUE TITLE
[Feature Request] Log sorting and filtering

### ISSUE THREAD

**Issue by dlewand691** [bdkjones/CodeKit#424]
When building a project, the log can get pretty long. I've set my build process to continue every with errors and can then go back through and find/fix the errors. 

Rather than scrolling through the entire log, hunting for errors or issues, it would be great to be able to sort or filter it by condition to quickly narrow them down.

**Comment by bdkjones** [comment]
This is definitely in progress.

**Comment by bdkjones** [comment]
Implemented in 3.5.2 and released.
