### ISSUE TITLE
Two app icons

### ISSUE THREAD

**Issue by johann1301h** [bdkjones/CodeKit#426]
There are two different icons for this app. 

One white, and one black. 
I see the white one in the Dock, and the black as the .app icon.

This seems a bit odd? Is it intentional?

**Comment by bdkjones** [comment]
Yes. The icon adjusts automatically based on whether you have your menubar in dark mode or not.

**Comment by ties-s** [comment]
For me it has a black icon in light mode and a white icon in dark mode. Is that the way it should be? Seems mixed up?

**Comment by bdkjones** [comment]
That’s correct. The icon is designed to contrast with the theme.
