### ISSUE TITLE
cssgrid parameters failing via global frameworks

### ISSUE THREAD

**Issue by Timoti** [bdkjones/CodeKit#427]
GOAL: pass  cssgrid parameters with fr units to a mixin in my global framework, 

RESULT: Fails with "Mixin grid-context has no parameter named.."

DETAILED STEPS

```
@mixin grid-context($tpl-cols: repeat(3 , 1fr)) {
	display: grid;
	grid-gap: $global-gutter;
	grid-template-columns: $tpl-cols;	
	}
// use..
@include grid-context($tpl-cols:repeat(8 / 1fr)); 

```

RESULT Mixin grid-context has no parameter named $tpl-cols

Occurs if i rely on mixin defaults OR try to pass in a new variable as above

BUT if  I move the mixin into my project the errors cease.  So I'm assuming a _global framework_ issue with grid.. something 

ck 3.4.2

**Comment by bdkjones** [comment]
I believe this may be an issue with Libsass, which hasn't been updated to handle the latest CSS standards. Try turning Libsass off for this file. That may still fail, because I think Ruby Sass was just updated last week with support for this.

**Comment by Timoti** [comment]
cheers.  Ruby (after an icy-blast-from-the-past compile time) threw me the most verbose list of depreciations i've ever seen, and reduced CK to scrolling sludge - but yes, interestingly, AFAICT no error on this mixin with ruby referencing my global framework.

But the kicker i would have thought is (with libsass) that, as i mentioned, the mixin WORKS when part of the project - only when shifted out to the global framework does it fail - so internally - libsass is playing nice there.  

So meanwhile, the practical workaround appears to be to  just keep the mixin in the project.

**Comment by Timoti** [comment]
oops sorry - correction - ruby DOES throw the error while in the global framework - written to my rendered web page, but not, AFAICT to the codekit log (but as i say verbosity...).

So looking less like a libsass error again.  ALbeit workaroundable.

**Comment by bdkjones** [comment]
I’m not following what you mean by “in the framework”. Can you post a test case that shows the issue?

**Comment by Timoti** [comment]
I'm meaning i have my own common global framework of mixins, supporting multiple projects, stored outside project folders.  I'm trying to refer to the mixin there and thats where i get the error.  If instead, the mixin is placed within the project folder, it works.  So there's soething about the global framework functionality that seems to be at issue, with cssgrid variables, rather than sass itself - either libsass or rubysass.

yes I could supply the project package (or parts thereof) and global framework, if that helps - what  - zip it up here???  email?

**Comment by bdkjones** [comment]
Mmm, it sounds like your mixin is calling or using something (like a variable) that is not defined when the mixin is used from a CodeKit Framework. I’d verify that next.

**Comment by Timoti** [comment]
[time went by] no i checked that many times 

But i have just found that on project #1 the issue has mysteriously disappeared, and on project #2  importing the the global framework directly to the partial concerned, has eliminated the problem.  I don't understand why - other partial dependencies on global mixins work ok while this mixin failed, and the sass error message complaining about variables put us off the scent I think - so this feels like a workaround rather than a fix, but i'm going to call this issue closed all the same - cheers!
