### ISSUE TITLE
Styling Remote Websites Doesn't Repath CSS files

### ISSUE THREAD

**Issue by Timoti** [bdkjones/CodeKit#429]
While the remote site is being served up via codekit, I just can’t get the relevant css files to substitute.

CK should rewrite that link to 

**Exact steps to reproduce:**

The key file to substitute is 
/themes/custom/semantique/css/app.css?p2s973

Within my project (a drupal theme) the pertinent path is
/css/app.css  
(we're running foundation)

I have reset the browser refresh server to the remote DNS
TLS is enabled in CK
I added /themes/custom/semantique as a document root subpath 
changed port to 5758 as codekit asked
Refreshed everything 
We are, as per usual, using the drupal css-link contributed module to enable css injection  

The dev site is behind htaccess screening so i'd have to send you access via other channels - let me know if you want that

CK 3.4.2

I’ve been excited about using this feature as I’ve wanted it so often in the past, tried it out of academic interest when you released this feature with no result,  and right now now have a serious need, theming the SSL enabled  commerce section of a drupal 8 webapp, which would be quite problematic to do locally.

**Comment by bdkjones** [comment]
Your local file needs to be at the same path as the remote one. The paths must match exactly. Here, you’ve set the doc root to the parent path, so your remote file’s path is:

/themes/custom/semantique/css/app.css

And your local file’s path is:

/app.css

This is why it’s failing.

**Comment by Timoti** [comment]
Thanks - yes i had mistakingly thought i could use document-root-subpath, even with the “not applicable for remote servers” warning   (though in fairness your video has a /build sub folder in there so… you could let me off lightly on that one). 

For anyone out there with similarly nested projects, as within a drupal CMS, and also wanting to avoid all the config pain of jumping between local and remote serving, which we do need to do when using remote for just part of a project, e.g. commerce… (the TLS, domain, port, etc differences add up to plenty of hassle),  I have a kind of workaround.

This acknowledges that having multiple code kit projects including the same codebase is not normally permitted - CK forces us to choose one and will destroy the CK config of the other.. But if we can be disciplined enough to only have one project enabled at a time, we can achieve the same with symlinks, to avoid local/remote reconfig pain, and also contain the scope of codekit's file listening.  

So in my drupal 8 situation I have created an alternate CMS root folder with just /themes/custom directories inside.  Then inside /custom is a symlink to the actual theme-project folder in the active local CMS  instance - so now there is a path matching the remote:
themes/custom/[project-theme-name]/css/app.css

This works to the point of the correct code kit  headers showing in devtools inspector, though some other issue remains which I will file separately as it seems be beyond the scope of this one.

But i'm interested to know if there's anything intrinsically bad with this approach? As a workaround until there is some kind of 'root-subpath-enabled server profile switching' switching facility in a future Codekit.
