### ISSUE TITLE
symlinked folders are not shown / compiled

### ISSUE THREAD

**Issue by JohnMica** [bdkjones/CodeKit#433]
Not sure if my setup is wrong but i cant seem to figure this one out or even if it is possible.

**Quick, short summary:**

I cloned 2 github repos into their main folders (to be able to commit/pull individual changes / updates).

Main idea is to have a Theme repo and a Full-site-repo that will include the Theme repo in it so any changes made to the theme will update the Full-site-repo as well...

I symlinked those 2 repos into a Project folder (aka the website).
The root symlink is show inside the CK project.
The second (included inside as a symlinked folder) doesnt show any content inside the CK project.

**Expected results:**

To be able to see all folders and their contents that have been symlinked inside the Project Folder (aka the website)

**Actual results:**

the included symlinked folder is not shown - thus I cannot compile the sass / twig / ... files with CK

**Exact steps to reproduce:**

clone the repo bellow, open with CK and the 'story' folder doesnt appear :(

the 'story' folder is located at user/themes/ as a submodule (it's own github repo)

**A link to download a simplified project or file that shows the issue:**

https://github.com/JohnMica/grav-story

**Your configuration (any details about your system that you think might be relevant)**

MacOSX totally high

**Comment by bdkjones** [comment]
Yea, CodeKit skips symlinks because not all of the tools in the app can work with them correctly.
