### ISSUE TITLE
.kit is broken, removing content and closing tags when using optionals

### ISSUE THREAD

**Issue by dongepulango** [bdkjones/CodeKit#437]
My code works before, I didn't touched it. But after the update I compiled and now everything is broken.

My code is:
`<li <!--$nav-active1?-->> <a href="index.html">Home/a> </li>`

compiled to:
`<li class="active">`

**Comment by devilskitchen** [comment]
Yes, it's the same issue as here: https://github.com/bdkjones/CodeKit/issues/434

@bdkjones is aware and looking at a fix.

In the meantime, your project will compile if you insert a space either side of the variable name, i.e. `<!-- $nav-active1? -->`.

**Comment by bdkjones** [comment]
Fixed in 3.5.1
