### ISSUE TITLE
Preview Feature not working once I initialized Git

### ISSUE THREAD

**Issue by bradleyDouglas** [bdkjones/CodeKit#438]
Hello

I was working on a project and the Preview feature was working just fine. Once I initialized Git, the preview feature stopped working. I now get this error:

"External Server Error"
"The returned error was: "The request timed out." (Code -1001)"

My setup is:

Editor: VS Code 
Local Environment: Local by Flywheel
CodeKit Version: 3.4.2

Is there a way to get this to start working again?

Thanks!

**Comment by bdkjones** [comment]
What have you tried to fix the issue? Rebooting is a great first step.

**Comment by bradleyDouglas** [comment]
I completely shut down Local and CodeKit. Re-started and still experiencing the same issue

**Comment by bdkjones** [comment]
Restarted what, the app or your Mac? Have you followed the steps on codekitapp.com/help/troubleshooting/?

**Comment by bradleyDouglas** [comment]
Restarted just the applications. Then the Mac. And went through the troubleshooting guide. Still getting the same issue

**Comment by bdkjones** [comment]
Ok, well, the next thing to do is test your local server. Can you view it directly without CodeKit?

**Comment by bradleyDouglas** [comment]
Yes, I can view the site directly without using Codekit. Which isn't a bad option, but I liked the use of browser-refresh + viewing every device at once.

**Comment by bdkjones** [comment]
What are you using for your external server?

**Comment by bdkjones** [comment]
Also, have you tried the non-Bonjour preview address?

**Comment by bradleyDouglas** [comment]
I switched my external server address from my localhost:5757 to the site domain Local creates. After I changed that, it appears to be working fine. 

Thank you for all your prompt responses!
