### ISSUE TITLE
Compressed output style gives incorrect css.map

### ISSUE THREAD

**Issue by ricklecoat** [bdkjones/CodeKit#441]
**Quick, short summary:**
css maps generated during scss compilation report the wrong scss partial when compiled using 'Compressed' output style. Recompiling using any of the other options (Expanded, Nested, or Compact) provides the correct partial.

**Expected results:**
In the provided demo page, doing 'inspect element' on the screenshot image (showing code) *should* yield a reported code partial of '_objects.content-images.scss:20'.

![compact](https://user-images.githubusercontent.com/13526883/36586521-0b18b474-187a-11e8-9b0b-bfc87106a7e0.png)

This is what is reported when using Expanded, Nested, or Compact output styles (this screenshot was taken using the Compact output mode)

**Actual results:**
When compiled using 'Compressed' output, however, it reports the partial as being _objects.news-articles.scss:53, as shown in this screenshot:

![compressed](https://user-images.githubusercontent.com/13526883/36586648-7d6e2d24-187a-11e8-8860-531c49c5f05a.png)

**Exact steps to reproduce:**
In the Codekit project's window (Files section) select mysupport-styles.scss and recompile it using different output styles. Re-inspect the image in the browser each time, clearing the cache first to make sure the changes are being reflected. (Note: I did these tests *without* using Codekit's preview server tool) 

**A link to download a simplified project or file that shows the issue:**
[Demo zip file here](http://www.efreeti.lecoat.com/Codekit_bugtest.zip). I've simplified the page down quite a lot and the problem still manifests, but I've deliberately avoided simplifying the modular scss structure in case that's the cause of the issue.

**Your configuration (any details about your system that you think might be relevant)**
Nothing really.

**Comment by bdkjones** [comment]
CodeKit doesn't create the source maps itself; the Sass compilers do that. If you're using Libsass, this bug should be reported on their GitHub repo. If you're using the Ruby Sass compiler, it would go there. CodeKit just writes what the compilers generate!
