### ISSUE TITLE
The field "build folder name" is no longer configurable

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#442]
Hi Bryan!

There is a problem with version 3.5 and 3.5.1.

I usually configure Codekit so that the build folder name is like this "../build"

Since version 3.5.X it is no longer possible to add 2 dots of affiliates.
I think the field is read live and self corrects.
I just did the test with version 3.4.2 I'm doing well.

**Comment by bdkjones** [comment]
This is correct. Earlier versions of CodeKit allowed entries like / which caused the build process to delete everything in the project folder. ../build is not valid because it targets a path above the project root folder.

**Comment by rvola** [comment]
ok I understand, damned user !!
How is it possible to make a build in a folder other than that of source?

**Comment by rvola** [comment]
I think in the way of Elon Musk to be able to add a mode "yes I am crazy man and I want to put what I want"
I'm sorry, because I know you like the big V8 gasoline 😁

**Comment by bdkjones** [comment]
Your build folder must be a child of the project's root folder. It does NOT need to be a child of your "source" folder:

    [project root]
        |--> [Source Folder]
                      |--> file.scss
        |--> [Build Folder]
                      |--> file.css

**Comment by rvola** [comment]
thank you Bryan
