### ISSUE TITLE
SVGO error with certain optimisations

### ISSUE THREAD

**Issue by pixelmachine** [bdkjones/CodeKit#443]
When optimising an SVG, selecting any of the following options results in an error:
```
- <script> elements
- XML Namespace
- Inline <style> elements to attributes
```

Error:
```
SVGO: Error: Couldn't parse config JSON.
SyntaxError: Unexpected token { in JSON at position 1019
```

I've tried with a few different SVGs in different projects, restarted etc.. 
Latest CodeKit 3.5.1 on MacOS 10.12.6. Happy to send you a simple project file if you can't reproduce it.

**Comment by bdkjones** [comment]
Thanks very much. I've found the problem and have addressed it for the next release.
