### ISSUE TITLE
CodeKit Hook shows error with exit code 0 when a message is sent to stderr

### ISSUE THREAD

**Issue by hpohlmeyer** [bdkjones/CodeKit#444]
**Quick, short summary:**
I am using Rollup to bundle my files with CodeKit.  
Rollup writes the code output to stdout and its info and log messages to stderr (https://github.com/rollup/rollup/issues/1955#issuecomment-364339972). If CodeKit sees a message in stderr, it throws an error, even though the exit code is 0.

![rollup-codekit-err](https://user-images.githubusercontent.com/6564077/37003774-7c47603a-20ce-11e8-8da7-5a9ecebedc0f.png)

**Expected results:**
CodeKit should log the messages from stderr, but only throw an error if the exit code is > 0.

**Actual results:**
CodeKit throws an error.

**Exact steps to reproduce:**
Use a hook that writes a message to stderr and uses an exit code of 0.

**A link to download a simplified project or file that shows the issue:**
[codekit-err.zip](https://github.com/bdkjones/CodeKit/files/1782898/codekit-err.zip)

**Comment by bdkjones** [comment]
Yea, the issue here is that Rollup is violating Unix convention. If you return `0`, you aren't supposed to write to `stderr`. I'm sort of in a damned-if-I-do-damned-if-I-don't situation because *other* tools incorrectly return 0 when they fail, but rely on me seeing that `stderr` isn't empty to determine that they had a problem.

Does Rollup have a `silent` option? That may be your best bet; if you can keep it from writing anything but errors, you should be set.

**Comment by bdkjones** [comment]
Also: I'd be interested in seeing how you're using Rollup in CodeKit via a Hook. Support for native bundling is underway, but the industry seems to have standardized on Webpack for that. What made you use Rollup?

**Comment by hpohlmeyer** [comment]
Ahh I see … it seemed kind off odd to me, that you put log messages to stderr but, when they said that stdout is reserved for actual output (not error messages) that did make sense to me. I solved it temporarily by redirecting the stderr to stdout, but using the silent flag sound far superior (yes rollup has one).

---

On Rollup:

The reason I am using rollup is that I like to keep my tasks separate. Webpack is great for bundling complex applications but needs a  lot of configuration (… or used to now with version 3). I like rollup for its simplicity. It bundles my JS and nothing more, which is what I want. Webpack comes in handy when I need to build complex apps with frameworks like Vue, but for smaller projects I still like rollup.

My Hook looks like this:
```
node_modules/rollup/bin/rollup -c --input "$CK_INPUT_PATH" --output.file "$CK_OUTPUT_PATH"
```
I just realised, that you could also use npx now, so this should work too:
```
npx rollup -c --input "$CK_INPUT_PATH" --output.file "$CK_OUTPUT_PATH"
```

Since bundling my files is the first thing I do, I have to disable Babel, Uglify and ESLint in CodeKit, otherwise it will throw errors because of the import syntax. Linting is done in VSCode, so I don’t need to do it in CodeKit. For transpiling and code minification i use `rollup-plugin-babel` and `rollup-plugin-uglify`.

CodeKit takes care of compiling my Sass code and setting up a dev server. This is still faster to set-up as a full-blown task runner.

The only major drawback with this approach is the missing CI support. With task runners I can spin up a Docker image on CI server, build my project and deploy it to my production-server. Unfortunately I am not aware of a way to install CodeKit on the fly on the CI server and let it build my project, which is why I have to upload my files manually to the production-server.

I have thought about running a Mac Docker image (wich seems to be possible with some hacks), install CodeKit via `brew cask` and control it with AppleScript to build my project, but especially with Docker not really supporting Mac images I don’t think it is worth the hassle.

I hope, I did not pollute the issue too much and my insights in the odd ways I use CodeKit can be of some help. ;)

**Comment by hpohlmeyer** [comment]
Oh and could you point me to the unix convention if has been written down anywhere? This would be helpful to discuss the way they handle log messages.
