### ISSUE TITLE
[BUG] Unable to configure UglifyJS 'max-line-len'

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#446]
**Quick, short summary:**
Tried to turn off 'max-line-len' in UglifyJS Prefs to stop annoying warnings. It kept warning me, despite being turned off. Set the number of chars to '32768' (UglifyJS's default). The input field disappeared from CodeKit's interface, and 'max-line-len' continues to be ON, regardless of checkbox setting.

<img width="720" alt="screen shot 2018-03-18 at 10 45 14 am" src="https://user-images.githubusercontent.com/2994472/37561090-b6c5d456-2a99-11e8-9912-4024fd8727c3.png">

<img width="713" alt="screen shot 2018-03-18 at 10 49 06 am" src="https://user-images.githubusercontent.com/2994472/37561110-3a690274-2a9a-11e8-829b-54efc153bcc2.png">

**Expected results:**
If 'max-line-len' is switched off, I'd expect UglifyJS not to check the outputted line length. If it is ON, I'd expect UglifyJS to quietly introduce line breaks, within the specified limit. I was a bit surprised at getting continuing warnings.

I'd also expect the input field to remain visible in the interface, regardless of the checkbox setting (that is how the other preference items work).

**Actual results:**
After entering '32768' in the input field for 'max-line-len', the field disappeared, never to return...
Also: the 'max-line-len' setting seems to be checked *always*, regardless of whether we set it to be 'on' or 'off'. 

**Exact steps to reproduce:**
Open a project that includes several js files, that once concatenated and compiled will result in an output of over 32000 characters. UglifyJS will issue 'warnings', regardless of whether 'max-line-len' is on or off.

Then, go to the 'max-line-len' setting and enter '32768' in the input field. Exit the preferences, recompile your js, and go back to the preferences. Your input field should now have magically disappeared.

**Your configuration (any details about your system that you think might be relevant)**
Using version 3.5.2 - build 26330 - on a MacBook Pro.

**Comment by bdkjones** [comment]
Well that's some straight-up magical nonsense right there. I've reproduced it on my machine and will now attempt to discover why the app is possessed by demons.

**Comment by bdkjones** [comment]
Are you using Uglify in "beautify" mode? The `max-line-len` option is only meaningful when Uglify is beautifying rather than minifying code.

**Comment by bdkjones** [comment]
Also, the "warning" that uglify prints is just ludicrously awful: `WARN: Output exceeds true characters` 

What the fuck does that even mean? How is a human supposed to parse that? Some developers should not be allowed to write ANY user-facing strings. The way this warning SHOULD read is: `Warning: Line 5 contains 32,312 characters. The maximum is 32,000.`

**Comment by luxlogica** [comment]
This whole issue seems to be an UglifyJS hiccup...

We _should_ be able to set a 'max-line-len' **both** when compressing and beautifying - as pointed out [in this issue](https://github.com/mishoo/UglifyJS2/issues/2624). But there seems to be a [very old issue](https://github.com/mishoo/UglifyJS2/issues/304) that makes it misbehave.

Not sure whether it works reliably at all....

**Comment by bdkjones** [comment]
Ah, I see what's up here. It's a classic integer overflow because that value is stored as a 16-bit int. I'll fix that part. As for `max-line-len` being on/off: it only applies when Uglify.js is set to beautify instead of minify.

**Comment by bdkjones** [comment]
@luxlogica you'll need to open the `codekit3.config` file in a text editor, search for `max-len-len` under the `uglifyjs2` flags and change that to a positive integer between 1 and 32760. When you install the next release, you'll be able to use any positive integer between 1 and 9,223,372,036,854,775,807. However, if you don't edit that value, CodeKit will see it as a negative one, which is the signal to the app to hide that value textfield.

I would suggest, as a practical matter, that if you manage to obtain a file with 9,223,372,036,854,775,807 characters on a single line that you: 

(A) Re-evaluate your life choices.

(B) Travel back in time to share with us the insanely powerful future computer capable of parsing and displaying that file.
