### ISSUE TITLE
Projects not refreshing on open

### ISSUE THREAD

**Issue by lewisdonovan** [bdkjones/CodeKit#447]
**Quick, short summary:**
When opening the app, the initial project & framework refresh hangs endlessly.

**Expected results:**
Project & framework refresh finishing after a minute or so, and then being able to use the app.

**Actual results:**
Project & framework refresh not finishing (have been waiting over 10 mins). I can't interrupt the refresh to remove any stale projects, and there's no option in the preferences to disable it.

**Exact steps to reproduce:**
Open the app

**A link to download a simplified project or file that shows the issue:**
N/A

**Your configuration (any details about your system that you think might be relevant)**
All preferences are set as default. The issue is not project-specific - or if it is, I have no feedback on which project is causing the hang.

**Comment by lewisdonovan** [comment]
This was due to an issue connecting to a folder on a local server in the building. Closing this issue.

**Comment by bdkjones** [comment]
Interesting. If you can give me a setup to reproduce that, I'd like to get some logic in there that times out after a while if the folder can't be reached across the LAN.

**Comment by lewisdonovan** [comment]
AFAIK it's just an old Mac machine, acting as a file server. It was set up by the network guys at our office so don't really know beyond that.
