### ISSUE TITLE
SVGO syntax error

### ISSUE THREAD

**Issue by pixelmachine** [bdkjones/CodeKit#450]
Hey there seems to be another SVGO syntax bug like #443 

This time it's the "Lists of values" option, resulting in:
```
SVGO: Error: Couldn't parse config JSON.
SyntaxError: Unexpected token ] in JSON at position 1101
```

**Comment by bdkjones** [comment]
Ah yes. It only happens when that option is turned on, right? I see why and I've fixed it for the next update, which should be out next week.
