### ISSUE TITLE
Do not see updates anymore (foundation)

### ISSUE THREAD

**Issue by delirius** [bdkjones/CodeKit#451]
Thanks for the update, install foundation with npm. At the moment I do not see updates anymore -> installed packages

![image](https://user-images.githubusercontent.com/2039398/38422850-8388f3f8-39ac-11e8-929e-bfde4e6ed3ac.png)

**Comment by bdkjones** [comment]
Yep. That's because Foundation is not installed through Bower any longer. Migrating away from Bower is coming in a near-future release. When I have that done, updates through the GUI will be available again.
