### ISSUE TITLE
Codekit 3 doesn't refresh PHP pages in browser

### ISSUE THREAD

**Issue by johnbirt** [bdkjones/CodeKit#452]
Had problems getting Codekit 3.5.2 to use the Apache server and PHP on OSX High Sierra 10.13.4.
It appeared that updates to OSX overwrite stuff in .conf files and that was the cause. That has been resolved and browser refresh seems to work OK with the native Apache server at least for html files.

Saving alterations to PHP files in Microsoft Visual Code Editor cause Codekit to update/re-compile OK but the browser page does not refresh. A manual refresh works so a niggle rather than a major inconvenience.
John B

**Comment by bdkjones** [comment]
Do you have opCache enabled? That’s usually the cause of this and why I recommend using Mamp—CodeKit automatically detects it in Mamp and warns you.

**Comment by johnbirt** [comment]
I have opCache disabled in PHP.ini but it shows up as enabled in oh-admin.php. A couple of utilities show the Zend module not loaded?

All rather confusing! I don’t wish to run MAMP when I have a native server so i will stick with things as they are and refresh pages myself until i find a fix.

Thanks for your attention.

Regards.

John

On 6 Apr 2018, at 18:57, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have opCache enabled? That’s usually the cause of this and why I recommend using Mamp—CodeKit automatically detects it in Mamp and warns you.

**Comment by bdkjones** [comment]
If opcache is running, that’s 99% likely to be the culprit. If you modify a stylesheet in an obvious way, do you see that change in the browser? When you save your php file, does the browser url bar show a reload event?

**Comment by johnbirt** [comment]
Bryan.

I have now tried XAMPP which behaves the same as native Apache - refreshes HTML, CSS changes perfectly but does not refresh the browser for PHP. Although phpadmin.php seems to suggest ZEND opCache is running, it is not according to other utils.

I have also tried MAMP which indicated that opCache was NOT running but CodeKit thought it was and disabled it and requested a restart. After that browser refresh would not work AT ALL for any file changes and CMD-R was necessary to get a refresh.

I have now removed XAMPP and MAMP altogether and will try a different editor see what happens. I did however disable any editor plugins that may have caused an issue.

For now am happy to use CMD-R in the browser window and use native Apache. Not a big issue but puzzling.

I have to say there is a great deal to be said in all the usual internet sources re trying to enable/disable opCache and it appears to have been a continuing issue with no clearcut answer.

Not helped by the surprising fact that PHP 7.1.14 suppled with 10.13.4 doesn’t by default use a PHP.ini as afar as I can see you have to make one up yourself using cp /etc/php.ini.default /etc/php.ini and then adjust as needed e.g. to disable/enable opCache which I did. Certainly phpadmin.php verifies that /etc/php.ini is being used. It looks as though opCache is switched on by default if the module is loaded. However as pointed out in all my investigations the Zend module is NOT loaded as far as I can see and the info via oh-admin.php is bogus.

I will leave it there for now and report back if I find anything - not worth wasting further time on avoiding a couple of key-presses but an annoying niggle nevertheless.

I find it most puzzling that MAMP didn’t even produce the CodeKit “Finished processing" notification” for me and did not browser refresh at all but the page refresh button in CodeKit and CMD-R in the browser worked fine. Although Apache is not easy to configure on a Mac especially since Apple keep messing with the installation every update it is at least for me preferable to having MAMP or XAMPP which for me were not better at all.

Kind regards.

John



On 7 Apr 2018, at 00:53, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

If opcache is running, that’s 99% likely to be the culprit. If you modify a stylesheet in an obvious way, do you see that change in the browser? When you save your php file, does the browser url bar show a reload event?
