### ISSUE TITLE
Codekit trying to import a file when the word import is in a string

### ISSUE THREAD

**Issue by marysomerville** [bdkjones/CodeKit#453]
I updated CodeKit this morning to version 3.6 build 26667

I have the Javascript below in my file and the word import is being picked up by CodeKit and trying to import something. It was fine in the previous version of CodeKit.

```
'en': {
          text: "You can recycle large wooden boxes, that might have been used to ship exotic animals or valuable jewels.",
          answer: "Unpainted wood gets chipped down and used for fuel. This means that we can import less coal.",
          result: true
        }
```

I then get the compile error 

> The file "/assets/js/app.js" attempts to import a file that cannot be found: ","

It took me a while to realise it was this string that was causing the issue. If I remove the word import from the sentence it compiles fine. 

How do I fix this?

**Comment by bdkjones** [comment]
Ah, thanks. I've pulled the 3.6 update for the moment as it seems folks on older releases of macOS are having some issues. I'll get this addressed for the next time I release it.

**Comment by marysomerville** [comment]
Version 3.6.1 has fixed this for me.
