### ISSUE TITLE
Codekit 3.6 does not work anymore

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#454]
**Quick, short summary:**
The new version does not compile anymore

**Expected results:**
Compile files or project

**Actual results:**
The compilation of a project begins.
The system seems to hang (several tests on several projects)
CPU by hell

**Comment by bdkjones** [comment]
I need a demo project that shows the issue and details about your system. This report by itself doesn't give me anything to go on.

**Comment by rvola** [comment]
Sorry Bryan, for the disgusting report.
I was doing a demo video and I just saw that version 3.6 no longer exists.

I read a problem here #453.
Yes I also use Mac 10.12.6

**Comment by rvola** [comment]
the problem occurred during the compression of the JS that does not arrive at the end.
The project was so large that I can not see the end of the report.

Sorry to have more items to provide.
