### ISSUE TITLE
Cannot play local video 

### ISSUE THREAD

**Issue by xcrap** [bdkjones/CodeKit#455]
I cannot play any local video with in my localhost, sometimes it plays some seconds and stops sometimes it does not play nothing...

<video src="videos/videos.mp4">... 

POST https://app.getsentry.com/api/30379/store/?sentry_version=7&sentry_client=raven-js%2F3.9.1&sentry_key=af2f5e9fb2744c359c19d08c8319d9c5 400 (BAD REQUEST)

If I replace the local link to a http link it works without a problem.
If I use Mamp Pro (http://site.local/videoplayer.php) directly without using Codekit also works with local files without a problem.

This only happens running under Codekit Browser Preview.

**Comment by bdkjones** [comment]
Please send me the project in question and all files I need to duplicate the issue over here.

**Comment by xcrap** [comment]
http://www.waka.pt/villaboscana.zip
It's available here. 

It works great on http://villaboscana.local (From Mamp) but fails at http://xcrap:5757 (Codekit)
I'm having this issue with all my projects that includes local videos, using direct video tags, slideshows, Plyr, basically anything that includes videos.

**Comment by bdkjones** [comment]
Hmm. So your test project works flawlessly in Safari and Firefox. I do see the problem you reported in Chrome when using the Preview Server addresses. And I do see that Chrome plays the video fine when viewed on MAMP directly.

I don't know if this is a CodeKit issue or a Chrome issue. Can you remove all the ancillary JavaScript junk around the video and eliminate that from the page? It reduces variables—whatever all that JavaScript is could be the culprit on Chrome.

**Comment by bdkjones** [comment]
Firefox does stop playing after a while with this error:

![screen shot 2018-04-09 at 18 26 05](https://user-images.githubusercontent.com/926566/38531196-973e4a46-3c23-11e8-9252-024baa0c9713.png)

**Comment by xcrap** [comment]
If you remove all the JS it will play fine.

<video src="videos/villaboscana.mp4" poster="videos/villaboscana_poster.jpg" id="video_loop" preload"auto" autoplay muted loop></video>

Something like this with Codekit server will work perfectly. This problem comes with the introduction of any JS video player or slideshow, I've tested like I told, Plyr or MasterSlideshow, this are big scripts that I use in a lot of projects and whenever they play the local videos it hangs in Chrome. You're right, it's working well in Safari and Opera, just failing on Firefox and Chrome, beeing Chrome my n1 test tool. I don't get it why it's only with local files, makes no sense but in deed only happens with additional scripts :\

**Comment by xcrap** [comment]
I'll keep checking future updates of Chrome and also this scripts to see if it makes any difference or even others to see how they react, or if I discover something new that is relevant I'll let you know. Thanks. Back to remote streaming testing :)

**Comment by bdkjones** [comment]
The other option is to preview in Safari! Way better battery life than Chrome, and a faster browser to boot. The web inspector is not as good, but you can use Chrome's for that.
