### ISSUE TITLE
Project list has intermittent problems closing

### ISSUE THREAD

**Issue by nodinx-eric** [bdkjones/CodeKit#457]
When attempting to close the project list by clicking out of it will sometimes not actually close it. It seems to rear it's ugly head more if I click on the project thumbnail twice.

Ideally, getting the project list to go away should take 1 click and it shouldn't matter where that click is within the window. I find myself almost always clicking on the project thumbnail to get the list to go away. It never works.

[screencast of this](https://drive.google.com/open?id=1dhsm6mW5shcOL6qzzSQVcFxlOf4Y2ur5)

For me it's been happening ever since v3.0, and results in rage clicks!

Currently on macOS v10.13.4 / CodeKit v3.6.1 (build 26680)

**Comment by bdkjones** [comment]
Uh... clicking on the project icon is what *opens* the projects popover. In every other case I can find on macOS, clicking the thing that opens a popover will not dismiss the popover. For example, buttons in the Safari toolbar that open popovers for browser extensions. 

If you want to dismiss the popover, don't click the thing that shows the popover.
