### ISSUE TITLE
Codekit 2 File Watcher not detecting changes to project

### ISSUE THREAD

**Issue by pressoholics** [bdkjones/CodeKit#460]
Having an intermittent issue when saving a sass file in phpstorm, the file watcher doesn't detect the change and trigger the recompile, i then have to recompile manually by clicking the button.

This doesn't seem to happen every time, sometimes it works for a while but then stops detecting changes. I then have to shutdown and restart codekit which sometimes fixes it but not always.

Using PHPStorm, Vagrant, vvv2

Any trouble shooting steps I can try?

Thanks

**Comment by bdkjones** [comment]
Use CodeKit 3.6.1
