### ISSUE TITLE
Output settings are not applied when I change the file extension

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit#464]
**Quick, short summary:**

The output settings are not applied when the file extension is changed. CodeKit 3.6.1 — Build 26680.

**Steps to reproduce:**

1. Go to Languages > Other
1. Add a new extension, e.g., `*.tmpl`
1. Set `*.tmpl Output` to `Ignore *.tmpl files on change/build` or to `Process *.tmpl files on change/build`
1. (Optionally click `Apply Changes To Existing Files`)
1. Create a new file: `test.txt`
1. Rename the file to `test.tmpl`

**Expected results:**

The file `test.tmpl` is handled according to the settings for `*.tmpl` files.

**Actual results:**

The file with the new extension is still handled as if it had the previous extension: `.txt`.

Only after I go and click `Apply Changes To Existing Files` will the file be ignored or processed.

**Comment by zengabor** [comment]
Starting to notice that this happens when I change the extension of the file. For example, from `something.tmpl` to `something.gohtml`. CodeKit still acts like as if the file had the previous extension. Updated the reproduce steps accordingly.

Unfortunately this happens often because my editor always creates new files with a specific extension, so I have to rename most of the newly created files. :(

**Comment by bdkjones** [comment]
Ok, I’ll take a look. Thanks!

**Comment by zengabor** [comment]
If anyone faces the same issue: the workaround is hitting the `Apply Changes To Existing Files` button. This will update all files according to the new extension.

**Comment by zengabor** [comment]
Looks like this is only reproducible if both the old and the new extensions belong to the "Other" file types. Known extensions like `.kit` are not affected. So an easy workaround was changing the editor's default file type.

**Comment by bdkjones** [comment]
I see why this is occurring. CodeKit uses one fileType for all "other" kinds of files. When refreshing a project, if you change a file from, say, *.scss to *.js, CodeKit changes the fileType assigned to that item and then deletes the old entity and rebuilds a new one with settings for the new fileType. 

In the case of "other" files, the actual fileType doesn't change even though the extension has changed, so CodeKit does not rebuild the model entity for that item and the settings don't switch. When evaluating other types, I'll need to look at the extension.

**Comment by bdkjones** [comment]
Fixed for the next release. Nice edge case.
