### ISSUE TITLE
High memory usage / Unstable

### ISSUE THREAD

**Issue by Brandoning** [bdkjones/CodeKit#465]
**Quick, short summary:**
In certain projects, even after fully clearing the project list using safe mode and re-loading it then dragging the project back in it will use over 1GB of RAM or become slow and unusable.

There is nothing special about this project, other than it includes files from node_modules but even with that folder skipped it still becomes slow and unresponsive.

**Expected results:**
Considering other file watching preprocessors do not use this level of RAM and stay stable throughout changes to the project I would not expect CodeKit to be this slow. It does work great for certain projects but ones with large file structures or doing codekit-append/codekit-prepends.

**Actual results:**
CodeKit freezes, no settings can be changed even if you can reach the settings screen, has what appears to be a memory leak and then crashes eventually. Even after starting the application in safe mode.

**Exact steps to reproduce:**
Start in safe mode with a project with large node_modules folder and include some files from it to a "libs.js" file for example.

**A link to download a simplified project or file that shows the issue:**
N/A - Project includes client files

**Your configuration (any details about your system that you think might be relevant)**
![screen shot 2018-05-22 at 10 41 49](https://user-images.githubusercontent.com/5629295/40355271-e2399a54-5dad-11e8-91c9-e2e2dd1892de.png)
![screen shot 2018-05-22 at 10 41 39](https://user-images.githubusercontent.com/5629295/40355330-ff81d5cc-5dad-11e8-93a9-b3375dcdaabd.png)
![screen shot 2018-05-22 at 10 41 30](https://user-images.githubusercontent.com/5629295/40355351-0b65c52e-5dae-11e8-83f6-577ceaa88c4c.png)

Apologies if this is too vague but I see this issue more increasingly with newer builds of CodeKit. Maybe some optimisation is needed shortly? Or am I configuring things wrong

**Comment by bdkjones** [comment]
I need a demo project. I test with 70,000 item projects and do not see this behavior.

**Comment by bdkjones** [comment]
It sounds like you may have set up an infinite import loop in a project. CodeKit detects most of those and warns you, but there are certain edge cases where detection isn't possible.

**Comment by bdkjones** [comment]
Also: the memory usage reported in Activity Monitor is not the app's current memory footprint. It's a high-water-mark; the max amount the OS has currently provided to that app. It's not unusual for that to be around 1GB when dealing with 70,000 item projects, as CodeKit opens and scans most of those files while indexing and does so on up to 16 threads, which means a lot of simultaneous RAM usage at the high point. The only accurate gauge of memory use is to run the app attached to Instruments.
