### ISSUE TITLE
[FEATURE REQUEST] A close button on notification pop ups

### ISSUE THREAD

**Issue by jaredgeddy** [bdkjones/CodeKit#466]
When CodeKit creates a notification on my Mac it blocks my right top corner of my screen. I understand this seems very minor however, it occasionally ends up blocking the tab I'm trying to bring to focus in my browser. Hovering only makes it stay longer and there is no system default to close notifications. They just sit there blocking anything behind them. I don't want to have to turn off notifications, just be able to quickly close them if they are in the way.

**Comment by bdkjones** [comment]
Dragging them to the right will swipe them away. CodeKit supports Growl and posts notifications through Growl's API, which targets the system notification API if Growl is not installed. I'll see if it's possible to add the buttons.

**Comment by jaredgeddy** [comment]
Good to know, thank you! This has plagued me on countless other apps, I had no idea I could drag those buggers to the right. Thanks for the protip!
