### ISSUE TITLE
[Feature Request] Unicode 12 / Emoji 12 converter

### ISSUE THREAD

**Issue by BenjaminHoegh** [bdkjones/CodeKit#467]
A feature to be able to make CodeKit convert Unicode/Emoji's codepoints (eg  `U+1F600` or 😀) to there HTML hex value to make them display in the browser

**Comment by bdkjones** [comment]
This is sort of an edge case and implementing something that’s built into CodeKit would require constant updating as new emoji come out.

A better vector for this is an npm package (one must exist already, no?) that can be installed and then run with a Hook.
