### ISSUE TITLE
Renaming file with same name but different capitalization doesn't trigger refresh

### ISSUE THREAD

**Issue by dlewand691** [bdkjones/CodeKit#468]
**Quick, short summary:**
Changed asset name from Image.jpg to image.jpg and refresh did not happen.

**Expected results:**
Project refresh and asset updated.

**Actual results:**
No change.

**Exact steps to reproduce:**
Change the capitalization of an asset name, but keep it the same.

**Comment by bdkjones** [comment]
Mmm, this is because the standard macOS disk format is case-insensitive. The file technically was not renamed, so no change event registered.

**Comment by bdkjones** [comment]
Unfortunately, there doesn't seem to be anything I can do about this. The kernel doesn't send a file-changed event for the rename because, as far as it's concerned, there WAS no rename.
