### ISSUE TITLE
[Feature Request] Ability to define basedir for Pug/Jade

### ISSUE THREAD

**Issue by feshin** [bdkjones/CodeKit#470]
When using Pug to generate html files there is no way to specify the basedir (although I could totally be missing some magical way to do it within Codekit). Without the basedir, when adding new .pug files that extend a base template, such as _base.pug, the reference must be relative instead of absolute.

For example: A nested subpage such as www.site.com/en/some-page/a-sub-page/index.pug would need to reference the master template like so: "extends ../../../includes/_base" (assuming _base.pug is at site.com/includes/). 

With basedir set, an absolute reference can be used: "extends /includes/_base". 

This would be super helpful, as the relative references continually need to be changed, depending on the folder structure.

**Comment by bdkjones** [comment]
This was added in 3.13 I believe. The basedir is always the root project folder, so as long as you specify the paths from there you can use absolute paths.
