### ISSUE TITLE
Legacy browser "support"

### ISSUE THREAD

**Issue by chris-scheurle** [bdkjones/CodeKit#471]
The topic of Accessibility is not limited to 'blind people surfing the web'. It's also about poor people that can't afford to buy a new computer every 2 years (or even decades). *And* old perople,  e.g. like my MD, who just *like* things how they painstakingly set them up some 27 years ago (yes, that means Windoes 95™ and at least in my country, there's a **lot** more of those than blind people, or colorblind).

So I try my best. It's not about 'pixel perfect'. It's just about
> They get the necessary information without all of the features. And if all things go well, there's no confusing  error messages popping up.

Debugging those situations with CodeKit is tiresome. The code you use for your injector scripts is rather modern, even IE9 (still supported by jQuery, based on usage statistics in the US) gets a bit bothered and runs away screaming.

So, *please*: either add an option to 'just serve stuff, don't interfere' to CodeKit's user preferences, or even simpler, just add
```javascript
try {
```
*[your injection scripts here...]*
```javascript
} catch (e) {
    alert('This browser is very, very old');
}
```
to your code.

**Comment by bdkjones** [comment]
I obviously don’t test IE 9, but if you can pinpoint the exact issue I may be able to help. It’s not nearly as simple as wrapping things in a try block—that’s already in place for the websocket connection. 

IE9’s usage is down to 1% globally and it’s 7 years old, so it’s extremely hard to justify worrying about it. If you’re running CodeKit, by definition you have a machine capable of running newer browsers.

**Comment by chris-scheurle** [comment]
@bdkjones wrote:
> If you’re running CodeKit, by definition you have a machine capable of running newer browsers.

If I'm running *CodeKit*, by definition I have a *Mac* :smirk:

@bdkjones wrote:
> IE9’s usage is down to 1% globally and it’s 7 years old, so it’s extremely hard to justify worrying about it.

Well, then it's 1% for legacy IE, 1% for old Firefox, 1% for old Chrome, 1% for old Opera, 1.5%, for unrecognized browsers and I'm sure *somewhere*, there's still some lonely Lynx roaming about. These things tend to add up.

I totally get that you can't worry about every piece of outdated software on the planet. Hence my suggestion to serve the page preview in a way that doesn't break unsupported browsers.

@bdkjones wrote:
> if you can pinpoint the exact issue I may be able to help

:smile:

Seems like IE9 doesn't know `WebSocket`:
```javascript
window.WebSocket = window.WebSocket || window.MozWebSocket;
g = new WebSocket(m, ['ckrp']);
```

So, some simple feature detection should solve that problem:
```javascript
window.WebSocket = window.WebSocket || window.MozWebSocket;
if (!window.WebSocket) {
    return;
}
g = new WebSocket(m, ['ckrp']);
```

**Comment by chris-scheurle** [comment]
*thanks!*
