### ISSUE TITLE
[Feature Request] Update to Less v3.7.0

### ISSUE THREAD

**Issue by calvinjuarez** [bdkjones/CodeKit#472]
https://github.com/less/less.js/releases
https://www.npmjs.com/package/less

Less has updated to v3.5.3.

**Comment by bdkjones** [comment]
Yea. I attempted to put 3.0 in the last CodeKit release, but it was so monstrously buggy that I had to pull it. I decided to wait and let the Less team shake out their issues. I'll give it another go for the next release.

**Comment by bdkjones** [comment]
Any particular reason you're not on Sass? The industry seems to have standardized on that language.

**Comment by calvinjuarez** [comment]
I prefer Less and how it works.  I also feel like Less, like tab indentation, is more popular than it sometimes seems.

Yeah, 3.0 was buggy.  3.5 has a ton fixed, though.  For what it's worth, I'd be happy to be your point man on bugs you find.

**Comment by bdkjones** [comment]
At the time, Less 3.0 would not load plugins correctly and I couldn't get it to handle the minification plugin (less-clean-css). That made it a non-starter for shipping. 

If that's fixed in 3.5, I think I can include it.

**Comment by seanCodes** [comment]
@bdkjones Kind of off topic, but I wonder if some of these language-update complexities/dependencies could be worked out by the community to save you time and effort. Would it be practical at all to shift some of that burden to users/maintainers?

**Comment by katerlouis** [comment]
I'll also watch out for bugs, since I am a LESS guy myself.
fyi: one big reason why I stick to LESS is the much shorter way to call mixins:

```css
// less
.something {
    .mixin("great", "stuff");
}

// scss
.something {
    @include mixin ("meeh", "so long!");
}
```

Also great, normal classes can be used as a mixin aswell. If you don't want to pollute the css with this mixin, just do `.mixin() { ... }` – also really nice.

**Comment by luxlogica** [comment]
Also: as someone who has to teach pre-processing languages to newbie frontend developers, I assure you LESS is easier for someone already familiar with CSS. Like CSS, Less is declarative (a mere superset of CSS), while SASS is imperative (more like a programming language) which requires a different mindset to master. 

The LESS parser can also be embedded in the browser, which makes it handy for developing things like admin interfaces, where speed is not an issue and you want dynamic stylesheet functionality.

**Comment by calvinjuarez** [comment]
Update: Less is on version 3.7.0

**Comment by calvinjuarez** [comment]
It's mostly been features, like an `each()` function, and housekeeping, like updating some dependencies for CI testing.

**Comment by calvinjuarez** [comment]
Has this been shelved, then?

**Comment by bdkjones** [comment]
Hmm? No; I update all components for each release.

**Comment by calvinjuarez** [comment]
Understood.  Just seemed like it'd been dismissed.  I'll wait for the next release.  Thanks!

**Comment by devilskitchen** [comment]
OK, severely opinionated comment inbound...

LESS is for actual, y'know, real front-end developers who started on CSS, and understand its power.

SASS is "standard" in the industry for developers who _think_ that they understand CSS, and who have spent their lives in fetid bedrooms with their beloved PHP $ signs. They are the same people who think that Bootstrap is the best thing in the world _eva_.

Real CSS wranglers use LESS.

**Comment by bdkjones** [comment]
Mmm, I think Less lost the battle because their releases were buggy and people couldn’t depend on them. They removed features and changed things without a formal deprecation process. When it was just cloudhead, Less was pretty great. When a whole slew of folks got involved, quality declined and using the language became frustrating. Folks left for Sass and that was that.

I’m not saying they need to be perfect or that Sass is 100% bug-free. But when you cut a release and then you have to cut 34 more over three weeks…something went wrong. 

Sass also moved to Libsass, which *blows away* JavaScript in performance. Especially as implemented in CodeKit, where there’s not even a JS wrapper around Libsass—it’s a straight C-to-C++ interface. 

But, at the end of the day, I don’t think the one you use matters. Whatever CSS-like language you love, we can all agree on one thing: it’s better than fucking javascript.

**Comment by devilskitchen** [comment]
God, I love your comments—and still love your release notes (read ‘em every time).

You’re probably right in all of the below: however, our company uses LESS over SASS (my fault) and I’d like to see it updated occasionally. Having said that, most of our FEDs are about as quick to embrace change as a snail embracing an exciting new plant—so no hurry.

Regards,

c

--------------------------------------------
Chris Mounsey
"Devil's Repose"
--------------------------------------------
http://devilsrepose.com

**Comment by bdkjones** [comment]
Oh, it’ll be updated in the next cycle. This one is longer because of work to support Mojave. Getting close.

**Comment by devilskitchen** [comment]
OK, while we’re here, I’ll just say that CodeKit is totes amazing. The best feature by far is the ability to over-ride with local CSS. Sooooo much time saved—especially with our on-premise clients.

Regards,

c

P.S. I understand your Pattern thing; you want to do other things. But I would rather you concentrated on the tool that I use. Selfish, I know. But hey ho…

--------------------------------------------
Chris Mounsey
"Devil's Repose"
--------------------------------------------
http://devilsrepose.com

**Comment by katerlouis** [comment]
When you think you know a tool :D 
@devilskitchen What is overriding local css?

**Comment by calvinjuarez** [comment]
> Whatever CSS-like language you love, we can all agree on one thing: it’s better than fucking javascript.

🙌 💯 🙌

**Comment by bdkjones** [comment]
Implementing Less 3.x today and it appears they solved the bugs that were around in the initial 3.x release. Plugins now load correctly, so I can move forward.
