### ISSUE TITLE
Mojave Issue

### ISSUE THREAD

**Issue by garethjohnsdesign** [bdkjones/CodeKit#474]
I've recently started running MacOS Mojave but there is an issue with the Codekit interface basically making it unusable, the interface works fine in High Sierra. Is there any settings I can change to get this working or does it need to be updated on your end?

<img width="949" alt="screenshot 2018-07-09 at 13 13 49" src="https://user-images.githubusercontent.com/6154956/42449854-218afc60-837a-11e8-87eb-6ac342d6604f.png">

**Comment by BenjaminHoegh** [comment]
also have this issue, possible its just a bug in the beta, but could relate to the new dark-mode. So I would not say it doesn't need to be updated to Mojave

**Comment by garethjohnsdesign** [comment]
Did you manage to fix this?

**Comment by garethjohnsdesign** [comment]
I just installed Mojave Beta 3 but it's still causing issues, obviously my fault for installing beta software but is there anyway to fix this?

**Comment by bdkjones** [comment]
You got it right: beta software. CodeKit will work perfectly on Mojave when Mojave is released. Until then, your mileage may vary. I’m working on updates, but if *I* am not running Mojave on my primary Mac, you should not be either.

**Comment by floppyTop** [comment]
@garethjohnsdesign , just curious... Is this issue only replicated with Dark Mode enabled? I'm thinking about installing Mojave tonight, am curious if this is still an open issue or not.

**Comment by bdkjones** [comment]
The issue is closed. CodeKit 3.7.1 is 100% ready for Mojave. Make sure you have 3.7.1.
