### ISSUE TITLE
Mojave Issue 2 - Missing App icon

### ISSUE THREAD

**Issue by BenjaminHoegh** [bdkjones/CodeKit#475]
<img width="282" alt="skaermbillede 2018-07-09 kl 16 12 38" src="https://user-images.githubusercontent.com/22152591/42455617-0b2ab0be-8393-11e8-97fe-ca7195f933b3.png">

**Comment by bdkjones** [comment]
As usual, Apple has fixed their bugs in later developer previews. Mojave shows the icon now.
