### ISSUE TITLE
Feature Request: is it possible to perform a clean build but leave the .git folder in the build foldder?

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [bdkjones/CodeKit#477]
My environment:
I use two repo's.
One is in the source folder for GitHub and one is in the build folder because I use Git to autodeploy to my server.

If there is a better way to achieve my goal I would like to hear your feedback otherwise  

I would like the feature to perform a clean build but leave some folders intact.
Kinda like you can with the 'skipped folder' function.

I don't know if this is possible or if this is doable or even if it might already exist.

Platform: macOS 10.13.5

**Comment by bdkjones** [comment]
It’s not directly possible. The build folder should never contain any items that are UNIQUE to that folder; the items should always exist elsewhere. You could achieve this by adding a couple steps to the build process. First one would copy the Git folder to a temporary spot, then have CodeKit build your project. Last build step would copy the Git folder back to /build. The “run script” step with the cp command will get the job done.

**Comment by bdkjones** [comment]
An alternate approach would be to disable the clean build option, then add your own “clean” step to the start of the build process that deletes only the items you want to delete. Could even have a Bash script that tests filenames against criteria to decide. This is why CodeKit has this capability—for custom edge cases like this.

**Comment by Luca-Castelnuovo** [comment]
Thank you for the information I will implement the script after build solution.
