### ISSUE TITLE
Folder Modified Date (Not Updating on SCSS Changes)

### ISSUE THREAD

**Issue by xcrap** [bdkjones/CodeKit#483]
So I normally have the following folders for my projects
/sources/custom.js -> Processes to /js/custom.min.js
/sources/styles.scss > Processes to /css/styles.min.css

When processing JS files, the JS folder is correctly updated with the modified date of the last change, that is the custom.min.js. But when I process an SCSS file it's not updating my CSS folder. The file itself is updated correctly but the folder keep an older date and it's never updated.

It would be food it when processing an SCSS file the folder would also have a modified date from the last update because when I'm using FTP I normally order by Last Changed to I only upload the last modified files, it works with everything except SCSS processing at this point. I'm not sure if that's an expected behavior or not.

**Comment by bdkjones** [comment]
Hmm. The generated CSS file should register as a new (or modified) file with your FTP app. The metadata for the folder it's in should have nothing to do with it. What FTP client are you using?

**Comment by xcrap** [comment]
Well, the CSS file has a new date, that's correct. But the folder where the file is into it's not updating it's "Modified Date". But the folder where the JS is compiled to it does. Is it not weird?

**Comment by bdkjones** [comment]
It shouldn't make a difference to an FTP client. That FTP client should find changed files, wherever they are. CodeKit does not normally write JS or Sass output files itself; it allows the respective compilers to handle that. (Except in some cases, where the file-writing is handled by the app itself.) One compiler may modify metadata on the enclosing folder while the other does not.

**Comment by xcrap** [comment]
<img width="1358" alt="screen shot 2018-08-05 at 13 40 18" src="https://user-images.githubusercontent.com/828596/43686481-6571bc9c-98b6-11e8-9920-895f78803a5f.png">

Well I'm using Transit, the FTP does not search for the modified file inside the folder, it presented the list of files and folder and use their modified date, for folders too instead of searching inside them as you can see on the list. But I think it's a problem how macOS reflects the modified date.

I've just updated the styles.scss and custom.js inside sources. The "modified date" of the own folder where I've updated the files was not updated. Also with the CSS folder of the generated styles.min.css was not updated but somehow the compiler for the js files have updated the folder modified date of /js.

I've realized if I copy a new file using MacOS GUI it updates the folder. If you remove or delete a file throughout  macOS GUY always update and the answer appears to be in this first comment:

https://discussions.apple.com/thread/2395788

"If a file is modified by a non-GUI process, it may not mark the folder as having been modified. You can use the Terminal to edit a file or just touch it to change the modified date, but it will not change the date modified of the parent folder.  Editing with a GUI process seems to mark the folder as being modified, also."

**Comment by bdkjones** [comment]
Hmm. I use Transmit all the time and have never had an issue with it not recognizing certain files as modified. Transmit is what I use to sync CodeKit’s website to my server, for instance, and it always finds the newly-generated output files from Sass and JavaScript source files, regardless of the metadata on the enclosing folders.

Can you put together a small demo project and an *exact* set of steps to reproduce what you’re seeing?
