### ISSUE TITLE
Problem Minifying Certain JS Files

### ISSUE THREAD

**Issue by xcrap** [bdkjones/CodeKit#484]
This has nothing to do with Codekit and it's probably a problem with external scripts or some UglifyJS2 parameters but maybe someone could help.

I have a problem when minifying some scripts. The compiled file always produced an error like that (see below). I've been having this minifying problem for years with Codekit. I also tried to avoid using scripts that make this happen but sometimes it's impossible.

<img width="1679" alt="screen shot 2018-08-03 at 13 35 45 1" src="https://user-images.githubusercontent.com/828596/43681067-aa825784-9838-11e8-9453-7d88a4fd50e2.png">

If I disable the minify option It works perfectly. 
This only happens when I prepend some scripts like for example:
Gmaps.js (https://github.com/hpneo/gmaps/blob/master/gmaps.min.js)
Tilt.js (https://gijsroge.github.io/tilt.js/)

If I don't use then I can minify the files, if I use the I have to uncheck the minify. This is a problem because I always like the optimized JS for obvious reasons. Does anybody have any idea of what the problem can be?

I always prepend external JS in a single file like...
// @codekit-prepend "tilt.jquery.min.js";

**Comment by bdkjones** [comment]
3.7.3 contains a much newer version of UglifyJS. Give this a shot with the latest version of CodeKit and see what you get.
