### ISSUE TITLE
Is it possible to add missing preview browser to list

### ISSUE THREAD

**Issue by macfire** [bdkjones/CodeKit#486]
**Quick, short summary:**
I recently installed Brave browser (brave.com) and would like to easily use it as a preview browser with CodeKit.

I found an explanation of why it may not be appearing as an option: "That list is populated dynamically by looking for bundle IDs of known browsers." @ https://github.com/bdkjones/CodeKit/issues/410#issuecomment-342332680

Brave is a new browser I believe, so maybe it's not a "known browser"?
Is there a way to manually add a browser to the dropdown list?

**Expected results:**
Finding Brave browser as option for preview browsers.

**Actual results:**
Safari, Firefox, Opera only appear.

**Exact steps to reproduce:**
1. Install Brave browser.
2. Launch CodeKit.
3. Click on Preview icon.

**Comment by bdkjones** [comment]
Sure, send me the bundle identifier of the app and I’ll get it in the next update coming next week.

**Comment by macfire** [comment]
From Info.plist:
CFBundleIdentifier:   com.electron.brave

Thanks.

**Comment by bdkjones** [comment]
Is this browser an Electron app? Why would you want to use an Electron-based browser?

**Comment by macfire** [comment]
> Is this browser an Electron app?

I suppose. That bundle identifier came from the plist file I found in the app package contents.

> Why would you want to use an Electron-based browser?

I don't have an opinion; I'm not familiar with Electron.
I'm only interested in the Brave browser as it (purportedly) blocks tracking and ads.

**Comment by macfire** [comment]
Sounds bad.
Thanks for adding bundle ID and recommendation on Ghostery extension.

**Comment by bdkjones** [comment]
Okay, added for 3.7.3, which I'm about to push live.
