### ISSUE TITLE
Auto-detected icon overrides icon set by user upon refresh

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit#487]
**Quick, short summary:**

I add a project to CodeKit, which then identifies one of the "standard" icons and assigns it as the project's icon. I pick another icon to use specifically for the project, but whenever the project is refreshed, CodeKit assigns the auto-detected icon back again.

**Expected results:**
The icon I chose as the project's icon should remain as such, even after a refresh.

**Actual results:**
CodeKit assigns the auto-detected icon as the project icon.

**Exact steps to reproduce:**

1. Download the attached ZIP (below) with a reduced project and unzip.
2. Drag the "project-icon-test" folder onto CodeKit to add it as a new project.
3. Observe that CodeKit assigns the red `assets/apple-touch-icon-precomposed.png` file as the project icon.
4. In CodeKit, navigate to the green `assets/icons/the-one-that-i-want.png` file; right-click and choose **Use As Project Icon** from the context menu.
5. Observe that CodeKit correctly assigns it as the new project icon.
6. Refresh the project by clicking the refresh button in the sidebar.
7. Observe that CodeKit reverts to use the red `assets/apple-touch-icon-precomposed.png` file as the project icon once again :(

**A link to download a simplified project or file that shows the issue:**

[project-icon-test.zip](https://github.com/bdkjones/CodeKit/files/2353749/project-icon-test.zip)

**Your configuration (any details about your system that you think might be relevant)**

* 15" MacBook Pro (Retina, Mid 2012) with macOS High Sierra (10.13.6)
* CodeKit Version 3.6.1 (build 26680)

**Comment by bdkjones** [comment]
Great bug writeup! Wish everyone was this thorough; it made fixing it very easy. This issue is addressed for the 3.8 release.
