### ISSUE TITLE
Sass "decimal precision"

### ISSUE THREAD

**Issue by tbnv** [bdkjones/CodeKit#488]
**Quick, short summary:**
The Sass "decimal precision" option doesn't seem to work.

**Expected results:**
Numbers should be rounded with the precision defined in the option above.

**Actual results:**
Atom (Emmet) evaluates math operations with a 15 digits precision.
After CodeKit's processing, numbers in the final CSS still have a 15 digits precision, whatever the "X digits" defined in the "decimal precision" option.

**Comment by bdkjones** [comment]
Which version of CodeKit are you running? Are you using the Sass or Libsass compiler? Can you post some demo code I can use to test with?

**Comment by tbnv** [comment]
I'm using CodeKit 3.6.1 Build 26680.
And the Libsass compiler because, well, it's recommended in the languages settings. ;)

**Comment by bdkjones** [comment]
Ok. And the code demoing the issue?

**Comment by tbnv** [comment]
[test.zip](https://github.com/bdkjones/CodeKit/files/2393270/test.zip)
