### ISSUE TITLE
Update to CodeKit 3.7 and the UglifyJS comments option

### ISSUE THREAD

**Issue by isg-software** [bdkjones/CodeKit#490]
**Quick, short summary:**
Since upgrading to CodeKit 3.7, the semantics of the UglifyJS's comments option appears to have changed significantly, causing many of my "minified" JavaScript files to increase in size dramatically – until I change the UglifyJS `comments` setting (for every project).

**Expected results:**
Minified JS Output should be about the same size after updating to CodeKit 3.7 as it was before the update.

**Actual results:**
After updating, UglifyJS does not remove my comments any more. Especially JavaScript files containing JSDoc comments now get hardly minified effectively any more.
This can be fixed, however, by switching off the `comments` option of UglifyJS. 

**Exact steps to reproduce:**
I re-opened an existing project with the following setup for JS files:
* Check Syntax with ESLint
* Transpile With: Nothing
* Minify the output
* When this file changes or builds: Process it.

The `comments` option in the CodeKit project's UglifyJS settings is _on_.

If I now change a file by simply adding and removing a space and save it, it gets recompiled. But as a quick view in my version control system (git), I see, the minified output file is now dramatically larger. A diff shows that this is due to all comments being included which had been removed with earlier CodeKit versions.

I compared CodeKit's UglifyJS settings on a computer running CodeKit 3.7 and one running CodeKit 3.6.1: In fact, both versions show in the project's options that `comments` is checked (turned on). But the discription of this option has changed to completely different semantics:

CodeKit 3.7: “Keep all comments. When this is off, add "@license" or "@preserve" to the start of comments that should be kept.”
CodeKit 3.6: “Enable this option to keep JSDoc-like comments that contain "@preserve", "@license" … all other comments will be discarded.”

So de facto the option's semantics have almost inverted, and the best thing to do seems to also invert this flag for every CodeKit JavaScript project.

So this appears to be mainly an UglifyJS issue, but I think, I'd have preferred CodeKit to change this setting/flag after the upgrade automatically. This behaviour hit me by surprise, and the need to edit every project's setting is kind of cumbersome.

**Comment by bdkjones** [comment]
CodeKit 3.7 includes UglifyJS 3.4.9, which is a much newer version of the minifier. You’re correct that its handling of comments has changed so that, by default, jsdoc-style comments with certain keywords are preserved.

That is the default for Uglify and the best default for most users: inline comments will be stripped while copyright and other block comments won’t be.

Sorry for the small migration hassle. As tooling evolves, there’s always a little overhead in tweaking settings. I’m glad you got this sorted though!
