### ISSUE TITLE
Codekit crashes when opening Target Browsers section

### ISSUE THREAD

**Issue by neahan** [bdkjones/CodeKit#492]
**Quick, short summary:**

I can't edit  Autoprefixer options. When I click the link to "Target Browsers"  or when I select "Target Browsers" section directly, CodeKit crashes. 

**Expected results:**

I can open section and  amend settings

**Actual results:**

CodeKit crashes. 

**Exact steps to reproduce:**

See above

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Date/Time:** 2018-09-25 15:27:42.789 +0100
**OS Version:**  Mac OS X 10.11.6 (15G31)
**Model:** iMac17,1, BootROM IM171.0105.B08, 4 processors, Intel Core i5, 3.2 GHz, 16 GB, SMC 2.33f10
**Graphics:** AMD Radeon R9 M390, AMD Radeon R9 M390, PCIe, 2048 MB
**Version:**  CodeKit 3.7 Build 28795

Apple report attached
[apple-report_2018-09-25-15-27.txt](https://github.com/bdkjones/CodeKit/files/2415624/apple-report_2018-09-25-15-27.txt)

**Comment by bdkjones** [comment]
Yea, this is because your OS is three years out of date. I'll push an official release with a fix later today, but for now you can grab https://codekitapp.com/binaries/beta/codekit-test371.zip
