### ISSUE TITLE
Importing css or scss files failed

### ISSUE THREAD

**Issue by wdgBernd** [bdkjones/CodeKit#493]
**Quick, short summary:**
1. Compiling css-files will not work since update to 3.7.
![bildschirmfoto-2018-09-26-um-11 01 18](https://user-images.githubusercontent.com/43602766/46069375-b6fd6c80-c17b-11e8-9292-3a95120ec64b.png)

My import:
  @import "../../bower_components/jQuery.mmenu/dist/jquery.mmenu.all ( without the .css - extension this worked fine since the last update )
If i import the file with the .css - extension, the compiling error dissapears but the css-statements aren´t integrated in the compiled file.

2. even a scss-file will be not imported ( codekit does the compiling without errors, but the imported scss-statements are just as little imported as from the css-file )

**Expected results:**
correct imports of css and scss - files

**Comment by bdkjones** [comment]
The current behavior is correct. Sass changed the way they deal with CSS imports: you’re no longer allowed to write them without an extension.

**Comment by wdgBernd** [comment]
thanks for fast replay, bryan...ok, but when i only use the import statement with extension, the file will be not included in my all-min.css.
In that case i would produce additional requests. and that is one thing that i try to prevent.
it´s also no solution, to change the extension from css in scss because bower_components shouldn´t be changed.
any ideas how to deal with that?!

**Comment by bdkjones** [comment]
Unfortunately, no, I don’t have a suggestion. There’s a big discussion about this happening on the Sass repo and some talk of next-generation imports. In the meantime, my advice would be to make sure the relative path in the import statement is correct and let your server fill the @import on page load. One extra css file makes no appreciable difference in page load speed

**Comment by wdgBernd** [comment]
Ok - thank you!
