### ISSUE TITLE
Cannot read renaming project text after 3.7 upgrade

### ISSUE THREAD

**Issue by Daronspence** [bdkjones/CodeKit#494]
**Quick, short summary:**
Cannot read name of project on macOS 10.13.6 when renaming. Text is white.
**Expected results:**
Text should be legible
**Actual results:**
Text is not legible 
https://cl.ly/b9e2558561c1
**Exact steps to reproduce:**
Have a Mac without dark mode or possible disable dark mode?
**A link to download a simplified project or file that shows the issue:**
See above ☝️ 
**Your configuration (any details about your system that you think might be relevant)**
2015 MB Pro on macOS 10.13.6 and CodeKit version 3.7

**Comment by bdkjones** [comment]
Fixed in 3.7.3. Thanks!
