### ISSUE TITLE
Dark Mode Project Label Text is White (Invisible)

### ISSUE THREAD

**Issue by garrisonhughes** [bdkjones/CodeKit#495]
**Quick, short summary:**
Label text is white on a white background when editing project name when using Dark Mode. 

**Expected results:**
Label text should be black or dark.

**Actual results:**
Label text is invisible.

**Exact steps to reproduce:**
Use Dark Mode, click the project title to open the pop-up of existing projects, click the project title in the list to edit the name of the project.

**A link to download a simplified project or file that shows the issue:**
![screen shot 2018-09-27 at 9 25 50 am](https://user-images.githubusercontent.com/5141118/46149338-16b94d80-c238-11e8-875a-1a15ae0c7f30.png)

**Comment by bdkjones** [comment]
Ah. I see what's going on here. The popup is, as far as macOS is concerned, a separate window. Each window gets its own field editor, which is a textfield that the system swaps into place whenever any field in the window needs to edit. The one for the main window is customized to handle color changes:

<img width="542" alt="screen shot 2018-09-27 at 15 30 41" src="https://user-images.githubusercontent.com/926566/46178131-77617e00-c26a-11e8-97ac-f7d6937c7fbd.png">

So I just need to beat another field editor into submission. Will fix.

**Comment by bdkjones** [comment]
Fixed in 3.7.3
