### ISSUE TITLE
“Unused IDs” Setting on SVGs

### ISSUE THREAD

**Issue by LarryAzevedo** [bdkjones/CodeKit#496]
Under the “Optimize By Cleaning Up” section, if you check on “Unused IDs” it will only remove IDs inside SVG files that are empty strings; not actually remove IDs that are unused.

**Comment by bdkjones** [comment]
Can you post a really simple demo project that shows the issue? Do you get the same results if you run SVGO outside of CodeKit?

**Comment by LarryAzevedo** [comment]
Ok so this doesn't occur on simple SVGs but does occur if the SVG has a <style> tag in it.  For example, this SVG would get it's id attribute removed:
```
<svg id="Layer1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">
    <path>...</path >
```
But this one will not:
```
<svg id="Layer1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">
    <style>...</style>
```

**Comment by bdkjones** [comment]
This sounds like an issue for the SVGO team. CodeKit just runs SVGO. Are you able to reproduce this if you run SVGO from the command line yourself?

**Comment by LarryAzevedo** [comment]
Command line?!?!?  I'm a designer man.  (enough said)  ;-)

**Comment by bdkjones** [comment]
Ha, open the issue on the SVGO repo and see what they say. I doubt that CodeKit is involved in this.

**Comment by LarryAzevedo** [comment]
Ok so you mean here right?  https://github.com/svg/svgo/issues

**Comment by bdkjones** [comment]
Yep.

**Comment by LarryAzevedo** [comment]
Thank you sir and in case you care: https://github.com/svg/svgo/issues/1046
BTW, I can't tell you how much I love CodeKit. Keep up the ~good~ great work.
