### ISSUE TITLE
[bug] Build folder settings are not applied to a new project.

### ISSUE THREAD

**Issue by dwkns** [bdkjones/CodeKit#498]
**Quick, short summary:**
When creating a new project with 'This project uses a build folder' checked. The server defaults to serving from your project root, not the build folder. 

 **Expected results:**
Site should be served from build folder.

**Actual results:**
Site is served from project root.

**Exact steps to reproduce:**

1. Use 'Edit Defaults for New Projects' to ensure that the 'This project uses a build folder' option is checked and Source and Build folders have names.

2. Create a new project with a HTML file in Source folder.

3. Build the project

4. Click the preview/launch browser button

5. The site is served from the project root. 

Note that clicking Project Settings > Build Process > Apply Changes fixes the issue but this shouldn't be required.

**A link to download a simplified project or file that shows the issue:**
[proj.zip](https://github.com/bdkjones/CodeKit/files/2442983/proj.zip)

**Comment by bdkjones** [comment]
Ooh, great catch. I’ll get that fixed soon.

**Comment by dwkns** [comment]
I'm pretty sure (but haven't done enough proper testing) that Project Settings > General > Skipped folders that are added via 'Edit Defaults for New Projects' are not honoured properly either.

**Comment by dwkns** [comment]
Confirmed. 

Skipped folders are included in the build when added via 'Edit Defaults for New Projects'. 

**Quick, short summary:**
When creating a new project with a skipped folder added 'Edit Defaults for New Projects'. The skipped folder status is ignored when building. 

**Expected results:**
Skipped folders should be skipped, not processed.

**Actual results:**
Skipped folders are not skipped and copied to build folder.

**Exact steps to reproduce:**

1. Use 'Edit Defaults for New Projects' to check 'This project uses a build folder' and to add a skipped folder 'node_modules' 

2. Create a new project which includes a 'node_modules' folder and add it to CodeKit

3. Build the project
 
4. The node_modules folder is copied to the build folder. 

**A link to download a simplified project or file that shows the issue:**
[demoProject.zip](https://github.com/bdkjones/CodeKit/files/2446485/demoProject.zip)

**Comment by bdkjones** [comment]
This is incorrect. Skipped folders are simply not indexed in CodeKit’s UI. The node_modules folder should absolutely be copied into /build, or the site will break.

Once you’ve skipped a folder, you can control what happens to it during builds by selecting the Skipped Folder in the files list.

**Comment by dwkns** [comment]
I see. It's not 100% clear in the UI that skipped folders means that they are not indexed, rather than processed. 

Generally you shouldn't copy the node_modules folder. 

In a web project you would end up copying tons of unused / unneeded additional files. Including any development only modules, binaries, source code, readme's etc. It's often better to reference a specific required JS lib from within node_modules and copy that to something like `build/js/libs`. Is not the point of the build folder to be just the files needed for deployment?

Also some node_modules include binaries and these may not work when deployed if you just copy them. It's better to use `npm install` on your target platform to ensure you get the correct binaries. 

Regardless the ability to set certain files & folders as 'Do not process' by default would be very useful especially if you have anything more than a very simple workflow. Something like...? 

![group](https://user-images.githubusercontent.com/5578117/46483066-b6ee1400-c7ee-11e8-9c89-1e87f62efd0b.png)
