### ISSUE TITLE
babel always adding sourcemap to js files.

### ISSUE THREAD

**Issue by felixwerner** [bdkjones/CodeKit#499]
while building babel always adds a `//# sourceMappingURL=script.min.js.map`
 to minified js files without creating a sourcemap.

**Comment by bdkjones** [comment]
If I recall correctly, it’s actually the JS minifier (uglifyjs) that does this. I have filed a bug with Uglify to have it fixed.

**Comment by bdkjones** [comment]
This is an uglifyJS issue. Uglify seems like it hasn't had any updates since August; I may switch to Terser if I can guarantee no breaking changes.
