### ISSUE TITLE
Memory Overload

### ISSUE THREAD

**Issue by bbertucc** [bdkjones/CodeKit#500]
When codekit was left running in the background for a few hours, it over-filled my aloted application memory. Nothing was special with my config other than I had browser-refreshing and SASS compiling on. I was making quite a few changes to SASS in Visual Studio when I got the error notice:
![screen shot 2018-10-09 at 10 52 12 am](https://user-images.githubusercontent.com/46652/46752661-6dd11080-cc83-11e8-8cfc-4526750071b1.png)

**Comment by bdkjones** [comment]
The most likely cause of this is a corrupt data file. Quit the app, then hold the Option key while launching it to clear everything out and start fresh.

**Comment by bbertucc** [comment]
Thanks @bdkjones - that worked.
