### ISSUE TITLE
Languages settings always closed

### ISSUE THREAD

**Issue by tbnv** [bdkjones/CodeKit#503]
Whenever I go to a project's settings, the "Languages" folder is closed. Only this one. Why?
It's the one I go the more often to, so it would save clicks if it could stay open like the others. 🙂

<img width="196" alt="capture" src="https://user-images.githubusercontent.com/1021579/46950352-b4a87700-d084-11e8-97d3-ec1b8656c2b1.png">

**Comment by bdkjones** [comment]
It stays open after the first time you open it, until restart. It’s collapsed by default because most folks only use a couple languages and I don’t want the submenu pushing down the rest of the app’s options.
