### ISSUE TITLE
Ignore already minified JS

### ISSUE THREAD

**Issue by tbnv** [bdkjones/CodeKit#504]
How can I tell CodeKit to ignore `jquery.min.js` for example, or basically any `.min.js` file?

In Languages > Other, I set a rule for `*.min.js` like you see in the screenshot but it doesn't work, CodeKit continues to process these files.

Am I doing something wrong?

<img width="510" alt="capture" src="https://user-images.githubusercontent.com/1021579/46950808-4fee1c00-d086-11e8-98c1-0e07eb10bf64.png">

**Comment by bdkjones** [comment]
This doesn’t work because .js is the extension, not “.min.js”

You should be installing jquery into a node_modules or Bower_components folder and then using it from that location. Those folders are automatically skipped, so processing won’t occur.
