### ISSUE TITLE
Run Autoprefixer not working anymore

### ISSUE THREAD

**Issue by paddle07** [bdkjones/CodeKit#505]
Hi
I have installed the latest Version 3.7.4 and just noticed that the option «Run Autoprefixer on the CSS file» is not working anymore. Could you check. 
Thanks.

**Comment by bdkjones** [comment]
It's working just fine. Folks are surprised at how few prefixes are needed in modern browsers. Adjust your browserslist string to something ridiculous and you'll see more prefixes.
