### ISSUE TITLE
Update libsass

### ISSUE THREAD

**Issue by Timoti** [bdkjones/CodeKit#507]
Any reason why codekit couldn't run 3.5.6?  3.5.4 was released in 2017.

My personal motivation is a hope – fueled somewhat [by this hint](https://github.com/sass/sass/issues/2233), that longstanding issues I've had compiling grid-template repeat variables may be resolved post 3.5.4.

**Comment by bdkjones** [comment]
CodeKit 3.7.4 contains the absolute latest version of Libsass—it’s actually a few commits ahead of the last stable release.

**Comment by bdkjones** [comment]
There is no 3.5.6 release of Libsass. 3.5.4 is the latest: https://github.com/sass/libsass/releases

**Comment by Timoti** [comment]
ah  - ok thanks - i had confused with the main sass project
https://github.com/sass/sass/releases
