### ISSUE TITLE
Can't add a new skipped folder in 'Edit Defaults For New Projects'

### ISSUE THREAD

**Issue by helloDanuk** [bdkjones/CodeKit#508]
**Quick, short summary:**
Trying to add a skipped folder in 'Edit Defaults For New Projects'. I can add a new skipped folder, but after click 'Done' and open 'Edit Defaults For New Projects' again, this new skipped folder is not listed anymore.

It still works in project settings though.

**Expected results:**
Skipped folder should be added to the list. 

**Actual results:**
Only existing skipped folder are listed. 

**Exact steps to reproduce:**
Open 'Edit Defaults For New Projects' and try to add a skipped folder. Click an other setting-tab and change back to 'General'. New skipped folder is not listed anymore.

**Your configuration (any details about your system that you think might be relevant)**
<img width="1160" alt="bildschirmfoto 2018-11-05 um 15 21 55" src="https://user-images.githubusercontent.com/8265902/48004188-ca9fd980-e110-11e8-80b9-4224eaf535bb.png">

**Comment by bdkjones** [comment]
Thanks for the report; I’ll look into this for the next update.

**Comment by bdkjones** [comment]
Okay, this is fixed for the 3.8 release. Thanks!
