### ISSUE TITLE
Placeholder/Instructions missing in the registration tab

### ISSUE THREAD

**Issue by manuelmoreale** [bdkjones/CodeKit#509]
**Quick, short summary:**
The two fields for email and license code inside the registration tab are missing any kind of instruction or placeholder text.

**Expected results:**
Some sort of instruction about what goes inside those two fields

**Actual results:**
This:
![screenshot 2018-11-09 at 10 21 39](https://user-images.githubusercontent.com/1738077/48254747-24ebb380-e40b-11e8-801b-752a01e577c0.jpg)

**Exact steps to reproduce:**
Open a fresh copy of Codekit and check the registration tab

**Your configuration (any details about your system that you think might be relevant)**
10.14.1 with dark color scheme enabled (not sure if that matters or not )

**Comment by bdkjones** [comment]
Thanks! I’ll get that fixed.

**Comment by bdkjones** [comment]
Okay, this is fixed for 3.8. Thanks.
