### ISSUE TITLE
[BUG] JS files still linted when Output set to Ignore

### ISSUE THREAD

**Issue by dwkns** [bdkjones/CodeKit#510]
**Quick, short summary:**
When a JS file's output is set to 'Ignore' editing, then saving that file will still cause it to be Linted by CodeKit

**Expected results:**
Any files who's output is set to 'Ignore' should not be Linted by Codekit. 

**Actual results:**
As summary.

**Exact steps to reproduce:**
1. `$ defaults delete com.incident57.CodeKit3`
2. Launch CodeKit with 'Option' held down -> Perform Safe Start
3. Add project folder containing single file 'main.js' with code... 
````javascript
var first = 'Joe';
var last = 'Blogs';
console.log('Hello'+first+' '+last);
````
4. Set 'main.js' Output > When This File Changes > **Ignore it**
7. Edit main.js 
````javascript
var first = 'Peter';
var last = 'Pan';
 console.log('Hello'+first+' '+last);
````
8. Save main.js

**Log** 
>  ESLint found 1 issue: Unexpected console statement.

**A link to download a simplified project or file that shows the issue:**
[test.zip](https://github.com/bdkjones/CodeKit/files/2565718/test.zip)

**Your configuration (any details about your system that you think might be relevant)**
CodeKit 3.7.4

**Comment by dwkns** [comment]
Thinking about it...
Is this because otherwise there would be no way to check syntax unless you are processing the file to another location?

If so, I would suggest you add a 'Check syntax without processing' option to the 'When this file changes' dropdown.  Or better, not hide the 'Check Syntax With' dropdown when you hide the Transpile / Minification settings.

**Comment by bdkjones** [comment]
Please see the JS documentation on Codekitapp.com. There is a shield checkbox in the Linked Files list that controls this.

**Comment by dwkns** [comment]
@bdkjones I'm confused. It's just a single fine project. There are no linked files so the shield checkbox does not appear. Am I missing something?

**Comment by bdkjones** [comment]
Ah, I see. In that case you want to change the Syntax Checker for that file to “none”. It’s at the top of the options when you select the file and you can set that as the default for all files and then opt-in the ones you want to lint by changing the same option in Project Settings > Languages > Javascript.

**Comment by dwkns** [comment]
Something like this...

![group](https://user-images.githubusercontent.com/5578117/48473966-758b5400-e7f1-11e8-948a-aaa5e43779e9.png)

Where the shield control works for linked files, this would work for individual files. They shouldn't conflict with each other as they are effectively the same setting on a file in different contexts.

**Comment by bdkjones** [comment]
This is a good point. The UI changed to hide Settings for ignored files a while back because I got so many emails from folks insisting the app was broken when they simply forgot that they had set a file to “ignore”. 

I think, conceptually, skipping linting-on-save for ignored files makes sense.

**Comment by bdkjones** [comment]
Very nice to see someone using custom accent colors. Spent all summer on that.
