### ISSUE TITLE
[Feature Request] Ignore added files & folders setting

### ISSUE THREAD

**Issue by dwkns** [bdkjones/CodeKit#511]
Currently when you add any file to CodeKit it tries to figure out what you likely want done with it. In many cases this is fine. 

As we move to ES6 JS and projects have more files/folders which don't need to be processed (they may get imported in future, or be node_modules etc), CodeKit automatically processes them as they are added even if you don't want them to be (you usually create a module before you import it). 

To counter this you have to manually change the settings for each folder or file. This can get annoying during development as your flow gets interrupted. 

This feature would be a project setting which automatically sets any added file or folder to be ignored / not processed by default unless the file settings are manually changed. This would be the opposite of the default behaviour.

**Comment by bdkjones** [comment]
This has been in CodeKit since 2011. You’re looking to set the default Output Action for a language, likely in Defaults For New Projects. See the help page at https://codekitapp.com/help/output-paths/

**Comment by dwkns** [comment]
@bdkjones I understand that you can set the defaults for a particular language but that is *not* what I am suggesting here. 

Currently the premise is that CodeKit processes *all* files of all types by default when a project is added. Then you need to go through your project and select which files you don't want to be processed and set them to ignore. 

For many projects this is fine, but when you are dealing with multiple projects of multiple types (different file import / processing pattens) it's easier to select the files you *do* want to be processed rather than all the files you don't.

I'm suggesting that there be a global project setting which toggles the default behaviour from assuming that you do want any file (of any type) added to be processed, to assuming that you don't want any file added to be processed.

The only way to achieve this at the moment is to go through every filetype in the default settings and set it to ignore. Which again is fine if you *always* want your projects to work this way, but when you are working on projects of different types having to change the setting for each project is a right ball ache.

**Comment by bdkjones** [comment]
If such a setting existed, it would violate the contract established by the existing settings.

If you have “global off” enabled, the only time that would be meaningful is when a project is first added to the app—that’s when files get their initial Output Action. Once the Output Action is set, it stays constant unless you change it.

If you have the Output Action set to “compile” for, say, Sass files but then you flip on the “global off” option and add a new project, your Sass files get set to “ignore” even though the default Output Action for files of that type is “process”. This creates confusion and I will get tons of email about CodeKit being broken because folks forget they enabled the global off.

**Comment by dwkns** [comment]
Yeah OK, I can see that. That sort of conflict would be a problem.

What about a modifier key when you add a project? Holding down 'alt' when you drag and drop a project on the window sets the initial state of all files to ignore?

That would mean users would be taking an intended action every time they wanted this behaviour (no forgetting a global setting), CodeKit's default behaviour would not change (consistency for existing users) and useful additional functionality added for those that need it.
