### ISSUE TITLE
Severe issue with autoprefixer since latest 2 versions, deleting CSS rules

### ISSUE THREAD

**Issue by qantumthemes** [bdkjones/CodeKit#512]
**Summary**
SCSS Autoprefixer should be updated.

**Expected results:**
Expecting autoprefixer to leave vendor specific rules, without need to add `/*! autoprefixer: ignore next */`

**Actual results:**
Autoprefixer is removing many vendor-prefixed css rules, while it wasn't before the last 2 updates.

**Exact steps to reproduce:**
Write this code

```
.qt-ellipsis {
	display: block;
	-webkit-line-clamp: 1;
	-webkit-box-orient: vertical;
}
```

Compile with normal or libsass compiler, you get this:

`.qt-ellipsis {
 display: block;
}`

While instead with prior version you were getting this:

```
.qt-ellipsis {
	display: block;
	-webkit-line-clamp: 1;
	-webkit-box-orient: vertical;
}
```

And to preserve the rules **I have now to add**
`/* autoprefixer: ignore next */`

The guys from Autoprefixer confirmed that they should have fixed this, so a library update should fix it and bring it back to normality.

Please read also:

// https://github.com/postcss/autoprefixer/issues/1014
// FIX: https://github.com/postcss/autoprefixer/issues/776

Actually I would like to revert back to the old Codekit as it was working fine, can I?

**Comment by bdkjones** [comment]
The latest version of Autoprefixer is in 3.8, which should ship early next week.

**Comment by mrjakebaker** [comment]
did the fix for this get pushed out after? I can't see 3.8 anywhere

**Comment by bdkjones** [comment]
Not yet; hopefully tonight. Writing docs and recording screencasts for new features takes time.
