### ISSUE TITLE
Popups not working in codekit app?

### ISSUE THREAD

**Issue by ethorn** [bdkjones/CodeKit#514]
**Quick, short summary:**
When trying to change project icon or access the ESLint documentation the popup is just white, not showing anything. I installed codekit for the first time yesterday.

**Actual results:**

![screen shot 2018-11-19 at 08 42 57 fm](https://user-images.githubusercontent.com/994129/48692743-75b39700-ebd7-11e8-8f08-a077e04ebf0e.png)
![screen shot 2018-11-19 at 08 43 30 fm](https://user-images.githubusercontent.com/994129/48692744-75b39700-ebd7-11e8-9ebe-2adf05a80f42.png)

*Exact steps to reproduce:**
I just click on the buttons as normal.

**Your configuration (any details about your system that you think might be relevant)**
![screen shot 2018-11-19 at 08 46 40 fm](https://user-images.githubusercontent.com/994129/48692806-a8f62600-ebd7-11e8-8652-d917c9a9df23.png)

Thanks,
Eric

**Comment by bdkjones** [comment]
Mmm, I'd be willing to be that's something related to El Cap. Try restarting the app. Do you have any accessibility features enabled and do you see any error messages in Console.app?

**Comment by ethorn** [comment]
No accessibility features. I do see errors in console.app:
***
2018-11-19 18:34:40,850 CodeKit[54179]: com.apple.message.domain: com.apple.automation.scripting_dictionary_loaded
com.apple.message.signature: com.incident57.CodeKit3
com.apple.message.summarize: YES
SenderMachUUID: 1B458E15-4E3B-3F99-ADB5-31102797B442
***
There are other errors as well, but not directly related to codekit. Do you want these as well?

**Comment by bdkjones** [comment]
Those aren't errors; they're just informational messages. I haven't had any other reports of this from anyone on 10.11 (or any other version of macOS). Do you have a different Mac you can test on?

**Comment by bdkjones** [comment]
Ok, I did some more investigating here and found a race condition. It should be resolved for the 3.9 release, which is coming in the next couple days.
