### ISSUE TITLE
[Feature Request] Applescript 'preview in browser' extra 'wait' functionality 

### ISSUE THREAD

**Issue by rlb222** [bdkjones/CodeKit#515]
**Quick, short summary:**
 in my Applescript it is inconvenient that the preview window is starting without being ready for it. It would be very nice if `preview in browser` would wait a bit until the codekit internal server is ready for it.

Sidenote: I'm very happy Codekit support Applescript, so thanks!

**Description**
I created an Applescript for my workflow to open a project with starting MAMP (not pro) with the right settings, Codekit and an editor (vsCode) with the right project.

In the last steps I call upon Codekit to show the preview (in a browser) of the site. This is dependent on Mamp  and Codekits internal server having started.

I have added `delay`s in the applescript. But sometimes even these delays are not long enough. And worse: sometimes they are too long and im waiting for nothing.

**Expected results:**
I expected Codekit to wait for itself to be ready to show the preview in the browser before attempting to actually starting the preview.  

**Actual results:**
Codekit is starting the preview regardless of the internal server being ready. If it's not ready Codekit will show a popup to tell 
'Im not ready yet for my own action of starting the preview'  : )
This popup is also inconvenient in this workflow. 

**Exact steps to reproduce:**
I have the Applescript for you if you are interested.

**Feature Requests**
In order of meaningfulness.

_No delay_
Some kind of way that I don't need to issue a 'delay' before issuing the 'preview in browser' command. e.g. 
`tell application "CodeKit" to preview in browser when internal server is ready for it`

_I am ready now_
Or some kind of way to check whether I can give the 'preview in browser' command yet. e.g.
` tell application "CodeKit" to set myVar to check if internal server has started `

_Please no popup_
Or an extra switch to not show a popup if previewing is not possible, e.g. 
`tell application "CodeKit" to preview in browser Firefox without showing popup`

**Comment by rlb222** [comment]
If the AppleScript must have the same behaviour as the gui, then I agree with you.

In the gui you can see a green ‘light’ when the server is up. in an AppleScripts you cannot. The extra query for readiness would have that check the green light function. 

As far as the gui/ux is concerned, the pop up that is showing up is a bit annoying there as well. 
You have to get rid of it and push it again. Hopefully you have realised (as the user) to wait for the green light to come on. 

Maybe you could add  some retry in to the pop up as well. For the ux?
“Trying to start the preview, but the server is not ready yet. I will retry when it’s started”.
Button: [stop retrying]

Just a suggestion. 
Thanks for the quick response!

**Comment by bdkjones** [comment]
Okay, this is implemented for 3.8. It looks like this:

    tell application "CodeKit" to get preview server status

This returns an Integer:

    1 - Server running normally
    0 - Server not running
    2 - Server is starting up
    3 - Server is updating addresses
    -1 - An error occurred 

So all you need to do is have your script call this API once a second until the value returned is `1`. Though I recommend having an escape clause that, say, after 20 seconds or when the return value is negative, aborts the attempt. Otherwise, you could get an infinite loop.

This should be released soon. Tidying some things up. Also, minor trivia: the class that handles this script command is the absolutely very first piece of CodeKit written in Swift.

**Comment by rlb222** [comment]
That is great!
Super, thank you!

René 

Verstuurd vanaf mijn iPhone
