### ISSUE TITLE
Problem with import in JS

### ISSUE THREAD

**Issue by saulsolorzano** [bdkjones/CodeKit#517]
**Quick, short summary:** Hi, I'm using in JavaScript "Check syntax with: USLint" and in "Transpile With: Babel". In my main.js file I have `import anime from 'animejs';` 

**Expected results:** The animejs is loaded correctly

**Actual results:** I get this `Uncaught ReferenceError: require is not defined at main.min.js:1`

**Exact steps to reproduce:** Configure codekit like i said before

**Your configuration (any details about your system that you think might be relevant)** Version 3.7.4 Build 28905.

Thanks

**Comment by bdkjones** [comment]
You need the beta build that contains JS bundling. Download it from codekitapp.com/binaries/beta/bundle4.js

See the other issue about JS bundling for details.

**Comment by saulsolorzano** [comment]
Awesome! Thanks

**Comment by bdkjones** [comment]
The latest beta build should be good-to-go on bundling: codekitapp.com/binaries/beta/bundle7.zip

Will likely become the release version of 3.8 in a few days.

**Comment by Kevinlearynet** [comment]
Still seeing this sporadically in version 3.13.3 - Build 33081 with the following JavaScript compile settings:

- ESLint
- Babel
- IIFE
