### ISSUE TITLE
[Feature request] Make OS notifications for CodeKit clickable and let them open the log

### ISSUE THREAD

**Issue by robdekort** [bdkjones/CodeKit#519]
I find myself clicking the notifications whenever an error occurs and expecting the log to open to see the errors I'm producing. I think it would improve the UX.

**Comment by bdkjones** [comment]
Agreed. Implemented for 3.9, which should ship this weekend.

**Comment by robdekort** [comment]
Nice. Can’t wait for the new release 

Verstuurd vanaf mijn iPhone
