### ISSUE TITLE
Can't Register CodeKit with Ease due to dark mode

### ISSUE THREAD

**Issue by anthony0030** [bdkjones/CodeKit#523]
**Quick, short summary:** Can't Determine what fields are required in the registration

**Expected results:**
![screen shot 2019-01-09 at 12 27 28](https://user-images.githubusercontent.com/13033263/50893621-f473c600-1409-11e9-87ca-46209269de3e.png)

**Actual results:**
![screen shot 2019-01-09 at 12 22 32](https://user-images.githubusercontent.com/13033263/50893571-d73ef780-1409-11e9-987c-3a4b3478755f.png)

**Exact steps to reproduce:**
1) Enable Dark Mode on OSX Mojave (10.14.1)
2) Try to register Codekit (3.7.4 Build 28905)

**Comment by bdkjones** [comment]
This has been fixed for the next update. Thanks!
