### ISSUE TITLE
[Feature request] Get the path of a project

### ISSUE THREAD

**Issue by tiptronic** [bdkjones/CodeKit#524]
Let me get the path of a project programmatically

**Comment by bdkjones** [comment]
This exists for Hooks. Do you mean the AppleScript API?

**Comment by tiptronic** [comment]
I didn’t know about the hooks…. sorry.

I meant in the AppleScript API and (in first place) somewhere in the project settings window 😉 

btw. after the update to the latest version, my project didn't build any more and complains about 'const' keywords.
It turns out, that Uglifyjs is the culprit.
Is there any way to replace Uglifyjs with uglify-es or something similar?

I can't transpile, because this gives more troubles than anything else, but I still like to minify the output.

Ideas?

Cheers

Andy





> Am 17.01.2019 um 18:15 schrieb Bryan Jones <notifications@github.com>:
> 
> This exists for Hooks. Do you mean the AppleScript API?
> 
> Sent from my iPhone
>

**Comment by bdkjones** [comment]
Okay, this has been implemented for the next update. You use it like this:

    tell application "CodeKit" to get path of active project
