### ISSUE TITLE
[Enhancement] When choosing output filename make existing files clickable

### ISSUE THREAD

**Issue by robdekort** [bdkjones/CodeKit#525]
It's just a little annoyance. When choosing an output file in Codekit I can't click existing files. That would save me from having to type the filename I want the output file to have. 

Other MacOS save dialogs work this way so I'm always disappointed that this one doesn't.

<img width="911" alt="screenshot 2019-01-18 at 11 40 02" src="https://user-images.githubusercontent.com/4067523/51382195-6f2d9700-1b16-11e9-908b-6127b95336df.png">

**Comment by bdkjones** [comment]
Ok, this is implemented for 3.9. 

Files are selectable only when you launched the panel with a single file selected in CodeKit. (It doesn't make sense to allow file selection when multiple things are selected; they can't all have the same output path.)

If you select a file, the field automatically changes to show you the new name. If you subsequently select a directory, the field changes back to the current output filename (to guard against folks who will accidentally click a file and then choose a folder, but not realize the output filename changed automatically.)

**Comment by robdekort** [comment]
👌

Verstuurd vanaf mijn iPhone
