### ISSUE TITLE
LESS Compilation of UIKit with CodeKit Fails

### ISSUE THREAD

**Issue by luxlogica** [bdkjones/CodeKit#526]
**Quick, short summary:**
Ttrying to do a custom build of [UIKit](https://getuikit.com) - the LESS version - simply by including the _uikit.less_ file into a custom _test.less_ file. The _test.less_ file has nothing except the `@include` directive. The build fails, with several errors like this:

```
Less compiling failed with this error: 
Skipped data-uri embedding of ../../images/backgrounds/list-bullet.svg because file not found
```
It seems that the compiler is trying to resolve relative paths in relation to the _test.less_ file, rather than in relation to the file where the path was originally declared/used.

**Expected results:**
UIKit should compile without any warnings or errors.

**Actual results:**
CodeKit errors out as it cannot seem to resolve the relative paths.

**Exact steps to reproduce:**
1. Start a new project with CodeKit
2. Clone UIKit from [their Github repo](https://github.com/uikit/uikit)
3. create a _test.less_ file, with just one line - the `@import uikit.less` directive
4. save the file

---

I've also cross-reported this issue in the [UIKit repository](https://github.com/uikit/uikit/issues/3730), as I'm not certain whether this should be solved here or there - apologies for the cross-posting.

**Comment by bdkjones** [comment]
Pretty sure Less has an option to control how relative paths are resolved. Have you tried that?

**Comment by luxlogica** [comment]
Just had a look at the docs, and I can see two options: 

- if using _less.js_ in the browser, we can define a `relativeUrls` property inside a script tag, before loading _less.js_, and it will work. Only useful if you're using .less files directly in the browser, rather than pre-compiling them with CodeKit.
- if using `lessc` on the command-line to precompile, we can pass a`--rewrite-urls` parameter - the default is `--rewrite-urls=off` (which is probably what CodeKit is doing), and what we really want is `--rewrite-urls=local`.

This info is from [this doc page]. I might have missed something, but I cannot see a way to actually change the setting in the .less file itself...

**Comment by bdkjones** [comment]
Yea, the rewrite URLs option is available in CodeKit. Select your file, turn it on.

**Comment by luxlogica** [comment]
**OMG, how could I miss that????** - *hangs head in shame...*

That's what happens when you program at 1:00am, I guess... 🙄
