### ISSUE TITLE
Coverage statistics not working

### ISSUE THREAD

**Issue by xaddict** [bdkjones/CodeKit#528]
**Quick, short summary:**
The coverage statistics (only the percentages) aren't working in any of my projects

**Expected results:**
Coverage percentages follow calculated browser support

**Actual results:**
Supported browsers show, but there are no global or local statistics

**Exact steps to reproduce:**
Set browser string to anything, for example:
">0.2%, last 2 versions, Firefox ESR, not dead"
Check under platforms if browsers are showing

**Your configuration (any details about your system that you think might be relevant)**
macOS Mojave 10.14.2 (18C54)
MacBook Pro 15 inch 2017

Codekit 3.7.4 - Build 28905

Dark Mode on

System Language:
English English - Primary
Nederlands Dutch (Netherlands)

![screenshot 2019-01-29 at 12 14 49](https://user-images.githubusercontent.com/3295364/52409794-d1a30300-2ad6-11e9-9a6e-e74dbb35434c.png)

**Comment by bdkjones** [comment]
This should have been fixed in 3.8.2. Is the issue still manifesting in that version? If so, what language and region is your Mac set to use?

**Comment by xaddict** [comment]
It's fixed now
