### ISSUE TITLE
Crash with a bower components [3.8.1]

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#533]
**Quick, short summary:**
The application crash after adding a particular bower components.

**Expected results:**
Avoid wasting time ...

**Exact steps to reproduce:**
Blank installation of Codekit (preferences, etc ...).
Adding a folder.
Search in the bower components "[Unsemantic](https://github.com/nathansmith/unsemantic)"
The install.
See the application crash.

**A link to download a simplified project or file that shows the issue:**
https://wetransfer.com/downloads/24941512d4af8821435abf84f5a6914720190228152554/a345e908e351e4c59982b18a00b8dfb120190228152554/968b3b

**Your configuration that you think might be relevant**
OS High Sierra 10.13.6

**Comment by bdkjones** [comment]
Ah, I see exactly what's happening here. Certain Bower component authors are abusing the `main` field of `bower.json`. That is supposed to provide a single entry point, but some component authors are passing an array of entry points. I'll update CodeKit to robustly handle malformations like that.

**Comment by bdkjones** [comment]
Okay, 3.8.2 is now live with a fix for this issue. Thanks for the report; sorry for the incompetence.

**Comment by rvola** [comment]
no problem !
The error is part of the dev.
thank you for your work
