### ISSUE TITLE
Browser refreshing over TLS has stopped working in Codekit 3.8.2 using Local by Flywheel

### ISSUE THREAD

**Issue by gTaylorRokk** [bdkjones/CodeKit#534]
Upgraded to 3.8.2 and browser refreshing seems to have stopped functioning when using TLS setting and any server preview urls. I'm using Local by Flywheel (version 3.0.4) for the local development server with SSL on. Browser refreshing was working OK prior to 3.8.2 release.

I Rolled back to previous 3.7.4 version to check if this was an issue with Local, but using browser refreshing over TLS with same local settings it works OK, so appears to be something related to the latest Codekit release.

In 3.8.2 I'm just getting a error timed out message when using any of the preview server urls and I've tried various projects I have using Local to ensure it isn't isolated to an individual project.

**Comment by bdkjones** [comment]
3.8.2 has no changes to any of the browser refreshing or preview server code. I do know that Local has been troublesome for folks in the past. Please test with Mamp instead and let me know how that goes. Despite a less-than-stellar-UI, Mamp always seems to have rock solid configurations.

**Comment by gTaylorRokk** [comment]
@bdkjones OK thanks for confirming. I've got MAMP installed so will upgrade again and test. I've mainly switched to Local for the cleaner UI and easier SSL setup but I can switch between the two if necessary.

**Comment by gTaylorRokk** [comment]
@bdkjones I've re-installed 3.8.2 and my original problem seems to be a certificate issue. For some reason when enabling TLS the codekit certificate was not created. I checked keychain access and there was no certificate installed. So followed the manual install instructions and now everything appears to be working just fine with Local and TLS preview urls. Hopefully this might help some other folks if they encounter the same issue.
