### ISSUE TITLE
Transpiling with Babel always minifies output

### ISSUE THREAD

**Issue by elliotcondon** [bdkjones/CodeKit#537]
When processing a JS file that uses the Babel transpiler, the output is always minified, even if the "Minify the output" setting is left unchecked.

I'm confident that in previous versions, the output did honor this setting and could produce an unminified output.

**Expected results:**
The processed file should reflect the "Minify the output" setting and not be minified.

**Actual results:**
The processed file is always minified.

**Exact steps to reproduce:**
1. Create a JS file.
2. Enable processing for this file in Codekit.
3. Select Babel as the transpile setting for this file.
4. Leave the "Minify the output" setting unchecked.
5. Process the file.
6. View the processed file.

Thanks
Elliot

**Comment by bdkjones** [comment]
Are you importing any files into the JS file? Someone else reported this, but I looked into it and the end result is that they were importing an already-minified file.

**Comment by elliotcondon** [comment]
Hi @bdkjones 

Thanks for the quick reply!

Interesting. The file in question is being used as an "empty container" to import other files.
That said, the other files are not being processed, and are not already minified.

Here is an example of the file structure:
/js
- _functions.js
- _components.js
- _etc.js
- theme.js

Where `theme.js` is the file being processed. Its contents looks like this:
```
// @codekit-prepend "_functions.js";
// @codekit-prepend "_components.js";
// @codekit-prepend "_etc.js";
```

Hope this helps.

**Comment by bdkjones** [comment]
Can you email me a link to download this project so I can take a look?

**Comment by bdkjones** [comment]
I just need the JS, as it's structured in the project. I don't need the whole website.

**Comment by elliotcondon** [comment]
Sure thing. I'll put together a fresh minimal project to replicate the issue and send it your way. Most likely tomorrow.

**Comment by rvola** [comment]
I have a similar problem.
In my project I have empty js files and I use Codekit to compile everything into one.

I noticed that with the new import write "./XXXX"
my file is not the same with // @ codekit-preprend

For example with a jQuery file I get "undefined" on all variables

**Comment by elliotcondon** [comment]
@rvola Your issue sounds a bit different to mine. Maybe you should open a new ticket with a more descriptive explanation?

**Comment by elliotcondon** [comment]
@bdkjones 

I've just put together a basic demo to replicate the issue.
Please find attached a .zip containing the following:
```
-compiled.js // The compiled output.
/build
    - _child.js // The actual JS functionality.
    - parent.js // The container that is processed.
config.codekit3 // The Codekit config.
```

Processing the "parent.js" file will always generate a minified "compiled.js" when using the Babel transpiler. You can toggle the "Minify the output" setting, but this won't have any effect.

Removing the Babel transpiler setting allows the "Minify the output" setting to work again, so perhaps this narrows down the problem?

Thanks for looking into this. I hope you are able to find the problem.

**Comment by bdkjones** [comment]
There does not appear to be an attachment.

**Comment by elliotcondon** [comment]
[Archive.zip](https://github.com/bdkjones/CodeKit/files/2959091/Archive.zip)

**Comment by bdkjones** [comment]
It appears there may be a problem with the minify checkbox in the right-hand file inspector. Try this: go to Project Settings > Languages > Javascript and uncheck the minify box there. Reprocess the file. Result?

**Comment by elliotcondon** [comment]
Just tried it but didn't fix the issue. Compiled output is always minified. 
I also tried toggling all the other "default javascript settings" without success.

**Comment by elliotcondon** [comment]
Using the latest CodeKit v3.8.2.

**Comment by elliotcondon** [comment]
@bdkjones Just checking up on this issue. Were you able to find a solution for this?

**Comment by bdkjones** [comment]
I'm looking into it still.

**Comment by elliotcondon** [comment]
Thanks @bdkjones

**Comment by mrkos67** [comment]
bump. 

I'm having the same problem.

**Comment by bdkjones** [comment]
Ok, I've got this fixed for the next release, which should be this weekend hopefully.

**Comment by elliotcondon** [comment]
Legendary. Thanks mate, looking forward to it.
