### ISSUE TITLE
How to import non-ES6 modules

### ISSUE THREAD

**Issue by Buddierdl** [bdkjones/CodeKit#540]
I see that CodeKit now supports ES6 Modules, but the docs say that you should no longer use @codekit-prepend/append for new projects. So what is the proper way now to bundle JS libraries that don't support ES6 modules (the one I'm looking at now is UMD)?

Thanks!

**Comment by bdkjones** [comment]
Use the legacy statements. They won't be removed from the app at any point, so they'll always work.
