### ISSUE TITLE
Image optimization settings 

### ISSUE THREAD

**Issue by BenjaminHoegh** [bdkjones/CodeKit#542]
I was just looking at what metadata CodeKit remove when using the optimization for images and I notes that it remove copyright data as well.

Will it be possible to make a setting for this so you can optimize a image without removing copyright information? e.g keep Artist/Auther and copyright notes

if yes remember there are EXIF, IPTC, XMP metadata types there all contain there own version of copyright data

**Comment by bdkjones** [comment]
I agree that this would be useful, but there is currently no way to do it because I don't have that level of granular control over the optimizers that CodeKit runs. Several of them are an all-or-nothing thing when it comes to removing metadata.
