### ISSUE TITLE
Unusual loading times

### ISSUE THREAD

**Issue by fietstouring** [bdkjones/CodeKit#544]
**Quick, short summary:**
After updating my CMS (based on PHP) I experience unusual long loading times when viewing websites via CodeKits preview server. I am looking for tipps or hints what could be the reason.
**Expected results:**
I doubled checked and duplicated my current project using the previous version of my CMS. Everything loads as expected with that. 
**Actual results:**
DevTool shows 4 seconds or longer TTFB (Time to First Byte). 
All three preview server URLs work, but same result. I get occasional orange messages "Unstable connection". **Crazy thing is: when I uncheck the project in CodeKit but keep it active, preview server loads perfectly well!**

**Your configuration (any details about your system that you think might be relevant)**
MAMP Pro, OSX 10.13.6

**Comment by fietstouring** [comment]
I just realized that CPU usage of CodeKit goes way up even to over 90% when browsing the site, whereas with the older CMS-version it is not going up over 5%...

**Comment by fietstouring** [comment]
quick solution was to remove the whole project from CodeKit and just re-add the folder that contains CSS and JS – leaving all the CMS files out.

**Comment by bdkjones** [comment]
The usual cause of this is CMS’s that write files to disk on page load (usually log files). That creates an infinite loop where CodeKit detects a file-change event, reloads the page, which triggers a new file written to disk, and so on. The solution is to add the folder where files are created to the Skipped Items list in Project Settings. This is likely why adding just the JS/css folders has solved the issue for you.

**Comment by fietstouring** [comment]
yeah, but actually I skipped all the folders except JS/CSS, it did not do the trick...
