### ISSUE TITLE
Typo in Settings/Languages text for Markdown

### ISSUE THREAD

**Issue by luxuryluke** [bdkjones/CodeKit#546]
When editing the settings for a site, and you click on **Languages** -> **Markdown**, the _Information_ text reads "CodeKit uses MulitMarkdown…" instead of **MultiMarkdown**.

It's a small error, but in the effort to have perfect documentation, I figured this would be a good fix to have.
Cheers!

**Comment by bdkjones** [comment]
Thanks! Fixed for the next update.
