### ISSUE TITLE
JS files not being processed unless "Minify the output" is checked

### ISSUE THREAD

**Issue by noraheuer** [bdkjones/CodeKit#548]
This has been haunting me for several days now seriously impeding my development process. At first I thought it might bean issue with my TextEditor, but this happens even if CodeKit is the only program running. Is there any way to trace CodeKit processing to see what is going on?

JS file is processed when "Minify the output" is checked. 
JS file is NOT processed when unchecked.
No errors reported by CodeKit.

![Screen Shot 2019-07-20 at 12 03 52 PM](https://user-images.githubusercontent.com/6789426/61581003-7abe4280-aae6-11e9-9925-898ba995f16b.png)

Complete Test Project :
[test.zip](https://github.com/bdkjones/CodeKit/files/3413776/test.zip)

CodeKit v. 3.8.2 Build 29156
MacOS High Sierra v. 10.13.6 (17G7024)

**Comment by bdkjones** [comment]
Hi Nora,

This bug is fixed for the next release. I’m working to get that out this weekend.

**Comment by noraheuer** [comment]
Thanks Brian, I was beginning to doubt my sanity :))
