### ISSUE TITLE
Typescript compiling failed with error TS6053

### ISSUE THREAD

**Issue by realfish** [bdkjones/CodeKit#550]
Updated to v3.9.1, when compiling Typescript files, CodeKit console reports:

```
Compiling failed with this error: error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
error TS6053: File '/Applications/CodeKit.app/Contents/Resources/engines/node_modules/typescript/lib/lib.d.ts' not found.
```

![codekit-v3 9 1-error-ts6053](https://user-images.githubusercontent.com/3247876/61873901-9c219300-af19-11e9-924a-65cf7159a5a3.png)

**Comment by bdkjones** [comment]
Thanks for the report! I've found the issue and will have a fix out this afternoon.

In the meantime, you can solve this yourself by selecting CodeKit in the Applications folder, control-clicking, and choosing "Show Package Contents". Look for the resources/engines/node_modules folder. Switch to that folder in the Terminal and run `npm install Typescript --production --no-optional`. 

Do all of that with CodeKit not running.

**Comment by bdkjones** [comment]
Okay, 3.9.2 is now live to fix this. SOME GODDAMN DAY I'm going to release an update that doesn't break something in node_modules.
