### ISSUE TITLE
Importing packages prevents bundling/transpilation

### ISSUE THREAD

**Issue by modermo** [bdkjones/CodeKit#554]
**Quick, short summary:**
Importing packages prevents transpilation

**Expected results:**
Importing a package such as `vue-carousel` like so:

```Import VueCarousel from 'vue-carousel';```

Should import successfully. 

**Actual results:**

I get this in my error logs:

```Bundling/transpiling failed with this error: 'default' is not exported by ../node_modules/vue-carousel/dist/vue-carousel.min.js```

**Exact steps to reproduce:**

Install a package via the UI, and then saving the module you're importing the package into. Other packages give the same result, such as:

```Bundling/transpiling failed with this error: 'default' is not exported by ../node_modules/underscore/underscore.js```

**Your configuration (any details about your system that you think might be relevant)**

Standard configuration. Happy to provide extra details if necessary.

**Comment by bdkjones** [comment]
That's because you shouldn't be transpiling installed packages; most of the time you'll be using a component that's already *been* transpiled when the package was built and published. Open Project Settings > Tools > Babel and show me the entries in the "Excluded Items" field. That field should read:

    /\/node_modules\//, /\/core-js\//, /\/bower_components\//

**Comment by modermo** [comment]
Thanks. I've got:

```'node_modules/**', 'bower_components/**', /\/core-js\//```

**Comment by bdkjones** [comment]
replace that with the content I listed above.

**Comment by modermo** [comment]
That works. Thanks!
