### ISSUE TITLE
Feature Request: Work with (css) files that have query string

### ISSUE THREAD

**Issue by pnutster** [bdkjones/CodeKit#557]
We work with a CMS system that while in development mode compiles scss files to css files that include a query string. i.e. custom_29.css?5d557e98

I have tried to find a workaround in Codekit to work remotely on this by using the external server options:

![image](https://user-images.githubusercontent.com/4218393/63114062-41081c80-bf6a-11e9-831b-4a2311e25365.png)

My workflow is that I then set up the directories on my local system using Codekit, but no matter if I use:

custom_29.scss?5d557e98 or
custom_29.scss

I cannot get Codekit to work nicely with the query stringed files - I cannot really determine wether the options are availabe... therefor the "Feature Request".

P.S. Once I set our system to "Live Mode" - we can use a configuration that makes query string disappears from css files and Codekit works fine. However, "Live Mode" has other undesireble consequences furing development - we are really looking for a solution that allows keeping the site in "Development Mode".

**Comment by bdkjones** [comment]
Yea, so the real solution here is to turn off the cache-busting in the CMS. CodeKit handles that anyway, and you can always just disable caching in your browser while developing.

If the CMS is actually **naming files** with a query parameter in them, you should find the author of that CMS and hit them. Cache-busting query parameters are applied to the URI in the <link> tag where the sheet is imported to the page.

**Comment by pnutster** [comment]
Yeah, the CMS (or better the template used) renames the file / adds the template. And is done with an if/else statement... I hardcoded some parts to allow for a better setup and have the query parameters removed. 

Thanks for the response! Appreciate it.

P.S. on another topic - as a matter of fact complete off-topic - I am an avid Espresso app user. Due to unforeseen circumstances the current owner has it "up for sale" - [https://twitter.com/espressoapp](url) - I saw a mention from someone that wrote, maybe Codekit could look into implementing some of Espresso App "live preview" features. [https://help.espressoapp.com/previewing/overrides.html](url)

Perhaps worth to have a look into this?

**Comment by bdkjones** [comment]
Glad you got it sorted. Renaming files to bust caches is just lazy and abusive; that’s bad practice so getting rid of it is a good call.

As for Espresso: the trouble with live-preview is that it works great for simple demos. But as web projects become more complex and require bundling 765 Javascript files, compiling on every edit no longer works well.

I’m aware that Espresso went down a while back, but I assumed somebody would have taken it over by now. I’m not willing to spend much money to acquire an ancient, legacy codebase (Espresso has been around for a long time), but if you like, reach out to MacRabbit and tell them to get in touch.
