### ISSUE TITLE
Codekit removing variables upon compliation

### ISSUE THREAD

**Issue by modermo** [bdkjones/CodeKit#558]
**Quick, short summary:**
It seems that Codekit is removing variables when compiling ES6 modules.

**Expected results:**

I expect the following function to include the `pageTitle` parameter in the function `attachListenersToPhoneMapEmailTriggers` 

```
export const setupEventListeners = pageTitle => {
  return attachListenersToPhoneMapEmailTriggers(pageTitle);
}
```

**Actual results:**
Codekit is removing the variable, such that it compiles like the following:

```
export const setupEventListeners = pageTitle => {
  return attachListenersToPhoneMapEmailTriggers();
}
```

**Exact steps to reproduce:**
Compile a JS module and observe output. 

**Your configuration (any details about your system that you think might be relevant)**
I've pretty much got Codekit JS defaults applied on this project. Terser, Babel, ESLint etc. ESLint is giving me the 'no-unused-vars' errors, which is odd, because I'm clearly using the variable in the inner function.

**Comment by modermo** [comment]
Something is definitely up, because this:
```
export const setupEventListeners = () => {
  function hello (sum) {
    return sum + 3
  }

  const boom = hello(4)

  return attachListenersToPhoneMapEmailTriggers(boom);
}
```
becomes: 
```
var setupEventListeners = function setupEventListeners() {
    return attachListenersToPhoneMapEmailTriggers();
 };
```

I'd be happy to share a config file if necessary, but this is the first time it has happened in the history of the project and I haven't changed any settings.

**Comment by bdkjones** [comment]
I’d need a demo project showing the issue so I can look at it over here. Are you running CodeKit 3.9.2?

**Comment by modermo** [comment]
I am running 3.9.2

I've had play around, and I'm able to replicate it the issue. Run the following with these options:

Transpile With: 'Babel'
Javascript:  'Minifiy output with Terser: Unchecked
ES6 Bundle Format: IIFE

Run the below and watch how this:

```
export const hello = (pageTitle) => {
  return attachListenersToPhoneMapEmailTriggers(pageTitle);
}

const attachListenersToPhoneMapEmailTriggers = (pageTitle) => {
  return document
    .querySelectorAll('[data-ga-event-listener]')
    .forEach(clickElement => {
      return clickElement.addEventListener('click', (event, pageTitle) => sendPhoneMapEmailClicksToGA(event, pageTitle))
    })
}
```

...becomes this:

```
var index_min = (function (exports) {
  'use strict';

  var hello = function hello(pageTitle) {
    return attachListenersToPhoneMapEmailTriggers(); // pageTitle disappears
  };

  var attachListenersToPhoneMapEmailTriggers = function attachListenersToPhoneMapEmailTriggers(pageTitle) {
    return document.querySelectorAll('[data-ga-event-listener]').forEach(function (clickElement) {
      return clickElement.addEventListener('click', function (event, pageTitle) {
        return sendPhoneMapEmailClicksToGA(event, pageTitle);
      });
    });
  };

  exports.hello = hello;

  return exports;

}({}));
```

**Comment by modermo** [comment]
Actually, here's an even simpler version that still causes the issue:
```
const bam = (pageTitle) => {
  return 'boom'
}

export const hello = pageTitle => {
  return bam(pageTitle);
}
```

Try commenting out `const bam` and watch how `pageTitle` reappears in the compiled output.

**Comment by bdkjones** [comment]
The source code examples aren’t sufficient. I need an actual project to download, with the codekit.config file so I can make sure I’m comparing with the same settings you’re using.

**Comment by modermo** [comment]
Just shot you an email.

**Comment by modermo** [comment]
I have filed an [issue ](https://github.com/rollup/rollup/issues/3086)at rollup

**Comment by lukastaegert** [comment]
It is not a bug but a feature. Rollup is removing unused parameters that do not have side-effects themselves. Why is this causing issues? The generated code is equivalent to the source code in what is does.

**Comment by modermo** [comment]
I see how this is working. Confirmed, not a bug. You can close this if you want, @bdkjones
