### ISSUE TITLE
Is it possible to bundle ES6 imports into a vendors-bundle.js?

### ISSUE THREAD

**Issue by katerlouis** [bdkjones/CodeKit#562]
I'm in my `main.js` and do `import Swiper from "swiper"`. Cool. Now I do this with `gsap`, `jquery`, a few `lodash` functions etc.

Now I don't want these scripts to bloat my main.js; for better caching I'd like to bundle these scripts in `vendors-bundle.js`. Is that possible right now? 

I've seen a setup like this done with webpack

**Comment by bdkjones** [comment]
**Assuming you're using CodeKit 3.10.2**:

Your best bet to ensure fast page-loads is to use a CDN to load really common libraries such as jQuery and lodash. You do that with a separate `<script>` tag in the `<head>` element of your page. Google hosts copies of both libraries, I believe.

Then, in `main.js`, you still write: `import $ from jquery`, but you go into Project Settings > Tools > Rollup and you add an "external" entry that binds `jquery` to `$`. When you process `main.js`, Rollup will no longer include jQuery in the bundle. Instead, it will leave it as an external dependency. Just make sure jQuery is loaded before your `main.js` file and you'll be all set.
