### ISSUE TITLE
Dark mode buggy

### ISSUE THREAD

**Issue by brandonmcconnell** [bdkjones/CodeKit#564]
Some "light mode" elements appear unchanged in dark mode and cause the UI to look buggy.

https://i.imgur.com/wLlDY0r.png

e.g. the scroll bar, and right sidebar titles

**Comment by bdkjones** [comment]
Which version of macOS are you on?

**Comment by bdkjones** [comment]
If you’re on <10.14, I can’t do anything about the scrollbars. You have them set to “always show” in system preferences and those are drawn by the system framework; I can’t override that. The labels aren’t showing that way for me on 10.13 or 10.14.
