### ISSUE TITLE
ES7 with Babel?

### ISSUE THREAD

**Issue by indikatordesign** [bdkjones/CodeKit#565]
**It seems that Codekit isn't ES7 compatible with Babel.**

**When do you want to add support for it?**

**Comment by bdkjones** [comment]
I’m not sure what you mean. What are you trying to accomplish?

**Comment by indikatordesign** [comment]
With ES6 you need to declare properties with the "this" keyword and you cannot declare methods with arrow functions. In ES7 you can declare props without "this" (works also for inheritance) and you can use arrow methods.

I think Babel 7.2 should support this but CodeKit works with Babel 6.

So this is the old ES6 way:

```
class membership {
	constructor() {
		this.highest = 'Gold';
	}

	getDefault() {
		return this.highest;
	}
}

class member extends membership {
	constructor( name, level = false ) {
		super(); // inheritance
		this.name = name;
		this.level = level;
	}

	printMember() {
		const level = this.level ? this.level : this.highest;
		console.log( this.name + ' is ' + level + '-Member' + ' and the default level is ' + this.getDefault() );
	}
}

const member1 = new member( 'Jerry' );

member1.printMember(); // Jerry is Gold-Member and the default level is Gold

const member2 = new member( 'Tony', 'Silver' );

member2.printMember(); // Tony is Silver-Member and the default level is Gold
```

And this is a new possible way with ES7, but it is not possible to compile it with CodKit:

```
class membership {
	highest = 'Gold';

	getDefault() {
		return this.highest;
	}
}

class member extends membership {
	setProps = ( name, level = false ) => {
		this.name = name;
		this.level = level ? level : this.highest;
                return this; // return this for concatenation
	}

	printMember = () => {
		console.log( this.name + ' is ' + this.level + '-Member' + ' and the default level is ' + this.getDefault() );
	}
}

const member1 = new member();

member1.setProps( 'Jerry' ).printMember(); // Jerry is Gold-Member and the default level is Gold

const member2 = new member();

member2.setProps( 'Tony', 'Silver' ).printMember(); // Tony is Silver-Member and the default level is Gold
```
Check this out: [Babel Playground](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEC2CmsBG8BOEAWBLADtA3gFACQ2A5hvBAC7QC80A5AOID2IAJowNyElnxqAEXgAzMAFcQ1ABQBKAiWKpBE1ADto1bBAB05SjV7EAvoTOFQkGAmRpo8AB7V46jjcQp02PEWIRBAAVUVhwYBhlodTAEABpoEHgAN3gQemhxEADoBToAPkViYm0sPWiEdPL4Y2KdXUSUtIYG1OgAfgTk1oAuLTqDKmpeaBHRkZVqNU0SiG5oAHp56AmpvtKM1lRoYFZ1YDAXaOosXZILYhxULHVqAFlPewjcgr9iHfUIdnh61jJImd0VWgAGomNB1owQWs9C00qDGABae52VCQ-HQMBuPrwaAcMSSaSdRrgmBo6G6ATCfFSWQKOTGMwWd40OAPVAARkq8AA7qyUfJeIRbF52boAtRgqEIJFGAApNCoACekLkuku1zubIFCyW8tQSpJ0DYnCRbIxWO0OLx4hpRNa62NHD4zNowrQACYuby3agBXwfe6xUEQmEZQAVXbK-KMADKWBAKVROTVVxuyK82sW0Aj6kVhrjCbQppR5o42Nx1MJsMNjsIQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=es2017%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Cenv&prettier=false&targets=&version=7.6.4&externalPlugins=)

**Comment by bdkjones** [comment]
This is just the latest version of Babel. CodeKit has used Babel 7 since it shipped and currently has Babel 7.5.5. Babel 7.6 will be in the next release, which I hope to have published in the next 24 hours.

**Comment by indikatordesign** [comment]
Something new?

**Comment by bdkjones** [comment]
Yep. Should be pushing the new update in a few hours. Finishing the documentation.

**Comment by indikatordesign** [comment]
Nice work. Thanks! Still shows a warning, but that has to do with the fact that it is still very experimental. Is it possible to disable warnings?

**Comment by bdkjones** [comment]
No. The warning is a good thing—you should definitely not be using this in production yet. You can stop CodeKit from beeping and coming to the front on warnings in Preferences > Notifications.

**Comment by indikatordesign** [comment]
You can use this style in production very well if you work with react in combination with yarn.

But I really like to use CodeKit to play with the things, because it is much easier to setup. Here I will gladly listen to your advice until you give the green light ;-)

Thanks for implementing it.

**Comment by bdkjones** [comment]
The warning isn’t from me; Babel itself is producing them. They’ll disappear when Babel decides this is safe.
