### ISSUE TITLE
Error when compiling on Catalina

### ISSUE THREAD

**Issue by titifrim** [bdkjones/CodeKit#567]
I updated from Mojave to Catalina today and Codekit can no longer compile files :(. Any idea ???

Compiling failed with this error: Errno::EROFS on line ["239"] of /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb: Read-only file system @ dir_s_mkdir - /.sass-cache
Run with --trace to see the full backtrace

**Comment by bdkjones** [comment]
Enable Libsass. I replied to your email. This is a Catalina issue, since the root volume is now read-only and Ruby Sass stupidly tries to write a hidden cache folder to the drive root.
