### ISSUE TITLE
Less compiling failed: Unable to load plugin ie-compat

### ISSUE THREAD

**Issue by realfish** [bdkjones/CodeKit#568]
After updating to v3.10.1, the Less file, whose “enable IE8 compatibility checks” option is check, will be unable to be compiled successfully. The CodeKit console reports:

> Compiling failed with this error: Unable to load plugin ie-compat please make sure that it is installed under or at the same level as less

**Comment by bdkjones** [comment]
Well, after looking into this, it seems like the Less team screwed something up. The `--ie-compat` option is a valid option shown in the help for `lessc`, and it worked flawlessly in the last Less release. There is no "ie-compat" plugin that I can find (the Less folks are famous for modularizing stuff into plugins). It looks like Less just broke this option.

It applies only to IE8 anyway, which is an ancient browser. Your best bet is to uncheck the box and carry on. I'll remove the option from the UI in the next release.

**Comment by bdkjones** [comment]
Okay, this is fixed in 3.10.2, which is now live. I discussed the issue with the Less guys and it is indeed a bug on their end. Furthermore, the "enable IE compatibility checks" option has been inert since Less 3.0 shipped. As such, it's been removed from CodeKit 3.10.2 entirely.
