### ISSUE TITLE
NPM no longer installing/upgrading packages

### ISSUE THREAD

**Issue by noraheuer** [bdkjones/CodeKit#575]
CodeKit version 3.10.2 -- Build 31934
MacOS High Sierra 10.13.6 (17G9016)

Not sure when this started but I can no longer install/upgrade any NPM packages through CodeKit. CodeKit will create/update the package.json file, but the modules themselves are never installed/upgraded.

I keep getting the following unhelpful response:
![Screen Shot 2019-11-28 at 11 30 59 AM](https://user-images.githubusercontent.com/6789426/69821917-ed48d880-11d2-11ea-838b-307a1b6a62bd.png)

This happens in both existing and new projects. 

Bower still works as it always did.

I can manage npm packages via cli (latest brew install of node), but I like that extra visual context CodeKit provides for version control.

Any hints? I must be missing something.

**Comment by bdkjones** [comment]
What are you trying to install? A package.json file or a single package? What changes have happened to your system between now and the last time everything worked? My guess is that you've got a conflict with the locally-installed version of Node and the one bundled in CodeKit.

**Comment by noraheuer** [comment]
I get this error trying to install any npm package. 
If I don't already have a package.json, CodeKit will create it. If package.json exists CodeKit will update it. But the packages itself are never installed.

If I remove my locally installed Node, I get the same error from CodeKit. <-- this was my first thought.

I cannot pinpoint when this has started to occur or what changes I had made to my system prior.
I've been dealing with this for several weeks now. 

Do you think clean-installing CodeKit might help? That's the one ting I haven't yet tried.

**Comment by bdkjones** [comment]
Doubtful. Check console.app to see if any error messages are logged there.

**Comment by mikeboutte** [comment]
I'm having the exact same issue. I've done a clean install of everything including Codekit. Nothing installs on a new project and no existing packages read as being installed on old projects.

**Comment by bdkjones** [comment]
Do you have Node and npm installed locally on your Mac? Try that and see if the problem persists.

**Comment by bdkjones** [comment]
Also: which version of macOS is everyone running? If it’s 10.15, this could be yet another “feature” of Catalina’s ridiculous security over-reaches.

**Comment by mikeboutte** [comment]
OS 10.14.6 for me.
And I have Node (12.13.1) and npm (6.12.1) installed

**Comment by bdkjones** [comment]
Well, I tried to reproduce this issue tonight on my machine (macOS 10.14.6, CodeKit 3.10.2), but was unable to do so. 

I created a brand new, empty folder on my Desktop. Dragged it onto CodeKit. Switched to the packages area and installed `underscore`. Everything showed up like it should have.

Please repeat that exact sequence and see what happens on your end. 

## Also Try:

1. Open a Finder window and make sure you can see hidden files/folders. If you can't, hit `shift+command+.` 

2. Go to your Home folder.

3. Delete the hidden folders `.config`, `.local`, `.npm`, `.cache`.


@mikeboutte Do you have npm and node installed through Brew as well?

**Comment by mikeboutte** [comment]
Me too and I got it to work. I did a complete reinstall of Node etc. and I
think what did it for me was repairing permissions in those installs.
