### ISSUE TITLE
Terser Options: Comments is not removing /*! these multiline comments */

### ISSUE THREAD

**Issue by asantos** [bdkjones/CodeKit#578]
**Quick, short summary:** If _Comments_ is not checked in Terser Tools, it should remove ALL comments.

**Expected results:** All comments should be removed.

**Actual results:** This specific kind of comments are not being removed:
```
/*!
 * Sizzle CSS Selector Engine v2.3.4
 * https://sizzlejs.com/
 *
 * Copyright JS Foundation and other contributors
 * Released under the MIT license
 * https://js.foundation/
 *
 * Date: 2019-04-08
 */
```

**Exact steps to reproduce:** Copy that portion of javascript code and paste it into one of your projects javascript files, then save the javascript file, and the comment will still be there.

**Your configuration (any details about your system that you think might be relevant)** Uncheck Comments in the Terser Tools options.

**Comment by bdkjones** [comment]
This is correct behavior. The `/*!` delimiter indicates a "strong" comment that should survive minification. These are often used for copyright notices, required license inclusions, and other things that must be kept in the file. (In the case above, removing that comment would violate the MIT license for Sizzle.)

If you want the comment removed, use a normal `/*` or `//` delimiter. 

I do agree that the explanation text needs updating though. Terser just adopted the new strong-comment delimiters at my request a couple months ago.
