### ISSUE TITLE
SASS Compressed Output Style messes up the CSS

### ISSUE THREAD

**Issue by markvanwijnen** [bdkjones/CodeKit#581]
**Quick, short summary:**
Create a .scss document with the following code:
```
body > *:not(.you) {
	background: red;
}
```
And put the output style of sass on Compressed. On other modes this bug does not occur.

**Expected results:**
```
body > *:not(.you) {
    background: red;
}
```

**Actual results:**
```
body > * :not(.you) { //<-- notice the space between * and :
    background: red;
}
```

**Comment by bdkjones** [comment]
Interesting! You’ll need to open this on the Libsass repo though. It’s a bug in Libsass, not CodeKit. (Make sure your project IS using the Libsass compiler first.)

**Comment by markvanwijnen** [comment]
What are the settings CodeKit uses for Libsass when the output style is set to compressed? It might help me better submit the issue at their repo.

**Comment by bdkjones** [comment]
When compiling a Sass file that's set to a `compressed` output style, CodeKit uses Libsass's value for that output style, which is an `int` that has value `3`:

<img width="231" alt="Screen Shot 2020-01-27 at 21 44 38" src="https://user-images.githubusercontent.com/926566/73238642-80a87680-414e-11ea-894d-878e3b90cef1.png">

**Comment by bdkjones** [comment]
Be sure to download and test with the very latest version of Libsass. I had to roll back to the version before that during CodeKit's last update because the latest version of Libsass had some large regressions that many people complained about.
