### ISSUE TITLE
TLS misconfigured warning forces horizontal scroll

### ISSUE THREAD

**Issue by luxuryluke** [bdkjones/CodeKit#582]
**Quick, short summary:**
When viewing on local wifi iOS device, the TLS warning contains inline styles that makes the warning wider than device width, forcing the test site to scroll sideways and allows other elements to expand beyond width of device in the browser.
**Expected results:**
I've followed all of the steps to view in iOS via wifi using bonjour. Everything is working.
**Actual results:**
Everything is working, but the TLS Misconfigure warning exists underneath the site, causing the horizontal scrolling.
**Exact steps to reproduce:**
design a site that responds to mobile device width.
setup TLS host in MAMP (Pro)5.5.1
setup site in CodeKit 3.10.2
turn on external server for PHP
share certificate with iOS device
load site on iOS device using https://[localmachinename].local:5757
view source on site and see that the injected js script in the HEAD is creating element with warning underneath site
**A link to download a simplified project or file that shows the issue:**
https://www.dropbox.com/s/6spgrpnt1i0k269/horscroll.jpeg?dl=0
**Your configuration (any details about your system that you think might be relevant)**
2017 iMac MacOS 10.15.2
Latest everything
iOS 13.3 iPhone 8

**Comment by bdkjones** [comment]
The issue here is likely that the CSS on your custom site is affecting the styling of the warning banner. I do my best to avoid that, but there are simply cases where the cascade will affect the banners and overlays CodeKit shows. Try with a clean, non-styled page and see if you get the same result.

**Comment by luxuryluke** [comment]
I see. I'll try and do a test to see if that resolves it.
Does this element exist on the page, even when there are no issues to warn about?
I know it's crazy, but if all of the styles are inline anyway, couldn't you add in a z-index of 99999 and a position of fixed so that it's always showing on top of anything? Or just add in a font-size that brings down the size of the headline in this case.

**Comment by luxuryluke** [comment]
Wait, I've set everything up properly. Why is this error showing up? I've installed the certificates, etc.
