### ISSUE TITLE
app.jsand app.scss keeps changing where they copy to in build folder

### ISSUE THREAD

**Issue by kriskenyon** [bdkjones/CodeKit#583]
**Quick, short summary:**
When compiling app.js and app.scss Codekit moves from builda/js/app.js to/build/js/app-min.js and app.scss moves to /build/scss/app.css instead of build/css/app.css even though the project settings are correct and setting the output of these files does not stick over application restarts.
**Expected results:**
Files compile to where they are specified and configurations are saved in the settings.
**Actual results:**

**Exact steps to reproduce:**
This is a very old site that has spanned from Codekit 2 to the latest. This problem started at the time of upgrading to Catalina everyones favotite most stable Mac OS release ever....
**A link to download a simplified project or file that shows the issue:**
I cannot give this over due to the customer. I can do a remote session if you want to see the probelm in acgtion as it is easy to reproduce.
**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Mmm, this is likely a configuration issue. Set the output path for those files explicitly using the right-hand inspector panel. Then verify that the Output Path does not include a *-min.css suffix for Sass files. Make sure you also click the “apply to existing files button” there.

**Comment by kriskenyon** [comment]
Bryan,
I have done this and even went into git to pull old versions of config.codekit3 to stop this.  These 2 files keep overwriting to app-min.js and scss/appp.css instead of holding the hardset values.  I am frustrated as all heck…. I know you understand.

--
Kris Kenyon
http://mysupportpad.com<http://mysupportpad.com/>
214-254-4444
Download my VCARD<http://mysupportpad.com/MySupportPad.vcf>

On Jan 31, 2020, at 10:13 PM, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Mmm, this is likely a configuration issue. Set the output path for those files explicitly using the right-hand inspector panel. Then verify that the Output Path does not include a *-min.css suffix for Sass files. Make sure you also click the “apply to existing files button” there.

**Comment by bdkjones** [comment]
Well, the issue is definitely isolated to you. Please zip the entire project and post a download link. I’ll take a look over here.

**Comment by kriskenyon** [comment]
Bryan,
Unfortunately by agreement with my client I cannot send the files BUT I truly appreciate the offer. Just so you understand what I am seeing here is a video of the scss.

Basically when I launch the scss file points the build target to build/scss/app.css
I change the path to build/css/app.css
I quit codekit
on relaunch it goes back to build/scss/app.css

Also other pertinent info/steps I have tried

I tried making a fresh config.codekit3 by removing the old file and re-adding the project. Setting the defaults as they were in the past. This exhibited the same behavior. I went back to the old config.

I tried an older config from git and this worked for about a day and then started this behavior again.

The files quit actually auto compiling they say they are compiling and my Mac sends me an alert BUT I have to actually go to these 2 files and click Compile for changes to show up.

All other files work as expected.

I am also including the screenshots of the configs for Javascript and less for you to see.

[cid:4FFD040F-7CF7-4873-A008-C8E91519B5F0@4harmony.net]

[cid:58022DF1-28CA-46EE-92C0-AD436FB800A6@4harmony.net]



Here is a dropbox link to the video. Your emila does not allow 14MB attachments.
https://www.dropbox.com/s/8uqcv2s1gz2on2l/kk_2020-02-01_08-16-21_AM.mov?dl=0


--
Kris Kenyon
http://mysupportpad.com<http://mysupportpad.com/>
214-254-4444
Download my VCARD<http://mysupportpad.com/MySupportPad.vcf>

On Jan 31, 2020, at 11:59 PM, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, the issue is definitely isolated to you. Please zip the entire project and post a download link. I’ll take a look over here.

**Comment by bdkjones** [comment]
Is this project in any sort of syncing folder, such as Dropbox or iCloud? Which editor are you using?

**Comment by kriskenyon** [comment]
Bryan,
Sorry busy all day. The answer it no to syncing folders they cause too many problems (I am certain you know this) as to editors I use 2 phpstorm most of the time and sublimetext occasionally.

--
Kris Kenyon
http://mysupportpad.com<http://mysupportpad.com/>
214-254-4444
Download my VCARD<http://mysupportpad.com/MySupportPad.vcf>

On Feb 1, 2020, at 1:14 PM, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this project in any sort of syncing folder, such as Dropbox or iCloud? Which editor are you using?

**Comment by bdkjones** [comment]
Okay. Try using Sublime Text with PHPStorm not running. Does the problem persist? PHPStorm is a non-native app and doesn’t use the system save APIs, so weird things can sometimes happen there.
