### ISSUE TITLE
Autoprefixes stripped with CSS @include

### ISSUE THREAD

**Issue by otheroom** [bdkjones/CodeKit#586]
**Quick, short summary:**

When a css file is included into a kit file via @include the autoprefixing is stripped in the html output file if the build is triggered by a change to the scss file.

**Expected results:**

The SASS autoprefixes should be in the resulting html file.

**Actual results:**

No autoprefixes unless the html build is triggered by a change to the kit file.

**Exact steps to reproduce:**

index.kit
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Codekit test</title>
	<style>
		<!-- @include css/main.css -->
	</style>
</head>
<body style="background: #ddd;">
	<form>
		<p>Unstyled Elements</p>
		<input type="radio">
		<div class="styled">
			<p>Styled Elements</p>
			<input type="radio">
		</div>
	</form>
</body>
</html>
```

main.scss
```
.styled {
	input[type=radio] {
		appearance: none;
		background: #333;
		width: 30px;
		height: 30px;
		border: 4px solid #aaa;
		border-radius: 15px;
	}
}
```

main.css
```
.styled input[type=radio]{-webkit-appearance:none;-moz-appearance:none;appearance:none;background:#333;width:30px;height:30px;border:4px solid #aaa;border-radius:15px}
/*# sourceMappingURL=main.css.map */
```

Change the index.kit file and save and you can see that *appearance* has the autoprefixing.
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Codekit test</title>
	<style>
		.styled input[type=radio]{-webkit-appearance:none;-moz-appearance:none;appearance:none;background:#333;width:30px;height:30px;border:4px solid #aaa;border-radius:15px}
		/*# sourceMappingURL=main.css.map */
	</style>
</head>
<body style="background: #ddd;">
	<form>
		<p>Unstyled Elements</p>
		<input type="radio">
		<div class="styled">
			<p>Styled Elements</p>
			<input type="radio">
		</div>
	</form>
</body>
</html>
```
Change the main.scss file and save and you can see that *appearance* does not have the autoprefixing even though main.css does.
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Codekit test</title>
	<style>
		.styled input[type=radio]{appearance:none;background:#333;width:30px;height:30px;border:4px solid #aaa;border-radius:15px}
		
		/*# sourceMappingURL=main.css.map */
	</style>
</head>
<body style="background: #ddd;">
	<form>
		<p>Unstyled Elements</p>
		<input type="radio">
		<div class="styled">
			<p>Styled Elements</p>
			<input type="radio">
		</div>
	</form>
</body>
</html>
```

**A link to download a simplified project or file that shows the issue:**

[Codekit test.zip](https://github.com/bdkjones/CodeKit/files/4242221/Codekit.test.zip)

**Your configuration (any details about your system that you think might be relevant)**

MacOS 10.14.6
Codekit 3.10.2

**Comment by bdkjones** [comment]
This is happening because the first action on the Sass file (compiling) creates a file-change event that triggers the Kit file to re-compile because a file it imports has changed. The Kit file finishes processing before the Autoprefixer step has finished on the Sass file—it’s a race condition that the Kit compiler will win 99.99% of the time because it’s written in C and is therefore orders of magnitude faster than the Javascript-based AutoPrefixer.

The correct way to do what you want is to use @compile instead of @import and pass the path to the Sass file. See codekitapp.com/help/Kit/ for details.
