### ISSUE TITLE
Php files not being built out

### ISSUE THREAD

**Issue by treyseals** [bdkjones/CodeKit#588]
When saving a .php file (and the language added to the settings) that is targeted by a hook, the file is not built (output/saved) to the build location.

**Comment by treyseals** [comment]
Not sure what occurred, but deleting the hook and re-pasting it fixed the issue.

**Comment by luxlogica** [comment]
@treyseals perhaps providing a bit more information would be helpful. What kind of processing do you need done with the php file? How did you configure your 'Other' language settings? What happens in the hook? Are you able to take screenshots and show us?

**Comment by bdkjones** [comment]
I'm not able to help without examples. It's almost certainly a configuration issue, though, as all my Hook test projects work normally with the current production release of the app.
