### ISSUE TITLE
JS Minification With Sourcemap & Buildfolder

### ISSUE THREAD

**Issue by sinnestaeter** [bdkjones/CodeKit#590]
My project is configured to use a build folder named "build" which processes & copies all my project files from a folder named "source".

In the JavaScript settings I turn on the options "Minify output with Terser" and "Create source map". The problem is now, that all source map files are successfully created but the "sources" parameter within the map file still points to my source folder, which is not accessible from the server (serves only the build folder).

Example:

**Minified/processed `build/js/orders.js` in the build folder:**
`define([],(function(){$("div.order-list > div.item").on("click",(function(){document.location.href="account.orders.order.php"}))}));
//# sourceMappingURL=orders.js.map`

**Source map file `build/js/orders.js.map`:**
`{"version":3,"sources":["../../source/js/orders.js"],"names":["define","$","on","document","location","href"],"mappings":"AAIAA,OAEE,IAGA,WAQEC,EAAE,6BAA6BC,GAAG,SAAS,WACzCC,SAASC,SAASC,KAAO"}`

**The `source`property should be:**
`..., "sources":["../../build/js/orders.js"], ...`

Is that a bug or can I configure the Terser --source-map parameter somewhere?
Thanks! Greg.

**Comment by bdkjones** [comment]
Is your project using an External Server?

CodeKit has some magic that allows certain HTTP requests to escape the document root folder specifically to handle this case—allowing source maps to reference files above the document root. This magic gets overridden if you're using an external server, though, because in that case CodeKit simply proxies *every* request over to that server.

**Comment by sinnestaeter** [comment]
Yes, I'm using an external server to handle my php files and the rest of the content within the `build` folder. So do you mean, that the usage of an external server breaks the source map support? Thanks for the quick reply!

**Comment by bdkjones** [comment]
Yes. Using an external server overrides CodeKit’s ability to serve content from outside of the document root. When you run an External Server, CodeKit gets out of the way to ensure that whatever your server serves is what the browser gets. This is especially important for dynamically-generates content, redirects, etc.

**Comment by bdkjones** [comment]
Unfortunately, there's nothing I can do at this time to resolve the external server + source maps issue. You'd need to add some custom rules to your server (via .htaccess, or apache config) that redirects requests for *.map files to the appropriate path on your machine. 

However, an option I AM exploring is inline-source-maps, which would let me speed up the compiling workflow considerably by avoiding intermediate hits to disk between steps. If I implement that, this problem will no longer exist.
