### ISSUE TITLE
Bundled and transpiled successfully, but with warnings: Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by xcrap** [bdkjones/CodeKit#592]
Compiling my js in a project I suddently got this:

Bundled and transpiled successfully, but with warnings: Browserslist: caniuse-lite is outdated. Please run next command `npm update`

Minified successfully.

So... I've made no updates on any NPM, no updates at my system nothing. Yesterday was everything okay and today I got this... I don't even have those packages in my project. Feeling frustrated again.

**Comment by Ariane-B** [comment]
I have that too. It's probably just that he needs to update the version of caniuse-lite bundled into CodeKit. There's a new version coming up, so we shouldn't worry.

**Comment by bdkjones** [comment]
Yep, that’s the cause. I’ll have an update out soon to address this.

**Comment by xcrap** [comment]
There's any date for this update?
This warnings notification is annoying and disabling it's not the best for perfectionists.

**Comment by bdkjones** [comment]
Working on validating the update and updating the website now. Shooting to have it out in the next few days.

**Comment by bdkjones** [comment]
Sorry for the delay. I migrated my servers to CentOS 8 and PHP 7 along with a massive change in the payment flows. Let's just say that it did not go...smoothly. 

That's all done now and everything is in place on the server to support the next release of the app. I'm tidying that up tonight and will ship it live tomorrow.

**Comment by xcrap** [comment]
I think I've refreshed the updates page and the check for updates about 20 times. Just saying. :)

**Comment by bdkjones** [comment]
Fighting with Xcode to get Apple’s notary service to upload the app. It keeps crashing Xcode 11.4, so I’m restoring 11.3 from a backup. The app has to be notarized before I can ship it now, thanks to the dumpster fire that is Catalina.

-Bryan

**Comment by bdkjones** [comment]
Notarization came back and the app is up at codekitapp.com/binaries/codekit-32001.zip

You can download that directly if you don't want to wait for me to push the update out. I'll have to do the release notes and website updates tomorrow though. It's 4AM here. 

In case you miss the release notes: this version includes the new license expiration ("Sketch model") stuff I mentioned in the release notes a year ago. Everyone who had a license set to expire before this in 2020 has been pushed to 15 May 2020. Your license will always unlock any version of CodeKit that was shipped before it expired.
