### ISSUE TITLE
SCSS autoprefixer not working on Version 3.11

### ISSUE THREAD

**Issue by xcrap** [bdkjones/CodeKit#596]
Updated the new version, the project I was working on started to display some inconsistencies. 

Realized that "background:linear-gradient" was not auto prefixing for -webkit-linear-.. etc...
So checked the CSS and the auto prefixer is not working at all...Does anyone have the same problem?

In https://autoprefixer.github.io/ (autoprefixer: v9.7.3)

This
.ux-header-hero .background-clouds .cloud {background:linear-gradient(to top,#f1f1f1 5%,#fff 100%);border-radius: 100px;box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);height: 120px;position: relative;width: 350px;transform: scale(0.55);}

Converts to this
.ux-header-hero .background-clouds .cloud {background:-webkit-gradient(linear,left bottom, left top,color-stop(5%, #f1f1f1),to(#fff));background:-o-linear-gradient(bottom,#f1f1f1 5%,#fff 100%);background:linear-gradient(to top,#f1f1f1 5%,#fff 100%);border-radius: 100px;-webkit-box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);height: 120px;position: relative;width: 350px;-webkit-transform: scale(0.55);-ms-transform: scale(0.55);transform: scale(0.55);}

My CSS is the same size with or without autoprefixer, makes absolutely nothing :/
Of course, this part of Codekit was working fine till this update, tried with other projects it removes all autoprefixes from my final CSS files...

Wonder if the autoprefixer updates removed prefixes with browser updates?
It’s strange because it removed all of them

**Comment by xcrap** [comment]
In https://autoprefixer.github.io/

This
.ux-header-hero .background-clouds .cloud {background:linear-gradient(to top,#f1f1f1 5%,#fff 100%);border-radius: 100px;box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);height: 120px;position: relative;width: 350px;transform: scale(0.55);}

Converts to this
.ux-header-hero .background-clouds .cloud {background:-webkit-gradient(linear,left bottom, left top,color-stop(5%, #f1f1f1),to(#fff));background:-o-linear-gradient(bottom,#f1f1f1 5%,#fff 100%);background:linear-gradient(to top,#f1f1f1 5%,#fff 100%);border-radius: 100px;-webkit-box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);height: 120px;position: relative;width: 350px;-webkit-transform: scale(0.55);-ms-transform: scale(0.55);transform: scale(0.55);}

My CSS is the same size with or without autoprefixer, makes absolutely nothing :/

**Comment by bdkjones** [comment]
Every CodeKit update includes a newer version of the `caniuse` database. The exact prefixes that are applied depend on the target browsers you choose. It's likely that your selected browsers no longer require the prefixes you used to see.

I just tested CodeKit 3.11 using the demo on Autoprefixer's repo. Here is the result (input file on the left, compiled CSS on the right):

<img width="1223" alt="Screen Shot 2020-04-06 at 21 45 18" src="https://user-images.githubusercontent.com/926566/78631011-fcf6be80-784f-11ea-9d9d-f92cc35ee343.png">

**Comment by bdkjones** [comment]
Give that demo text a shot with CodeKit's default Target Browsers and let me know if you don't see prefixed output.

**Comment by xcrap** [comment]
Thanks, I confirm, the prefixes that I used were all dropped down, sorry for the mistake.
