### ISSUE TITLE
Check Syntax results now expanded as default?

### ISSUE THREAD

**Issue by d1ch0t0my** [bdkjones/CodeKit#597]
**Quick, short summary:**
Version 3.11 Build 32001 now auto expands JS syntax check results.

**Expected results:**
Not to see results auto expanded.

**Actual results:**
Results are expanded by default.

**Exact steps to reproduce:**
Check syntax of JS file using ESLint or other checker.

If this is a changed behaviour is there a away to revert back to having results un-auto-expanded as they were in previous versions? I've checked through the release notes and can't find any reference to this nor can I find a setting to change this myself within the app. I'm probably being dumb though so appreciate any advice, thanks for a great app!

**Comment by bdkjones** [comment]
The behavior in the last release was a bug. The last row of the Log collapsed child objects, which include not only the syntax issues, but the log message itself. For 9 years before the last release, the behavior was as it is now.

If your file has syntax issues, those now appear directly underneath the log message. If your file imports OTHER files, the syntax issues for each file in the chain are shown. To suppress syntax messages in the former case, set the "Check Syntax With" option on the file to "Nothing". To suppress syntax issues for certain files in the import chain, select the base file, choose the "Linked Files" tab of the right-hand inspector, then un-check the shield checkbox next to files that should not report syntax issues (jQuery, etc.)

**Comment by d1ch0t0my** [comment]
OK thanks for clearing that up. Neither option works for me as I want don't want to suppress I want to choose whether to expand the result to show those errors. Having it as it is now can mean a lot of scrolling to find specific entries (if like me you have lots of errors to whittle down!). Anyway, I will just suck it up and work with it. Thanks again.

**Comment by bdkjones** [comment]
If you uncheck the shield next to imported files, the files are still linted as normal, the entries are simply collapsed in the log until you expand them. It's exactly what you're after.

**Comment by d1ch0t0my** [comment]
Got it, I was being dumb. Perfectly solved. Thanks so much :).
