### ISSUE TITLE
Codekit 3.11 break the pause watching shortcut 

### ISSUE THREAD

**Issue by rvola** [bdkjones/CodeKit#600]
Hello @bdkjones 

With mac Mojave 10.14.6 and Codekit 3.11,
the global shortcut to stop scanning files no longer works.

You must have selected Codekit for it to work.

Previously it worked a few times the application in focus.

**Comment by bdkjones** [comment]
Try resetting the shortcut in Preferences and see if that does the trick.

**Comment by rvola** [comment]
MACHINE !!! 💪
but no I just tried before, even by changing the default shortcut.

I just try again with codekit ver 31934, it works.
The bug is present in version 32001.

**Comment by bdkjones** [comment]
Interesting. I’ve been able to reproduce it over here, so I’ll take a look. Thanks!

**Comment by bdkjones** [comment]
Fixed for the next update, which should be out tomorrow. Thanks!
