### ISSUE TITLE
Feature request: clean-css support

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#601]
I wanted to automatically remove overridden styles from a same SCSS/CSS ruleset. A simple example would be a reset mixin. I'll `@include` that mixin which sets all sorts of properties to 0, including `padding`. And then I'll set a padding to my element myself. The resulting style would look like:

```css
.my-rule {
  padding: 0;
  padding: 1em;
}
```

This cannot possibly be the most optimized thing.

So, I was looking around for ways to strip the overridden rules, and it seems [clean-css](https://github.com/jakubpawlowicz/clean-css) allows this through its `overrideProperties` setting. It also has some more cool optimizations that Sass sadly doesn't offer out of the box, such as automatically merging `@media` statements.

It would be nice if it were possible to run this optimizer after compiling Sass files, the same way we can run Autoprefixer on them.

It seems to support source maps, too, although I'm not sure how well that would play along with Sass's source maps, which already aren't 100% reliable... but even if it doesn't ever work well, I wouldn't mind. I could just disable clean-css during development and then enable it before the code reached production stage.

**Comment by Ariane-B** [comment]
It seems there are others than clean-css. It might be worth looking into them.

[This benchmark](https://github.com/GoalSmashers/css-minification-benchmark) indicates that clean-css might not be the best one after all.

(To see the benchmark results, you have to download [index.html](https://github.com/GoalSmashers/css-minification-benchmark/blob/gh-pages/index.html). It seems they did something wrong with their Readme.)

**Comment by bdkjones** [comment]
This is going live in 3.14, soon. PurgeCSS is available for CSS, Sass, Stylus, and Less files.
