### ISSUE TITLE
Compiled CSS suddenly contains a byte-order mark which leads to errors

### ISSUE THREAD

**Issue by Celldweller** [bdkjones/CodeKit#602]
**Summary**
The CSS build suddenly seems to add a BOM (byte-order mark) to the beginning of the css file <U+FEFF>
Thus my CSS file starts with
`<U+FEFF>@import url("https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,600,700");`
This leads to display problems. The browsers (tested with Safari, Chrome, Firefox on Mac) cannot display the font any more.

**Expected results:**
The compiled CSS file does not have a BOM at the beginning.

**Actual results:**
The compiled CSS file does have a BOM at the beginning.

**Exact steps to reproduce:**
Compile a SCSS file

I just updated to 3.11 Build 32001 and never had this problem before.
Mac version is 10.15.3 (19D76)

**Comment by bdkjones** [comment]
Please post a link to a sass file I can use to duplicate the issue. I did not make any intentional changes that would have produced this behavior.

**Comment by bdkjones** [comment]
Also: check your CSS file for non-ASCII Unicode text. I believe the BOM is automatically added when the file contains Unicode multi-byte code points.

**Comment by bdkjones** [comment]
You should also ensure that your text editor is set to use UTF8 for the file's text encoding. Nothing else is supported by the tooling in CodeKit.

**Comment by bdkjones** [comment]
If you use the Dart Sass compiler (new in CodeKit 3.12) you can now control when this directive is added to your CSS.
