### ISSUE TITLE
Feature request: More visual Sass errors

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#603]
I absolutely love how CodeKit displays the JS errors and warnings from ESLint:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/6244273/79625675-892e9e80-80f8-11ea-9f98-2ff01c02d372.png">

With this, I can tell at a glance that the error is in `scripts.js` and that it's on line 895. Compare this with the errors from Libsass:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/6244273/79625769-52a55380-80f9-11ea-8661-c3909e9ab0fc.png">

My eyes are always dancing around  to find on which line the error is, since it's all plain, single colour text... and there's a lot of it!

I realize it's probably not exactly simple since (I guess) you're basically outputting the raw command-line errors that Libsass gives you. Even if a completely visual error reporting system like you did with ESLint isn't feasible, maybe something else would be possible.

For example, highlighting the final file names and line numbers with color would do wonders to help direct the eye away from the mostly irrelevant long path.

**Comment by bdkjones** [comment]
Yep. I can do this with ESLint because their executable returns JSON that’s easily parsed. Libsass and other tools do not, so I can’t easily format their content.

**Comment by Ariane-B** [comment]
You can't even pass a regex on it to add colors?

**Comment by bdkjones** [comment]
Nope. There is no such option. The way colored output in the terminal works is that the string the sass compiler outputs has extra characters in it that specify how to color the text. Those characters are parsed and removed by the terminal. Outside of the terminal, the extra characters would show up and appear as garbage in the output.

**Comment by Ariane-B** [comment]
Oh. That's unfortunate, but I understand.
