### ISSUE TITLE
[feature request] ability to define multiple outputs for each language

### ISSUE THREAD

**Issue by tmcgill** [bdkjones/CodeKit#604]
For my specific use case, I'd like to generate two css files when saving my sass....
1. a un-minfied css file (.css extension)
2. a minified css file (.min.css extension)

At current, I see the capability to output only one of the two above.

**Comment by bdkjones** [comment]
Source maps make this arrangement unnecessary, but if you’d still like to do it simply create two “master” files that each import the other files you need. Set each “master” file to compile to a separate location and configure one to be minified and the other to be expanded. Whenever you save an imported file, both master files will recompile to capture the changes.

**Comment by tmcgill** [comment]
True. This came up because I'm collaborating on a project and the primary developer's build tools generate the two files I mentioned, both of which are included in the repo. Was looking for a way for keeping both up-do-date with sass regardless of who commits, but I suppose the issue I'm facing here is more of a repo-management issue rather than a than a build process issue.

**Comment by bdkjones** [comment]
Yea, my recommendation would be to ditch the unminified file and use source maps. Those show you the original sass in the browser inspector, which is far more useful. It’s also twice as fast to compile and less overhead to keep track of.
