### ISSUE TITLE
Grid View is not running on this page

### ISSUE THREAD

**Issue by Marcia911** [bdkjones/CodeKit#607]
**Quick, short summary:**

**Expected results:**

**Actual results:**

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by Marcia911** [comment]
When I try to use the waffle I installed, I see Grid View is not running on this page.
Below it is Source code available at Github.

How do I get the Grid View to run?

Thank you,

Marcia

**Comment by bdkjones** [comment]
I'm sorry, there's no information here that would let me tell you what's going on.
