### ISSUE TITLE
Autoprefixer not working after 3.12 Update

### ISSUE THREAD

**Issue by cubano** [bdkjones/CodeKit#609]
Hi, after finally updating to macOS Catalina, I also updated to Codekit 3.12. 

Before the update, Autoprefixer correctly added -ms vendor prefixes for Flexbox. After the update, the prefixes are not added anymore. No matter which browsers I target, nothing happens. Any idea?

Thanks

**Comment by bdkjones** [comment]
Autoprefixer currently has some problems with the IE Grid option. Make sure that option is disabled, then add the grid prefixes yourself for the time being. There are several open issues about this at Autoprefixer's GitHub repo. 

As for flexbox prefixes: verify that your targetBrowser string includes a browser that requires those prefixes. Every CodeKit update includes a newer version of the caniuse database, which is what drives the prefix decisions. It's most likely that your targetBrowser string no longer includes a browser that requires those prefixes.

**Comment by bdkjones** [comment]
Update to CodeKit 3.12.5, which was just released. It includes a fix for an issue that caused Autoprefixer to sometimes ignore custom browserlist strings. That's likely what affected the flexbox prefixes.
