### ISSUE TITLE
PostCSS support: is this planned?

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#611]
I noted in https://github.com/bdkjones/CodeKit/issues/601 that I would like it if a CSS simplifier such as clean-css were supported. However I realize now that this kind of optimization is globally [PostCSS](https://postcss.org/)'s job with plugins.

I realize it's probably not simple (especially if you want to allow us to use custom plugins), but asking costs $0: are there any plans to implement this in CodeKit?

**Comment by CydGoblin** [comment]
Seems like it's coming https://github.com/bdkjones/CodeKit/issues/593#issuecomment-736272186

**Comment by garethjohnsdesign** [comment]
@bdkjones Do you have an idea when 3.14 will be released, I'm on the verge of starting a new project but not sure to wait for the update or try a workaround

**Comment by bdkjones** [comment]
Should be next week. I came down with a cold on New Years, which prevented me from recording the screencasts for the new features. I’m working on those and the docs currently. 

-Bryan

**Comment by garethjohnsdesign** [comment]
Ah great. Is there a beta version of the program that I can use for now even without docs?

**Comment by bdkjones** [comment]
This is going live soon in 3.14. Look for the screencast and docs explaining it, because there are some things to know when working custom PostCSS plugins into the chain of plugins that are built into CodeKit.
