### ISSUE TITLE
CodeKit generates FILENAME.min-blessed1.css

### ISSUE THREAD

**Issue by ties-s** [bdkjones/CodeKit#613]
**Quick, short summary:**
When compiling Sass with the "Run Bless" option, CodeKit generates an additional file with a `*.min-blessed1.css` suffix

**Expected results:**
Just a css file

**Actual results:**
Another file

**Exact steps to reproduce:**
Compile sass file (with either Libsass or Dart Sass) with Bless option

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**
MacOS 10.15.4
CodeKit 3.12.1

**Comment by bdkjones** [comment]
How many selectors are in your file? This is what Bless does: split your CSS file into multiple files and then link them together via @import so that IE will load them. I believe you’re just seeing Bless do what it does when your selectors exceed 4096.

-Bryan
