### ISSUE TITLE
[Feature Request] webp image generation

### ISSUE THREAD

**Issue by JayHoltslander** [bdkjones/CodeKit#619]
Now that Safari ([The last major hold out](https://caniuse.com/#search=webp)) will support the [highly superior](https://www.smashingmagazine.com/2019/10/speed-up-your-website-webp/) webp image format I'd really like to see CodeKit be able to generate webp files from jpegs and pngs during it's image optimization step using [cwebp](https://developers.google.com/speed/webp/docs/cwebp) simply by clicking a checkbox. 

The resulting webp files could live right next to their jpg or png counterparts. The website's .htaccess could take care of [substituting the webps for jpgs](https://github.com/vincentorback/WebP-images-with-htaccess) in browsers that support the format or we could just use [the picture element with multiple sources](https://codepen.io/j_holtslander/pen/xQgaWZ) to ensure a fallback.

Currently I do it manually on the command line like [this](https://gist.github.com/JayHoltslander/05cab870ef701e909f0ff2a5f68bb6d6).

**Comment by bdkjones** [comment]
![](https://i.imgur.com/SXFJR8I.png)

**Comment by iocouto** [comment]
@bdkjones this issue can probably be closed now, right?...
