### ISSUE TITLE
Selectable Items are Super Small

### ISSUE THREAD

**Issue by dcolter** [bdkjones/CodeKit#624]
It should be noted, this is a report from Big Sur (beta 5)

**Summary:**
Everywhere there is a selectable item, the circle and (if selected) green checkmark are almost invisible. The font is also pretty small.

<img width="527" alt="CodeKit Select Icons" src="https://user-images.githubusercontent.com/3046325/90957959-ed72bd80-e45e-11ea-9e33-018b11635669.png">

**Comment by bdkjones** [comment]
That's an Apple bug that will get resolved before GM. Thanks.
