### ISSUE TITLE
Autoprefixer won't run when certain CSS values are present 

### ISSUE THREAD

**Issue by janogarcia** [bdkjones/CodeKit#625]
**Quick, short summary:**

It seems that Autoprefixer chokes on certain CSS value combinations and silently fails when those are encountered.

**Expected results:**

Autoprefixer should run normally, according to the browserlist configuration and independently of the CSS values used in your code.

**Actual results:**

Autoprefixer won't run at all.

**Exact steps to reproduce:**

Try running the following CSS snippet through Autoprefixer, for the default browserlist `>0.2%, last 2 versions, Firefox ESR, not dead`.

```
.test {
    clip-path: polygon(0 100%, 100% 0, 100% 100%);
    align-items: start;
    display: flex;
}
```

The output will be unaltered, where it should have been as follows:

```
.test {
    -webkit-clip-path: polygon(0 100%, 100% 0, 100% 100%);
            clip-path: polygon(0 100%, 100% 0, 100% 100%);
    align-items: start;
    display: flex;
}
```

Autoprefixer will run as expected for the following CSS value combinations, though:

- The correct values for Flex: `align-items: flex-start; display: flex;`
- The correct values for Grid: `align-items: start; display: grid;`

That is, when in the same CSS declaration block there's a combination of `display: flex` and a Flex positioning property like `align-items` or `justify-content` which value is mistakenly set to a value of the Grid module (e.g. `start` instead of `flex-start`), then Autoprefixer will fail to run.

**Your configuration (any details about your system that you think might be relevant)**

CodeKit 3.12.5 Build 32186, bundled Autoprefixer 9.8.0
macOS Catalina 10.15.6

**Comment by bdkjones** [comment]
What is the outcome if you run Autoprefixer from the command line directly? What is the outcome if you use Autoprefixer’s web interface with the same input?

**Comment by janogarcia** [comment]
**Input**

```
.test {
    clip-path: polygon(0 100%, 100% 0, 100% 100%);
    align-items: start;
    display: flex;
}
```

**CLI output**

I get this warning when running it [via npx](https://github.com/postcss/autoprefixer#cli).

`3:5	⚠  start value has mixed support, consider using flex-start instead [autoprefixer]`

The output being correct, though.

```
.test {
    -webkit-clip-path: polygon(0 100%, 100% 0, 100% 100%);
            clip-path: polygon(0 100%, 100% 0, 100% 100%);
    align-items: start;
    display: flex;
}
```

**Autoprefixer interactive demo output**

```
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v7.0.29,
* Autoprefixer: v9.7.6
* Browsers: >0.2%,last 2 versions,Firefox ESR,not dead
*/

.test {
    -webkit-clip-path: polygon(0 100%, 100% 0, 100% 100%);
            clip-path: polygon(0 100%, 100% 0, 100% 100%);
    align-items: start;
    display: flex;
}
```

**Comment by bdkjones** [comment]
Ok. Do you have the IE Grid option enabled in CodeKit? Project Settings > Tools > Autoprefixer

-Bryan

**Comment by janogarcia** [comment]
Nope. It's disabled on CodeKit. 👍

**Comment by bdkjones** [comment]
Looks like this was fixed with an update to Autoprefixer. It's working correctly in the update I'm about to release. I think it should also be working correctly in CodeKit 3.13.3, the current production release.
