### ISSUE TITLE
Using Dart SASS modules with global variables as a framework

### ISSUE THREAD

**Issue by jgmedialtd** [bdkjones/CodeKit#626]
**Quick, short summary:**

Cannot use a SASS variable configuration file when using as a Framework in CodeKit

**Expected results:**

CodeKit would check for a local version of a configuration file which would take priority over the file in the Framework folder

**Actual results:**

The configuration file in the framework folder takes priority

**Exact steps to reproduce:**

Two SASS files used as a Framework, as follows:

A. _global_variables.scss
B. _file_using_global_variables.scss

In A:

$color: blue;

In B:

@use "global_variables" as var;
body { color: var.$color; }

Now when using these files as a Framework, it is necessary to override the variables. With @import is was simple - you simply used a local file, which would be imported in preference the Framework file, however with @use, the imported files will always use the Framework version of the _global_variables.scss file.

So in the project's style.scss file...

@use "global_variables" as var; //will use local global_variables file - define $color as red
@use "file_using_global_variables"; //will use the global_variables file from Framework folder - $color is blue;

Hopefully, if I've explained this properly it will be clear that it will be very difficult to use SASS with @use as a CodeKit Framework and be able to also use a configuration file to set variables, which I suspect will be a common use case.

**Comment by bdkjones** [comment]
I'm not sure what you mean by:

     //will use local global_variables file - define $color as red

I don't see red set anywhere. If you mean that your project has a local file that is ALSO named "global_variables", this behavior is correct. @use (and @import) resolve to local files in the project (if able) before any Frameworks are considered.

**Comment by jgmedialtd** [comment]
Sorry @bdkjones - I realise this isn’t easy to follow.

The problem is the difference in behaviour between @use and @import 

With @use, you need to include the statement at the top of every sass file.

So framework sass files will look in their local folder for the variables file regardless of what’s set locally by an identical file. It doesn’t seem possible to set variables locally when using as a framework, which are respected by the framework files.

If you define $color as red in the local file, any other files which rely on this variable in the framework will default back to the framework $color

Does this make better sense?

**Comment by bdkjones** [comment]
Sass is behaving as designed, if I understand your example.

@use is not @import and it does not follow the same semantics. This means you'll likely need to restructure the Sass in your Framework to adopt to the new "module" system in Sass.

What that means is that you should not have a complex interdependency where your Framework exposes many different Sass files that your project brings in with @use. Your Framework should expose a single MASTER Sass file that projects use. 

Additionally, you would use the default! flag to set default values for variables and then override those defaults when you @use the master sass file in your project. This process is explained pretty thoroughly on the Sass documentation page for @use.

**Comment by jgmedialtd** [comment]
Thanks for this - I’ll have a rethink
