### ISSUE TITLE
Browser preview replaces input attribute type value "reset" with window.location.host

### ISSUE THREAD

**Issue by stenito** [bdkjones/CodeKit#627]
**Quick, short summary:**
Chrome / Safari / FF preview replaces input attribute type value "reset" with window.location.host  **when an external server is used**

**Expected results:**
input type="reset" should stay "reset" 👍 

**Actual results:**
Chrome / Safari / FF preview replaces input attribute type value "reset" with window.location.host  **when an external server is used**
When surfing to the standard codekit preview URL the issue is there.
When surfing to the external server URL directly on :5757 the issue is there.
When surfing to the external server URL directly on its standard ports, there is no issue.
Removing or using the ckcachecontrol variable does not change the outcome.

Screenshot from VSCode
<img width="373" alt="Screenshot 2020-09-22 at 11 22 42" src="https://user-images.githubusercontent.com/13723043/93865047-0bce1200-fcc6-11ea-95fd-780b4612504d.png">

Screenshot from Chrome Dev tools
<img width="321" alt="Screenshot 2020-09-22 at 11 18 37" src="https://user-images.githubusercontent.com/13723043/93864670-85193500-fcc5-11ea-8183-e46d4996ac8d.png">

**Your configuration (any details about your system that you think might be relevant)**
OSX Catalina, Chrome Version 85.0.4183.102 (Official Build) (64-bit), Safari, FF

**Comment by bdkjones** [comment]
What’s the external server address you’ve entered in CodeKit’s project settings?

-Bryan

**Comment by stenito** [comment]
It’s http://reset/

Steven

**Comment by stenito** [comment]
:) I see... :)

Steven

**Comment by bdkjones** [comment]
Yep. There’s your problem. Use a valid, fully-formed URI as it would appear on the Internet. I recommend reset.site or reset.test. (Reset.dev is an option, but requires TLS in Chrome.)

For speed, CodeKit does not parse the page to perform replacements. It simply swaps the proxy server address for all instances of the origin server address. Hence, all instances of “reset” are being replaced on your page.

-Bryan
