### ISSUE TITLE
Global pause/resume shortcut not working after latest update.

### ISSUE THREAD

**Issue by stenito** [bdkjones/CodeKit#630]
**Quick, short summary:**
Global pause/resume shortcut not working after latest update.

**Expected results:**
Global pause/resume shortcut should be working after latest update :)

**Actual results:**
I updated to 3.13 33056 and since then the global pause/resume shortcut does not work anymore.
I tried restarting, refreshing the keyboard combination, in all combinations and orders. Doesn't work. 

*Update*
File watching is working, but the beep, purple banner, notifications or bringing codekit tot the front are not working.

**Comment by bdkjones** [comment]
Goddammit. Believe it or not, the actual *pausing* isn't broken; just the UI that tells you about it. The reason is a missing `dynamic` keyword. Version 3.13.1 will be live in a few minutes with the fix. Thanks!
