### ISSUE TITLE
3.13.3 crash while adding / loading projects

### ISSUE THREAD

**Issue by jmanzano2** [bdkjones/CodeKit#634]
**Quick, short summary:**
I've been using Codekit for different projects. Today I updated the software from 3.12.5 to 3.13.3 but the new version crashes on startup as it tries to load the projects.

**Exact steps to reproduce:**
I've tried the following:

* Restart the computer
* Unistalled the app and installed the 3.13.3 again: it crashes
* Unistalled the app and installed the 3.12.5: it asks to delete app data created by new version, press OK and add a new project. It works fine.
* Uninstalled version 3.12.5 and installed 3.13.3: as there are no projects, it starts perfectly; as soon as I try to add a project, it crashes. I tried to add the following type of projects, all of them with the same results:
- Project created with 3.12.5 with config.codekit
- Project created with 3.12.5 but without config.codekit and sass-cache
- Very simple new project, never used with Codekit
* Start 3.13.3 in safe mode (control key + open). It starts but as soon as I try to add a project, it crashes

**Your configuration (any details about your system that you think might be relevant)**
MacOs 10.14 Mojave

**Comment by bdkjones** [comment]
I’m betting you’re running an old release of Mojave. Update your Mac to at least 10.14.6 and you’ll be all set. Then, keep your Mac up to date! 

-Bryan

**Comment by jmanzano2** [comment]
That was it. 

Thanks a lot!!
