### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by mike85** [bdkjones/CodeKit#635]
Will the new M1 Macs support CodeKit?

**Comment by bdkjones** [comment]
Yes. Version 3.13.3 runs through Rosetta and is actually slightly faster than it is running natively on x86. Version 3.14 will be out in a couple weeks and that build will be fully native on `arm64`.

**Comment by mike85** [comment]
> Yes. Version 3.13.3 runs through Rosetta and is actually slightly faster than it is running natively on x86. Version 3.14 will be out in a couple weeks and that build will be fully native on `arm64`.

Thanks, for the detailed answer. Looking forward to the native version. 🎉

**Comment by bdkjones** [comment]
CodeKit uses 20 third-party libraries/frameworks/binaries that had to be rebuilt for Apple Silicon. Some of those are massive, complex libraries (looking at you, OpenSSL) that produced nothing but headaches. I also needed an M1 Mac to test on, which I now have. My development builds are now fully native and running well; I anticipate a release sometime in the first half of December. 

This is also a large feature release. New things coming.
