### ISSUE TITLE
Plain CSS minification using Libsass instead of Dart to syntax check

### ISSUE THREAD

**Issue by winstongrace** [bdkjones/CodeKit#637]
When I process plain CSS files to output minified versions, I understand from an older issue here that you treat them as SCSS and they get processed via Libsass.

Can they be processed via Dart instead? I'm getting syntax issues that are not present when processing as `.scss` using the Dart compiler.

**Comment by bdkjones** [comment]
The next update removes the Sass compiler from the equation completely and, instead, processes plain CSS files with csso.
