### ISSUE TITLE
App won't start on new M1 Mac

### ISSUE THREAD

**Issue by tyssen** [bdkjones/CodeKit#644]
**Quick, short summary:**
I've downloaded version 3.14.2 from the website and when I try to run it, the app icon bounces in the dock for quite a while. Eventually, it stops bouncing but it doesn't have the black dot underneath it to indicate that it's active, and clicking on it does nothing. Right-clicking says _Application not responding_ and the only option is to force quit.

**Expected results:**
App starts.

**Actual results:**
See above.

**Exact steps to reproduce:**
Launch the app either from Spotlight, Alfred, or clicking on the app icon.

**Your configuration (any details about your system that you think might be relevant)**
2020 M1 Mac running 11.2.1, 16Gb memory, Codekit 3.14.2.

**Comment by tyssen** [comment]
I've tried launching the app with the option key held down, even though there have been no projects been added on this Mac yet, but it didn't change the behaviour.

**Comment by bdkjones** [comment]
HI @tyssen. Nobody else is reporting this issue. Do you have security software or antivirus apps that are running? Did you unzip the download with some third-party utility instead of the archive utility built into macOS? 

Launch Terminal, type `cd /Applications`, and hit return.

Then, run this command: `spctl --verbose=4 --assess --type execute CodeKit.app`

Let me know what you get.

**Comment by tyssen** [comment]
No antivirus, I used the native Apple archive utility.

Running the above command, I get:

> objc[36526]: Class SPExecutionPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class AppWrapper is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class AppWrapperPolicyResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class AppWrapperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class SPLog is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class MIS is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class SPExecutionHistoryItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class SPExecutionPolicyItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class SPDeveloperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[36526]: Class GKScanResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
CodeKit.app: accepted
source=Notarized Developer ID

**Comment by bdkjones** [comment]
Well, the code signature is intact. The next things to try:

1) Reboot your Mac.

2) Disconnect from the Internet entirely and then try opening the app. (macOS phones home to Apple to verify the notarization status of every app you launch. A couple months ago, that process got screwed up because Apple's servers went down and that left apps unable to launch.)

3) List all the apps you have running on your machine.

**Comment by tyssen** [comment]
A reboot did the trick. What didn't happen when I was trying to open it before was the popup that says "Codekit is an application downloaded from the Internet. Are you sure you want to open it?"

**Comment by bdkjones** [comment]
Sigh. Good 'ol Apple Engineering. 

The old guard that actually built macOS has retired and now we have the B-squad who grew up on jQuery trying to write operating systems. Combine that with stupid popups that everyone just clicks "yes" on without even reading—seriously, Apple, where the fuck else would an app come from in 2021? I didn't install it from a goddamn floppy—and you get this sort of nonsense, where a bunch of people and third party developers waste time dealing with Apple's shitty, declining software quality.

Glad you got it sorted.
