### ISSUE TITLE
Codekit always resets 'Minify the output with CSSO' to Never. 

### ISSUE THREAD

**Issue by samuelfarrell** [bdkjones/CodeKit#646]
**Quick, short summary:**

Set 'Minify the Ouput With CSSO' does not remember its value.

**Expected results:**

It should remember its value. 

**Actual results:**

Always reverts back to 'Never'. 

**Exact steps to reproduce:**

Set 'Minify the Ouput With CSSO' to anything but 'Never', and watch it revert back.

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
I’m not able to reproduce this over here. Which language are you using? Where are you setting the option? Please attach a small demo project that shows the issue with exact steps to reproduce.

-Bryan

**Comment by bdkjones** [comment]
I tested Sass, Less, Stylus, and CSS. They're all working correctly over here. Are you maybe switching branches in Git to a branch with different settings? Or maybe you're changing the option in Project Settings and forgetting that doing so will instantly change it on ALL files of that language in the Project?
