### ISSUE TITLE
Faster way to toggle prod/dev environment

### ISSUE THREAD

**Issue by andremacola** [bdkjones/CodeKit#648]
1 - It would be nice if we can determine the output style based on the environment. For example: compressed and autoprefixed sass if in production mode.

2 - Maybe two compile buttons, one for dev, another for production. In some projects, like wordpress or legacy websites, most developers do not use the build process and swap between production and development environment requires to much clicks: Go to settings > general > open select > back to editor and save or back to the file in codekit and compile.

**Comment by bdkjones** [comment]
Output Style can generally just stay on “compressed” because you’ll use source maps to see the original code in your browser; there’s no need to have uncompressed output.

**Comment by bdkjones** [comment]
<img width="828" alt="Screen Shot 2021-03-17 at 19 00 47" src="https://user-images.githubusercontent.com/926566/111570891-f9a7ca80-8762-11eb-825c-106276bdadcb.png">

Added for the next update.
