### ISSUE TITLE
Purge Issue

### ISSUE THREAD

**Issue by muhammedjenos** [bdkjones/CodeKit#649]
Codekit 3.14.3. Set up a new tailwind project. deleted all boilerplate pages and created a very simple page. exported to production and noticed a lot more classes in the final css (apart from the reset styles) than required. around 29KB. Set up the same project without codekit and just 16KB CSS in production. Any setting I missed to properly purge the unused css?

Also did not modified the tailwind config in any form.

**Comment by muhammedjenos** [comment]
I further notice, since I have official tailwind forms installed but not used, its still adding the entire forms css without purging at the end. Is it expected outcome?

**Comment by bdkjones** [comment]
Add: `source/` to the beginning of each entry in the PurgeCSS Content list in Project Settings.

Long story, but PurgeCSS is scanning the node_modules folder, which is where it's finding all those classes. I'm working on getting PurgeCSS to properly support skipping folders again.
