### ISSUE TITLE
fullcalendar.js Bundling failed with this error: Unexpected token

### ISSUE THREAD

**Issue by Serifenlos** [bdkjones/CodeKit#651]
**Quick, short summary:**
I want to bundle the library of fullcalendar as descript here: https://fullcalendar.io/docs/initialize-es6. But while compiling my js-file, Codekit throws me an error "Bundling failed with this error: Unexpected token (Note that you need plugins to import files that are not JavaScript)". 
Unfortunately, I don't understand exactly where to look for the error. Why can't it find the Javascript file? Do I need an upstream Babel translation here? - Sorry, but can you please help me? 

My test-project looks like this. All options are default.  
thanks in advance,
Ciao Simon.
[fullCalendar_testInstall.zip](https://github.com/bdkjones/CodeKit/files/6135875/fullCalendar_testInstall.zip)

![Bildschirmfoto 2021-03-14 um 01 38 07](https://user-images.githubusercontent.com/1432856/111053667-f7452800-8465-11eb-91fc-7ab7b81dda83.png)
![Bildschirmfoto 2021-03-14 um 01 38 11](https://user-images.githubusercontent.com/1432856/111053670-fc09dc00-8465-11eb-9b5e-37b2f58499fd.png)

**Comment by bdkjones** [comment]
The reason this is failing is that the JS project you're building tries to import CSS files into the JS, for which CodeKit does not currently have built-in support.

What you CAN do is follow the example here: https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/rollup-scheduler

Install the necessary packages in your project (including rollup, etc) and then use a Hook (codekitapp.com/helps/hooks/) to run the bundler when that file is saved. You would turn OFF bundling in CodeKit's UI and basically replace the built-in bundling with your Hook, which will run the local version of Rollup you install and configure in your project. That way, you can tell Rollup to handle the CSS imports.

**Comment by Serifenlos** [comment]
After I installed all the dependencies, I ended with setting the Hook like this 
`$CK_PROJECT_ROOT/node_modules/.bin/rollup -c --silent --input "$CK_INPUT_PATH" --output.file "$CK_OUTPUT_PATH"`
Now it works - Thanks a lot.

**Comment by bdkjones** [comment]
@serifenlos glad you got it sorted. That's exactly the sort of edge-case Hooks are designed to tackle.
