### ISSUE TITLE
Tailwind intellisense fail after installing plugin with error

### ISSUE THREAD

**Issue by muhammedjenos** [bdkjones/CodeKit#652]
Installed @tailwindcsss/forms plugin via codekit packages area.

Added it in the plugins area in tailwind.config.js as:
`plugins: [require("@tailwindcss/forms")]`
 
when save, tailwind intellisense bring up this warning in vscode:

`Tailwind CSS: Cannot find module '@tailwindcss/forms' Require stack: -`

The plugin itself work after that, but intellisense stopped working from there onwards.

Any help?

**Comment by bdkjones** [comment]
I’m not sure what you mean by “intellisense”. If the project compiles correctly, CodeKit is not the cause of this. Sounds like a misconfiguration in VSCode maybe?

**Comment by muhammedjenos** [comment]
You maybe right. The issue disappeared today after restarting Vscode. Wasted my 4 hours last night trying to figure out what was wrong. Will report back if it appears again. Thanks 🙏🏼
