### ISSUE TITLE
[ACCESSIBILITY] Dark mode issue (Carets)

### ISSUE THREAD

**Issue by JayHoltslander** [bdkjones/CodeKit#653]
In dark mode the carets to expand and collapse navigation aren't high enough contrast.

**Current:**
![](https://i.imgur.com/HGmj51F.jpeg)

**Desired:**
![](https://i.imgur.com/AyNQrOc.jpg)

**Comment by bdkjones** [comment]
I'm guessing your version of macOS is out of date? This is not an issue on Big Sur at all and on Catalina it should disappear if you restart the app after changing the dark mode setting.

It's definitely an issue to address for outdated macOS versions, but it was lower priority than shipping other stuff at the current time.

**Comment by JayHoltslander** [comment]
Ah, yes. Work machine.

[EDIT] Clarifying, this was on Mojave 10.14.6

**Comment by bdkjones** [comment]
This is resolved in 3.15.....on Big Sur. I did not test Mojave.
