### ISSUE TITLE
Less PostCss unhelpful console errors

### ISSUE THREAD

**Issue by bnjmnrsh** [bdkjones/CodeKit#657]
**Quick, short summary:**

**Expected results:**
Run all the things

**Actual results:**

> /assets/css/app.min.less

>Compiled successfully.
>PostCSS tried to run this chain of plugins:
>1. postcss-csso
>But there were errors:
>SyntaxError: HyphenMinus is expected

**Exact steps to reproduce:**
Run older bootstrap project 

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

Basically, I *think* postCSS is complaining that another character other than a `HYPEN-MINUS` has been used in this `less` project. Unfortunately, there isn't any line number or file name associated with the issue, so I'm scratching my head trying to find the bug. 

Bryan, I hate scratching my head -- got better things to do, like play with my cats, mow the lawn, etc. But here I am procrastinating thinking about this but. So ... thank you?

**Comment by bdkjones** [comment]
The issue here is that the Less compiler is very lax with syntax while CSSO's parser is not.

Line/Column information isn't displayed because the error has occurred in the *compiled* CSS and the CSSO parser can't use the source map to tell you which line in your Less file produced the CSS that's failing.

To figure it out, select a large chunk of your Less file and comment it out. Keep going until the error goes away. Then uncomment segments of the file until you track down the line causing the error. I would assume the issue is probably something like you used — instead of -, somewhere. Both would appear the same in a mono-spaced font.

**Comment by bnjmnrsh** [comment]
Wow, its early in the UK. R U CLONE?

Ok, will start that approach pattern. 

Im confused though, I now have the output style as "Compressed", and all the postCSS options off, and yet Im still getting the error, and the file _isn't not_ compressed. Doesn't LESS have a native compressed output like SASS, or do we use CSSO for all the things?

**Comment by bdkjones** [comment]
The old less optimizer (less-plugin-clean-css) had a bunch of security issues reported by npm, so now CSSO is used whenever you either enable CSSO or choose the "compressed" option for Less files.

CSSO is much stricter in parsing, but it doesn't allow the Russians to take over your computer so, you know, tradeoffs.

**Comment by bnjmnrsh** [comment]
Nice one, thanks for the quick response!

**Comment by bnjmnrsh** [comment]
the culprit:

```
/* ============================================*/
/* Bizarre Safari 4-5 hack
/* https://jeffclayton.wordpress.com/2014/07/22/the-chrome-and-safari-css-hacks-collection/
   ============================================ */

@media screen and (-webkit-min-device-pixel-ratio: 0) {
  /* Safari only override */
  _:window-inactive, body:nth-last-child(n0) aside#sidebar.span4 {
    width: 28%;
  }

  _:window-inactive, body:nth-last-child(n0) h3.bannerR,
  _:window-inactive, body:nth-last-child(n0) .bannerR .widget-inner > h3 {
    width: 250px;
    right: -5px !important;
  }
}
```

Obvs I've not touched this codebase in a while!
