### ISSUE TITLE
[Mangler] Exceptions doesn't works

### ISSUE THREAD

**Issue by Menaquinone** [bdkjones/CodeKit#658]
**Quick, short summary:**
When i add an exceptions on Terser, it does not take it into account

**Expected results:**
![Capture d’écran 2021-05-14 à 12 11 06](https://user-images.githubusercontent.com/5324582/118256608-fce2dc80-b4ad-11eb-801d-9e321a77bdd6.jpg)

**Actual results:**
![Capture d’écran 2021-05-14 à 12 10 48](https://user-images.githubusercontent.com/5324582/118256629-00766380-b4ae-11eb-8466-16a4a0d4248e.jpg)

**Exact steps to reproduce:**
![Capture d’écran 2021-05-14 à 12 21 22](https://user-images.githubusercontent.com/5324582/118257539-0a4c9680-b4af-11eb-906e-b89dcbd1dfdd.jpg)
![Capture d’écran 2021-05-14 à 12 15 41](https://user-images.githubusercontent.com/5324582/118256750-20a62280-b4ae-11eb-875c-9cd0fc4d3b74.jpg)

**Comment by bdkjones** [comment]
Ah, it looks like Terser changed the syntax for this option. Fixed for the next release. Thanks!

**Comment by Menaquinone** [comment]
You'r welcome
