### ISSUE TITLE
Emit a @charset when not requested

### ISSUE THREAD

**Issue by picasso** [bdkjones/CodeKit#659]
**Quick, short summary:**
When compiling a `scss` file, a charset is added, although the option **"Emit a @charset for non-ASCII text"** is switched off. This only happens when the **Dart Sass** compiler is selected. This does not happen when **Libsass** is selected.

**Expected results:**
```
blockquote::before {
  content: "\201C"; }
```
**Actual results:**
```
@charset "UTF-8";
blockquote::before {
  content: "“";
}
```
**Exact steps to reproduce:**
compile file with the following:
```
blockquote::before {
	content: "\201C";
}
```
**Your configuration (any details about your system that you think might be relevant)**
Codekit 3.14.4
Sass 1.32.8
Libsass 3.6.4

**Comment by bdkjones** [comment]
Please try compiling your file using Dart Sass at the command line without the charset option. See what output you get.

**Comment by finderski** [comment]
I can confirm, I'm having the issue. I have done as requested and compiled using the CLI with the --no-charset option and dart compiled without adding the @charset stuff.

However, using CodeKit it always adds it, regardless whether the Emit a @charset for non-ASCII text is checked or not.

The version of sass I'm using with the CLI is 1.34.1

**Comment by bdkjones** [comment]
Ah, okay. I see what the issue is and the issue is that I'm a moron.

Fixed for the next update. Should be out this week.

**Comment by finderski** [comment]
LOL - Awesome. Thanks. :)

**Comment by picasso** [comment]
Thanks
