### ISSUE TITLE
Emit @charset when not requested

### ISSUE THREAD

**Issue by finderski** [bdkjones/CodeKit#661]
This was originally opened under this ticket: https://github.com/bdkjones/CodeKit/issues/659?_pjax=%23repo-content-pjax-container

That ticket has since been closed, but I'm still having this issue. I keep checking for an updated version of CodeKit, but it always tells me my version is the latest version. Just wondering if/when this will be corrected?

Thanks.

**Quick, short summary:**
When compiling with Dart, @charset "UTF-8" is being emitted, even when it is expressly disabled/turned off.

**Expected results:**
I should not get an @charset "UTF-8" appended to my CSS file.

**Actual results:**
I'm getting that @charset "UTF-8" appended to the beginning of my CSS output file.

**Exact steps to reproduce:**

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Ah, yea, I need to publish that. I was holding for a new feature but that’s taking longer than planned. I’ll push an update.

**Comment by bdkjones** [comment]
This is resolved in 3.15. Thanks again!
