### ISSUE TITLE
Unable to Use Tailwind in 'JIT' Mode 

### ISSUE THREAD

**Issue by iocouto** [bdkjones/CodeKit#664]
**Quick, short summary:**
The next version of Tailwind will be based on their **['just-in-time' compiler](https://tailwindcss.com/docs/just-in-time-mode)**, which is currently in 'preview' mode. It adds *a lot* of new features to Tailwind, simplifies its configuration, and makes extending and customising it easier. We should be able to start using the JIT compiler right now - and Tailwind's new features - by putting a `mode: 'jit'` entry in our 'tailwind.config.js' file, as [described in their docs](https://tailwindcss.com/docs/just-in-time-mode).

**Expected results:**
We should be able to see faster compilation, and have the ability to use Tailwind's new features, such as 'arbitrary values', 'color opacity shorthand', and thorough 'pseudo-class support'. 

**Actual results:**
Codekit seems to fail to compile, and produces a stylesheet that only has the 'base' styles from Tailwind - not even the built-in utility styles get compiled.

**Exact steps to reproduce:**
1. Start a new Tailwind project.
2. add `mode: 'jit'` to the top of your 'tailwind.config.js' file, as suggested in their docs
3. create a new html file - e.g., 'test.html'. Add some basic html skeleton code to it.
4. create a couple of html elements, and start adding Tailwind classes to them.
5. Preview

It's probably important to get CodeKit to work nicely with the new JIT compiler, as the Tailwind folks have already announced widely that this is going to be the way forward: the JIT compiler is the cornerstone of the upcoming Tailwind 3.0.

**Comment by bdkjones** [comment]
Yep. Support for JIT is included in the next update, which will be out this week. Shooting for Monday.

**Comment by bdkjones** [comment]
JIT mode is now available in CodeKit 3.15, which just went live. Sorry for the delay. The GM release of Xcode screwed up something that prevented Swift-NIO from building: https://github.com/apple/swift-nio/issues/1955

**Comment by bengoshow** [comment]
I'm still seeing this issue in CodeKit 3.15. I'm on macOS Catalina 10.15.7, and I'm unable to upgrade either the OS or XCode to v13 (currently 12.4). Is there any other workaround to enable 'JIT' mode?

**Comment by bdkjones** [comment]
@bengoshow what does your tailwind config file look like?

**Comment by bengoshow** [comment]
`module.exports = {
  mode: 'jit',
};
`
For testing, I've reduced it down to just this line. If I comment out `mode:'jit'` CodeKit compiles and includes tailwind's base, components and utilities. Otherwise, with 'jit' enabled it only includes base styles.

**Comment by bdkjones** [comment]
And what does your HTML look like? Which tailwind utility classes are you using in the HTML that aren’t being included when tailwind compiles?

-Bryan

**Comment by bengoshow** [comment]
More than this, but here's a sample. None of these classes are being included with JIT. 

This started because I was trying to figure out how to style pseudo classes in Tailwind, which apparently is only supported with JIT.

```
<div class="cta 
      bg-cover 
      bg-center 
      w-4/5 
      mx-auto 
      my-20 
      p-20
      before:absolute 
      before:inset-0
      before:z-[-10]
      before:block
      before:w-full 
      before:h-full
      before:bg-gradient-to-r 
      before:from-green-400 
      before:to-blue-500" style="background-image: url('https://source.unsplash.com/random')">
        <div class="container mx-auto">
          <div class="max-w-md mx-auto">
            <h1 class="text-white">This is a CTA</h1>
            <p class="text-white">This is the CTA message</p>
            <a class="button">Click</a>
          </div>
        </div>
      </div>
    </div>
```

**Comment by bdkjones** [comment]
Zip the project and send me a link to download it.

**Comment by bengoshow** [comment]
brand new install from CodeKit worked fine, then added `mode:'jit'`
https://github.com/bengoshow/tailwind-jit
