### ISSUE TITLE
File count in CodeKit isn't updating when new files are added

### ISSUE THREAD

**Issue by lolbat** [bdkjones/CodeKit#666]
**Quick, short summary:**
When I replace files in a directory that is part of a CodeKit project the app sometimes doesn't correctly acknowledge the files.

**Expected results:**
When I drag and drop new files into a project directory and replace the old ones CodeKit should know they are there and be able to process them correctly.

**Actual results:**
Codekit lists the files but has an inaccurate count of the number of files in the directory. When you go to process them it attempts to do so but gives the following error for each file

```
This file could not be processed because critical information about it is missing. Refresh the containing Project in CodeKit to update that information and try again.
```

The first image below is what the files section displays after I quit the app and it rereads the project files.

The second image is what CodeKit displays after I replace the files in the directory

**Exact steps to reproduce:**
Up until today this hasn't been an issue. It now does this every time I try to replace files in a directory.

**Your configuration (any details about your system that you think might be relevant)**

<img width="882" alt="Screen Shot 2021-09-16 at 2 00 46 PM" src="https://user-images.githubusercontent.com/4564571/133678160-fac3e6da-5a54-485a-a59e-bc8e59a750c5.png">

<img width="896" alt="Screen Shot 2021-09-16 at 2 00 06 PM" src="https://user-images.githubusercontent.com/4564571/133678163-1395b169-4e0e-4f46-adbd-6f9bdad4190c.png">

**Comment by bdkjones** [comment]
Where is the project folder? On your local disk, or an external/network drive? Does refreshing the Project not solve the issue? Is any other service interacting with these files (Dropbox, Sugarsync, iCloud Drive, etc.)?

**Comment by lolbat** [comment]
It is on my local drive. Nothing else is interacting with it. I will try to refresh next time it give me the error.

**Comment by bdkjones** [comment]
Which version of CodeKit and which version of macOS are you running?

-Bryan

**Comment by lolbat** [comment]
Mac OS 11.6 CodeKit 3.14.4

**Comment by bdkjones** [comment]
Did you try resetting the app by holding the Option key at launch?

**Comment by lolbat** [comment]
No I did not. I will be getting back to that project next week and I will try that if it happens again. 

I think the source of the issue may be the number of times those files change. Over the course of a week I think I updated them about a dozen times due to changes in the structure of the JSON objects as I was adding features.

**Comment by lolbat** [comment]
I have not yet been able to replicate this so I will close it
