### ISSUE TITLE
Dark mode group name readability

### ISSUE THREAD

**Issue by stenito** [bdkjones/CodeKit#667]
<img width="1008" alt="Screen Shot 2021-09-18 at 08 31 55" src="https://user-images.githubusercontent.com/13723043/133879044-004f70bf-5956-46ff-a6ea-c971143e8d7f.png">

**Dark mode group name focus has light background. Text not legible.  On hover, show/hide is dark text. Can't see it, not even if i wear my night vision goggles!!!**

**Dark background when editing, light text when hovering :)**

**See screenshot (edit bg only)**

**Big Sur 11.5.2**

**Comment by bdkjones** [comment]
Is your entire Mac running in dark mode, or just CodeKit?

**Comment by stenito** [comment]
It is entirely dark. 

// the dark side is omni-present

On 18 Sep 2021, at 09:06, Bryan Jones ***@***.***> wrote:


Is your entire Mac running in dark mode, or just CodeKit?

**Comment by bdkjones** [comment]
<img width="478" alt="Screen Shot 2022-05-03 at 21 22 22" src="https://user-images.githubusercontent.com/926566/166622883-23fe33e3-2d04-4d35-8005-530ce3e73bad.png">

This appears to be a Big Sur thing. I can't reproduce it on Monterrey. That's a standard system textField, so I'll chalk this one up to good ol' Apple Engineering.
