### ISSUE TITLE
File extension .mjs causes MIME type error in preview server

### ISSUE THREAD

**Issue by danpoynor** [bdkjones/CodeKit#671]
**Quick, short summary:**
CodeKit doesn't recognize the `.mjs` file extension as a JavaScript module file, which appears as an error in browser console when using the CodeKit preview server.

**Expected results:**
The preview server should recognize .mjs files as JavaScript and send the appropriate headers (`Content-Type: application/javascript` instead of `text/plain` I believe).

**Actual results:**
Error appears in Chrome browser console:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."

**Exact steps to reproduce:**
Create a JavaScript module file with the .mjs file extension, import it into another js file which is loaded into a web page then use the preview server to see error in browser console. Note changing the file extension to .js in the example repo works.

**A link to download a simplified project or file that shows the issue:**
https://github.com/danpoynor/es6-module-example-with-timeout

**Your configuration (any details about your system that you think might be relevant)**
Using most recent version 3.15 build 34214.

**Comment by danpoynor** [comment]
Noticed I can use MAMP as an external server and added `AddType application/javascript      .mjs` there in the virtual host field.

**Comment by johnozbay** [comment]
@danpoynor Thanks for writing about this! Saved me a lot of head-scratching time. 🙏🏻

Pinging @bdkjones, as I ran into the same problem just now and I'll probably end up setting up an external server just for this one mjs file. It would be ideal if CodeKit's server used `application/javascript`. 

— p.s. Seizing this opportunity to say thanks again for everything Bryan! — missing the unmuzzled podcast.

**Comment by bdkjones** [comment]
Dammit. I KNEW there was something I forgot to put in the last update. CodeKit uses Apache's Mime type list (although I haven't updated it in several years, at least). You should be able to hack in a fix by doing this:

1. Quit CodeKit.
2. Navigate to CodeKit in /Applications, right-click, and choose "Show Package Contents". 
3. Find the Resources folder and then mimes.plist
4. Add an entry for `mjs` following the existing format.

**Comment by johnozbay** [comment]
That worked wonders @bdkjones! Many million thanks for the hack! ✌🏻
