### ISSUE TITLE
[Bug] tailwind jit: PurgeCSS Safelist Entries are ignored

### ISSUE THREAD

**Issue by derby** [bdkjones/CodeKit#675]
When using tailwinds JIT mode, the Safe List Entries, set in the Codekit UI (Project Settings > Tools > PurgeCSS > Safe List), are ignored, so that the selectors are not inside the output file.

If I deactivate JIT, the safelist selectors are inside the output file.

When I specify a safelist inside the tailwind.config.js, it works:
```
purge: {
  safelist: [
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
  ]
},
```
But here I cannot use RegEx.

I think it's a bug, because it does not make sense, that the safelist set in Codekit UI is ignored in JIT mode.

![codekit-purgecss-safelist](https://user-images.githubusercontent.com/245440/142611651-10cb8495-7c3f-4853-91bc-cdac1be07c81.png)

**Comment by bdkjones** [comment]
PurgeCSS is not used at all in JIT mode. This is documented on the Tailwind site.

If you want the same functionality, the only way to achieve it is to put an html file somewhere in your project that lists the classes you want to keep. Regex is not supported, so the classes must be listed exactly.

**Comment by derby** [comment]
Thanks for your answer. I don't understand why the safelist defined in the tailwind config file works with jit although it is not supported. It gives the impression that it should be possible to get your codekit purgeCSS settings also work with jit, don't you think?

**Comment by bdkjones** [comment]
That's a valid point, but I'm not sure what the actual answer is. JIT mode is still experimental and hasn't been officially released. The Internet is full of dated documentation about it and I'm just going on what I found while googling another person who had this issue (without CodeKit) earlier. I suppose we'll have to see how JIT shakes out when it finally comes out of beta.

**Comment by derby** [comment]
Right, that's also a good point. So I will just deal with workarounds as long as jit is beta. Thanks!

**Comment by derby** [comment]
Hi again, now tailwind version 3 has been released. PurgeCSS ist not used any more because it is based on JIT. The **purge** option in the tailwind.config is has been renamed to **content**  ans the **safelist** option has been moved from purge/ content to the root of the config object. So your options inside the Codekit purgeCSS settings seem to be obsolete, will you integrate a tailwind setting where you can configure the safelist?

**Comment by bdkjones** [comment]
Yep. Tailwind 3 has been out for like 48 hours. 

-Bryan

**Comment by derby** [comment]
🤣 you are right! I do not want to annoy you, Codekit is great!
I am asking because we use it in a current project and I would like to know if there will be settings in codekit to configure the safelist in regex, e.g. Settings -> Frameworks -> Tailwind -> Safelist or whatever. If you plan such an option we do not have to spend more time on custom workarounds.
