### ISSUE TITLE
Compile CSS on HTML/Twig file change

### ISSUE THREAD

**Issue by hassanmah** [bdkjones/CodeKit#677]
**Quick, short summary:**
I want the CSS to compile when I update a HTML/Twig file. I am using Tailwind in JIT mode.

**Expected results:**
Whenever I change and save a HTML/Twig file, the CSS should compile automatically

**Actual results:**
CSS compiles only on change to CSS files, not HTML/Twig.

**Comment by bdkjones** [comment]
Are you using Tailwind in JIT mode?

If not, have you adding the Twig file extension to the list of filetypes to be scanned in PurgeCSS's settings?

**Comment by hassanmah** [comment]
@bdkjones I am using it JIT mode

**Comment by RyanHelmn** [comment]
Also ran into a similar issue - would be useful to have the css processed when saving HTML files. Haven't found a workaround just yet 😀

**Comment by bdkjones** [comment]
Something isn't configured correctly in your project. Html file saves should trigger a recompile of the CSS file when Tailwind is in JIT mode.

If you want to compile when *.twig files are saved, you need to add that entry to Project Settings > PurgeCSS, in the "content" list. Alternately, you can manually set the "content" array in the tailwind config file and CodeKit won't automatically populate that array.

**Comment by RyanHelmn** [comment]
> Something isn't configured correctly in your project. Html file saves should trigger a recompile of the CSS file when Tailwind is in JIT mode.
> 
> If you want to compile when *.twig files are saved, you need to add that entry to Project Settings > PurgeCSS, in the "content" list. Alternately, you can manually set the "content" array in the tailwind config file and CodeKit won't automatically populate that array.

Hmmm I'll deffo double check everything! I just downloaded the app today as I'm considering switching over from PrePros (so far so good btw!) so this is a fresh project/install.

**Comment by RyanHelmn** [comment]
@bdkjones sorry just to add - this is with Tailwind 3, so I guess JIT is out of the box now. Does that make any difference? Might not be related to the OG issue, happy to create another one to move it to an appropriate thread.

**Comment by bdkjones** [comment]
What does your tailwind config file look like? Did you create the 3.0 project with CodeKit?

**Comment by RyanHelmn** [comment]
> What does your tailwind config file look like? Did you create the 3.0 project with CodeKit?
> […](#)
> On Dec 28, 2021, at 17:14, Ryan Helmn ***@***.***> wrote: ﻿ @bdkjones sorry just to add - this is with Tailwind 3, so I guess JIT is out of the box now. Does that make any difference? Might not be related to the OG issue, happy to create another one to move it to an appropriate thread. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Everything's the same, bar a couple of new fonts & typography plugin: [tailwind.config.js](https://gist.github.com/RyanHelmn/4ef24a33ab7c53a8b646d6a792b19a80)

& yeah the project was generated with CodeKit

**Comment by bdkjones** [comment]
Zip the project and send me a link to download it.

**Comment by RyanHelmn** [comment]
> Zip the project and send me a link to download it.

Here you go: [statics.zip](https://we.tl/t-iiV0NAf2aO)
Thanks!

**Comment by bdkjones** [comment]
Okay, I've narrowed down the cause of this and have released 3.16.1 to fix it. Update to that version and you should be all set.

**Comment by RyanHelmn** [comment]
Sorry for the delayed response, latest update works perfectly 😎 thanks

**Comment by hassanmah** [comment]
Can confirm works for me too
