### ISSUE TITLE
Semicolon classes from TailwindCSS (3.x) ignored by PurgeCSS

### ISSUE THREAD

**Issue by psntr** [bdkjones/CodeKit#683]
**Quick, short summary:**
I have an issue with the latest TailwindCSS and purgeCSS. Any class that contains a semicolon is ignored from purgeCSS.
**Expected results:**
Keep the semicolon class in the final build stylesheet.
**Actual results:**
All classes including a semicolon is removed from the build stylesheet.
**Exact steps to reproduce:**
1. Initiate a project with Tailwind as framework.
2. Enable purgeCSS
3. Switch environment from "Development" to "Production"
4. Build the project
5. Inspect the page, all semicolon classes are not in the final stylesheet.
**Your configuration (any details about your system that you think might be relevant)**
Codekit v.3.16.1

**Comment by bdkjones** [comment]
Don't use PurgeCSS with Tailwind 3.X; it's not necessary.

**Comment by psntr** [comment]
Good to know. Thank you for the answer!
