### ISSUE TITLE
Babel custom plugins – minify

### ISSUE THREAD

**Issue by psntr** [bdkjones/CodeKit#687]
**Quick, short summary:**
I'm trying to use some Minify Plugins, but CodeKit is unable to compile even if I have the `@babel/core` installed in my `node_modules` project folder and specified them in the "Custom Plugins List".
**Expected results:**
To have CodeKit compiling the code with the custom plugins
**Actual results:**
CodeKit seems to ignore the "Custom Plugins List".
**Exact steps to reproduce:**
1. Create new project
2. Create a new javascript file
3. Enable babel with "I'll Manually Select Which plugins to use, Below"
4. Install @babel/core
5. Add the plugin to use (babel-plugin-minify-dead-code-elimination) in the "Custom Plugins List"
6. Enable the "Minify Plugins" (Minify-Dead-Code-Elimination)
7. Compile

**Comment by bdkjones** [comment]
The plugin you've listed isn't part of `@babel/core`. You'd need to install it separately. That said, the Babel minification plugins shouldn't be used. Just flip on Terser instead—its entire mission is to minify JavaScript.

**Comment by bdkjones** [comment]
The minify plug-ins aren’t part of Babel Core. You’d need to install them separately. You should really use Terser to minify JS, however. It’s a lot more comprehensive than the Babel minifier.

-Bryan

**Comment by psntr** [comment]
Thank you! I was just confuse when i saw it part of the options in babel. But I'm currently using Terser as you suggested, no problems so far.
