### ISSUE TITLE
watch files outside project folder to trigger browser reload

### ISSUE THREAD

**Issue by pixeline** [bdkjones/CodeKit#689]
**Quick, short summary:**
I would like CodeKit to refresh the browser when I edit php files outside CodeKit's project folders.
A use case: a PHP basic MVC structure, using Tailwindcss for the frontend.
the backend framework sits in "web/app" with only the "index.php" in the public-visible folder.
CodeKit is using the "web/htdocs" folder as project root.
Here is my web application folder tree:

```ascii
web/
├─ app/
│  ├─ views/
│  │  ├─ header.php
│  │  ├─ body.php
│  │  ├─ footer.php
├─ public/
│  ├─ index.php
│  ├─ source/
│  │  ├─ css/
│  │  │  ├─ main.css
│  ├─ build/
│  │  ├─ css/
│  │  │  ├─ main.css

```

**Expected results:**

Editing files in the app/views folder should trigger browser reloading.

**Actual results:**
The folder being outside the CodeKit project, no changes in the View files trigger browser reloading.

As I type this, I realize I could have CodeKit watch the "web" folder instead, and adapt the files and folders output path. But it feels counterintuitive, as CodeKit is a (beautiful) frontend tool. Plus, I wonder if Tailwindcss will not get confused, and the "vendor / node_modules" folder not be misplaced. I'll try it.

**Comment by bdkjones** [comment]
Adding `web` as the project root and then setting the path to the `source` and `build` folders correctly in Project Settings is the way forward here.

It's extremely clear what CodeKit's watching right now: the folders you add. 

If we start mucking around with settings that allow people to watch arbitrary places, here's the way that goes for me:

1. Some idiot adds `/` as the folder to watch, accidentally or intentionally. 
2. Said idiot, best case, emails me to complain about the app being slow. Worst case, he complains on social media.
3. I have to summon the willpower to avoid replying, "No shit, Sherlock; you've told it to watch 4.7 billion files for changes."
4. Said idiot *INSISTS* that he's not watching external folders.
5. We exchange 17 more emails until I finally tell him to send me screenshots of all his Project Settings where, lo and behold, he's set the app to watch some stupid folder.
6. I go to jail. 

The easier solution is to use `web` as the project folder.

**Comment by pixeline** [comment]
Thank you for the zest of surrealism, you cracked me up :-)

I have made the change (I deleted and recreated a new CodeKit project, this time pointing to the `web/` folder as root). It seems tailwindcss does not like it.

In the NPM configuration ui, i have set 'public' as the place to store the `package.json` and `node_modules` folder.

On building the project I get this error: 
> "PostCSS failed. TailwindCSS is not installed in this project's node_modules folder. Install that package, then try compiling again."

I've checked and the `tailwindcss` folder sits correctly inside the `web/public/node_modules` folder.

```ascii
web/
├─ config.codekit3
├─ tailwind.config.js
├─ postcss.config.js
├─ app/
│  ├─ views/
│  │  ├─ header.php
│  │  ├─ body.php
│  │  ├─ footer.php
├─ public/
│  ├─ node_modules
│  ├─ index.php
│  ├─ source/
│  │  ├─ css/
│  │  │  ├─ main.css
│  ├─ build/
│  │  ├─ css/
│  │  │  ├─ main.css
``` 

What am I doing wrong?

**Comment by pixeline** [comment]
I realize you closed this topic. Will open a new issue and reference this one.

**Comment by pixeline** [comment]
Ok, so i've put the node_modules back into the root folder. 
The issue I now have is that CodeKit puts a copy of the `app` folder in the build folder. I don't find a way to tell CodeKit to process the php files (to trigger browser reloads, or to search for tailwindcss class names ) but not copy them in the build folder (which is only for static frontend assets). Shouldn't there be an additional option to "ignore file", "process/compile" and "copy only": "observe" or something like that?

**Comment by bdkjones** [comment]
CodeKit still refreshes browsers when “ignored” files change. And to get tailwind to scan the files for class names, you just need to make sure *.php is in the list under CSSO’s options in Project Settings. (Alternately, you can edit the tailwind config file to override CodeKit’s GUI and provide the list of files/locations to scan.)

**Comment by pixeline** [comment]
Ah, thank you for this, everything is clear now. 🙇
