### ISSUE TITLE
When changing npm setting "Package.json folder",  tailwindcss goes 404

### ISSUE THREAD

**Issue by pixeline** [bdkjones/CodeKit#690]
In the NPM configuration ui, i have set 'public' as the place to store the `package.json` and `node_modules` folder.

On building the project I get this error: 
> "PostCSS failed. TailwindCSS is not installed in this project's node_modules folder. Install that package, then try compiling again."

I've checked and the `tailwindcss` folder sits correctly inside the `web/public/node_modules` folder.

```ascii
web/
├─ config.codekit3
├─ tailwind.config.js
├─ postcss.config.js
├─ app/
│  ├─ views/
│  │  ├─ header.php
├─ public/
│  ├─ node_modules
│  ├─ index.php
│  ├─ source/
│  │  ├─ css/
│  │  │  ├─ main.css
│  ├─ build/
│  │  ├─ css/
│  │  │  ├─ main.css
``` 

Setting npm 'package.json folder' parameter back to "" then installing the packages fixes the issue.

Full discussion: https://github.com/bdkjones/CodeKit/issues/689

**Comment by bdkjones** [comment]
This is correct. The node_modules folder can only be located in the project’s root folder.

-Bryan

**Comment by pixeline** [comment]
I find the NPM settings interface to be a tad misleading on that particular item. It implies that it can be changed.
<img width="540" alt="Capture d’écran 2022-05-20 à 13 55 47" src="https://user-images.githubusercontent.com/393415/169523226-31fa8514-757a-4b4a-846e-5409109800ab.png">
