### ISSUE TITLE
Babel Transpile Error.

### ISSUE THREAD

**Issue by imtiazwazir** [bdkjones/CodeKit#692]
Babel transpile providing following error

`Uncaught ReferenceError: regeneratorRuntime is not defined.`

Created the new project also did not help.

**Comment by imtiazwazir** [comment]
Just for the record:

Did went through the step mentioned here https://codekitapp.com/help/babel/ and still the issue persist.

It is impossible to transpile with babel with async/await with codekit.

**Comment by bdkjones** [comment]
That is not correct. When you think it's the tooling, double-check your own code.

There's a whole section about async/await in CodeKit's docs.

**Comment by imtiazwazir** [comment]
Already checked the docs. 

also code does work without Babel Transpile and with Babel it always shows errors.

Just for your info Babel has removed many support for pollyfills  so you may want to look into it.

**Comment by bdkjones** [comment]
![image](https://user-images.githubusercontent.com/926566/173921495-89adaaef-b1b8-46d6-8247-25c0a8793ff0.jpeg)

**Comment by imtiazwazir** [comment]
Yes, I already mentioned here https://github.com/bdkjones/CodeKit/issues/692#issuecomment-1155918490, I went through that documentation and no success.
