### ISSUE TITLE
Sonoma GUI Issues

### ISSUE THREAD

**Issue by andyunleashed** [bdkjones/CodeKit#705]
**Quick, short summary:** The GUI is broken in Sonoma. I know you don't support betas by default but figured this might be a problem on release as well.

**Expected results:** GUI should not be broken.

**Actual results:** GUI is broken.

**Exact steps to reproduce:** Be on any beta for Sonoma.

**A link to download a simplified project or file that shows the issue:
![CleanShot 2023-07-27 at 19 19 20](https://github.com/bdkjones/CodeKit/assets/1426079/cd909c68-f07a-4941-8f45-67368f636cc6)

**Your configuration (any details about your system that you think might be relevant)** Sonoma Beta 4 (also an issue on previous betas)

**Comment by bdkjones** [comment]
Stuff like this always gets resolved before the GM. It's why I don't chase betas. On the bright side, at least beta 4 didn't brick your Mac!

**Comment by andyunleashed** [comment]
Still having this trouble now on the public release sadly :(

**Comment by andyunleashed** [comment]
Can confirm latest patch fixed this :)
