### ISSUE TITLE
[CodeKit 3.26] "Send feedback" switches to the browser but no link is opened

### ISSUE THREAD

**Issue by slackero** [bdkjones/CodeKit#708]
**Quick, short summary:**
Tried to send feedback using the built-in "Send feedback…" in the Help menu of CodeKit 3.26 — Build 34564 is not working as expected. It switches to my default browser but no link is opened. "Follow the developer…" works as expected.

**Expected results:**
I land on the feedback page somewhere in the internet.

**Actual results:**
No change in the browser

**Exact steps to reproduce:**
Select menu item "Send feedback…"

**Comment by bdkjones** [comment]
If that's failing, you don't have a default email client set with macOS. The menu item simply calls the system utility to compose a new email.

**Comment by slackero** [comment]
sophisticated, setting Apple Mail as default email client has worked
