### ISSUE TITLE
[CodeKit 3.26] Upgrading a project failes

### ISSUE THREAD

**Issue by slackero** [bdkjones/CodeKit#709]
**Quick, short summary:**
The auto update of a single existing projects in CodeKit fails, it refreshes and upgrades the `codekit.json` forever.

**Expected results:**
Update the related `codekit.json` and done.

**Actual results:**
Refreshes the CodeKit dashboard all the time as long I have this project active.

**Exact steps to reproduce:**
Auto-updated CodeKit to current version 3.26 — Build 34564.

Select the related project (it was inactive) it is updated and then agin and again in an endless loop. Hard to deactivate, but stops when the project is inactive. All other active projects work as expected.

To solve it I have tried to merge the `codekit.json` of an equal project with just slightly different changes (only paths and naming) to the as-exact-as-possible copy. This worked once. Deactivating the project and reactivating it again shows the same behavior.

Crazy fact — it always changes to the old `codekit.json`: `"creatorBuild" : "34513"` -> `"creatorBuild" : "34518"` but expected is `"creatorBuild" : "34564"` and all other changes I have made in the file are gone. I see this in the Git changes.

It seems CodeKit uses some file cache and this might be broken and is not cleared on removing the project from the list. Re-adding the `codekit.json` seems to find a match in the cache and uses this instead of rebuilding it.

**Comment by bdkjones** [comment]
Is the Project in a syncing folder such as iCloud Drive, or do you have iCloud Documents/Desktop turned on? Are you on Sonoma?

**Comment by slackero** [comment]
It's a folder not under iCloud sync but inside the Dropbox folder — as the other successfully updated projects too. The manually merged file – CodeKit was not running – is correctly synced to Dropbox.

And yes, I am on Sonoma 14.1 (23B74).

**Comment by slackero** [comment]
I have updated CodeKit on another machine which is linked to the same Dropbox and there it has worked without any problem for the project which fails on the machine were I have the problem. Same OS, same type of MacBook Pro M1.

**Comment by slackero** [comment]
I used the data from the other machine — especially `~/Library/Application Support/com.incident57.CodeKit3/CodeKit8.datastore`

Has worked and the project which couldn't be updated can be switched on/off again. The `codekit.json` keeps all changes.
