### ISSUE TITLE
CodeKit flikker and resets itself

### ISSUE THREAD

**Issue by BenjaminHoegh** [bdkjones/CodeKit#712]
No idea why this is happening as I have used CodeKit for years now. I did try a reinstall and removed the files from the system but no luck

https://github.com/bdkjones/CodeKit/assets/22152591/9b7aa183-3f21-4ddc-ba50-3e8c197e400f

---

- MacOS: 14.3.1 (23D60)
- CodeKit: 3.26 - Build 34564

**Comment by bdkjones** [comment]
Your project folder is in a syncing folder such as iCloud Drive or you have iCloud desktop and documents enabled. Starting in Sonoma, macOS is much more aggressive about deleting files and storing them only in the cloud, even though it looks like they exist locally. You're seeing lots of downloads finish when the sync service returns the files to your local disk and CodeKit refreshes to scan them.

Do not put your project folder in a syncing folder.

**Comment by BenjaminHoegh** [comment]
Ahhh okay i see, thanks for the quick response. What a annoying change hope they do something about it
