### ISSUE TITLE
.tsx files that render fragments using short syntax throw error TS17016

### ISSUE THREAD

**Issue by jdgcss** [bdkjones/CodeKit#716]
When using the .tsx file extension for components that return fragments using the short syntax the following error is thrown:

`Compiling failed with this error: Fragment.tsx(5,9): error TS17016: The 'jsxFragmentFactory' compiler option must be provided to use JSX fragments with the 'jsxFactory' compiler option.`

Here is a simplified example to reproduce. 

In a file called Fragment.tsx the following code will transpile as expected:

```
import React from 'react';

function FragmentComponent() {
    return (         
        <React.Fragment>I am a Fragment!</React.Fragment>
    );
}

export default FragmentComponent;
```

But if you change it to use the Short Syntax:

```
import React from 'react';

function FragmentComponent() {
    return (         
        <>I am a Fragment!</>
    );
}

export default FragmentComponent;
```

This will throw the error.

**Comment by bdkjones** [comment]
What is your `JSX Factory` option set to (see screenshot)? Are you using Babel or Rollup in the pipeline, or is this just simply compiling with the TypeScript compiler?

![Screenshot 2024-09-05 at 20 21 01](https://github.com/user-attachments/assets/8cbbea76-603b-42cf-8172-44f1b82d562a)

**Comment by jdgcss** [comment]
My typescript settings are like so:

![image](https://github.com/user-attachments/assets/34b39b9e-30a3-4aa9-9a85-a620ec93d216)

Then the settings the Fragment.tsx file look like this:

![image](https://github.com/user-attachments/assets/b72595d8-8263-4a95-9adc-ea5758cb8e45)

This isn't using any bundling yet, just pressing the compile button on that single file.

**Comment by bdkjones** [comment]
Okay, it looks like I just need to add the `jsxFragmentFactory` option to the app. I should be able to get to that in the next week or so.

**Comment by bdkjones** [comment]
@jdgcss I'm not a React guy, so please confirm that the below is correct.

Providing `jsxFragmentFactory = "Fragment"` to the TypeScript compiler required modifying your example code to add an additional import:

```
import {React, Fragment} from 'react';

function FragmentComponent() {
    return (         
        <>I am a Fragment!</>
    );
}

export default FragmentComponent;
```

Using the same settings as in your screenshot, the above now compiles to:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = require("react");
function FragmentComponent() {
    return (react_1.React.createElement(react_1.Fragment, null, "I am a Fragment!"));
}
exports.default = FragmentComponent;
```

Does that look correct?
