### ISSUE TITLE
TerserJS Mangler ignores function names for exceptions

### ISSUE THREAD

**Issue by dpkonofa** [bdkjones/CodeKit#720]
**Quick, short summary:**
When adding a function name to the "Exceptions" list, it still gets dropped/mangled. Variables are properly excepted when listed but function names get dropped and/or mangled. I'm not sure if this is a bug or if this is the expected behavior but I'm guessing that the functions are being dropped because they're not called elsewhere in the file since they're triggered by 'onclick' events in the HTML. If this is not a bug, is there some other way to minify the file while maintaining a function name so that it can be called via input events?

**Expected results:**
The original function names listed should exist in the minified version

**Actual results:**
Function names are mangled/dropped along with all the other functions and variables

**Exact steps to reproduce:**
Create a simple JS file that has a function. Add the function name to the "Exceptions" list in CodeKit and build the project. The function name is dropped.

**A link to download a simplified project or file that shows the issue:**
This basic JS file drops both functions, even if they're added to the exception list as "refreshRates" or "refreshRates()". Neither version works.

```
var itemType = document.getElementById("item-type").value,
    itemFee = 0,
    itemCharge = 1;
    
function refreshRates() {
    console.log(itemType);
    console.log(itemFee);
    console.log(itemCharge);
}

function testRates() {
    console.log(itemType);
    console.log(itemFee);
    console.log(itemCharge);
}
```

**Your configuration (any details about your system that you think might be relevant)**

**Comment by bdkjones** [comment]
Enable the "keep_fnames" option and you should be all set.

**Comment by dpkonofa** [comment]
keep_fnames still doesn't work and also doesn't give the option to drop/mangle all the other function names. As shown in my example JS, the functions are being called via "onclick" and "onchange" attributes which result in the function not being found when its scope gets changed.

I guess the expected behavior would be to be able to mangle all function names but exclude the ones that are called via those attributes. That doesn't seem possible with the way the ignore function works right now.

**Comment by bdkjones** [comment]
Do you have "drop/mangle in top level scope" enabled?

I tested over here and the function names are dropped only if that option is enabled.

**Comment by dpkonofa** [comment]
It doesn’t matter if I do. Any of the 3 options results in those functions breaking. In my example, there are 2 functions that are both in the top scope and they break whether that option is on or not as long as 1 of those options is enabled.

**Comment by bdkjones** [comment]
That’s not what I see over here. Zip up a demo project and send me a link to download it. You’re also running the latest version of CodeKit?On Dec 14, 2024, at 06:30, Derek ***@***.***> wrote:﻿
It doesn’t matter if I do. Any of the 3 options results in those functions breaking. In my example, there are 2 functions that are both in the top scope and they break whether that option is on or not as long as 1 of those options is enabled.
